Added 2 Examples to install-powershell.ps1 which fixes #10912
PowerShell/PowerShell pull request #10913
Opened 2019-10-27 03:47 UTC by kilasuit

Fixes issue #10912

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2019-10-27 18:34 UTC, TravisEz13 commented on tools/install-powershell.ps1
> +    iex "& { $(irm 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.ps1') } -daily"
```suggestion
    iex "& { $(irm 'https://aka.ms/install-powershell.ps1') } -daily"
```

2019-10-27 18:35 UTC, TravisEz13 commented on tools/install-powershell.ps1
> +    iex "& { $(irm 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.ps1') } -daily"
This allows us a little flexibility in managing the script

2019-10-27 23:49 UTC, TravisEz13 approved these changes

2019-10-27 23:49 UTC, TravisEz13 commented
@PoshChan Please remind me in 20 hours

2019-10-28 03:30 UTC, iSazonov approved these changes

2019-10-28 03:31 UTC, iSazonov commented on tools/install-powershell.ps1
> +    iex "& { $(irm 'https://aka.ms/install-powershell.ps1') } -daily"
```suggestion
    Invoke-Expression "& { $(Invoke-RestMethod 'https://aka.ms/install-powershell.ps1') } -daily"
```

2019-10-28 19:50 UTC, PoshChan commented
@TravisEz13, this is the reminder you requested 20 hours ago

2019-10-30 19:33 UTC, TravisEz13 commented
@kilasuit Can you merge or rebase to resolve the test issue?

2019-11-08 00:53 UTC, SteveL-MSFT commented
@kilasuit looks like a bad merge?  I would suggest reverting to the commit prior to pulling master in and then do something like:

```none
git pull upstream master
```

(assuming upstream points to PS/PS repo and not your fork)

2019-11-08 16:27 UTC, kilasuit commented
Just incase others see this and fall foul to messy merges I needed to run this as my local repo's default upstream is my fork

`git pull psrepo master -s recursive -X theirs`

2019-11-08 16:35 UTC, vexx32 commented
In case you need them for future reference, these might be useful in similar situations:

- `git merge upstream master` (this one might be `upstream/master` depending on how git wants to do it? I don't recall exactly for this one)
- `git pull --rebase upstream master`
- `git rebase -i upstream/master`

(where `upstream` is the name of the remote that maps to the main PowerShell project, looks like yours was `psrepo` instead)

2019-11-08 16:54 UTC, SteveL-MSFT requested changes

2019-11-08 16:54 UTC, SteveL-MSFT commented on CHANGELOG.md
> +- Add `-Emphasize` parameter to colorize `Select-String` output (#8963) (Thanks @derek-xia!)
Looks like you still have this commit in your PR

2019-11-09 06:19 UTC, kilasuit commented
Closing this PR and opening another from a clean branch with the requested changes from this one

2019-11-09 06:19 UTC, closed without merging