add basic info for install-powershell.ps1 fixes #10911
PowerShell/PowerShell pull request #10914
Opened 2019-10-27 03:58 UTC by kilasuit

Adds some basic details for install-powershell.ps1 script

# PR Summary

Adds some basic details to install-powershell-readme.md for the install-powershell.ps1 script

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2019-10-27 18:59 UTC, SteveL-MSFT requested changes

2019-10-27 18:59 UTC, SteveL-MSFT commented on tools/install-powershell-readme.md
> +iex "& { $(irm 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.ps1') } -daily"
The URL can be replaced by https://aka.ms/install-powershell.ps1 which points to the same location.

2019-10-27 18:59 UTC, SteveL-MSFT commented on tools/install-powershell-readme.md
> +* can be called directly from git
Bullet points should start capitalized

2019-10-27 23:48 UTC, TravisEz13 approved these changes

2019-10-28 01:17 UTC, SteveL-MSFT approved these changes

2019-10-28 01:17 UTC, SteveL-MSFT commented
@kilasuit looks like you amended your commit rather than push a new commit?  This makes it hard to see what changed.  In general, you should just push new commits.  When we merge, it'll be squashed.

2019-10-28 03:32 UTC, iSazonov commented on tools/install-powershell-readme.md
> +iex "& { $(irm 'https://aka.ms/install-powershell.ps1') } -daily"
Please expand aliases.

2019-10-28 03:32 UTC, iSazonov commented on tools/install-powershell-readme.md
> +iex "& { $(irm 'https://aka.ms/install-powershell.ps1') } -UseMSI"
The same.

2019-10-28 12:22 UTC, kilasuit commented
@SteveL-MSFT - noted your comment and will remember this in future as I have a habit of rebasing and rewriting commit history

2019-10-28 19:34 UTC, PoshChan commented
@TravisEz13, this is the reminder you requested 1 hour ago

2019-10-29 22:31 UTC, TravisEz13 commented
@PoshChan Please remind me in 1 hour

2019-10-29 23:31 UTC, PoshChan commented
@TravisEz13, this is the reminder you requested 1 hour ago

2019-10-30 19:31 UTC, merged