Update ADOPTERS.md
PowerShell/PowerShell pull request #11261
Opened 2019-12-03 23:27 UTC by edyoung

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2019-12-04 00:19 UTC, SteveL-MSFT commented
@edyoung You'll need to fix the Codacy issue which is to indent you bullet by 2 spaces.  Also, @TravisEz13 we should consider updating .spelling to ignore this specific file since we're askinging the adopter to submit the PR and we'll likely hit many new words.

2019-12-04 00:19 UTC, SteveL-MSFT requested changes
Address Codacy issue

2019-12-04 00:19 UTC, SteveL-MSFT commented on ADOPTERS.md
> +* [Azure Cloud Shell](https://shell.azure.com/) provides a batteries-included browser-based PowerShell environment used by Azure administrators to manage their environment. It includes up-to-date Pow
```suggestion
  * [Azure Cloud Shell](https://shell.azure.com/) provides a batteries-included browser-based PowerShell environment used by Azure administrators to manage their environment.
  It includes up-to-date PowerShell modules for Azure, AzureAD, Exchange, Teams, and many more.
```

2019-12-04 17:13 UTC, SteveL-MSFT requested changes

2019-12-04 17:13 UTC, SteveL-MSFT commented on ADOPTERS.md
> +  * [Azure Cloud Shell](https://shell.azure.com/) provides a batteries-included browser-based PowerShell environment used by Azure administrators to manage their environment.
Looks like I read the Codacy issue wrong, the bullet is left aligned, the content underneath is whitespaced
```suggestion
* [Azure Cloud Shell](https://shell.azure.com/) provides a batteries-included browser-based PowerShell environment used by Azure administrators to manage their environment.
```

2019-12-04 18:17 UTC, SteveL-MSFT approved these changes
LGTM, the Codacy markdown rule seems incorrect.  It's complaining about the spacing between the `*` and the content.

We can debate the .spelling separate from this PR

2019-12-04 21:20 UTC, TravisEz13 commented on ADOPTERS.md
> +  It includes up-to-date PowerShell modules for Azure, AzureAD, Exchange, Teams, and many more.
```suggestion
  It includes up-to-date PowerShell modules for Azure, AzureAD, Exchange, Teams, and many more.
  More information about Azure Cloud Shell is available at [Azure Cloud Shell Overview.](https://docs.microsoft.com/en-us/azure/cloud-shell/overview)
```

2019-12-04 21:21 UTC, TravisEz13 commented on ADOPTERS.md
> +  More information about Azure Cloud Shell is available at [Azure Cloud Shell Overview.](https://docs.microsoft.com/en-us/azure/cloud-shell/overview)
```suggestion
  More information about Azure Cloud Shell is available at [Azure Cloud Shell Overview.](https://docs.microsoft.com/azure/cloud-shell/overview)
```

2019-12-04 21:22 UTC, TravisEz13 commented
@PoshChan Please remind me in 1 hour

2019-12-04 22:22 UTC, PoshChan commented
@TravisEz13, this is the reminder you requested 1 hour ago

2019-12-04 22:23 UTC, TravisEz13 commented on ADOPTERS.md
> +  It includes up-to-date PowerShell modules for Azure, AzureAD, Exchange, Teams, and many more.
```suggestion
  It includes up-to-date PowerShell modules for `Azure`, `AzureAD`, `Exchange`, `Teams`, and many more.
```

2019-12-04 22:24 UTC, TravisEz13 commented
@PoshChan Please remind me in 1 hour

2019-12-04 23:24 UTC, PoshChan commented
@TravisEz13, this is the reminder you requested 1 hour ago

2019-12-05 04:27 UTC, iSazonov commented
It would be nice to have an soft integrations with adopters CIs so that we could see their daily status for latest pwsh builds - this helps us to discover, track and resolve breaking changes for tools (now we have only formal check boxes in PR template).

2019-12-06 19:45 UTC, TravisEz13 commented
@iSazonov Please file a new issues for new enhancements rather than commenting in an existing PR/Issue

2019-12-06 19:45 UTC, merged