First batch of new Pester tests for debugger functionality
PowerShell/PowerShell pull request #11336
Opened 2019-12-13 08:47 UTC by KirkMunro

# PR Summary

- updated HelpersDebugger module to support more debugging scenarios with PowerShell
- added tests for `BreakpointUpdated` and `DebuggerStop` handlers when working with `LineBreakpoint`, `VariableBreakpoint`, and `CommandBreakpoint` objects
- added debugger SDK tests

## PR Context

Bring old unit tests that were written in .NET forward as Pester tests in PowerShell.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2019-12-13 09:06 UTC, PoshChan commented on test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1
>          }
@KirkMunro, your last commit had 1 failures in `PowerShell-CI-linux`
Basic debugger command tests.Callstack (k, Get-PSCallStack) command should show the current call stack.Should only have CallStackFrame output from the callstack command
```powershell
Expected the value to have type [System.Management.Automation.CallStackFrame] or any of its subtypes, but got $null with type $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1: line 217
217:             $result['k'].Output | Should -BeOfType System.Management.Automation.CallStackFrame
```

2019-12-13 09:08 UTC, SSJ9899TDylan commented
Close my ass

On Fri, 13 Dec 2019 at 8:06 pm, PoshChan-Bot <notifications@github.com>
wrote:

> *@PoshChan* commented on this pull request.
> ------------------------------
>
> In test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1
> <https://github.com/PowerShell/PowerShell/pull/11336#discussion_r357544413>
> :
>
> > @@ -214,14 +214,13 @@ Describe 'Basic debugger command tests' -tag 'CI' {
>          }
>
> @KirkMunro <https://github.com/KirkMunro>, your last commit had 1
> failures in PowerShell-CI-linux
> Basic debugger command tests.Callstack (k, Get-PSCallStack) command should
> show the current call stack.Should only have CallStackFrame output from the
> callstack command
>
> Expected the value to have type [System.Management.Automation.CallStackFrame] or any of its subtypes, but got $null with type $null.
> at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1: line 217217:             $result['k'].Output | Should -BeOfType System.Management.Automation.CallStackFrame
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PowerShell/PowerShell/pull/11336?email_source=notifications&email_token=AIPXOJTSWANSVUID6TP6YRLQYNGDDA5CNFSM4J2JY6UKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCPC7CQY#pullrequestreview-331739459>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPXOJUCIHJV5BOAZFANZHLQYNGDDANCNFSM4J2JY6UA>
> .
>

2019-12-13 09:09 UTC, PoshChan commented on test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1
>          }
@KirkMunro, your last commit had 1 failures in `PowerShell-CI-macos`
Basic debugger command tests.Callstack (k, Get-PSCallStack) command should show the current call stack.Should only have CallStackFrame output from the callstack command
```powershell
Expected the value to have type [System.Management.Automation.CallStackFrame] or any of its subtypes, but got $null with type $null.
at <ScriptBlock>, /Users/runner/runners/2.160.1/work/1/s/test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1: line 217
217:             $result['k'].Output | Should -BeOfType System.Management.Automation.CallStackFrame
```

2019-12-13 09:10 UTC, PoshChan commented on test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1
>          }
@KirkMunro, your last commit had 1 failures in `PowerShell-CI-windows`
Basic debugger command tests.Callstack (k, Get-PSCallStack) command should show the current call stack.Should only have CallStackFrame output from the callstack command
```powershell
Expected the value to have type [System.Management.Automation.CallStackFrame] or any of its subtypes, but got $null with type $null.
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\Debugging\DebuggerCommand.Tests.ps1: line 217
217:             $result['k'].Output | Should -BeOfType System.Management.Automation.CallStackFrame
```

2019-12-13 22:02 UTC, PaulHigin approved these changes
Just one minor comment.  Otherwise LGTM.

2019-12-14 01:23 UTC, KirkMunro commented on test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
> +        $testScriptPath = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), 'BreakpointTestScript.ps1')
No, it just wasn't top of mind (old habits die hard). I'll update this test to use test drive instead.

2020-01-03 18:30 UTC, adityapatwardhan requested changes
Just one small change. Rest looks good.

2020-01-03 18:30 UTC, adityapatwardhan commented on test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
> +        [System.IO.File]::Delete($testScriptPath)
This is unnecessary as the content of the test drive will be deleted.

2020-02-13 06:00 UTC, closed without merging