Re-add check for Invoke-Command job dispose.
PowerShell/PowerShell pull request #11388
Opened 2019-12-17 23:59 UTC by PaulHigin

## PR Summary

This fixes session reconnect regression bug: #11150. 

## PR Context

Invoke-Command creates a disconnected job object to facilitate session re-connection, when WinRM abruptly disconnects the session due to network issues.  The EndProcessing() block was disposing the disconnected job object so that a session reconnect could not occur.

Fix is to add the checks back in the code which prevents EndProcessing() from disposing the disconnected job, and added comments explaining why the code checks are there.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2019-12-18 00:04 UTC, SteveL-MSFT requested changes
Code change looks fine, possible to add a local loopback test?

2019-12-18 17:10 UTC, PaulHigin commented
@SteveL-MSFT 

Regarding automated tests, the repro requires abruptly disconnecting a synchronous running Invoke-Command (Invoke-Command -AsJob does not exhibit the problem).

This is moderately easy to do interactively, but difficult for an automated CI test since it involves multiple processes and timing.

My concern is creating yet another fragile test that fails randomly, adding unnecessary misery to build engineers.

2019-12-18 17:25 UTC, SteveL-MSFT approved these changes

2019-12-18 20:32 UTC, PaulHigin commented
Actually, I thought about this some more and have found a simpler way to test this scenario.  I feel the test should be reasonably reliable and will add it here.  We can always remove the test if it turns out to be fragile.

2019-12-20 20:13 UTC, anmenaga approved these changes

2019-12-20 20:13 UTC, merged