Fix ModuleInfoGrouping format
PowerShell/PowerShell pull request #11950
Opened 2020-02-25 17:13 UTC by ThomasNieto

# PR Summary

This PR fixes #11927 and #7856 by updating the `PSEdition` column in the `Module` table format to check `PrivateData.PSData.Tags` if `CompatiblePSEditions` is not defined. This allows module authors to indicate compatible `PSEditions` without limiting module compatibility to 5.1+ by using `CompatiblePSEditions`.

```powershell
# Current
PS C:\> Get-Module -ListAvailable | Where-Object Name -eq pester | Select-Object -First 1

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.9.0                 Pester                              Desk      {Describe, Context, It, Should…}

# New
PS C:\> Get-Module -ListAvailable | Where-Object Name -eq pester | Select-Object -First 1

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.9.0                 Pester                              Core,Desk {Describe, Context, It, Should…}
```

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-02-25 17:37 UTC, iSazonov commented
@ThomasNieto  #11927 and #7856 is issues with conclusions. It seems the PR fixes only #7856.

2020-02-25 18:04 UTC, ThomasNieto commented
@iSazonov the newest commit adds logic for modules in `$PSHOME` and Windows PowerShell in-box.

2020-02-25 18:22 UTC, iSazonov commented
I'd expect that core modules is fixed in its manifests.

2020-02-25 19:47 UTC, ThomasNieto commented
@iSazonov have any idea why CodeFactor failed? How do I get it to retry?

2020-02-26 17:41 UTC, iSazonov commented
Code Factory CI is not mandatory. We use it as temporary recommendations.

2020-03-13 06:09 UTC, daxian-dbw commented on src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
> +                                elseif ($_.ModuleBase -like '{0}*' -f $PSHOME) {
```suggestion
                                elseif ($_.ModuleBase -like ""$PSHOME*"") {
```

2020-03-13 06:10 UTC, daxian-dbw commented on src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
> +                                        $_.ModuleBase -like '{0}\Windows\system32\WindowsPowerShell\v1.0\Modules' -f $Env:SystemDrive ) {
```suggestion
                                        $_.ModuleBase -like ""$Env:SystemDrive\Windows\system32\WindowsPowerShell\v1.0\Modules"") {
```

2020-03-13 06:22 UTC, daxian-dbw commented
The changes in this PR conflicts with the effort in #11943, which tries to make the module formatting script work in strict mode.
If this is the right fix, then the code needs to be updated to work in strict mode.

2020-05-08 10:01 UTC, iSazonov commented
@ThomasNieto Could you please address latest comments?

2020-05-27 17:15 UTC, TravisEz13 requested changes
Please address @daxian-dbw  comments

2020-06-22 06:00 UTC, closed without merging