Fix IPC default named pipe clean up on exit
PowerShell/PowerShell pull request #12187
Opened 2020-03-23 23:13 UTC by PaulHigin

# PR Summary

This PR addresses Issue #11599.  On Linux platforms, the default named pipe file was not getting cleaned up on PowerShell exit.

## PR Context

Windows PowerShell uses the CLR Appdomain unload event to dispose the NamedPipeServerStream object on exit, but that does not work with .NET core runtime.  This was not a problem on Windows platforms because the Windows OS releases all process resources on process exit, including named pipes.

Fix is to change this to use the CLR 'ProcessExit' event.

Note that this only works when PowerShell exits normally, i.e., via the 'exit' command.  If the console or terminal window is closed then the CLR cannot fire the event.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [x] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-03-24 03:56 UTC, iSazonov reviewed
> For Windows PowerShell we were using the CLR Appdomain unload event to dispose of the server pipe, but that is not implemented in dotNet core.

Is this a fundamental Unix behavior/problem or we should open an issue in .Net repo to request a fix?

2020-03-24 03:56 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
> +                throw new PSArgumentNullException("processName");
```suggestion
                throw new PSArgumentNullException(nameof(processName));
```

2020-03-24 03:56 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
> +                throw new PSArgumentNullException("appDomainName");
```suggestion
                throw new PSArgumentNullException(nameof(appDomainName));
```

2020-03-24 03:56 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
> +                // Ignore.
Can we have more useful comment?

2020-03-24 03:56 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
> +                // Ignore.
The same.

2020-03-24 03:56 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
> +                        // Ignore.
The same.

2020-03-24 03:56 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.Tests.ps1
> +        $psProc = Start-Process -FilePath $psPath -ArgumentList "-File $testfilePath -LiveFilePath $aliveFile" -PassThru
We use `Start-Process "$PSHOME/pwsh"` pattern in all tests.

2020-03-24 15:15 UTC, PoshChan commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
>                                      else if (process.ProcessName.Equals(pName, StringComparison.Ordinal))
@PaulHigin, your last commit had 1 failures in `PowerShell-CI-linux`
Basic SysLog tests on Linux.Verifies logging level filtering works
```powershell
Expected $null, but got PSLogItem.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/Logging.Tests.ps1: line 256
256:         $items | Should -Be $null
```

2020-03-24 15:17 UTC, PoshChan commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
>                                      else if (process.ProcessName.Equals(pName, StringComparison.Ordinal))
@PaulHigin, your last commit had 1 failures in `PowerShell-CI-macos`
Test-Connection.TraceRoute.TraceRoute works
```powershell
Expected exactly '10.79.0.125', but got 127.0.0.1.
at <ScriptBlock>, /Users/runner/runners/2.165.2/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 257
257:             $result[0].TargetAddress | Should -BeExactly $realAddress
```

2020-03-24 15:19 UTC, PoshChan commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
>                                      else if (process.ProcessName.Equals(pName, StringComparison.Ordinal))
@PaulHigin, your last commit had 1 failures in `PowerShell-CI-windows`
ForEach-Object -Parallel Functional Tests.Verifies parallel task queuing
```powershell
Expected the actual value to be greater than 5, but got 5.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Foreach-Object-Parallel.Tests.ps1: line 369
369:         $results[2] | Should -BeGreaterThan 5
```

2020-03-24 15:49 UTC, PaulHigin commented
@PoshChan  Please rerun tests

2020-03-24 15:49 UTC, PoshChan commented
@PaulHigin, I do not understand the build target(s) `tests`; I only allow `static`, `windows`, `macos`, `linux`, `all`

2020-03-24 15:51 UTC, PaulHigin commented
@PoshChan Please rerun all

2020-03-24 15:52 UTC, PoshChan commented
@PaulHigin, successfully started rebuild of `PowerShell-CI-static-analysis, PowerShell-CI-Windows, PowerShell-CI-macOS, PowerShell-CI-Linux`

2020-03-24 16:11 UTC, PoshChan commented on src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
>                                      else if (process.ProcessName.Equals(pName, StringComparison.Ordinal))
@PaulHigin, your last commit had 1 failures in `PowerShell-CI-macos`
Test-Connection.Ping.Force IPv4 with implicit PingOptions
```powershell
Expected exactly '10.79.2.161', but got 10.79.0.26.
at <ScriptBlock>, /Users/runner/runners/2.165.2/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 83
83:             $result[0].Address | Should -BeExactly $realAddress
```

2020-03-24 17:11 UTC, iSazonov approved these changes

2020-03-25 16:32 UTC, SteveL-MSFT requested changes

2020-03-25 16:32 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.Tests.ps1
> +        Test-Path -Path $pipeFilePath | Should -BeTrue
```suggestion
        $pipeFilePath | Should -Exist
```

2020-03-25 16:32 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.Tests.ps1
> +        Test-Path -Path $psNamedPipePath | Should -BeTrue
```suggestion
        $psNamedPipePath | Should -Exist
```

2020-03-25 16:32 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.Tests.ps1
> +        Test-Path -Path $psNamedPipePath | Should -BeFalse
```suggestion
        $psNamedPipePath | Should -Not -Exist
```

2020-03-25 20:40 UTC, PaulHigin commented
@PoshChan  Please rerun all

2020-03-25 20:41 UTC, PoshChan commented
@PaulHigin, successfully started rebuild of `PowerShell-CI-static-analysis, PowerShell-CI-Windows, PowerShell-CI-macOS, PowerShell-CI-Linux`

2020-03-25 21:01 UTC, SteveL-MSFT approved these changes

2020-03-26 16:47 UTC, merged

2020-04-21 13:13 UTC, MaFreiberger commented
PowerShell 7.1.0-preview.1 on debian 9.12

Problem still exists. Every time i power up a console (pwsh-preview) it creates something like
srwxr-xr-x  1 iteanova iteanova    0 Apr 21 15:07 CoreFxPipe_PSHost.D617DDBE.10883.None.pwsh
srwxr-xr-x  1 iteanova iteanova    0 Apr 21 15:08 CoreFxPipe_PSHost.D617DDE2.11055.None.pwsh
srwxr-xr-x  1 iteanova iteanova    0 Apr 21 15:09 CoreFxPipe_PSHost.D617DE06.11252.None.pwsh
srwxr-xr-x  1 iteanova iteanova    0 Apr 21 15:10 CoreFxPipe_PSHost.D617DE2A.11431.None.pwsh

2020-04-21 14:05 UTC, iSazonov commented
@MaFreiberger It is not in Preview1. You can load nightly build or wait next Preview.

2020-09-30 23:14 UTC, rjmholt commented
Should this be backported to PowerShell 7.0?

2020-10-01 03:16 UTC, iSazonov commented
Have we requests for this?

2021-02-02 22:28 UTC, rjmholt commented
Just labelled this as backport consider so that we can discuss whether this should be backported (since otherwise the LTS will just pollute named pipes onto the system). Just a suggestion though -- we can skip it if it's not thought to be severe.