Fix broken link in README.md
PowerShell/PowerShell pull request #12887
Opened 2020-06-03 20:39 UTC by xtqqczze

# PR Summary

Fix #12886

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-06-03 23:17 UTC, daxian-dbw requested changes

2020-06-03 23:17 UTC, daxian-dbw commented on README.md
> +[windows-nightly-site]: https://powershell.visualstudio.com/PowerShell/_build/?definitionId=32
```suggestion
[windows-nightly-site]: https://powershell.visualstudio.com/PowerShell/_build?definitionId=32
```

2020-06-03 23:35 UTC, daxian-dbw approved these changes

2020-06-04 10:03 UTC, iSazonov commented
@PoshChan Please rebuild static

2020-06-04 10:03 UTC, PoshChan commented
@iSazonov, successfully started rebuild of `PowerShell-CI-static-analysis`

2020-06-04 10:16 UTC, iSazonov commented
@xtqqczze It seems another link died. Could you please look?

2020-06-04 14:42 UTC, xtqqczze commented
Issue opened: https://github.com/ironmansoftware/universal-dashboard/issues/1652

2020-06-04 16:37 UTC, iSazonov commented
@PoshChan Please rebuild static

2020-06-04 16:37 UTC, PoshChan commented
@iSazonov, successfully started rebuild of `PowerShell-CI-static-analysis`

2020-06-04 16:45 UTC, merged

2020-06-04 16:45 UTC, adityapatwardhan commented
@xtqqczze Thank you for your contribution!