Add HoloLens to list of PowerShell adopters
PowerShell/PowerShell pull request #12940
Opened 2020-06-10 22:53 UTC by reynoldsbd

# Summary

Add information to ADOPTERS.md describing how PowerShell is used for Microsoft HoloLens development.

# Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-06-11 06:03 UTC, iSazonov commented on ADOPTERS.md
> +* [Microsoft HoloLens](https://www.microsoft.com/en-us/hololens) makes extensive use of PowerShell throughout the development cycle to automate tasks such as firmware assembly and automated testing.
> en-us

Can we use generic link?

2020-06-11 14:31 UTC, SteveL-MSFT commented on ADOPTERS.md
> +* [Microsoft HoloLens](https://www.microsoft.com/en-us/hololens) makes extensive use of PowerShell throughout the development cycle to automate tasks such as firmware assembly and automated testing.
```suggestion
* [Microsoft HoloLens](https://www.microsoft.com/hololens) makes extensive use of PowerShell 7+ throughout the development cycle to automate tasks such as firmware assembly and automated testing.
```

2020-06-11 14:32 UTC, SteveL-MSFT requested changes
URLs should not contain the locale as it's detected by the website.  Also suggest calling out PS7 specifically since HoloLens dependency is specifically PS7+

2020-06-11 14:34 UTC, SteveL-MSFT requested changes
You'll also need to add the word `HoloLens` to our spelling dictionary right before this line: https://github.com/PowerShell/PowerShell/blob/master/.spelling#L336

2020-06-11 18:27 UTC, SteveL-MSFT commented
CI failure is due to https://github.com/PowerShell/PowerShell/issues/12935 and isn't blocking for this PR.

2020-06-11 18:27 UTC, SteveL-MSFT approved these changes

2020-06-16 17:44 UTC, SteveL-MSFT commented
@iSazonov I think we're good to merge this one

2020-06-16 18:39 UTC, iSazonov commented
@SteveL-MSFT I haven't permissions to force the merging. So waiting CI-macos resolving.

2020-06-17 01:00 UTC, SteveL-MSFT commented
@iSazonov ok, I rebased this branch and that should pass CI

2020-06-17 03:35 UTC, merged