Bump rcedit version
PowerShell/PowerShell pull request #13060
Opened 2020-06-30 05:26 UTC by TylerLeonhardt

# PR Summary

Bump rcedit version used.

## PR Context

rcedit is failing to set icons in CI scenarios. This bumps the version to see if a newer version works for CI.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-06-30 06:01 UTC, iSazonov commented
@TylerLeonhardt Does new version work? Can we merge?

2020-06-30 13:29 UTC, SteveL-MSFT approved these changes

2020-07-01 04:25 UTC, TylerLeonhardt commented
This needed more work because apparently the _actual_ issue is that the ICO doesn't exist. I'm tracking down why, but this change is nice because setting the ICO isn't too important.

cc @adityapatwardhan

2020-07-01 18:39 UTC, adityapatwardhan commented
Setting of the icon should be done in packaging instead

2020-07-01 18:41 UTC, adityapatwardhan commented
Changes should be done here: https://github.com/PowerShell/PowerShell/blob/d1aa11e367581736ffea570722cee93815c07a41/tools/packaging/packaging.psm1#L1618

2020-07-02 21:28 UTC, TravisEz13 commented
If we take this type of fix, I think we should do something more temporary like:  https://github.com/PowerShell/PowerShell/pull/13078/files

2020-07-02 21:30 UTC, TravisEz13 requested changes

2020-07-02 21:30 UTC, TravisEz13 commented on tools/install-powershell.ps1
> +                $rceditUrl = "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe"
Does this need to run on the client machine?

2020-07-07 18:34 UTC, TylerLeonhardt commented
Closing this in favor of #13123

2020-07-07 18:34 UTC, closed without merging