Add SupportsWildcardsAttribute to parameters
PowerShell/PowerShell pull request #13362
Opened 2020-08-06 01:39 UTC by ThomasNieto

# PR Summary

This PR is the second-half of #4716 to add `[SupportsWildcards]` attribute to all parameters that support wildcards.

## PR Context

The `[SupportsWildcards]` attribute is queried by the help system to inform the user if wildcards are supported. The list of parameters was generated by @sdwheeler.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-08-06 20:42 UTC, sdwheeler approved these changes
Looks OK to me. Is there a way to test these?

2020-08-06 20:50 UTC, ThomasNieto commented
@sdwheeler To test if they have the attribute applied or that the help system is picking it up?

2020-08-06 20:58 UTC, sdwheeler commented
@ThomasNieto Testing the output of the Help System should be easy enough. I am more concerned about the accuracy of the list I created. Is that list accurate and complete? How do we test new parameters or cmdlet to ensure that '[SupportsWildcards]' is correct?

2020-08-06 21:16 UTC, ThomasNieto commented
@sdwheeler I used a PS script to gather the globbing value from the help system. If external help is present it uses what you put in the maml. I compared the output to your list and caught a couple of extra parameters. As for ensuring that the attribute is added on new parameters and cmdlets I'm not sure about the best way to do that.

@vexx32 had an idea in #4715 if it was the pre-1.0 days to have parameters use `WildcardPattern` as the parameter type. As a related suggestion we could have a generic type of `[Wildcard<T>]` so the module author can indicate at the type level if wildcards are supported. The generic type could have properties/methods that wrap or use `WildcardPattern` to validate `IsMatch()`. There are a couple of examples in the PS code where the input type of a wildcard parameter is not a string. Those cases use an argument transform attribute.

2020-08-06 23:09 UTC, rjmholt commented
> As a related suggestion we could have a generic type of [Wildcard<T>] so the module author can indicate at the type level if wildcards are supported

This and a similar type for paths are something I'd really like to see. Something with an implicit conversion from string I don't think would cause any breaks.

2020-09-01 21:48 UTC, daxian-dbw commented
@PowerShell/powershell-maintainers reviewed this PR and agreed to accept it after it's been thoroughly reviewed. We think this will not block 7.1 GA. /cc @SteveL-MSFT

2020-12-03 18:22 UTC, rjmholt requested changes

2020-12-03 18:22 UTC, rjmholt commented on src/Microsoft.PowerShell.Commands.Management/commands/management/CombinePathCommand.cs
> +        [SupportsWildcards]
Ok here is where I wondered about the validity of `[SupportsWildcards]`:

```
> join-path -Path .\PowerShell* -ChildPath *-*
.\PowerShell*\*-*
```

So it looks like `Join-Path` does not support wildcards.

In which case, I feel like the only way to guarantee the correctness of this PR is to test all the labelled parameters in question or read the code for something like `GetResolvedProviderPathFromPSPath()`

2020-12-03 20:24 UTC, sdwheeler commented
> Testing the output of the Help System should be easy enough. I am more concerned about the accuracy of the list I created. Is that list accurate and complete? How do we test new parameters and cmdlets to ensure that `[SupportsWildcards]` is correct?

As I said in a previous comment, I was concerned about the accuracy of the list. The list was built based on the existing documentation. If the documentation is not accurate then neither is the list. We need someone to verify how the parameters actually work and add the attribute where appropriate. The list was an attempt at limiting the scope of the effort instead of having to review every parameter of every cmdlet.

2020-12-04 17:03 UTC, rjmholt commented
I think rather than keeping this PR open, it might be best to go through the original list, validate it to create a new list, and then create a PR based on that

2020-12-09 20:02 UTC, rjmholt commented
I'm going to close this PR, since I don't think we're ready to consider code changes yet. Let's go through the process of verifying the parameters in an issue, which is a better format than a PR for such a discussion.

2020-12-09 20:02 UTC, closed without merging