Update README and metadata.json for 7.1.0-preview.7
PowerShell/PowerShell pull request #13565
Opened 2020-09-02 23:13 UTC by rjmholt

# PR Summary

Updates links in the README and the metadata.json file for preview.7.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-09-08 16:32 UTC, daxian-dbw approved these changes

2020-09-09 04:27 UTC, daxian-dbw commented
I have no idea why the CI tests failed.

2020-09-09 17:53 UTC, TravisEz13 requested changes

2020-09-09 17:53 UTC, TravisEz13 commented on README.md
> +[pv-centos8]: https://github.com/PowerShell/PowerShell/releases/download/v7.1.0-preview.7/powershell-preview-7.1.0_preview.6-1.centos.8.x86_64.rpm
missed the second version

2020-09-09 17:53 UTC, TravisEz13 commented on tools/metadata.json
> +  "NextReleaseTag": "v7.1.0-rc.1",
Keep this is a preview, even if it won't be
```suggestion
  "NextReleaseTag": "v7.1.0-preview.8",
```

2020-09-09 18:26 UTC, rjmholt commented
CI is now passing

2020-09-09 18:28 UTC, daxian-dbw commented
Magic! 😄

2020-09-09 20:37 UTC, TravisEz13 approved these changes

2020-09-09 20:57 UTC, merged