WIP: Add initial support for Blazor WebAssembly
PowerShell/PowerShell pull request #13776
Opened 2020-10-13 14:50 UTC by fMichaleczek

# PR Summary

- Declaring OperatingSystem.IsBrowser in the startup process
- Add a minimal logger support through Console.WriteLine
- Add a sample demo of a Blazor WebAssembly with SMA 

## PR Context

Fixes #13755

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-10-25 16:32 UTC, TravisEz13 commented on demos/Blazor/powershell-blazor-wasm-demo/wwwroot/index.html
> +    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
We should have a mention of the license and copyright for these files.

2020-10-25 16:35 UTC, TravisEz13 requested changes
Personally, I think this should be in a separate repo.
I'd rather not confuse people with license for the repo vs the product.

2020-10-25 16:35 UTC, TravisEz13 commented on demos/Blazor/powershell-blazor-wasm-demo/wwwroot/css/open-iconic/FONT-LICENSE
> +SIL OPEN FONT LICENSE Version 1.1
Compliance review needed

2020-10-25 16:35 UTC, TravisEz13 commented on demos/Blazor/powershell-blazor-wasm-demo/wwwroot/css/open-iconic/ICON-LICENSE
> +THE SOFTWARE.
add newline to make posix compliant

2020-10-25 16:36 UTC, TravisEz13 commented
cc @SteveL-MSFT Please comment if demos that add licenses should be in the same or different repos.

2020-11-02 23:52 UTC, fMichaleczek commented
@TravisEz13 

> The demo folder is more for reviewers if they want to see live working sample,  it's the default blazor webassembly template from the Asp.Net Core SDK. I am OK to remove it from the final review. I will publish a real sample later and we will discuss about it.
> I will remove the PowerShell Logger part in the PR because I don't need anymore, the boot process is clean and without error (Blazor already provide a logger for the rest). I will wait for an general logger improvement in 7.2 timeline.

2020-11-25 03:10 UTC, SteveL-MSFT commented
It may make sense to have a powershell-blazor repo for the demo files which may evolve into something more useful.  @fMichaleczek if you're ok with that, I can create the repo and you can submit a PR for the demo files there and just have this PR be PowerShell changes needed to run in browser

2020-11-25 04:11 UTC, fMichaleczek commented
@SteveL-MSFT This PR is a POC to say : it works, see by yourself. First, PowerShell need to be fileless in Blazor environment. I can first make a PR for the version git number and some path. Then it will be about your plugin system, do we go to DI like all dotnet projet for conf, log etc ? Microsoft.Extensions ? Finally we have to update the buildchain (to build on windows), the tests and the demos (maybe better outside). Then we will have an infrastructure and I will begin the RFC to ask community. Do you want more details about a particular item ?

2020-11-25 04:25 UTC, SteveL-MSFT commented
@fMichaleczek "fileless" meaning it has to be self contained and not try to access the file system?  We have a RFC coming for pluggable subsystems for PowerShell and maybe logging should be a subsystem and can be replaced.  What I'm specifically looking for is changes to PowerShell so that it can be hosted in blazor.  Just like how we have a console host today, I'd imagine there would be a separate blazor host which would be its own project/repo.

2020-11-25 05:00 UTC, fMichaleczek commented
@SteveL-MSFT 

> "fileless" meaning it has to be self contained and not try to access the file system?  

When you load SMA, the inmemory filesystem is empty. json, psd1, psm1 files are unavailable at starting. You can only use assemblies. or download the files and have a lot of latencies. 

> We have a RFC coming for pluggable subsystems for PowerShell and maybe logging should be a subsystem and can be replaced.  

args (maybe not apply to all cases), configuration file, logging and the way we load modules have to evolve.

> What I'm specifically looking for is changes to PowerShell so that it can be hosted in blazor.  

We are looking for changes to PowerShell so that it can be hosted in AspNetCore, Blazor Wasm, Blazor Wasm Server and MAUI Blazor Wasm.

- PowerShell is always loaded after the DI, so I need a fileless way to configure and inject SMA with a smallset of modules.

- webclient is broken and http is the only  way  to communicate

- MMI package is still weird for unknow platform

> Just like how we have a console host today, I'd imagine there would be a separate blazor host which would be its own project/repo.

I have a monacoeditor + xterm.js demo to finish. 200Mo, need a 100Mbits network 🙃 SMA + SDK are to big because of dependencies.

Maybe better to continue here :
https://github.com/PowerShell/PowerShell/issues/13755

2020-12-23 18:00 UTC, closed without merging