Fix nullable usage on SessionStateContainer.cs
PowerShell/PowerShell pull request #13806
Opened 2020-10-17 22:07 UTC by mkswd

# PR Summary

Changed nullable usage for better implementation.
Change in SessionStateContainer.cs

## PR Context

Change has done due to issue #13791 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None

2020-10-19 05:34 UTC, iSazonov approved these changes

2020-10-19 16:14 UTC, PaulHigin requested changes
This code should not change.  There is a difference between the languageMode being defined and having a default value of 'FullLanguage'.

Please revert this change.

2020-10-19 16:25 UTC, iSazonov requested changes

2020-10-19 16:25 UTC, iSazonov commented on src/System.Management.Automation/engine/SessionStateContainer.cs
> +                if (languageMode.GetValueOrDefault() == PSLanguageMode.ConstrainedLanguage || languageMode.GetValueOrDefault() == PSLanguageMode.NoLanguage)
Based on @PaulHigin conclusion:
```suggestion
                if (languageMode.HasValue && languageMode.GetValueOrDefault() == PSLanguageMode.ConstrainedLanguage || languageMode.GetValueOrDefault() == PSLanguageMode.NoLanguage)
```

2020-10-21 20:08 UTC, closed without merging

2020-10-21 20:09 UTC, mkswd commented
PR closed since this code should not  change