Use `Microsoft.PowerShell.MarkdownRender` package from `nuget.org`
PowerShell/PowerShell pull request #14090
Opened 2020-11-13 22:03 UTC by adityapatwardhan

# PR Summary

The code for `Microsoft.PowerShell.MarkdownRender` has been moved to a separate repository https://github.com/powershell/markdownrender. This PR removes the code from this repository and uses the package from nuget.org instead

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

2020-11-14 06:30 UTC, xtqqczze commented
I see the initial commit https://github.com/PowerShell/MarkdownRender/commit/345e2f35f2cc51b25a6dd86e12031c353c429f8a was on 2020-10-02. We should ensure changes made after this date are reflected in [powershell/markdownrender](https://github.com/powershell/markdownrender).

2020-11-19 18:12 UTC, TravisEz13 requested changes

2020-11-19 18:12 UTC, TravisEz13 commented on tools/packaging/packaging.psm1
> -        "Microsoft.PowerShell.MarkdownRender.dll")
This file should be signed in your build, so can you remove it from our signing?

2020-11-20 17:53 UTC, adityapatwardhan commented
@TravisEz13 - please re-review

2020-11-20 18:02 UTC, TravisEz13 approved these changes

2020-11-20 18:06 UTC, adityapatwardhan commented
@rjmholt This is ready for review now.

2020-11-20 18:08 UTC, adityapatwardhan commented
@xtqqczze - Filed issue in MarkdownRender repo to make sure the improvements mentioned above are taken there: https://github.com/PowerShell/MarkdownRender/issues/11

2020-11-24 17:41 UTC, adityapatwardhan commented
@rjmholt This is ready to merge.

2020-12-02 09:46 UTC, xtqqczze commented
@iSazonov We should avoid merging any more changes to `Microsoft.PowerShell.MarkdownRender`, like those in #14078.

2020-12-02 11:35 UTC, iSazonov commented
> @iSazonov We should avoid merging any more changes to `Microsoft.PowerShell.MarkdownRender`, like those in #14078.

These files will simply be deleted - this does not affect anything.

2020-12-09 19:54 UTC, rjmholt commented
@PoshChan please remind me in 1 hour

2020-12-09 20:29 UTC, merged

2020-12-09 20:55 UTC, PoshChan commented
@rjmholt, this is the reminder you requested 1 hour ago