Enable nullable: System.Management.Automation.LanguagePrimitives.IConversionData
PowerShell/PowerShell pull request #14187
Opened 2020-11-20 00:25 UTC by powercode

Tracking issue: #12631.

2020-11-20 16:51 UTC, iSazonov requested changes

2020-11-20 16:51 UTC, iSazonov commented on src/System.Management.Automation/engine/LanguagePrimitives.cs
> +
```suggestion
#nullable enable
```

2020-11-20 16:51 UTC, iSazonov commented on src/System.Management.Automation/engine/LanguagePrimitives.cs
> +
```suggestion
#nullable restore

```

2020-12-11 05:20 UTC, rjmholt approved these changes

2020-12-11 06:15 UTC, iSazonov approved these changes

2020-12-11 06:15 UTC, merged