Enable nullable: System.Management.Automation.Language.ICustomAstVisitor
PowerShell/PowerShell pull request #14191
Opened 2020-11-20 00:52 UTC by powercode

Tracking issue: #12631.

2020-11-20 05:16 UTC, iSazonov reviewed
Looks good. Only please move the directive.

2020-11-20 05:16 UTC, iSazonov commented on src/System.Management.Automation/engine/parser/AstVisitor.cs
> +
```suggestion
#nullable restore

```

2020-11-20 05:16 UTC, iSazonov commented on src/System.Management.Automation/engine/parser/AstVisitor.cs
> +
```suggestion
```

2020-11-20 05:16 UTC, iSazonov commented on src/System.Management.Automation/engine/parser/AstVisitor.cs
>      public interface ICustomAstVisitor
```suggestion
#nullable enable
    public interface ICustomAstVisitor
```

2020-11-21 13:46 UTC, iSazonov approved these changes

2020-11-21 14:17 UTC, iSazonov commented
@powercode Please add the standard XML comment like "This never returns null." to appropriate methods.

2020-12-11 05:19 UTC, rjmholt requested changes
> @powercode Please add the standard XML comment like "This never returns null." to appropriate methods.

Blocked on this

2021-05-18 19:44 UTC, rjmholt approved these changes

2021-05-19 03:48 UTC, merged