Enable nullable: System.Management.Automation.Language.ICustomAstVisitor2
PowerShell/PowerShell pull request #14192
Opened 2020-11-20 00:54 UTC by powercode

Tracking issue: #12631.

2020-11-20 10:52 UTC, iSazonov requested changes
Looks good but please move directives.

2020-11-20 10:52 UTC, iSazonov commented on src/System.Management.Automation/engine/parser/AstVisitor.cs
> +
```suggestion
#nullable restore

```

2020-11-20 10:52 UTC, iSazonov commented on src/System.Management.Automation/engine/parser/AstVisitor.cs
>      public interface ICustomAstVisitor2 : ICustomAstVisitor
```suggestion
    /// <summary/>
#nullable enable
    public interface ICustomAstVisitor2 : ICustomAstVisitor
```

2020-12-11 05:16 UTC, rjmholt approved these changes

2020-12-11 06:22 UTC, iSazonov approved these changes

2020-12-11 06:22 UTC, merged