Add PipelineStoppedException notes to PowerShell API
PowerShell/PowerShell pull request #15324
Opened 2021-04-29 23:23 UTC by rjmholt

# PR Summary

Fixes https://github.com/PowerShell/PowerShell/issues/15173.

Adds doc comments about how `PowerShell.Invoke()` and `PowerShell.InvokeAsync()` work with `PowerShell.Stop()`.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2021-04-29 23:51 UTC, daxian-dbw approved these changes

2021-04-29 23:51 UTC, daxian-dbw commented on src/System.Management.Automation/engine/hostifaces/PowerShell.cs
> +        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}"> to <see cref="PowerShell.BeginInvoke"/>
```suggestion
        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}"> to <see cref="PowerShell.BeginInvoke"/> for the <paramref name="output"/> parameter
```

2021-04-30 23:36 UTC, daxian-dbw commented
@rjmholt CodeFactor complains about invalid XML doc. Can you take a look and fix them?

2021-05-05 18:04 UTC, adityapatwardhan requested changes

2021-05-05 18:04 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/hostifaces/PowerShell.cs
> +        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}"> for the <paramref name="output"/> parameter,
```suggestion
        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}" /> for the <paramref name="output"/> parameter,
```

2021-05-05 18:04 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/hostifaces/PowerShell.cs
> +        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}"> for the <paramref name="output"/> parameter,
```suggestion
        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}" /> for the <paramref name="output"/> parameter,
```

2021-05-05 18:04 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/hostifaces/PowerShell.cs
> +        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}"> to <see cref="PowerShell.BeginInvoke"/> for the <paramref name="output"/> parameter
```suggestion
        /// supply a <see cref="System.Management.Automation.PSDataCollection{T}" /> to <see cref="PowerShell.BeginInvoke"/> for the <paramref name="output"/> parameter
```

2021-05-13 05:38 UTC, daxian-dbw commented
@adityapatwardhan Can you review again?

2021-06-03 19:27 UTC, adityapatwardhan approved these changes

2021-06-03 19:27 UTC, merged