Add new members to Engine and Cmdlet Working Groups (and typo fix)
PowerShell/PowerShell pull request #15560
Opened 2021-06-10 21:43 UTC by joeyaiello

# PR Summary

As discussed by @PowerShell/powershell-committee, we're happy to welcome new community members to our Engine and Cmdlet Working Groups (the latter of which we recently decided to instantiate to manage those modules that live within PowerShell/PowerShell). 

We're pleased to bring both @vexx32 and @rkeithhill onboard to the Engine WG, as well as @TobiasPSP and @jdhitsolutions to the Cmdlet WG. 

To move forward, we should probably get a final `Committee-Approved` label (as a formality) /cc @SteveL-MSFT 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2021-06-11 00:22 UTC, vexx32 approved these changes

2021-06-11 00:49 UTC, rkeithhill approved these changes

2021-06-14 17:53 UTC, daxian-dbw commented
```
/bin/bash --noprofile --norc /home/vsts/work/_temp/55508924-6b9e-4fb5-9ebd-2a4d95d6b426.sh
    docs/community/working-group-definitions.md
      139 | * @TobiasPSP 
      140 | * @jdhitsolutions 

>> 2 spelling errors found in 76 files
```

@joeyaiello The spelling checks failed in CI. You will have to update the `.spelling` file. You can run `mdspell '**/*.md' '!**/Pester/**/*.md' '!**/perf/**/*.md' --ignore-numbers --ignore-acronyms --en-us` and choose "add to ignore file" as a spelling issue is spotted, or you can manually update `.spelling`.

2021-06-14 19:44 UTC, rjmholt commented on docs/community/working-group-definitions.md
>  * @BrucePay
Is @BrucePay an Engine WG participant?

2021-06-15 19:47 UTC, SteveL-MSFT requested changes

2021-06-15 19:47 UTC, SteveL-MSFT commented on docs/community/working-group-definitions.md
> +* @jdhitsolutions
In general, I think names should be in alphabetical order

2021-06-15 19:58 UTC, SteveL-MSFT approved these changes

2021-06-15 21:09 UTC, merged