Use `bool?.GetValueOrDefault()` in `FormatWideCommand`
PowerShell/PowerShell pull request #15988
Opened 2021-08-24 15:15 UTC by xtqqczze

Contributes to #13791.

2021-08-24 16:21 UTC, xtqqczze commented
Verify Markdown Links.Verify links in /home/vsts/work/1/PowerShell/README.md.https://web.libera.chat/#powershell should work
Failed to complete request to "https://web.libera.chat/#powershell". 526 Response status code does not indicate success: 526 ().

Failure is unrelated.

2021-08-27 04:37 UTC, daxian-dbw requested changes

2021-08-28 16:43 UTC, xtqqczze commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-wide/Format-Wide.cs
> +            parameters.showErrorsInFormattedOutput = this.showErrorsInFormattedOutput.GetValueOrDefault();
[Muphry's law](https://en.wikipedia.org/wiki/Muphry%27s_law) strikes again: https://github.com/PowerShell/PowerShell/pull/13849#issuecomment-903717301 😛

2021-08-29 22:11 UTC, daxian-dbw approved these changes

2021-08-30 15:51 UTC, merged