New Parameter: Start-Sleep [-Duration] <timespan>
PowerShell/PowerShell pull request #16185
Opened 2021-10-01 20:55 UTC by IISResetMe

## PR Context

As originally propoesd in #12305, this PR adds a new `-Duration` parameter to the `Start-Sleep` cmdlet: 

```powershell
$duration = New-TimeSpan -Seconds 2

# -Duration accepts a [timespan] value
Start-Sleep -Duration $duration

# Supports positional binding
Start-Sleep $duration

# As well as pipeline binding
$duration |Start-Sleep
```

The existing parameter sets of `Start-Sleep` remain the same, and I have not changed the `DefaultParameterSetName`, but the pipeline binding _does_ interferes with the existing (buggy/counter-intuitive) binding behavior:
```
$ts = New-TimeSpan -Seconds 62 
$ts |Start-Sleep 
```

This PR also adds range validation support for `[timespan]` values via `[ValidateRange()]`:
```powershell
function Test-TimeMachine {
  param(
    # The time machine can only go back in time
    [ValidateRange('NonPositive')]
    [timespan]$Distance
  )
  
  # time-travel $Distance and back again
}
```

Strict range validation is not of much immediate use, but in a possible future with timespan literals we could do:
```powershell
function Request-Vacation {
  param(
    [ValidateRange(1d, 60d)]
    [timespan]$Duration
  )
  
  # ...
}
```

## PR Context

I believe this change is reasonable to make **without wrapping in an Experimental Feature** - the behavior that we're breaking ("piped `[timespan]` values are interpreted as seconds % 60") is rather counter-intuitive and deceptive. 

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2021-10-02 12:48 UTC, iSazonov commented
My understanding of PowerShell Committee conclusion in #12305 is that we need to implement something like
```powershell
Start-Sleep 3sec
Start-Sleep 1.5min
```
The PR is not follow the conclusion.

2021-10-02 21:57 UTC, IISResetMe commented
@iSazonov In order for that to ever work consistently, this change is needed. Without an option for binding `[timespan]` values the following would produce unexpected results:

```
# this returns after only 5 seconds
1m5sec |Start-Sleep

# ... for the same reason that this _currently_ returns after after 5 seconds
New-TimeSpan -Minutes 1 -Seconds 5 |Start-Sleep
```

2021-10-28 19:28 UTC, daxian-dbw requested changes

2021-11-24 01:34 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                    sleepTime = (int)Math.Floor(Duration.TotalMilliseconds);
@IISResetMe thoughts? No rush, but it would be nice to get this new parameter in 😄

2021-11-28 14:10 UTC, IISResetMe commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                    sleepTime = (int)Math.Floor(Duration.TotalMilliseconds);
@daxian-dbw  Sorry for the delay :) 

`TimeSpan` is backed by `long`, so this problem is not intrinsic to `TimeSpan`, but stems from the fact that we need to exchange the duration via a 32-bit integer - and I don't think changing `ValidateTimespanAttribute` to a enforce a limitation specific to a single cmdlet is a very good idea. 

Although not perfect, I think it's better to do partial validation on the parameter (eg. "ensure span is non-negative") and then throw on failure to convert to `[int]` inside.

2021-12-06 22:55 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                    sleepTime = (int)Math.Floor(Duration.TotalMilliseconds);
Thanks for the reply!

> Although not perfect, I think it's better to do partial validation on the parameter (eg. "ensure span is non-negative") and then throw on failure to convert to `[int]` inside.

That makes sense. Please go ahead to check if `Duration.TotalMilliseconds` is larger than `[int]::MaxValue`, and throw appropriate error when if so.

2021-12-22 06:00 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                    sleepTime = (int)Math.Floor(Duration.TotalMilliseconds);
@IISResetMe Please address the request.

2022-01-13 00:16 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                    sleepTime = (int)Math.Floor(Duration.TotalMilliseconds);
@IISResetMe A gentle ping. Hope you can address this when you get time.

2022-01-13 01:24 UTC, IISResetMe commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                    sleepTime = (int)Math.Floor(Duration.TotalMilliseconds);
Sorry, I'm not sure what's expected of me? Timespan duration exceeding `int.MaxValue` is taken care of in https://github.com/PowerShell/PowerShell/pull/16185/commits/3af5de7b2e2cc6afaf170a37cb1ee78b91ab0245 and negative timespans is already caught by parameter validation

2022-01-13 20:29 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                    sleepTime = (int)Math.Floor(Duration.TotalMilliseconds);
Oh, I didn't notice you already pushed the updates, thanks! Leaving a comment here when you pushed the commit would be helpful 😄

2022-01-13 20:36 UTC, daxian-dbw requested changes

2022-01-13 20:36 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Utility/resources/StartSleepStrings.resx
> +    <value>Provided TimeSpan exceeds maximum sleep duration</value>
Can you please call out the maximum sleep duration to be `int.MaxValue`?

2022-01-13 20:36 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Utility/resources/StartSleepStrings.resx
> +</root>
Please add a newline

2022-01-13 20:36 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Start-Sleep.Tests.ps1
> +    It "Should work properly when sleeping with a [TimeSpan]" {
Can you add a test to cover the `MaximumDurationExceeded` error?

2022-01-13 22:26 UTC, daxian-dbw approved these changes

2022-01-13 22:32 UTC, daxian-dbw reviewed
@IISResetMe Can you please address the CodeFactor issues? No need to address all, but just those issue related to your new changes.

2022-01-13 22:32 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
> +                                ErrorCategory.InvalidArgument, null));
```suggestion
                                ErrorCategory.InvalidArgument,
                                targetObject: null));
```

2022-01-13 23:19 UTC, daxian-dbw approved these changes

2022-01-14 00:42 UTC, IISResetMe commented
> @IISResetMe Can you please address the CodeFactor issues? No need to address all, but just those issue related to your new changes.

Thanks @daxian-dbw, I believe you already fixed all the relevant ones 😅  - the remaining issues all complain about documentation and I ignored those on purpose since it would break with the description convention in the existing comment docs (the property summaries all start with "Allows sleep time to be ...").

2022-01-14 01:39 UTC, merged

2022-01-14 01:41 UTC, daxian-dbw commented
I guess the other 4 are known to CodeRefactor and the remaining one is new :)
If I understand correctly, this PR is not supposed to close #12305, right?

2022-01-14 01:54 UTC, IISResetMe commented
> I guess the other 4 are known to CodeRefactor and the remaining one is new :) 

That must be the one for the property I added then, all good!

> [...] If I understand correctly, this PR doesn't mean to close #12305, but just one building step toward the ask in that issue, right?

That's exactly right! 

The other half of the puzzle in #12305 is implementing tokenization and parsing logic for timespan literals so we can do:

```
5sec374ms |Start-Sleep
```

I intend to pick this up too :)