Fix PSVersion parameter version checks and error messages for PowerShell core remoting
PowerShell/PowerShell pull request #16228
Opened 2021-10-12 16:15 UTC by PaulHigin

# PR Summary

This PR addresses issue #16062.  

## PR Context

Windows PowerShell supports remoting endpoint configurations that run on versions 2,3,4,5 of PowerShell.  However, the PowerShell core WinRM plugin only supports endpoints that run in the currently installed version of PowerShell core, and ignores the `-PSVersion` parameter.  This change removes the old supported version checks for the `-PSVersion` parameter on the configuration cmdlets and now throws a `not supported` error.

Also, `Start-Job` used to support running jobs in multiple WindowsPowerShell versions via the `-PSVersion` parameter, but now only supports version `5.1` in PowerShell core.  So this fix updates the version check and error message to provide correct information.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2021-11-02 05:37 UTC, daxian-dbw commented
@TravisEz13 and @SteveL-MSFT please review when you have time, thanks!

2021-11-10 22:29 UTC, JamesWTruher commented on src/System.Management.Automation/engine/remoting/commands/StartJob.cs
> +                if (value.Major != 5 || value.Minor != 1)
from a readability perspective, would it be more direct to the following:
```suggestion
                if (!(value.Major == 5 && value.Minor == 1))
```

2021-11-11 00:44 UTC, SteveL-MSFT requested changes

2021-11-11 00:44 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/remoting/commands/StartJob.cs
> +                if (!(value.Major == 5 && value.Minor == 1))
Do we need to check if this is Windows and return a different error if used on Linux/macOS?

2021-11-11 17:24 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Core/Job.Tests.ps1
> +    It "Verifies that -PSVersion is not supported except for version 5.1" -Skip:(-not $IsWindows) {
If we aren't doing a different error for non-Windows, then this test should also pass on non-Windows, right?

2021-11-26 07:01 UTC, SteveL-MSFT approved these changes

2021-12-01 23:54 UTC, merged