Fix #15186
PowerShell/PowerShell pull request #16563
Opened 2021-12-06 17:39 UTC by VeVrX

# PR Summary

Fix #15186 - To comply with RFC7230, empty body should not be added for Get Methods

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2021-12-06 21:44 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
> +            // Add the content headers except for Get Method
Can you please reference the RFC
```suggestion
            // Add the content headers except for Get Method per RFC7230
```

2021-12-06 21:44 UTC, TravisEz13 requested changes
see comments

2021-12-07 00:22 UTC, TravisEz13 commented
Two tests need to be updated:
https://dev.azure.com/powershell/PowerShell/_build/results?buildId=91101&view=logs&j=6cde3b71-baca-5747-8e0b-9d2766aa716f&t=47203bc9-c6f6-5ea0-f0a9-178d83600668&l=1580

2021-12-07 03:09 UTC, iSazonov approved these changes

2021-12-15 04:02 UTC, iSazonov commented
Oh, it is dup of #16587 and it seems the fix cover more scenarios but haven't tests. We need resolve the conflict and combine the PRs.

2021-12-17 22:59 UTC, SteveL-MSFT commented
Closing this PR as https://github.com/PowerShell/PowerShell/pull/16587 covers this and has necessary test changes

2021-12-17 22:59 UTC, closed without merging

2021-12-18 07:07 UTC, iSazonov commented
@VeVrX Thanks for your contribution! Sorry for the PR conflict.