[WIP] Add -ConfigurationFile command line parameter to pwsh.exe
PowerShell/PowerShell pull request #17172
Opened 2022-04-21 18:45 UTC by PaulHigin

# PR Summary

This PR adds a new `-ConfigurationFile` command line parameter to pwsh.exe, that takes a path to a .pssc configuration file.

## PR Context

This new command line parameter will allow PowerShell interactive or server mode sessions to run in a session configured by the provided .pssc file.  

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2022-04-22 07:50 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
> +            "configurationfile",
ABC-order?

```suggestion
            "configurationfile",
            "configurationname",
```

2022-04-22 07:50 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
> +                else if (MatchSwitch(switchKey, "configurationfile", "configurationf"))
ABC-order too?

2022-04-22 07:50 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
> +        internal string? ConfigurationFile
ABC-order too?

2022-04-22 07:50 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
> +        // Collection<CommandParameter> initialCommandArgs
Why do we need the comment?

2022-04-22 07:50 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
> +                else if (MatchSwitch(switchKey, "configurationfile", "configurationf"))
It seems it makes no sense to have the short name "configurationf".

2022-04-22 07:50 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
> +-ConfigurationFile | -configurationf
It seems it makes no sense to have the short name "configurationf".

2022-04-22 07:50 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
> +            "AssembliesToLoad"
Maybe sort the list for readability?

2022-04-22 07:50 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
> +        private static readonly HashSet<string> SupportedConfigOptions = new HashSet<string>(StringComparer.InvariantCultureIgnoreCase)
Can we use OrdinalIgnoreCase?

2022-04-22 07:50 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
> +        private static readonly HashSet<string> UnsupportedConfigOptions = new HashSet<string>(StringComparer.InvariantCultureIgnoreCase)
The same.

2022-04-22 07:50 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
> +            "PowerShellVersion"
The same for sorting.

2022-04-22 07:50 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
> +                if (!(key is string keyName))
Does follow work?
```suggestion
                if (key is not string keyName)
```

2022-04-22 07:50 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
> +                    }
If we throw on "unsupported" why do we nest this in `if (!SupportedConfigOptions.Contains(keyName))` condition? Should it has higher priority?

2022-05-25 22:49 UTC, JamesWTruher requested changes

2022-05-25 22:49 UTC, JamesWTruher commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
> +        internal string? ConfigurationFile
could you be sure to add telemetry for this new parameter? you may need to rebase.

2022-05-25 22:49 UTC, SteveL-MSFT commented
Need to re-enable `New-PSSessionConfigurationFile` cmdlet for non-Windows

2022-05-26 16:43 UTC, PaulHigin commented
/rebase

2022-05-26 21:57 UTC, PaulHigin commented
Rather than trying to rebase, I have created a new PR with the changes for this new feature (#17447).

2022-05-26 21:57 UTC, closed without merging