Re-enable ReadyToRun for release build
PowerShell/PowerShell pull request #17838
Opened 2022-08-03 23:03 UTC by SteveL-MSFT

# PR Summary

It appears that we had a workaround in place due to a ReadyToRun issue and we never re-enabled it.  This PR re-enables ReadyToRun for release builds.

## PR Context

We had a PR awhile back https://github.com/PowerShell/PowerShell/blob/master/PowerShell.Common.props#L140-L142 that disabled ReadyToRun due to a .NET 7 issue. 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2022-08-03 23:31 UTC, TravisEz13 approved these changes

2022-08-03 23:33 UTC, TravisEz13 commented
Tests are failing due to: 
https://dev.azure.com/powershell/PowerShell/_build/results?buildId=105745&view=logs&j=8579d1dd-da9d-5760-afc4-fb4c05cf5d6d&t=236f801b-8fac-50c5-f817-425a182daa54&l=278

2022-08-03 23:33 UTC, TravisEz13 commented
/rebase

2022-08-03 23:33 UTC, TravisEz13 commented
/remind me in 1 day

2022-08-03 23:52 UTC, daxian-dbw commented
All CIs failed because powershell cannot be started ... it seems the dotnet bug was not fixed
```
Exception: /home/vsts/work/1/s/tools/buildCommon/startNativeExecution.ps1:40
Line |
  40 |                  throw $errorMessage
     |                  ~~~~~~~~~~~~~~~~~~~
     | Execution of { & $powershell $PSFlags -c $command } by
     | build.psm1: line 1492 failed with exit code 64
```

2022-08-04 03:15 UTC, iSazonov approved these changes

2022-08-04 15:12 UTC, PaulHigin requested changes

2022-08-04 15:12 UTC, PaulHigin commented on PowerShell.Common.props
> -    <!-- disable ReadyToRun due to issue: https://github.com/dotnet/runtime/issues/65412
Please update this with the new issue preventing us from using ReadyToRun.

https://github.com/dotnet/runtime/issues/72550

2022-08-04 15:13 UTC, PaulHigin commented
This failure is a different issue than the original one back in February.  The comment in the file should be updated to reflect the new dotNet issue preventing the use of ReadyToRun.

https://github.com/dotnet/runtime/issues/72550

2022-08-04 16:45 UTC, iSazonov commented
I guess .Net team will issue fixed version of the Preview7?

2022-08-04 17:20 UTC, daxian-dbw commented
We are currently building with .NET 7 preview.7, so the fix is definitely not in preview.7. I will close this one and open a new PR to update the comment.

2022-08-04 17:20 UTC, closed without merging