Ensure error message resets the color
PowerShell/PowerShell pull request #17904
Opened 2022-08-15 20:54 UTC by SteveL-MSFT

# PR Summary

Prior to this change, after writing the error message if your prompt doesn't set any colors, the error color (default red) would continue to write to output.

Looked at changing it so that the color resets at writeline() time but that didn't work correctly across multiple lines as they should all be red, but because lines expect color to be retained, they would show incorrectly.

Ultimately, decided that the error message itself should reset the color (which also means that all output needs to reset at the end rather than expecting PS or ConsoleHost to fix it).

Manually tested with ConciseView and NormalView using:

```powershell
write-error 1;"hello"
```

Where the error should be in red even if multiple lines, but `hello` should be default foreground/background color.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/17885

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2022-08-17 23:22 UTC, daxian-dbw requested changes

2022-08-18 18:18 UTC, daxian-dbw commented
I cherry-picked the changes to 7.2.6 branch trying to make sure the changes work on 7.2.next. It turns out this works fine on Windows but not so well on Linux:

![screenshot](https://user-images.githubusercontent.com/127450/185465439-fc27f2e4-65c9-4aef-80e3-58e733536827.gif)

As shown in the GIF, the first prompt after `write-error` is in default color, but the following ones are in red color. So, it looks like writing out `Reset` VT sequence doesn't correctly reset the color change done by `Console.ForegroundColor = xxx`.

I also tried the 7.3 private build, and it works fine on both Windows and Linux. There are big changes in .NET 7 in the Console area, so I guess that was fixed in .NET 7. However, we need it to work well on 7.2.6 (.NET 6) if we want to backport this change.

2022-08-18 18:24 UTC, daxian-dbw commented
Given what I found above, I think we should not rely on setting `Console.ForegroundColor/BackgroundColor` for `NormalView/CategoryView`. Instead, we can translate `ConsoleColor` to VT sequences using `[System.Management.Automation.VTUtility]::GetEscapeSequence` and explicitly use VT sequences to set the color attribute, so that `Reset` at the end will reliably work on 7.2.6.

One caveat is that `[VTUtility]::GetEscapeSequence` seems to only convert foreground color, not background color, but that can be added pretty easily, I think.

2022-08-18 19:29 UTC, daxian-dbw commented
Actually, I have question: why do we have to use colors defined in `$Host.PrivateData` for the `NormalView` error rendering?
In my opinion, `$ErrorView` just defines how to render `ErrorRecord`, but not necessarily coupled with where the color should come from.

After introducing `$PSStyle`, we say this [in the doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals#:~:text=FromRgb(0xf5f5dc)-,%24PSStyle.,It%20replaces%20%24Host.):
> It replaces `$Host.PrivateData` as the way to manage colors for formatting rendering.

So, it feels to me we should just use `$PSStyle.Formatting.Error` regardless of `$ErrorView` as long as VT is supported.

2022-08-18 19:55 UTC, SteveL-MSFT commented
@daxian-dbw the feedback was that it broke existing users of NormalView who set the color in their $profile.  Perhaps we should have a WG review.

2022-08-18 21:01 UTC, daxian-dbw commented
> the feedback was that it broke existing users of NormalView who set the color in their $profile. Perhaps we should have a WG review.

It's already broken for other formatting color settings defined in `$host.PrivateData`, unless we want to make them all working. Marked for interactive-console WG review.

2022-08-22 16:18 UTC, SteveL-MSFT commented
Waiting on the WG-Interactive-Console group to decide what to do with PrivateData.

2022-08-26 23:09 UTC, daxian-dbw commented
The Interactive WG discussed `$Host.PrivateData` vs. `$PSStyle.Formatting`, and agreed that all formatting color settings should be in the same location, and `ErrorRecord` formatting should use `$PSStyle` instead of $host. See https://github.com/PowerShell/PowerShell/issues/17886#issuecomment-1229015174 for details.

2022-08-29 19:27 UTC, daxian-dbw commented
This PR is superseded by #17987

2022-08-29 19:28 UTC, closed without merging