Make experimental feature `PSRemotingSSHTransportErrorHandling` stable
PowerShell/PowerShell pull request #18046
Opened 2022-09-06 23:58 UTC by SteveL-MSFT

# PR Summary

PS-Committee reviewed this and this addresses a major issue with SSH remoting where native command use stderr as information and not an error which previously would kill the connection, so we want to take this fix

## PR Context

Per https://github.com/PowerShell/PowerShell/issues/17962 make stable

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2022-09-07 00:55 UTC, PaulHigin requested changes

2022-09-07 00:55 UTC, PaulHigin commented on src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
> +                    continue;
`continue;` statement is no longer needed.

2022-09-07 00:55 UTC, PaulHigin commented on src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
> -                    error = ReadError(reader);
Please also remove the `ReadError` method as it is no longer used.

2022-09-07 04:16 UTC, iSazonov approved these changes

2022-09-07 15:10 UTC, PaulHigin approved these changes

2022-09-08 00:34 UTC, merged

2022-09-12 23:48 UTC, adityapatwardhan commented
/backport to release/v7.3.0-rc.1

2022-09-26 15:29 UTC, jazzdelightsme commented
@SteveL-MSFT : will this be documented? I can't find any, and I don't know what this is, but it sounds interesting.

2022-09-26 18:12 UTC, daxian-dbw commented
@jazzdelightsme See https://github.com/PowerShell/PowerShell/pull/16205 for the description of the change.
It's more of a bug fix because stderr stream could contain non-error messages.