Use new LINQ Order() methods instead of OrderBy(static x => x)
PowerShell/PowerShell pull request #18395
Opened 2022-10-26 20:44 UTC by turbedi

Less code, a bit faster, less allocations.
Introduced in .NET 7 Preview 7

# PR Summary

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2022-10-26 21:28 UTC, turbedi commented
@microsoft-github-policy-service agree

2022-10-27 03:01 UTC, iSazonov approved these changes

2022-10-27 13:05 UTC, xtqqczze commented
@turbedi Please link to documentation for `Order<T>(IEnumerable<T>)` in the pull request description.

2022-10-27 14:08 UTC, turbedi commented
Added links to documentation to the related dotnet/runtime PR and issue.

2022-10-27 14:45 UTC, xtqqczze commented
@iSazonov Should we be caching `IComparer<PSObject>` objects, e.g. `CommandNameComparer`?

2022-10-27 15:10 UTC, xtqqczze commented
@xtqqczze We should investigate whether `List<CommandInfo> _accumulatedResults` can be of type `IEnumerable<CommandInfo>`, in order to avoid allocations.

2022-10-27 15:39 UTC, turbedi commented on src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
> +                var chosenVersionDirectory = Directory.EnumerateDirectories(tempAssemblyDirPath).Order().LastOrDefault();
Replaced the OrderBy().LastOrDefault() call with Max()

2022-10-27 15:42 UTC, xtqqczze requested changes

2022-10-27 16:27 UTC, iSazonov commented
@turbedi @xtqqczze I prefer to keep the PR simple and leave only the first commit.

2022-10-27 16:52 UTC, turbedi commented
> @turbedi @xtqqczze I prefer to keep the PR simple and leave only the first commit.

Done

2022-10-27 22:36 UTC, xtqqczze commented
@iSazonov @turbedi Could you please push a commit addressing rewording of code comments.

2022-10-28 03:34 UTC, iSazonov commented
> @iSazonov @turbedi Could you please push a commit addressing rewording of code comments.

I don't see wrong comments, but you could try to reword them in follow PR.

2022-10-28 06:19 UTC, turbedi commented
I can do a follow-up PR to apply the code suggestions and to rename/remove related comments.

2022-10-28 06:34 UTC, iSazonov commented
@daxian-dbw CommandPredictionTests doesn't work as expected 😕

2022-11-01 08:31 UTC, merged