Replace `msh` in public API comment based documentation with PowerShell equivalent
PowerShell/PowerShell pull request #18483
Opened 2022-11-07 20:40 UTC by SteveL-MSFT

# PR Summary

We are not generating and publishing API docs based on comment based docs and many still refer to MSH.  This PR updates those references to PowerShell equivalent.  The term monad is handled in a different PR.  Note non-public classes/methods aren't being changed in this PR.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/12839

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2022-11-07 20:50 UTC, JamesWTruher approved these changes
LGTM

2022-11-07 21:44 UTC, daxian-dbw approved these changes
LGTM

2022-11-07 22:53 UTC, PaulHigin requested changes

2022-11-07 22:53 UTC, PaulHigin commented on src/System.Management.Automation/engine/cmdlet.cs
> +    /// If your Cmdlet requires access to the PowerSHell Runtime (for example, variables in the session state,
```suggestion
    /// If your Cmdlet requires access to the PowerShell Runtime (for example, variables in the session state,
```

2022-11-07 23:32 UTC, PaulHigin approved these changes

2022-11-08 01:40 UTC, SteveL-MSFT commented
The Linux test failure is a timing issue with the prediction input test and not related to these changes.  Subsequent re-runs is just wasting compute at this point.

2022-11-08 02:08 UTC, daxian-dbw commented
You have to re-run the build stage in this case instead of the test stage. Re-runing now.

2022-11-08 03:27 UTC, merged

2022-11-16 16:59 UTC, sdwheeler commented on src/System.Management.Automation/engine/hostifaces/MshHost.cs
> +        ///     </PowerShell>
`<PowerShell></PowerShell>` is not a valid XML element for ///-comment documentation.