Update build.psm1 to require pwsh 7.0
PowerShell/PowerShell pull request #18556
Opened 2022-11-14 20:58 UTC by xtqqczze

2022-11-15 03:37 UTC, iSazonov approved these changes

2022-11-15 22:01 UTC, daxian-dbw commented
@adityapatwardhan @TravisEz13 Can you review and see if you have any concerns?

2023-02-16 23:30 UTC, TravisEz13 requested changes
There are still many places we use Windows PowerShell

2023-03-07 16:53 UTC, xtqqczze commented
I see #19040 reverted the changes to `build.psm1` that required `pwsh`, closing.

https://github.com/PowerShell/PowerShell/blob/e6e34adfb2cf0d02fb450b26ab92d081dc268c0c/build.psm1#L22
https://github.com/PowerShell/PowerShell/blob/089212c6b17356826ae88d4cfe92f7df534851e3/build.psm1#L22

https://github.com/PowerShell/PowerShell/compare/089212c6b17356826ae88d4cfe92f7df534851e3~1..089212c6b17356826ae88d4cfe92f7df534851e3#diff-1eb6991ceacad71a638a32bcf0a4ec906c7ec150f5086732ab6d7702a624914aL22

2023-03-07 16:53 UTC, closed without merging