Replace DllImport with LibraryImport for WNetGetConnection
PowerShell/PowerShell pull request #18690
Opened 2022-11-30 18:38 UTC by iSazonov

# PR Summary

Contributes to #18553.

- Move constants to new file since they are used for some pinvokes and we will add more in follow PRs.
- Remove intermediate method
- Remove Windows code from compiling on Unix
- Remove duplicate code
- Replace DllImport with LibraryImport

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2022-12-01 17:00 UTC, SteveL-MSFT requested changes

2022-12-01 17:19 UTC, iSazonov commented on src/System.Management.Automation/engine/Interop/Windows/Errors.cs
> +        // ERROR_INSUFFICIENT_BUFFER
The line is comment for next line.

2022-12-01 17:29 UTC, iSazonov commented on src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs
> +    #if DEBUG
Done.

2022-12-01 17:30 UTC, iSazonov commented on src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs
> +                return -1;
Done.

2022-12-02 17:35 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/Interop/Windows/Errors.cs
> +        // ERROR_INSUFFICIENT_BUFFER
So you mean `ERROR_MORE_DATA` == `ERROR_INSUFFICIENT_BUFFER`?  If so, then it makes sense, but perhaps the comment needs more context like:

```csharp
// ERROR_MORE_DATA here is equivalent to ERROR_INSUFFICIENT_BUFFER for the DEBUG path
```

2022-12-02 17:46 UTC, iSazonov commented on src/System.Management.Automation/engine/Interop/Windows/Errors.cs
> +        // ERROR_INSUFFICIENT_BUFFER
Yes.
`ERROR_MORE_DATA` is in docs, `ERROR_INSUFFICIENT_BUFFER` is used by .Net team (perhaps this is in SDK itself?).

2022-12-02 17:49 UTC, iSazonov commented on src/System.Management.Automation/engine/Interop/Windows/Errors.cs
> +        // ERROR_INSUFFICIENT_BUFFER
I removed the comment at all since it doesn't add understanding.

2022-12-02 20:34 UTC, SteveL-MSFT approved these changes

2022-12-03 12:16 UTC, merged