Fix parser error for using statements
PowerShell/PowerShell pull request #19134
Opened 2023-02-11 15:53 UTC by MartinGC94

# PR Summary
Fixes a parser error where an invalid namespace would cause the parser to crash when attempting to resolve a type name. For example: `using namespace [System];[S`

## PR Context
Fixes https://github.com/PowerShell/PowerShell/issues/17113

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2023-02-22 16:33 UTC, iSazonov commented
What about `using namespace !!!.!!!`?

2023-02-22 17:32 UTC, MartinGC94 commented
> What about `using namespace !!!.!!!`?

I haven't checked, but I'm fairly certain it's still allowed with this change. While it would certainly be nice if the parser prevented every invalid namespace entry, the main purpose of this change is just to fix the exception thrown when specific characters are used, see: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/ast.cs#L8457

2023-02-23 04:33 UTC, iSazonov commented
> For this issue, there are 2 potential fixes:

> - make using namespace to error on invalid namespace names
> - make the constructor of TypeName to tolerate invalid namespace names
It feels to me option 1 is the right one to go with, but it's not trivial to validate if the namespace name is legitimate using the C# identifier definition.

Although @daxian-dbw pointed out that the first solution is preferable I think full solution should include both since it is impossible to manually check whether a string valid namespace without direct test with the constructor.
I'd prefer to do formal notation check on first step (with Regex) and then try constructor. This allows us to make useful error messages and suggestions and block incorrect inputs.

2023-02-23 19:34 UTC, MartinGC94 commented
@iSazonov Using statements cannot be so strict during parsing because types can be created on the fly like this:

```
using namespace DemoNamespace
Add-Type -TypeDefinition @'
namespace DemoNamespace
{
    public class Hello
    {
        public static void World()
        {
            System.Console.WriteLine("Hello World");
        }
    }
}
'@
[Hello]::World()
```
I agree that the syntax check itself could be made more thorough.

2023-02-24 04:05 UTC, iSazonov commented
@MartinGC94 I mean the checks are performed at different times.
As for Regex we could start with simple one. I don't think we should be so strong as C# compiler. Our intention is to make useful error message instead of unexpected exception.

2023-02-24 05:57 UTC, MartinGC94 commented
@iSazonov If the intent is just to prevent unintentional exceptions then the current checks should be fine. Invalid namespaces like `using namespace !!!.!!!` won't throw any errors but they obviously won't do anything useful either.  
If you want, I can easily write a regex with the rules I think namespace identifiers have, I'm just saying there's a good chance I'll make a mistake because I don't fully understand the spec.

2023-02-24 16:56 UTC, iSazonov commented
You could play with `[regex]::IsMatch("a.q.w", "^([\p{L}_][\p{L}\p{Pc}\p{Nd}\p{Cf}\p{M}]*)(\.[\p{L}_][\p{L}\p{Pc}\p{Nd}\p{Cf}\p{M}]*)*$")`

For reference https://www.regular-expressions.info/unicode.html

2023-03-01 04:52 UTC, iSazonov commented on src/System.Management.Automation/engine/parser/Parser.cs
>                  && !Regex.IsMatch(stringAst.Value, @"^([\p{L}_][\p{L}\p{Pc}\p{Nd}\p{Cf}\p{M}]*)(\.[\p{L}_][\p{L}\p{Pc}\p{Nd}\p{Cf}\p{M}]*)*$"))
Please add comment with daxian-dbw's links to explain the Regex.

2023-05-15 22:38 UTC, JamesWTruher commented
while I agree that this is a problem, I'm concerned about this approach. It seems that the issue is that `new TypeName` is not expected to throw and it clearly will under some circumstances. A simpler approach might be to address _that_.
I tried this approach and it seems to produce the proper result:

```csharp
TypeName newTypeName;
try
{
   newTypeName = new TypeName(typeName.Extent, newTypeNameToSearch);
}
catch (Exception e)
{
   exception = e;
   break;
}
```

this is around line 400 in engine/parser/TypeResolver.cs
here's the error message with this implementation:

```powershell
PS> using namespace [system];[s                   
ParserError: 
Line |
   1 |  using namespace [system];[s
     |                             ~
     | Missing ] at end of attribute or type literal.
```

After more consideration, a `TypeName.TryCreate` might be an even better approach (to enable better inlining) then checking to see if we were able to create it.

2023-05-15 22:39 UTC, JamesWTruher requested changes
please see my comments in the conversation

2023-05-16 20:23 UTC, MartinGC94 commented
@JamesWTruher I agree that adding `TypeName.TryCreate` could be useful but should it be in place of the existing changes that makes the namespace parsing more strict? Or in addition to it? I think it would be useful to have the parser show an error for invalid namespaces.

2024-01-31 00:53 UTC, daxian-dbw commented
Superseded by #21162. @MartinGC94 and @iSazonov Thanks for your initial investigation! I have called out the thanks to both of you in the new PR.

2024-01-31 00:53 UTC, closed without merging