-Encoding add ANSI option
PowerShell/PowerShell pull request #19298
Opened 2023-03-08 23:51 UTC by CarloToso

# PR Summary

- Add ANSI option to -Encoding
- Small cleanup
- Reorder stuff

-Encoding ANSI equals to `[System.Text.Encoding]::GetEncoding([CultureInfo]::CurrentCulture.TextInfo.ANSICodePage)`
or `-Encoding [CultureInfo]::CurrentCulture.TextInfo.ANSICodePage`

## PR Context
Fixes https://github.com/PowerShell/PowerShell/issues/6562 @mklement0 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2023-03-08 23:55 UTC, mklement0 commented
Thanks for tackling this, @CarloToso.

2023-03-09 06:41 UTC, iSazonov reviewed
Please add tests

2023-03-09 08:34 UTC, CarloToso commented on src/System.Management.Automation/utils/EncodingUtils.cs
> +        internal const string Unknown = "unknown";
I ordered them ABC (TabCompletionResults) + ABC (Others), is it ok?

2023-03-09 08:49 UTC, iSazonov commented on src/System.Management.Automation/utils/EncodingUtils.cs
> +        internal const string Unknown = "unknown";
It is one list of constants so I'd sort it as whole.

2023-03-09 08:55 UTC, CarloToso commented on src/System.Management.Automation/utils/EncodingUtils.cs
> +        internal const string Unknown = "unknown";
done

2023-03-09 19:05 UTC, CarloToso commented
Unrelated error

2023-03-10 03:26 UTC, iSazonov approved these changes

2023-03-13 17:57 UTC, SteveL-MSFT approved these changes

2023-03-13 17:59 UTC, SteveL-MSFT commented
This change is adding to an already custom list, so I don't believe there's a concern supporting ANSI encoding

2023-03-13 18:13 UTC, daxian-dbw requested changes

2023-03-13 19:43 UTC, CarloToso commented on src/System.Management.Automation/utils/EncodingUtils.cs
>                  Ascii, BigEndianUnicode, BigEndianUtf32, OEM, Unicode, Utf7, Utf8, Utf8Bom, Utf8NoBom, Utf32
done

2023-03-13 21:33 UTC, daxian-dbw approved these changes

2023-03-13 22:05 UTC, merged