WIP: fix unixmode to handle setuid/sticky when not executable
PowerShell/PowerShell pull request #20366
Opened 2023-09-25 20:46 UTC by JamesWTruher

# PR Summary

This is a fix for #20278 

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2023-09-26 04:55 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/UnixStat.Tests.ps1
> +                $i.UnixMode | Should -Be $Perm
```suggestion
                $i.UnixMode | Should -BeExactly $Perm
```

2023-09-29 05:19 UTC, iSazonov commented on src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
> +                    modeCharacters[0] = itemTypeTable[ItemType];
nit:
```c#
                    Span<char> modeCharacters = stackalloc char[10];
```

Also there are two common strings we could return as static (as we do in Windows case):
```
drwxr-xr-x
-rw-r--r--
```

2023-10-03 03:24 UTC, iSazonov approved these changes

2023-10-03 03:24 UTC, iSazonov commented on src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
> +                    if ((Mode & 0xFFF) == 292)
Maybe it is more readable use `UnixFileMode` consts here too instead of `292`?

2023-10-11 22:42 UTC, daxian-dbw requested changes

2023-10-11 22:42 UTC, daxian-dbw commented on src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
> +                    else if ((ItemType == ItemType.Directory) & ((Mode & 0xFFF) == 493))
```suggestion
                    else if (ItemType == ItemType.Directory & (Mode & 0xFFF) == 493)
```

2023-10-11 22:42 UTC, daxian-dbw commented on src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
>                  private readonly Dictionary<ItemType, char> itemTypeTable = new()
It's better to make this a static member, so you don't create the dictionary every time when creating a `CommonStat` object in `CopyStatStruct`.

2023-10-11 22:45 UTC, daxian-dbw commented on src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
> +                    else if ((Mode & 0xFFF) == 420)
```suggestion

                    if ((Mode & 0xFFF) == 420)
```
No need the `else`, given that the previous if block will return.

2023-10-11 23:27 UTC, daxian-dbw approved these changes
LGTM

2023-10-11 23:54 UTC, merged