docs: corrected grammatical errors in README.md
PowerShell/PowerShell pull request #20509
Opened 2023-10-17 19:26 UTC by alienishi

# PR Summary

I have corrected several grammatical errors in README.md.

## PR Context

Since README.md is like an instruction manual it should be error free.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2023-10-17 19:28 UTC, alienishi commented
@microsoft-github-policy-service agree

2023-10-17 19:29 UTC, alienishi commented
@iSazonov 
Please review my PR and if according to the guidelines please do merge it :)

2023-10-17 19:36 UTC, alienishi commented
@microsoft-github-policy-service agree company="Microsoft"

2023-10-17 21:36 UTC, daxian-dbw commented
@sdwheeler Can you please review the changes in this PR? Thanks!

2023-10-17 22:11 UTC, sdwheeler requested changes
I have a couple of minor suggestions.

2023-10-17 22:11 UTC, sdwheeler commented on README.md
> +for dealing with structured data (e.g., JSON, CSV, XML, etc.), REST APIs, and object models.
```suggestion
for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models.
```

2023-10-17 22:11 UTC, sdwheeler commented on README.md
> +Although this repository started as a fork of the Windows PowerShell codebase, changes made in this repository do not automatically make their way back to Windows PowerShell 5.1.
```suggestion
Although this repository started as a fork of the Windows PowerShell codebase, changes made in this repository are not automatically ported back to Windows PowerShell 5.1.
```

2023-10-18 17:59 UTC, alienishi commented
Hi @sdwheeler 
Thanks for the suggestions and correcting me out 
I have made the changes :)

2023-10-18 18:04 UTC, sdwheeler approved these changes
LGTM

2023-10-18 18:17 UTC, alienishi commented
@iSazonov @SteveL-MSFT 
Please review my PR and if according to the guidelines please do merge it :)

2023-10-19 03:14 UTC, iSazonov approved these changes

2023-10-19 03:15 UTC, merged