Enable reproducible builds
PowerShell/PowerShell pull request #21077
Opened 2024-01-15 17:25 UTC by symbiogenesis

[Reproducible builds](https://github.com/dotnet/reproducible-builds) are an important way to improve the integrity of binary releases.

2024-07-31 19:19 UTC, TravisEz13 commented
/azp run PowerShell-CI-linux

2024-07-31 19:33 UTC, TravisEz13 commented on PowerShell.Common.props
> +      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
```suggestion
```

2024-07-31 20:43 UTC, TravisEz13 requested changes
Summary: our build doesn't work with these settings even if the CI passes.  Please file a feature request as we would need to do this work.

Some of the things you could do to move towards this:

- Please add the following as described here, so that we always link to the public repo, https://devblogs.microsoft.com/nuget/introducing-source-code-link-for-nuget-packages/

```
    <RepositoryUrl>https://github.com/powershell/powershell.git</RepositoryUrl> 
    <RepositoryType>git</RepositoryType>
```   
- After that, you should be able to set `PublishRepositoryUrl` to `true`

- Set `EmbedUntrackedSources` to `true` this should be safe.

- Set `ContinuousIntegrationBuild` properly

```
<PropertyGroup Condition="'$(OB_OUTPUTDIRECTORY)' != ''">
  <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
</PropertyGroup>
```

Notes:
- `DebugType` cannot be changed except for the Debug configuration
- I don't think we have any WPF, so, I don't think `IncludePackageReferencesDuringMarkupCompilation` is relevant.
- Some parts of the build are not reproducible:
  -  Adding modules
  - ResGen is not run as part of the build:  https://github.com/PowerShell/PowerShell/blob/8a8f2d4b234221c8ea2c47902c75d7db20fb5c33/build.psm1#L2487
  - TypeGen is not part of the build: https://github.com/PowerShell/PowerShell/blob/8a8f2d4b234221c8ea2c47902c75d7db20fb5c33/build.psm1#L2438
  - This analysis is for the main packages.

2024-08-01 03:25 UTC, iSazonov commented
> * Please add the following as described here, so that we always link to the public repo, https://devblogs.microsoft.com/nuget/introducing-source-code-link-for-nuget-packages/
> 
> ```
>     <RepositoryUrl>https://github.com/powershell/powershell.git</RepositoryUrl> 
>     <RepositoryType>git</RepositoryType>
> ```

Do we still need this? https://github.com/dotnet/sourcelink?tab=readme-ov-file#using-source-link-in-net-projects
> Starting with .NET 8, Source Link for the following source control providers is included in the .NET SDK and enabled by default:

>[GitHub](http://github.com/) or [GitHub Enterprise](https://enterprise.github.com/home)
[Azure Repos](https://azure.microsoft.com/en-us/services/devops/repos) git repositories (formerly known as Visual Studio Team Services)
[GitLab](https://gitlab.com/) 12.0+ (for older versions see [GitLab settings](https://github.com/dotnet/sourcelink?tab=readme-ov-file#gitlab))
[Bitbucket](https://bitbucket.org/) 4.7+ (for older versions see [Bitbucket settings](https://github.com/dotnet/sourcelink?tab=readme-ov-file#bitbucket))
If your project uses .NET SDK 8+ and is hosted by the above providers it does not need to reference any Source Link packages or set any build properties.

2024-08-26 18:21 UTC, closed without merging