Tee object can now store recieved error records to a variable.
PowerShell/PowerShell pull request #21565
Opened 2024-05-01 19:00 UTC by JamesWTruher

This addresses an aspect of issue #5184 

# PR Summary

This adds the parameter `-ErrorRecordVariable` (Alias `ERV`) to `Tee-Object`
if `Tee-Object` receives an ErrorRecord in the input stream and `-ErrorRecordVariable` is included,
`Tee-Object` will assign those error records to the variable. This enables the following scenario:

```powershell
PS> Get-Item $PSHOME,doesnotexist 2>&1 | Tee-Object -var out -ERV ee

    Directory: /Users/james/src/github/forks/jameswtruher/PowerShell-1/src/powershell-unix/bin/Debug/net9.0/osx-x64

UnixMode         User Group         LastWriteTime         Size Name
--------         ---- -----         -------------         ---- ----
drwxr-xr-x      james staff        5/1/2024 11:34         9024 publish

PS> $out

    Directory: /Users/james/src/github/forks/jameswtruher/PowerShell-1/src/powershell-unix/bin/Debug/net9.0/osx-x64

UnixMode         User Group         LastWriteTime         Size Name
--------         ---- -----         -------------         ---- ----
drwxr-xr-x      james staff        5/1/2024 11:34         9024 publish

PS> $ee
Get-Item: Cannot find path '/Users/james/src/github/forks/jameswtruher/PowerShell-1/src/Microsoft.PowerShell.Commands.Utility/commands/utility/doesnotexist' because it does not exist.
PS>
```

It works with file, literalfile, and variable parameter sets.
This works with native executables as well, as when stderr is written, we create an error record.
Errors created by `Tee-Object` are emitted in the normal way, it is only the input object which is inspected and handled by this new behavior.
Note: the `2>&1` is required to ensure that the error stream is emitted into the output stream

## PR Context

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

2024-05-01 19:17 UTC, SteveL-MSFT requested changes

2024-05-01 19:17 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Tee-Object.Tests.ps1
> +        $results = Get-Item $PSHOME,doesnotexist1,$PWD,doesnotexist2 2>&1 | Tee-Object -Variable outputVar -ErrorRecordVariable errVar
I think you should have a test case with a native command to ensure that use case doesn't break

2024-05-01 19:59 UTC, SteveL-MSFT approved these changes
LGTM

2024-05-02 02:04 UTC, Jaykul commented
From the example, you seem to have _eaten_ the error!?

Tee-Object should still pass through errors, surely.

2024-05-02 02:07 UTC, Jaykul commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Tee-Object.Tests.ps1
> +        $results = Get-Item $PSHOME,doesnotexist1,$PWD,doesnotexist2 2>&1 | Tee-Object -File $tempFile -ErrorRecordVariable errVar
Can we add a test where you Tee _a second time_ to prove the error is still passed through?

2024-05-02 02:12 UTC, Jaykul commented
Incidentally, is it **even possible** to get output in `-OutVariable` or `-ErrorVariable` from this command?

I mean, even when I do, say `| Tee-Object -File Variable:\Foo` or `| Tee -File NoSuchDrive:\log.txt` I do not get an error.

It's weird to me that it has _two parameters_ for output and error variables, but the one we all **EXPECT** ... does not work. It's pretty confusing.

2024-05-06 21:52 UTC, SteveL-MSFT commented
> Incidentally, is it **even possible** to get output in `-OutVariable` or `-ErrorVariable` from this command?
> 
> I mean, even when I do, say `| Tee-Object -File Variable:\Foo` or `| Tee -File NoSuchDrive:\log.txt` I do not get an error.
> 
> It's weird to me that it has _two parameters_ for output and error variables, but the one we all **EXPECT** ... does not work. It's pretty confusing.

If you redirect `stderr` to `stdout` and pipe to `Tee-Object`, you'll get both into the output stream and can do whatever you want.  We thought the ask was to be able to handle `stderr` separately thus the new variable to de-multiplex it.  Certainly you could do this yourself just by looking at the type of object and this was a convenience feature.

2024-05-17 19:33 UTC, mklement0 commented
@SteveL-MSFT, while I can appreciate what this PR is trying to achieve, I think it is ultimately the wrong way to go about it, especially given that it _requires modifying the call that provides the input_ (`2>&1`) in order to work meaningfully.

* #20381 is a great extension to how `>` and `>>` work, but it is currently limited to _consuming_ the targeted stream; that is, unlike with the common `-*Variable` parameters, the stream isn't passed through.
 
* Extending the `> variable:foo` syntax to optionally support pass-through - [as previously discussed](https://github.com/PowerShell/PowerShell/issues/5184#issuecomment-343741446), where you yourself suggested something like `>| variable:foo` - strikes me as the better alternative to extending `Tee-Object`.

2024-05-20 18:41 UTC, SteveL-MSFT commented
@mklement0 at this time we're not entertaining changes to the pipe syntax `2>|`, for example, so within the confines of the current syntax both this change and the redirect to variable change should support the requested scenarios.  I would agree that `2>&1 | Tee-Object` isn't obvious, but it's supported today and this is just an extension of that

2024-05-20 19:09 UTC, mklement0 commented
@SteveL-MSFT: Note that, as currently described, this feature seems to provide no additional functionality beyond the following.

```powershell
$out = Get-Item $PSHOME, doesnotexist 2>variable:ee
```

Given that, along with:

* the obscurity of requiring `2>&1` in the upstream pipeline segment

* the departure from the `Tee-Object`'s core mandate - to pass data _through_ - which, from what it seems, won't be done for the `ErrorRecord` objects in the pipeline (a concern expressed earlier by @Jaykul's).

this still strikes me as not worthwhile - even if you're not willing to tackle something like `2>|`

2024-06-10 22:31 UTC, mklement0 commented
@SteveL-MSFT, assuming you still see value in this PR (if so, please let us know _why_),
please consider the "collateral damage" relative to the perceived benefit:

* Increased implementation complexity of `Tee-Object`
* Documentation effort.
* Increased cognitive load on users who need to scan the more complex command-line help / documentation, even though they may never avail themselves of this feature.

2024-10-30 19:59 UTC, closed without merging