Provide an unsupported message for 'Verb' parameter (#1691)
PowerShell/PowerShell pull request #2156
Opened 2016-09-01 19:00 UTC by charub

Add the 'Verb' parameter to Powershell core and add an unsupported message
for the same.

2016-09-01 19:00 UTC, msftclas commented
Hi __@charub__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Charu Bassi). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-02 00:04 UTC, msftclas commented
Hi __@charub__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Charu Bassi). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-02 00:17 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
> +                ErrorRecord er =  new ErrorRecord(new NotSupportedException(errorMessage), "NotSupportedException", ErrorCategory.NotInstalled, null);
can you change `ErrorCategory.NotInstalled` to `ErrorCategory.NotImplemented`?

2016-09-02 19:28 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +	It "Should give an error when Verb parameter is used" {
The error shouldn't happen in Windows PowerShell - right? So I'd expect a `-Skip`.

2016-09-02 19:29 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +		Start-Process -Verb runas -FilePath $pingCommand -ArgumentList $pingParam
Indentation is messed up, and this does not follow the pattern @JamesWTruher has specified for tests that throw, please follow his guidelines.

2016-09-02 20:54 UTC, charub commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +	It "Should give an error when Verb parameter is used" {
will add skip if not coreclr

2016-09-02 23:08 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Management/resources/ProcessResources.resx
> +    <value>The parameter '{0}' is not supported for the cmdlet '{1}' on this edition of Powershell.</value>
>Powershell

it should be Power**S**hell

2016-09-02 23:09 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +        try
the indentation of this `try` line is still not right.

2016-09-02 23:15 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +	$err.FullyQualifiedErrorId | Should be "NotSupportedException,Microsoft.PowerShell.Commands.StartProcessCommand"
You are still not following the guideline for validating expected exception. Please see the try/catch example in https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md

2016-09-13 23:13 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +		$err.FullyQualifiedErrorId | Should be "NotSupportedException,Microsoft.PowerShell.Commands.StartProcessCommand"
Can you please follow the try/catch pattern described in https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md#writing-pester-tests?

2016-09-13 23:15 UTC, daxian-dbw commented
Not all comments are addressed. If you have concerns on any comments, please feel free to bring them up.

2016-09-15 00:24 UTC, charub commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +		$err.FullyQualifiedErrorId | Should be "NotSupportedException,Microsoft.PowerShell.Commands.StartProcessCommand"
Made appropriate changes

2016-09-15 00:24 UTC, charub commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +        try
Corrected the indentation!

2016-09-15 00:24 UTC, charub commented on src/Microsoft.PowerShell.Commands.Management/resources/ProcessResources.resx
> +    <value>The parameter '{0}' is not supported for the cmdlet '{1}' on this edition of Powershell.</value>
Done!

2016-09-15 05:22 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +            $_.FullyQualifiedErrorId | Should be "NotSupportedException,Microsoft.PowerShell.Commands.StartProcessCommand"
>                            else if (error == 0x424)
                            {
                                // The API 'CreateProcessWithLogonW' depends on the 'Secondary Logon' service, but the component 'Microsoft-Windows-SecondaryLogonService' 
                                // is not installed in OneCoreUAP. We will get error code 0x424 when the service is not available.
                                message = StringUtil.Format(ProcessResources.ParameterNotSupported, "-Credential", "Start-Process");
                                er = new ErrorRecord(new NotSupportedException(message), "NotSupportedException", ErrorCategory.NotInstalled, null);
                            }

I find `NotSupportedException` may be thrown from Start-Process by other code path too. Can you please check the error message to see if it contains `-Verb`?

2016-09-15 05:23 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +
please remove the extra line.

2016-09-15 05:24 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> -
It seems better keep this new line.

2016-09-15 05:27 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +            Start-Process -Verb runas -FilePath $pingCommand -ArgumentList $pingParam -ErrorAction Stop
`-Verb` would trigger a terminating error, so `-ErrorAction stop` is unnecessary here.

2016-09-15 05:27 UTC, daxian-dbw requested changes

2016-09-15 17:33 UTC, charub commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> -
Done!

2016-09-15 17:51 UTC, charub commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +            Start-Process -Verb runas -FilePath $pingCommand -ArgumentList $pingParam -ErrorAction Stop
Removed erroraction stop

2016-09-15 17:52 UTC, charub commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +            $_.FullyQualifiedErrorId | Should be "NotSupportedException,Microsoft.PowerShell.Commands.StartProcessCommand"
checking if the exception message contains '-Verb'

2016-09-15 17:53 UTC, charub commented on test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
> +
Done!

2016-09-16 03:59 UTC, daxian-dbw approved these changes
LGTM.

2016-09-16 04:00 UTC, merged