Adding test coverage for Alias provider
PowerShell/PowerShell pull request #2264
Opened 2016-09-14 20:27 UTC by ChrisUbben

Could you both take a look at this for me? @Francisco-Gamino @JamesWTruher 
Thanks!

2016-09-14 20:27 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-14 22:42 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +Describe "Basic Valdiation of Alias Provider" -Tags "CI" {
This test is testing alias provider. It should not belong to the Management module. Please move the test file to the appropriate folder.

2016-09-14 22:42 UTC, daxian-dbw requested changes

2016-09-15 01:10 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +Describe "Basic Valdiation of Alias Provider" -Tags "CI" {
Also fix the spelling of validation.

2016-09-16 22:46 UTC, daxian-dbw commented
@Francisco-Gamino could you please review this PR?

2016-09-19 18:45 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +Describe "Basic Valdiation of Alias Provider" -Tags "CI" {
Fixed spelling of validation.
I talked to @JamesWTruher and he said to put these provider tests in Modules/Microsoft.PowerShell.Management/.

2016-09-19 21:55 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-21 19:19 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +        New-Item -Path Alias:\ -Name $testAliasName -Value $testAliasValue
Maybe add **> $null** to `New-Item`?

2016-09-21 19:20 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +        Remove-Item -Path 'Alias:\NewTestAlias' -ErrorAction SilentlyContinue
Please move `Remove-Item` to a finally block, so that it will be cleaned up even if the above `Should Be` failed.

2016-09-21 19:21 UTC, daxian-dbw requested changes

2016-09-21 20:13 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +        New-Item -Path Alias:\ -Name $testAliasName -Value $testAliasValue
Fixed. Thanks Dongbo!

2016-09-21 20:13 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +        Remove-Item -Path 'Alias:\NewTestAlias' -ErrorAction SilentlyContinue
Fixed. Thanks Dongbo!

2016-09-21 22:28 UTC, daxian-dbw approved these changes
LGTM

2016-09-21 22:28 UTC, merged