Improve ModulePath calculation and refactor related method names
PowerShell/PowerShell pull request #2265
Opened 2016-09-14 20:31 UTC by daxian-dbw

Resolving #1744

The PR include following changes:

1. Refactor method names related to module path calculation.
2. Improve the logic that detects if a module path is PSHome module path derived from a different powershell core instance.
3. Add more sxs module path tests.

2016-09-14 20:31 UTC, msftclas commented
Hi __@daxian-dbw__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Dongbo Wang). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-14 20:32 UTC, daxian-dbw commented
@mirichmo could you please review this PR?

2016-09-14 21:49 UTC, mirichmo commented on test/powershell/enginecore/ModulePath.Tests.ps1
> +        New-Item -Path $fakePSDepsFile -ItemType File -Force > $null
The creation of the fake powershell.exe and deps file should be done in a BeforeEach and After each for this test. It should not be cleaned up in the next test. I suggest using a Context to limit the BeforeEach and AfterEach to this test.

2016-09-14 21:54 UTC, mirichmo commented on test/powershell/enginecore/ModulePath.Tests.ps1
> +        New-Item -Path $fakePowerShell -ItemType File -Force > $null
The creation of the fake powershell.exe and deps file should be done in a BeforeEach and After each for this test. It should not be cleaned up in the next test. I suggest using a Context to limit the BeforeEach and AfterEach to this test.

2016-09-14 21:55 UTC, mirichmo commented on src/System.Management.Automation/engine/InitialSessionState.cs
>              // in his module path, then that will get loaded instead of the actual nested module (from the GAC - in our case)
Are all 4 commits necessary for the history, or can they be squashed?

2016-09-14 21:55 UTC, mirichmo requested changes
The code changes look good. I have one issue with the tests though.

2016-09-14 22:01 UTC, daxian-dbw commented on test/powershell/enginecore/ModulePath.Tests.ps1
> +        New-Item -Path $fakePowerShell -ItemType File -Force > $null
Will fix it.

2016-09-14 22:02 UTC, daxian-dbw commented on src/System.Management.Automation/engine/InitialSessionState.cs
>              // in his module path, then that will get loaded instead of the actual nested module (from the GAC - in our case)
I think we should keep them separate commits, especially the one that rename the method names.

2016-09-14 22:22 UTC, daxian-dbw commented on src/System.Management.Automation/engine/InitialSessionState.cs
>              // in his module path, then that will get loaded instead of the actual nested module (from the GAC - in our case)
I have squashed test changes into one commit.

2016-09-15 00:21 UTC, mirichmo approved these changes
LGTM

2016-09-15 00:22 UTC, merged