Adding test coverage for PSDrive provider
PowerShell/PowerShell pull request #2267
Opened 2016-09-14 20:32 UTC by ChrisUbben

Could you both take a look at this for me? @Francisco-Gamino  @JamesWTruher 
Thanks!

2016-09-14 20:32 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-14 22:39 UTC, daxian-dbw commented
Please fix the test failures in Travis CI.

2016-09-16 22:46 UTC, daxian-dbw commented
> test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1

The test is about PSDrive, which doesn't belong to Microsoft.PowerShell.Management module. Please move the file to an appropriate folder.
@Francisco-Gamino could you please review this PR?

2016-09-19 18:49 UTC, ChrisUbben commented
I talked to @JamesWTruher and he said to put these provider tests in Modules/Microsoft.PowerShell.Management/.

2016-09-21 18:49 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +        Remove-PSDrive -Name "NewDifferentPSDrive" -ErrorAction SilentlyContinue
`Remove-PSDrive` should be put in a finally block, so even if the above `Should Be` failed, the test drive can still be cleaned up.

2016-09-21 18:49 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +        $driveProp.PSDrive | Should Be $psDriveName
maybe it should be `$driveProp.PSDrive.Name | Should Be $psDriveName`

2016-09-21 18:53 UTC, daxian-dbw requested changes

2016-09-21 20:04 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +        Remove-PSDrive -Name "NewDifferentPSDrive" -ErrorAction SilentlyContinue
Fixed. Thanks Dongbo!

2016-09-21 20:04 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +        $driveProp.PSDrive | Should Be $psDriveName
Fixed. Thanks Dongbo!

2016-09-21 22:21 UTC, daxian-dbw approved these changes

2016-09-21 22:22 UTC, merged