Add test coverage for Command discovery and requires
PowerShell/PowerShell pull request #2285
Opened 2016-09-16 17:48 UTC by adityapatwardhan

Added some tests for command discovery and requires.

2016-09-16 17:48 UTC, msftclas commented
Hi __@adityapatwardhan__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Aditya Patwardhan). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-16 21:50 UTC, lzybkr commented
The test failure is in one of the added tests.  Please fix before we review.

2016-09-19 20:24 UTC, adityapatwardhan commented
@lzybkr The test failure has been fixed. Please have a look.

2016-09-21 17:17 UTC, lzybkr commented on test/powershell/Language/Scripting/Requires.Tests.ps1
> +                        @{command = "#requiresappID`r`n$foo = 1; $foo" ; testname = "appId with newline"}
You use double quoted strings, but `$foo` is not defined, so you're not parsing what you think you are.

2016-09-21 17:19 UTC, lzybkr commented on test/powershell/Language/Scripting/Requires.Tests.ps1
> +                $_.FullyQualifiedErrorId | Should Be "ParseException"
You should validate the more specific error id. `ScriptBlock.Create` is wrapping the parse exceptions, but if you used `Parser.ParseInput`, you could validate a better error id, e.g. `ScriptRequiresInvalidFormat`.

2016-09-21 17:21 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +		setup -f testscripp.ps1 -content "TestScripp"
You have mixed tabs and spaces or the indentation is messed up.

2016-09-21 17:24 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +        setup -f testscript.ps1 -content "TestScript"
I don't think this file is meant to be run, but if it did, it would cause a stack overflow because it's recursive.

2016-09-21 17:27 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            throw "Command '$command' was found"
As stated, the error text sounds like success. I think it could be clearer that it's a failure, e.g.: `Should not have found $command`

2016-09-21 17:29 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            $env:PSMODULEPATH += [System.IO.Path]::PathSeparator + "$TestDrive" + [System.IO.Path]::PathSeparator + "$TestDrive"
I think I'd not use `+=` to ensure we don't accidentally find something else, however unlikely that might be.

2016-09-21 17:32 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            $aliasResult | Should Not BeNullOrEmpty
Maybe use `Should BeOfType` instead?

2016-09-21 17:52 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            Remove-Item alias:AliasCommandDiscoveryTest -Force -ErrorAction SilentlyContinue
Aliases are scoped so this isn't necessary, it should be removed automatically either after the `It` block runs, or if that was dot sourced, after the script exits.

2016-09-21 17:53 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            throw "'CyclicAliasA' should be not found"
This message is incorrect - the alias should be found.  A more accurate message would be `execution should not reach here` or something like that.

2016-09-21 17:54 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +    It "Cyclic aliases" {
You should also add a test with indirect cycles a=>b=>c=>a

2016-09-21 17:54 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            Remove-Item Alias:\CyclicAliasA -ErrorAction SilentlyContinue -Force
Again - not needed.

2016-09-21 17:55 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +         $commands = @(Get-Command)
`@()` not needed

2016-09-21 17:55 UTC, lzybkr commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +		foreach($command in $commands)
Indentation or mixed tabs/spaces

2016-09-21 17:57 UTC, lzybkr requested changes

2016-09-22 00:10 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +		setup -f testscripp.ps1 -content "TestScripp"
Fixed.

---
In reply to: [79886355](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79886355) [](ancestors = 79886355)

2016-09-22 00:12 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            throw "Command '$command' was found"
Fixed. Thanks.

---
In reply to: [79887793](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79887793) [](ancestors = 79887793)

2016-09-22 00:13 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            $env:PSMODULEPATH += [System.IO.Path]::PathSeparator + "$TestDrive" + [System.IO.Path]::PathSeparator + "$TestDrive"
Fixed. Used = instead.

---
In reply to: [79888252](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79888252) [](ancestors = 79888252)

2016-09-22 00:20 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            $aliasResult | Should Not BeNullOrEmpty
Thanks, did not know this existed.

---
In reply to: [79888903](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79888903) [](ancestors = 79888903)

2016-09-22 00:21 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            Remove-Item alias:AliasCommandDiscoveryTest -Force -ErrorAction SilentlyContinue
Removed.

---
In reply to: [79893261](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79893261) [](ancestors = 79893261)

2016-09-22 00:23 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            Remove-Item Alias:\CyclicAliasA -ErrorAction SilentlyContinue -Force
Removed.

---
In reply to: [79893698](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79893698) [](ancestors = 79893698)

2016-09-22 00:25 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +    It "Cyclic aliases" {
Added one more test.

---
In reply to: [79893640](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79893640) [](ancestors = 79893640)

2016-09-22 00:25 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +            throw "'CyclicAliasA' should be not found"
Resolved.

---
In reply to: [79893524](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79893524) [](ancestors = 79893524)

2016-09-22 00:27 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +         $commands = @(Get-Command)
Fixed.

---
In reply to: [79893791](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79893791) [](ancestors = 79893791)

2016-09-22 00:28 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +		foreach($command in $commands)
Fixed.

---
In reply to: [79893848](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79893848) [](ancestors = 79893848)

2016-09-22 00:40 UTC, adityapatwardhan commented on test/powershell/enginecore/CommandDiscovery.Tests.ps1
> +        setup -f testscript.ps1 -content "TestScript"
Fixed

---
In reply to: [79887091](https://github.com/PowerShell/PowerShell/pull/2285#discussion_r79887091) [](ancestors = 79887091)

2016-09-26 20:35 UTC, lzybkr approved these changes

2016-09-26 20:36 UTC, merged