Adding test coverage for Registry provider
PowerShell/PowerShell pull request #2307
Opened 2016-09-19 20:18 UTC by ChrisUbben

Could you both take a look at this for me? @Francisco-Gamino @JamesWTruher 
Thanks!

2016-09-19 20:19 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-21 20:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +            New-ItemProperty -Path $testKey -Name $testPropertyName -Value $testPropertyValue -PropertyType DWORD
These should be redirected to $null as well

2016-09-21 20:20 UTC, mirichmo requested changes

2016-09-21 20:29 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +Describe "Validate Registry Provider" -Tags "CI" {
I talked to @JamesWTruher, he said that this is the more correct way of skipping all tests in a describe block:  
#skip all tests on non-windows platform  
$originalDefaultParameterValues = $PSDefaultParameterValues.Clone()  
if ($IsWindows -eq $false) {  
      $PSDefaultParameterValues["it:skip"] = $true  
 }

2016-09-21 20:36 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +            New-ItemProperty -Path $testKey -Name $testPropertyName -Value $testPropertyValue -PropertyType DWORD
Fixed. Thanks Mike!

2016-09-21 21:05 UTC, mirichmo approved these changes

2016-09-23 00:14 UTC, merged