Adding test coverage for Variable provider
PowerShell/PowerShell pull request #2309
Opened 2016-09-19 22:40 UTC by ChrisUbben

Could you both take a look at this for me? @Francisco-Gamino @JamesWTruher 
Thanks!

2016-09-19 22:40 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-20 19:39 UTC, Francisco-Gamino commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +}
On Github, you need to an extra empty line.

2016-09-20 19:40 UTC, Francisco-Gamino commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +}
Should we add more variables to the test? You can see all built-in variables if you run "dir env:"

2016-09-20 22:34 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        $theError.FullyQualifiedErrorId.StartsWith("Argument") | Should be $true
Please follow the [error validation guidance for Pester tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md)

2016-09-20 23:53 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        $theError.FullyQualifiedErrorId.StartsWith("Argument") | Should be $true
Fixed. Thanks Mike!

2016-09-20 23:54 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +}
Added the new line.
We will analyze test coverage later and file a new issue with our results. At that point we will be adding additional test coverage.

2016-09-27 21:27 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +Describe "Validate basic negative test cases for Variable provider cmdlets" -Tags "CI" {
Negative test cases should be tagged "Feature"

2016-09-27 21:29 UTC, mirichmo requested changes

2016-09-27 21:29 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        $theError.FullyQualifiedErrorId | Should be "Argument,Microsoft.PowerShell.Commands.NewItemCommand"
Your update for handling negative test cases did not get posted

2016-09-29 19:17 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +Describe "Validate basic negative test cases for Variable provider cmdlets" -Tags "CI" {
Fixed. Thanks Mike!

2016-09-29 19:23 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        $theError.FullyQualifiedErrorId | Should be "Argument,Microsoft.PowerShell.Commands.NewItemCommand"
I changed
 $theError.FullyQualifiedErrorId.StartsWith("Argument") | Should be $true
to
$theError.FullyQualifiedErrorId | Should be "Argument,Microsoft.PowerShell.Commands.NewItemCommand"

Is this not what you were referring to when you said "Please follow the error validation guidance for Pester tests"?

2016-09-29 20:18 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        $theError.FullyQualifiedErrorId | Should be "Argument,Microsoft.PowerShell.Commands.NewItemCommand"
The guidance is this:
```
Try {
    New-Item -Name $testVarName -Value 5 -Path "Variable:" -ErrorAction Stop 
    throw "Expected exception not throw"
}
catch {
    $_.FullyQualifiedErrorId | Should be "Argument,Microsoft.PowerShell.Commands.NewItemCommand"
}
```

2016-09-29 21:56 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        $theError.FullyQualifiedErrorId | Should be "Argument,Microsoft.PowerShell.Commands.NewItemCommand"
I understand. I have fixed this.
Thanks Mike!

2016-09-30 16:01 UTC, mirichmo requested changes

2016-09-30 16:01 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        catch { $theError = $_ }
This still doesn't match the requested change. The "Should Be" assertion should be within the catch block

2016-09-30 19:05 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Variable.Tests.ps1
> +        catch { $theError = $_ }
Sorry about that. 
I have mad the changes now.

2016-10-03 17:38 UTC, mirichmo approved these changes

2016-10-03 17:39 UTC, merged