Fix $? assignment to not crash powershell
PowerShell/PowerShell pull request #2320
Opened 2016-09-20 21:14 UTC by daxian-dbw

Fix #2243 

There is another fix for this bug, which is to remove `|| (details.LocalTupleIndex == ForceDynamic && details.Automatic)` at
```
var orderedLocals = (from details in _variables.Values
                     where (details.LocalTupleIndex >= 0 || (details.LocalTupleIndex == ForceDynamic && details.Automatic))
```
I think it's OK to do so because the real automatic variable would have LocalTupleIndex set to be `ForceDynamic` only if there is type conversion or attributes associated with an assignment of the automatic variable, such as `[datetime]$pscmdlet=1` or `[ValidateNotNullOrEmpty]$PSCmdlet =1`. In that case, we will throw parsing error in semantic check at https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/SemanticChecks.cs#L739

cc @lzybkr

2016-09-20 21:14 UTC, msftclas commented
Hi __@daxian-dbw__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Dongbo Wang). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-20 21:50 UTC, vors commented
:shipit:

2016-09-21 17:11 UTC, lzybkr commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        & { [object]$_ = 1; $_ } | Should Be 1
Can we keep formatting changes in a different commit?

Ideally I'd like to see a tool fix all the tests for a few simple things, e.g. replace tabs, fix casing, don't use aliases, etc.

2016-09-21 17:12 UTC, lzybkr requested changes

2016-09-21 18:02 UTC, daxian-dbw commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        & { [object]$_ = 1; $_ } | Should Be 1
Sure, will keep the format changes in a different commit.

2016-09-21 20:00 UTC, lzybkr commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        { & ([ScriptBlock]::Create('$? = 1')) } | Should Throw
Do we need `[ScriptBlock]::Create`?  It seems like you only need:
```powershell
{ . { $? = 1 } } | Should Throw
{ & { $? = 1 } } | Should Throw
```

2016-09-21 20:02 UTC, daxian-dbw commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        { & ([ScriptBlock]::Create('$? = 1')) } | Should Throw
True. Will fix it.

2016-09-24 06:14 UTC, daxian-dbw commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        & { [object]$_ = 1; $_ } | Should Be 1
Fixed.

2016-09-24 06:14 UTC, daxian-dbw commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        { & ([ScriptBlock]::Create('$? = 1')) } | Should Throw
Fixed. Please take another look when you have time. Thanks!

2016-09-24 21:09 UTC, lzybkr approved these changes

2016-09-26 18:56 UTC, merged