Fixing how the LocalAcccounts tests are skipped in Pester
PowerShell/PowerShell pull request #2335
Opened 2016-09-21 21:48 UTC by mirichmo

I updated the filter to conform to Pester guidance.

2016-09-21 21:48 UTC, msftclas commented
Hi __@mirichmo__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Mike Richmond). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-21 21:52 UTC, vors commented
@mirichmo can you provide a link to this guidelines?
I find this way of skipping them questionable and potentially leading to problems. Would like to discuss.

2016-09-21 22:39 UTC, lzybkr commented
The guidance is in Jim's PR: https://github.com/JamesWTruher/PowerShell-1/blob/f8db6811a267e8cb7b58ee0b37181716d4317316/docs/testing-guidelines/WritingPesterTests.md

2016-09-22 03:02 UTC, vors commented
The current approach is definitely better then what it used to be. The problem that I see is that it's too verbose. There are a lot of Describe blocks with few It blocks inside and it creates an overwhelmingly verbose massaging to achieve the goal. I think it's appropriate to use a modification of this technique here: it could be done once per file, at the beginning, and then the rest of the file can be wrapped in try-finally, where previous parameters are restored in finally. It's less idiomatic, but saves a lot of copy-paste.

2016-09-22 17:12 UTC, mirichmo commented
The motivation for using this technique is that the tests are tracked consistently across all platforms. The original method caused these tests to disappear when run on non-Windows platforms. Now they can at least be tracked as skipped.

2016-09-22 17:29 UTC, vors commented
Exactly, that's why I said it's better then it used to be. I'm just proposing to use a less verbose variation of the skipping, do it as a top-level thing on the file. @JamesWTruher can you comment?

2016-09-22 18:15 UTC, mirichmo commented
I uncovered one wrinkle to this test skipping technique when fixing the tests. It becomes less clean when tests need to do actual work in the BeforeAll, AfterAll, BeforeEach, and AfterEach. This is what I settled on:
``` powershell
    BeforeAll {
        #skip all tests on non-windows platform
        $originalDefaultParameterValues = $PSDefaultParameterValues.Clone()
        $PSDefaultParameterValues["it:skip"] = ($IsWindows -eq $false)

        if ($PSDefaultParameterValues["it:skip"] -eq $false) {
            <work>
        }
    }
    AfterAll {
        if ($PSDefaultParameterValues["it:skip"] -eq $false) {
            <work>
        }
        $global:PSDefaultParameterValues = $originalDefaultParameterValues
    }
    BeforeEach {
        if ($PSDefaultParameterValues["it:skip"] -eq $false) {
            <work>
        }
    }

    AfterEach {
        if ($PSDefaultParameterValues["it:skip"] -eq $false) {
            <work>
        }
    }
```

2016-09-22 18:27 UTC, lzybkr commented
We could use a convention like:
```powershell
BeforeAll {
        #skip all tests on non-windows platform
        $originalDefaultParameterValues = $PSDefaultParameterValues.Clone()
        $skipIt = ($IsWindows -eq $false)
        $PSDefaultParameterValues["it:skip"] = $skipIt

        if ($skipIt) {
            # work
        }
    }
    AfterAll {
        if ($skipIt) {
            # work
        }
        $global:PSDefaultParameterValues = $originalDefaultParameterValues
    }
    BeforeEach {
        if ($skipIt) {
            # work
        }
    }

    AfterEach {
        if ($skipIt) {
            # work
        }
    }
```

I'm not really a fan of `PSDefaultParameterValues` though, so if enough people prefer to explicitly specify `-Skip:$skipIt`, I think I'd +1 that proposal.

2016-09-22 18:36 UTC, vors commented
I prefer explicit, because PSDefaultParameters contains global state and if something goes wrong it can mess-up the rest of execution royally. But for the bulk skip, explicit skip is too verbose.

2016-09-22 20:01 UTC, lzybkr commented
Maybe the right solution is to work with Pester to provide `-Skip` on `Describe` in such a way that reports everything we want. In the shorter term, we can live with this solution.

2016-09-23 21:20 UTC, mirichmo commented
@vors or @lzybkr it is ready for final review. Please take a look

2016-09-23 21:26 UTC, vors commented
We talked offline about the approach with @JamesWTruher and he agreed that it's too verbose. Please implement the top level try-finally.

2016-09-23 21:48 UTC, mirichmo commented
A top-level try-finally doesn't really shrink it all that much. This is what you end up with:

``` powershell
try {
  #skip all tests on non-windows platform
  $originalDefaultParameterValues = $PSDefaultParameterValues.Clone()
  $skipIt = ($IsWindows -eq $false)
  $PSDefaultParameterValues["it:skip"] = $skipIt

  Describe "Example for skipping a whole file" {
    BeforeAll {
        if ($skipIt) {
            # work
        }
    }
    AfterAll {
        if ($skipIt) {
            # work
        }
    }
    BeforeEach {
        if ($skipIt) {
            # work
        }
    }

    AfterEach {
        if ($skipIt) {
            # work
        }
    }
  }
}
finally {
  $global:PSDefaultParameterValues = $originalDefaultParameterValues
}
```
@JamesWTruher Please confirm this is what you want

2016-09-26 17:29 UTC, msftclas commented
Hi __@mirichmo__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Mike Richmond). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-09-26 22:28 UTC, mirichmo commented
@vors I made the try-catch change. It's ready for review now

2016-09-27 00:32 UTC, vors requested changes
Please, remove duplicated priority tags

2016-09-27 00:32 UTC, vors commented on test/powershell/Modules/Microsoft.PowerShell.LocalAccounts/Pester.Command.Cmdlets.LocalAccounts.LocalGroup.Tests.ps1
> +    Describe "Validate simple Get-LocalGroup" -Tags "CI", "Feature" {
In #2366 you mentioned that you addressed it.....

2016-09-27 00:32 UTC, vors commented on test/powershell/Modules/Microsoft.PowerShell.LocalAccounts/Pester.Command.Cmdlets.LocalAccounts.LocalGroup.Tests.ps1
> +    Describe "Validate simple New-LocalGroup" -Tags "CI", "Feature" {
Same comment

2016-09-27 17:54 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.LocalAccounts/Pester.Command.Cmdlets.LocalAccounts.LocalGroup.Tests.ps1
> +    Describe "Validate simple Get-LocalGroup" -Tags "CI", "Feature" {
I got most of them and missed those two. They are fixed now.

2016-09-27 23:30 UTC, vors approved these changes

2016-09-27 23:30 UTC, merged