Added feature level test coverage to Registry provider
PowerShell/PowerShell pull request #2417
Opened 2016-10-03 22:29 UTC by ChrisUbben

Adding more coverage to issue #2415
+ Added more cmdlet test coverage for Registry provider.
+ Moved "Verify Remove-ItemProperty Whatif" to the feature level tests

2016-10-03 22:29 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-04 22:31 UTC, mirichmo requested changes

2016-10-04 22:31 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +            $result."$testPropertyName" | Should Be $testPropertyValue
Include and Exclude should be verified in a measurable way here as well.

2016-10-04 22:31 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        It "Verfiy Piped Default Parameter" {
Spelling. Verify

2016-10-04 22:31 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        It "Verfiy Confirm" {
Bypass

2016-10-04 22:31 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        It "Verfiy Confirm" {
Bypass

2016-10-05 18:32 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +            $result."$testPropertyName" | Should Be $testPropertyValue
TL;DR Fixed.
You are right, I applied a path validation to all of the tests that I think it applies. This also found errors in my code so there are refactors in those areas as well.

2016-10-05 18:32 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +            $result."$testPropertyName" | Should BeNullOrEmpty
Fixed.

2016-10-05 18:32 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +            $result."$testPropertyName" | Should Be $testPropertyValue
Fixed.

2016-10-05 18:32 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        It "Verfiy Confirm" {
Fixed.

2016-10-05 18:32 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        It "Verfiy Confirm" {
Fixed.

2016-10-05 19:45 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-05 19:46 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-12 21:58 UTC, mirichmo approved these changes

2016-10-12 21:58 UTC, merged