Added feature level test coverage to PSDrive provider
PowerShell/PowerShell pull request #2418
Opened 2016-10-03 22:31 UTC by ChrisUbben

Adding more coverage to issue #2414
+ Added more cmdlet test coverage for PSDrive provider.
+ Changed common describe blocks into context blocks under 1 common describe block. (this is why the diff looks so messy)

2016-10-03 22:31 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-03 23:19 UTC, mirichmo requested changes

2016-10-03 23:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            Remove-PSDrive -Name $psDriveName -ErrorAction SilentlyContinue
-Force?

2016-10-03 23:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            $newDrive = New-PSDrive -Name "NewDifferentPSDrive" -PSProvider FileSystem -Root $psDriveRoot
This should be safe to put within the try. The finally silently continues.

2016-10-03 23:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            Remove-PSDrive -Name ${psDriveName} -ea SilentlyContinue
ea ==> ErrorAction
Tests shouldn't use aliases unless specifically testing aliases

2016-10-03 23:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            $drive.Used -gt 0 | Should Be $true
Is this still true if $psDriveName has no contents?

2016-10-03 23:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +        It "Verify Confirm" {
The original test was mis-named. this one is really validating that Confirm can be bypassed

2016-10-03 23:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            try { $globalDrive = Get-PSDrive -Name $psDriveName -Scope Global -ErrorAction Stop }
Please use multiple lines

2016-10-03 23:19 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +        It "Verify Confirm" {
Same here

2016-10-04 17:00 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            Remove-PSDrive -Name $psDriveName -ErrorAction SilentlyContinue
Fixed

2016-10-04 17:00 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            $newDrive = New-PSDrive -Name "NewDifferentPSDrive" -PSProvider FileSystem -Root $psDriveRoot
Fixed

2016-10-04 17:01 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            Remove-PSDrive -Name ${psDriveName} -ea SilentlyContinue
Fixed

2016-10-04 17:01 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            $drive.Used -gt 0 | Should Be $true
I changed it to just detecting if the variables exist.
I am not sure how to determine if the used/free properties are correct or not.

2016-10-04 17:02 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            try { $globalDrive = Get-PSDrive -Name $psDriveName -Scope Global -ErrorAction Stop }
Do you mean use multiple lines for the try or because line 81 is a particularly long line?

2016-10-04 19:57 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
> +            try { $globalDrive = Get-PSDrive -Name $psDriveName -Scope Global -ErrorAction Stop }
Line 83. The content of the try block should be on its own line and indented

2016-10-04 20:03 UTC, mirichmo approved these changes

2016-10-04 20:11 UTC, merged