Added feature level test coverage to Alias provider
PowerShell/PowerShell pull request #2419
Opened 2016-10-03 22:37 UTC by ChrisUbben

Adding more coverage to issue #2412
+ Added more cmdlet test coverage for Alias provider.
+ Moved all basic cmdlet test into a context block. (this is why the diff looks so messy)

2016-10-03 22:37 UTC, msftclas commented
Hi __@ChrisUbben__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Christopher Ubben). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-04 20:33 UTC, mirichmo requested changes

2016-10-04 20:33 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +    Context "Valdiation of Set-Item parameters for the Alias Provider" {
Context is not necessary if there is only one Context within the Describe.

2016-10-04 20:33 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +    Context "Validate basic Alias Cmdlets" {
Context is not necessary here

2016-10-04 20:57 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +    Context "Validate basic Alias Cmdlets" {
I made this change as a stylistic choice to be consistent with all of the other provider tests which do have more than 1 context block within the "Basic Alias Provider Tests" describe.
If you still think that I should remove the Context block please let me know.

2016-10-04 20:58 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +    Context "Valdiation of Set-Item parameters for the Alias Provider" {
I plan to add more cmdlet coverage to the "Extended Alias Provider Tests" describe block in the future. I was preparing for that future by putting the context blocks in now.
If you still think that I should remove the Context block please let me know.

2016-10-04 22:33 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +    Context "Validate basic Alias Cmdlets" {
I'd like you to remove it here. It is unnecessary for the test.

2016-10-04 22:34 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +    Context "Valdiation of Set-Item parameters for the Alias Provider" {
In this case it seems OK to leave it.

2016-10-05 18:52 UTC, ChrisUbben commented on test/powershell/Modules/Microsoft.PowerShell.Management/Alias.Tests.ps1
> +    Context "Validate basic Alias Cmdlets" {
Fixed.

2016-10-05 21:46 UTC, mirichmo approved these changes

2016-10-05 21:46 UTC, merged