Resolve issue #2478 by adding -TimeOut to Test-Connection
PowerShell/PowerShell pull request #2479
Opened 2016-10-14 14:34 UTC by jpsnover

2016-10-14 14:34 UTC, msftclas commented
Hi __@jpsnover__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, MSBOT;

2016-10-14 17:10 UTC, mirichmo requested changes

2016-10-14 17:10 UTC, mirichmo commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
> +        /// Buffer size sent with the this command. The default value is 32.
This comment must be updated. It was copied and pasted without modification.

2016-10-14 17:12 UTC, mirichmo commented
@jpsnover Please include test(s) for this change in ...\test\powershell\Modules\Microsoft.PowerShell.Management

@adityapatwardhan and @JamesWTruher Please review

2016-10-14 19:19 UTC, daxian-dbw commented
@jpsnover PRs should be sent out from a fork instead of from a branch directly pushed to powershell/powershell. That is to make sure powershell/powershell has a minimal number of branches. Could you please close this PR and send it from a fork after addressing the CR comments?

2016-10-17 18:28 UTC, JamesWTruher commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
> +        public Int32 TimeOut { get; set; } = 1000;
>1000 [](start = 45, length = 4)

I'm a little worried about this - how did you land on this value? Could the default value be Int32.MaxValue to maintain current behavior? Anyone using this new parameter would likely provide a much smaller number in any case

2016-10-17 18:52 UTC, closed without merging

2016-10-17 18:53 UTC, jpsnover commented
This was superseded by PR #2492