Steps to create Windows Packages such as MSI
PowerShell/PowerShell pull request #2494
Opened 2016-10-17 20:42 UTC by raghushantha

2016-10-17 20:42 UTC, msftclas commented
Hi __@raghushantha__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Raghu Shantha). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-17 20:44 UTC, andschwa commented on WindowsPackages/CreatingWindowsPackage.md
> +## Creating Windows10/Server2016 MSI Package
I think these instructions should be under [the releasing docs](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md#windows).

2016-10-17 22:35 UTC, mirichmo requested changes

2016-10-17 22:35 UTC, mirichmo commented on WindowsPackages/CreatingWindowsPackage.md
> +Start-PSPackage -Type msi
This needs 
``` powershell
Start-PSPackage -Type zip
```
as well doesn't it?

2016-10-17 22:35 UTC, mirichmo commented on WindowsPackages/CreatingWindowsPackage.md
> +## Creating Windows10/Server2016 MSI Package
This should be pushed from a child branch of your fork, not directly from a branch off PowerShell/master

2016-10-18 18:00 UTC, daxian-dbw commented on WindowsPackages/CreatingWindowsPackage.md
> +## Creating Windows10/Server2016 MSI Package
I agree. These instructions should be put in the `Windows` section in `docs/maintainers/releasing.md`.

2016-10-25 18:29 UTC, closed without merging