Get-ChildItem -Recurse -ErrorAction Ignore doesn't ignore the errors
PowerShell/PowerShell pull request #2503
Opened 2016-10-19 00:23 UTC by nitinbps

Added error handling for get-childitem.

2016-10-19 00:23 UTC, msftclas commented
Hi __@nitinbps__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Nitin Gupta). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-19 17:27 UTC, mirichmo commented
@Francisco-Gamino or @anmenaga Please review or find someone else appropriate for the review who is not on vacation

2016-10-19 21:19 UTC, daxian-dbw commented
@nitinbps GitHub cannot recognize the author of the second commit, can you please fix it?
![image](https://cloud.githubusercontent.com/assets/127450/19537998/fb79138e-9606-11e6-9e6c-a19c6db0dc7f.png)

2016-10-25 22:13 UTC, nitinbps commented
Fixed the author of the second commit.

2016-10-26 19:35 UTC, Francisco-Gamino requested changes

2016-10-26 19:35 UTC, Francisco-Gamino commented on src/System.Management.Automation/engine/SessionStateContainer.cs
> +            {
@nitinbps would it make sense to wrap this call into a function to avoid code duplication?

2016-10-26 19:35 UTC, Francisco-Gamino commented on src/System.Management.Automation/engine/SessionStateContainer.cs
> +                            if(accessException.InnerException != null &&
please add a space after the if statement, e.g., "if (){...}

2016-10-26 20:34 UTC, lzybkr commented on src/System.Management.Automation/engine/SessionStateContainer.cs
> +            {
I noticed that different exceptions are being caught between this call to IsItemContainer and the next. That smells like a bug, which could be fixed as @Francisco-Gamino suggests.

2016-10-27 18:41 UTC, nitinbps commented on src/System.Management.Automation/engine/SessionStateContainer.cs
> +                            if(accessException.InnerException != null &&
Done.

---
In reply to: [85202384](https://github.com/PowerShell/PowerShell/pull/2503#discussion_r85202384) [](ancestors = 85202384)

2016-10-27 22:52 UTC, Francisco-Gamino approved these changes

2016-10-27 22:54 UTC, Francisco-Gamino commented
LGTM @nitinbps 

Please check with @JamesWTruher to see if there are existing tests for scenario. If not, please add at least one test. Thanks.

2016-10-28 21:48 UTC, daxian-dbw commented
@nitinbps can you please add a test to cover the code change? It's required to have test coverage along with code changes unless it's purely refactoring that doesn't cause any functional/behavior change.

2016-11-02 17:45 UTC, nitinbps commented
The code is exercised when Get-ChildItem with recurse and ErrorAction Continue is used and system has files where MetaData can't be read reliably and will throw Access Denied Error. We have system tests to exercise this scenario.

2016-11-02 18:24 UTC, daxian-dbw commented
@nitinbps Thanks for the clarification! The system tests sound good to me.

2016-11-02 18:26 UTC, merged