Add ValidateNullOrEmpty to -Name parameter of Get-Service
PowerShell/PowerShell pull request #2542
Opened 2016-10-26 21:33 UTC by HemantMahawar

Fix for #2540

2016-10-26 21:33 UTC, msftclas commented
Hi __@HemantMahawar__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Hemant Mahawar). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2016-10-26 22:19 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Service.Tests.ps1
> +    It 'Should throw if null is passed to -Name parameter' {
You can use the `-Testcases` parameter to shorten this test a bit, e.g.

```powershell
$testCases =
    @{ data = $null; value = 'null' },
    @{ data = [String]::Empty, value = 'empty string' }

It 'Should throw if <value> is passed to -Name parameter' -TestCases $testCases {
    param($data)
    try { Get-Service -Name $data }
    catch [System.Management.Automation.ParameterBindingException] {$_.Exception.ErrorId | Should Be 'ParameterArgumentValidationError'}
}

It 'Should throw if <value> is passed to -Name parameter via pipeline' -TestCases $testCases {
    param($data)
    try { $data | Get-Service }
    catch [System.Management.Automation.ParameterBindingException] {$_.Exception.ErrorId | Should Be 'ParameterArgumentValidationError'}
}

```

2016-10-26 22:50 UTC, HemantMahawar commented
@lzybkr Thanks for the great tip. Incorporated your feedback.

2016-10-27 00:09 UTC, lzybkr approved these changes

2016-10-27 20:18 UTC, vors commented
@HemantMahawar it looks like GitHub cannot attribute commits to you. It's done via email on the commits. Can you add this email address to your email addresses in the GitHub settings?

2016-10-27 20:33 UTC, HemantMahawar commented
@vors Done

2016-10-27 21:17 UTC, vors requested changes

2016-10-27 21:17 UTC, vors commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Service.Tests.ps1
> +      catch [System.Management.Automation.ParameterBindingException] {$_.Exception.ErrorId | Should Be 'ParameterArgumentValidationError'}
Please, use [Should Throw](https://github.com/pester/Pester/wiki/Should#throw) instead.
The current code will report success, if no error is thrown (the only check happens in the catch statement).

2016-10-27 21:17 UTC, vors commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Service.Tests.ps1
> +    @{ data = [String]::Empty; value = 'empty string' }
Where is `value` used in the test cases?

2016-10-27 21:27 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Service.Tests.ps1
> +    @{ data = [String]::Empty; value = 'empty string' }
Isn't `<value>` in the description a reference to the variable?

2016-10-27 21:29 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Service.Tests.ps1
> +      catch [System.Management.Automation.ParameterBindingException] {$_.Exception.ErrorId | Should Be 'ParameterArgumentValidationError'}
Oops, I missed that - the pattern is to `throw "Expected error on previous command"` at the end of the `try` when you want to be specific about the exception thrown.

2016-10-27 22:24 UTC, HemantMahawar commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Service.Tests.ps1
> +      catch [System.Management.Automation.ParameterBindingException] {$_.Exception.ErrorId | Should Be 'ParameterArgumentValidationError'}
@vors @lzybkr Thanks for pointing out the holes in test (I should have caught them by running on PS 5.1 :)). Fixed

2016-10-27 22:24 UTC, HemantMahawar commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Service.Tests.ps1
> +      catch [System.Management.Automation.ParameterBindingException] {$_.Exception.ErrorId | Should Be 'ParameterArgumentValidationError'}
@vors @lzybkr Thanks for pointing out the holes in test (I should have caught them by running on PS 5.1 :)). Fixed

2016-10-27 22:25 UTC, HemantMahawar commented
@vors @lzybkr Thanks for pointing out the holes in test (I should have caught them by running on PS 5.1 :)). Fixed

2016-10-27 23:37 UTC, merged