Fix Get-Alias Name parameter allows Null value
PowerShell/PowerShell pull request #2545
Opened 2016-10-27 11:27 UTC by iSazonov

1. Add [ValidateNotNullOrEmpty()] to Name parameter
2. Add tests

Close #2544

2016-10-27 11:27 UTC, msftclas commented
Hi __@iSazonov__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-10-27 22:26 UTC, vors requested changes

2016-10-27 22:26 UTC, vors commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Alias.Tests.ps1
> +      catch [System.Management.Automation.ParameterBindingException] {$_.Exception.ErrorId | Should Be 'ParameterArgumentValidationError'}
Please, use 

```powershell
 try
    {
        get-item "ThisFileCannotPossiblyExist" -ErrorAction Stop
        throw "No Exception!"
    }
    catch
    {
        $_.FullyQualifiedErrorId | should be "PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand"
    }
```

pattern, as described in https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md

2016-11-01 00:19 UTC, merged

2016-11-01 00:19 UTC, vors commented
Thank you!

2016-11-01 04:27 UTC, iSazonov commented
@vors Thanks for review!