Performance improvements when group policies are in effect for ExecutionPolicy
PowerShell/PowerShell pull request #2588
Opened 2016-11-02 11:53 UTC by powercode

Fixes #2578 
When group policies are in effect for execution policy, a check is made to determine if the current process has been launched by gpscript.exe, and in that case, ignore the execution policy.
This is expensive to determine, is done over and over again, and has resulted in very long load times for scripts and modules.

One of the things that is checked (in an expensive way) is the parent id of the current process. That never changes, and is now cached.

The other change is to check once if we are launched by gpscript.exe or not and save that value.
This results in speedups in the order of a magnitude for module loads.

2016-11-02 11:53 UTC, msftclas commented
Hi __@powercode__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-11-02 12:23 UTC, iSazonov commented on src/System.Management.Automation/utils/PsUtils.cs
> +        private static int GetParentProcessIdNative(int processId)
Seems this should be in #if !UNIX

2016-11-02 12:29 UTC, powercode commented on src/System.Management.Automation/utils/PsUtils.cs
> +        private static int GetParentProcessIdNative(int processId)
Yes, you are correct. Fixing.

2016-11-02 12:43 UTC, iSazonov commented on src/System.Management.Automation/utils/PsUtils.cs
> +                        parentPid = (int) pe32.th32ParentProcessID;
PG do not accept formatting without code changes. It would be good to revert this.

2016-11-02 12:48 UTC, iSazonov commented on src/System.Management.Automation/security/SecuritySupport.cs
> +
Unneeded empty line.

2016-11-02 12:59 UTC, powercode commented on src/System.Management.Automation/utils/PsUtils.cs
> +        private static int GetParentProcessIdNative(int processId)
Fixed

2016-11-02 20:26 UTC, lzybkr commented
@powercode - it looks like these changes cause the test failures.

@LeeHolmes - can you review these changes?

2016-11-02 21:26 UTC, powercode commented
It is my bad. Fixing now.

2016-11-03 06:43 UTC, powercode commented on src/System.Management.Automation/utils/PsUtils.cs
> +            if (processId == s_currentProcessId && s_currentParentProcessId.HasValue)
Good point. Refactoring...

2016-11-03 07:09 UTC, powercode commented on src/System.Management.Automation/utils/PsUtils.cs
> +            if (processId == s_currentProcessId && s_currentParentProcessId.HasValue)
It is there to avoid creating a new process object every time the id of the current process is needed

2016-11-03 08:25 UTC, iSazonov commented on src/System.Management.Automation/utils/PsUtils.cs
> +            if (processId == s_currentProcessId && s_currentParentProcessId.HasValue)
Agree!

2016-11-03 08:28 UTC, iSazonov commented on src/System.Management.Automation/utils/PsUtils.cs
> +            return processId == s_currentProcessId ? s_currentParentProcessId.Value : GetParentProcessIdNative(processId);
I maybe stupid here but why you check s_currentProcessId instead of s_currentParentProcessId.HasValue?

2016-11-03 08:45 UTC, iSazonov commented on src/System.Management.Automation/utils/PsUtils.cs
> +            return processId == s_currentProcessId ? s_currentParentProcessId.Value : GetParentProcessIdNative(processId);
Clear -  "current" != "current" 😊

2016-11-14 21:30 UTC, LeeHolmes commented on src/System.Management.Automation/security/SecuritySupport.cs
>  #if UNIX
This conditional is the opposite of what I think you intended.

2016-11-14 21:33 UTC, LeeHolmes commented on src/System.Management.Automation/security/SecuritySupport.cs
> +                        // Be sure we aren't being called by Group Policy
Our coding style puts a newline above comment blocks, as it represents a paragraph of thought.

2016-11-14 21:34 UTC, powercode commented
Fixing

2016-11-14 21:47 UTC, powercode commented on src/System.Management.Automation/security/SecuritySupport.cs
> +                        // Be sure we aren't being called by Group Policy
Fixed

2016-11-14 21:59 UTC, powercode commented on src/System.Management.Automation/utils/PsUtils.cs
> +                        return parentPid;
Good point. Fixed.

2016-11-14 22:03 UTC, powercode commented on src/System.Management.Automation/security/SecuritySupport.cs
>  #if UNIX
Yes, fixed in the updated pull request

2016-11-15 01:59 UTC, LeeHolmes commented on src/System.Management.Automation/utils/PsUtils.cs
> +        internal static int GetParentProcessId(int processId)
This is very close to being a duplication of GetParentProcess(). I think it'd be OK to add the caching logic to GetParentProcessIdNative. Also, it doesn't have the start time validation that GetParentProcess has, so we should make sure we don't expose anything that looks like a useful helper function without this validation.

2016-11-15 08:10 UTC, powercode commented
Pushed new version with 
```private static int GetParentProcessIdCandidate``` 
instead of 
```internal static int GetParentProcessId```

2017-03-30 01:07 UTC, mirichmo commented
@powercode Can you please rebase this PR to the latest from master and push an update? It looks like it is ready to merge and just needs final code review sign off.

@LeeHolmes - Please take another look at this PR and provide feedback as appropriate.
@PaulHigin - I am adding you as Lee's backup if he is too busy or if you are curious

2017-03-31 20:06 UTC, PaulHigin requested changes
I looked through the code changes and comments.  I agree with Lee's comments but I notice that two have not yet been addressed:
1. GetParentProcessIdNative() helper method is not needed and can be merged with GetParentProcessId() method.
2. The GetParentProcessId() method should include the process start time check and return '0' if start time.  
3.  Actually I don't see a need for GetParentProcessId() at all, since it is always used within GetParentProcess() and nowhere else.  We can just add the s_currentParentProcessId caching in GetParentProcess().

2017-04-19 07:10 UTC, powercode commented
@PaulHigin We now have an implementation of GetParentPid available. Using it instead, and inlining the caching as suggested.

2017-04-20 23:19 UTC, PaulHigin approved these changes
LGTM

2017-04-26 01:07 UTC, merged