Moving Import-PowerShellDatafile from script to compiled cmdlet
PowerShell/PowerShell pull request #2750
Opened 2016-11-21 19:06 UTC by powercode

Fixes #2734

2016-11-21 19:06 UTC, msftclas commented
Hi __@powercode__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-12-04 20:41 UTC, vors commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +--********************************************************************/
@HemantMahawar should we have copyright preamble on the new files?

2016-12-04 20:48 UTC, vors requested changes
Please, avoid copy-paste

2016-12-04 20:48 UTC, vors commented on src/Microsoft.PowerShell.Commands.Utility/map.json
> +    "monad/src/commands/utility/ImportPowerShellDataFile.cs":  "commands/utility/ImportPowerShellDataFile.cs",
That's probably not needed

2016-12-04 20:48 UTC, vors commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +        private List<string> ResolveFilePaths(string[] filePaths, bool isLiteralPath)
This method is copied from https://github.com/PowerShell/PowerShell/blob/9a195f44c17773fdbb5a2e6a09de0c880072df23/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L1723

Can we avoid such copy-paste?

2016-12-05 18:26 UTC, HemantMahawar commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +--********************************************************************/
Given it is open-source code, I don't think it is needed. @joeyaiello Can you weigh in?

2016-12-06 20:29 UTC, powercode commented on src/Microsoft.PowerShell.Commands.Utility/map.json
> +    "monad/src/commands/utility/ImportPowerShellDataFile.cs":  "commands/utility/ImportPowerShellDataFile.cs",
removed

2017-01-04 00:43 UTC, lzybkr requested changes

2017-01-04 00:43 UTC, lzybkr commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +                        var data = ast.Find(a => a is HashtableAst, false);
I realize this is just a translation of the PowerShell implementation, but a psd1 can contain much more than a simple hashtable.  For example, the psd1 file contain 2 hashtables as an array, and this implementation would ignore the second one.

As implemented, the cmdlet is mostly useful for typical module manifests, but psd1 files are used for other things, e.g. localization, and sometimes use commands like `ConvertFrom-StringData`.

We should, as a minimum, not ignore any part of the ast.
We should also consider supporting more than a simple hashtable. `Ast.SafeGetValue` can certainly handle more (e.g. an array of hashtables).
We might also consider doing something more like what `Import-LocalizedData` does, though we'd need feedback from @LeeHolmes to understand the important differences and why this cmdlet was introduced.

2017-01-04 22:16 UTC, powercode commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +            set { _isLiteralPath = true; Path = value; }
A quick search gives that the pattern is in
```
AclCommands.cs
CertificateCommands.cs
CSVCommands.cs
ExportAliasCommand.cs
MatchString.cs
Out-File.cs
SaveHelpCommand.cs
SignatureCommands.cs
StartTranscriptCmdlet.cs
UpdateHelpCommand.cs
WriteFormatDataCommand.cs
XmlCommands.cs
```
But the cost of changing is very small.

2017-01-04 22:31 UTC, powercode commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +                        var data = ast.Find(a => a is HashtableAst, false);
Should we start with just the move as descripted in the issue, and open a new one for the functional changes?

2017-01-04 22:33 UTC, powercode commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +            var errorId = $"CouldNotParseAsPowerShellDataFile{extraError}";
corrected.

Rebased version pushed.

2017-01-04 22:37 UTC, powercode commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +            ValueFromPipeline = true,
Corrected.

2017-01-04 22:38 UTC, powercode commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +            set { _isLiteralPath = true; Path = value; }
either an extra field or
```
get { return _isLiteralPath ? Path : null; }
```

2017-01-05 06:01 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +                        var data = ast.Find(a => a is HashtableAst, false);
+1 don't block the PR and open new Issue.

2017-02-09 02:24 UTC, mirichmo commented
@lzybkr and @vors Are your concerns resolved or is there additional work left here?

2017-02-27 00:47 UTC, lzybkr commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
> +        public string[] Path { get; set; }
We don't need a change as this code is just following a somewhat broken pattern.

If `LiteralPath` was set, `_isLiteralPath` will be set to true.  Then, if `Path` is set, `_isLiteralPath` is not cleared.  This isn't really a scenario I guess, but it is handled correctly in some places in our code base, but in many others it is not.

2017-02-27 00:50 UTC, lzybkr approved these changes

2017-02-27 00:50 UTC, merged