Adding windows server names to the windows packages + Misc formatting fixes
PowerShell/PowerShell pull request #2757
Opened 2016-11-22 00:24 UTC by HemantMahawar

Misc fixes are:
- Added Get-PackageSemanticVersion function
- Added New-ZipPackage function to separate the Zip packaging code
- Removed ending ';' in hashtable syntax since entries are on new lines
- Standardized the variable name from $Source to $PackageSourcePath for various packaging functions
- Removed 'return' in the function end to output the variable value
- Added -verbose to Write-Verbose to show the paths of various packages

Addresses #2468

2016-11-22 00:25 UTC, HemantMahawar commented
@mirichmo and @raghushantha, can you take a look at this PR?

2016-11-30 18:38 UTC, mirichmo requested changes

2016-11-30 18:38 UTC, mirichmo commented on build.psm1
> +            'win81-x64' {$NameSuffix = 'win81-w2k12r2-x64'}
I added support for win7-x86 and win7-x64 in alpha.13. Please expand your change to support those runtimes as well

2016-11-30 18:38 UTC, mirichmo commented on build.psm1
> +        $packageSemanticVersion = $packageVersion,'0' -join '.'
Where does $packageVersion come from? Should it be $Version?

2016-11-30 18:38 UTC, mirichmo commented on build.psm1
> +    }
What about the case where 3 -gt $packageVersionTokens.Count? It should throw since $packageSemanticVersion will not be defined.

2016-11-30 18:38 UTC, mirichmo commented on build.psm1
> +    $PackageVersion = Get-PackageVersionAsMajorMinorBuildRevision -Version $PackageVersion
This is unused except in the Write-Verbose. The actual package name uses $ProductSemanticVesion

2016-12-03 00:24 UTC, HemantMahawar commented on build.psm1
> +    $PackageVersion = Get-PackageVersionAsMajorMinorBuildRevision -Version $PackageVersion
Not sure of the ask. Do you want me to remove the variable or call to write-verbose or something else?

2016-12-03 00:25 UTC, HemantMahawar commented on build.psm1
> +            'win81-x64' {$NameSuffix = 'win81-w2k12r2-x64'}
Addressed

2016-12-03 00:25 UTC, HemantMahawar commented on build.psm1
> +        $packageSemanticVersion = $packageVersion,'0' -join '.'
Good catch

2016-12-03 00:26 UTC, HemantMahawar commented on build.psm1
> +    }
Added code

2016-12-03 00:36 UTC, mirichmo commented on build.psm1
> +    $PackageVersion = Get-PackageVersionAsMajorMinorBuildRevision -Version $PackageVersion
Please remove unused variables

2016-12-06 19:00 UTC, HemantMahawar commented on build.psm1
> +    $PackageVersion = Get-PackageVersionAsMajorMinorBuildRevision -Version $PackageVersion
Fixed.

2016-12-07 21:15 UTC, mirichmo requested changes

2016-12-07 21:15 UTC, mirichmo commented on build.psm1
> +            'win7-x64'  {$NameSuffix = 'win7-win2k8r2-x64'}
Please add win7-x86 here too and throughout

2016-12-07 21:15 UTC, mirichmo commented on build.psm1
> +        throw "Cannot create semantic version from a string $Version containing more than 4 tokens"
How about this instead:
"Cannot create Semantic Version from the string $Version containing 4 or more tokens."

2016-12-08 06:17 UTC, HemantMahawar commented on build.psm1
> +            'win7-x64'  {$NameSuffix = 'win7-win2k8r2-x64'}
Given, there is no x86 version of w2K8r2, win7-x86 case should be covered by the `Default {$NameSuffix = $Runtime}` below, right?

2016-12-14 17:28 UTC, mirichmo approved these changes

2016-12-14 17:28 UTC, merged