Updated Split-Path to work with UNC Roots
PowerShell/PowerShell pull request #2788
Opened 2016-11-27 03:21 UTC by dchristian3188

Currently splitting a UNC root on windows will return a empty string.

Please reference:
#2301

2016-11-27 03:21 UTC, msftclas commented
Hi __@dchristian3188__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-11-30 23:34 UTC, JamesWTruher commented on test/powershell/Provider/FileSystemProvider.Tests.ps1
> +Describe "SplitPath Tests (Windows Only)" -tags "CI" {
>Windows  [](start = 27, length = 8)

It seems like these should just be added to `test/powershell/modules/Microsoft.PowerShell.Management/Split-Path.Tests.ps1`

2016-12-01 18:04 UTC, JamesWTruher commented on test/powershell/Provider/FileSystemProvider.Tests.ps1
> +Describe "SplitPath Tests (Windows Only)" -tags "CI" {
thanks!

2016-12-01 21:26 UTC, vors requested changes
Great work! Can we make tests more generic to cover Windows and non-Windows platforms?

2016-12-01 21:26 UTC, vors commented on test/powershell/Modules/Microsoft.PowerShell.Management/Split-Path.Tests.ps1
> +    Context "SplitPath Tests (Windows Only)" {
Why it's Windows Only? Can we cover all systems in these tests? I think the attitude of https://github.com/PowerShell/PowerShell/issues/2301#issuecomment-261118596 is to provide a consistent experience on all platforms.

2016-12-03 03:18 UTC, vors commented
Waiting on non-windows tests.

2016-12-04 20:23 UTC, dchristian3188 commented
Updated Tests. Please let me know if everything looks ok

2016-12-04 21:18 UTC, vors approved these changes

2016-12-04 23:00 UTC, merged