Wrapping a call to Registry so that Invoke-WebRequest does not fail on non-text responses
PowerShell/PowerShell pull request #2811
Opened 2016-11-30 08:21 UTC by JonathanMalek

A small bug where content types from an Invoke-WebRequest that are not text-based fall through to a registry check.  Wrapping that check (which is additive) with a #if !CORECLR.  I can't find any tests that test out that specific behavior, or I would be happy to extend them.  I'm also happy to add a new test, just not sure if that is desired.

2016-11-30 08:21 UTC, msftclas commented
Hi __@JonathanMalek__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSBOT;

2016-11-30 19:44 UTC, mirichmo requested changes
In general, we like/need/require tests for all code changes as a forcing function to increase test coverage. In this case, we have internal tests for Invoke-WebRequest that haven't yet been ported to run out of GitHub and you don't have access to them. The tests look like they cover this scenario, so requiring tests from you would be a needless duplication of effort.

2016-11-30 19:44 UTC, mirichmo commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
> +            #if !CORECLR // Registry access not supported on CoreCLR
PowerShell Core on Windows uses the registry. Use Platform.IsWindows to make it a runtime check.

2016-12-01 00:26 UTC, JonathanMalek commented
Thanks for the background @mirichmo.  Changed to check for Platform.IsWindows instead.

2016-12-02 19:37 UTC, mirichmo approved these changes

2016-12-02 19:38 UTC, merged

2016-12-02 19:38 UTC, mirichmo commented
@JonathanMalek Thanks for your contribution