Fix for group policy cache bug
PowerShell/PowerShell pull request #2855
Opened 2016-12-07 23:08 UTC by PaulHigin

The group policy settings cache was not using a unique enough name, with the result that GPO MachinePolicy ExecutionPolicy setting would be substituted for the UserPolicy setting.  

The fix is to use a unique name so that the two GPO settings are distinct in the cache.

2016-12-09 00:55 UTC, mirichmo commented on test/powershell/engine/ExecutionPolicy.GroupPolicy.Tests.ps1
> +        if (!$IsWindows) { return }
Please use the Skip technique instead. https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md#skipping-tests-in-bulk

2016-12-09 01:01 UTC, mirichmo commented
@PaulHigin Please nominate a reviewer to take a look at this change

2016-12-09 17:15 UTC, mirichmo requested changes

2016-12-09 17:15 UTC, mirichmo commented on test/powershell/engine/ExecutionPolicy.GroupPolicy.Tests.ps1
> +            $PSDefaultParameterValues["it:skip"] = $true
This was a good addition. It just needs a small tweak. Non-Windows systems should not execute the rest of the BeforeAll and the end of the AfterAll as well.

2016-12-09 17:42 UTC, PaulHigin commented on test/powershell/engine/ExecutionPolicy.GroupPolicy.Tests.ps1
> +            $PSDefaultParameterValues["it:skip"] = $true
More code for the same behavior...

2016-12-09 19:27 UTC, lzybkr commented on test/powershell/engine/ExecutionPolicy.GroupPolicy.Tests.ps1
> +Describe "User group policy execution policy should work" -Tags 'Feature' {
I don't think we have such a tag yet, but I think we need a tag saying the test changes important machine state.

I wouldn't want to run this test on my dev machine, especially knowing that `AfterAll` isn't guaranteed to run, e.g. if I hit Ctrl+C. My machine will be left in a weird state that would be hard to track down.

On a throw-away test machine like in CI - that's a non-issue of course.

2016-12-09 19:27 UTC, lzybkr commented on src/System.Management.Automation/engine/Utils.cs
> -                if ((s_cachedGroupPolicySettings.TryGetValue(settingName, out settings)) &&
If the key was a Tuple: settingName, preferenceOrder - would that fix this issue?

If it helps, we could make preferenceOrder an enum where we select from the 4 lists we of order we use now.

2016-12-09 23:51 UTC, PaulHigin commented on src/System.Management.Automation/engine/Utils.cs
> -                if ((s_cachedGroupPolicySettings.TryGetValue(settingName, out settings)) &&
A Tuple with settingName, groupPolicyBase, and preferenceOrder should have the needed uniqueness.  But this PR change also works.  It is not clear that Tuple hashing would be significantly faster than string hashing.

2016-12-09 23:51 UTC, PaulHigin commented on test/powershell/engine/ExecutionPolicy.GroupPolicy.Tests.ps1
> +Describe "User group policy execution policy should work" -Tags 'Feature' {
We are going to need tests that change machine state and these tests must always clean up afterwards, or will affect subsequent tests.  If AfterAll block is not reliable then maybe try/finally should be used.

2016-12-09 23:59 UTC, PaulHigin commented on test/powershell/engine/ExecutionPolicy.GroupPolicy.Tests.ps1
> +Describe "User group policy execution policy should work" -Tags 'Feature' {
Fair enough

2016-12-10 00:07 UTC, lzybkr commented on src/System.Management.Automation/engine/Utils.cs
> -                if ((s_cachedGroupPolicySettings.TryGetValue(settingName, out settings)) &&
If we don't find the cached item the first time through the loop, but do the second iteration, your way will:
* copy the setting name twice
* concat the searchKey twice
* hash that value twice
* read from the registry once

In contrast, the tuple will:
* allocate a single tuple (as opposed to two strings)
* combine the hash of 3 fields (combine is cheap, a shift, add, and xor per field)
* avoid reading the registry

Significantly faster? Who knows - but it seems better (does less) and I think it's simpler code.

2016-12-10 00:12 UTC, closed without merging