All test reorted as skipped if not applicable to the platform
PowerShell/PowerShell pull request #2892
Opened 2016-12-15 19:17 UTC by iSazonov

Fixed files:

powershell\Modules\Microsoft.PowerShell.Management\Clear-EventLog.Tests.ps1:1:if
($IsWindows -and !$IsCoreCLR) {

powershell\Modules\Microsoft.PowerShell.Management\Get-ComputerInfo.Tests.ps1:1325:
return

powershell\Modules\Microsoft.PowerShell.Management\Get-EventLog.Tests.ps1:1:if
($IsWindows -and !$IsCoreCLR) {

powershell\Modules\Microsoft.PowerShell.Management\New-EventLog.Tests.ps1:1:if
($IsWindows -and !$IsCoreCLR) {
powershell\Modules\Microsoft.PowerShell.Management\Registry.Tests.ps1:7:
if ($IsWindows -eq $false) {

powershell\Modules\Microsoft.PowerShell.Management\Registry.Tests.ps1:167:
if ($IsWindows -eq $false) {

powershell\Modules\Microsoft.PowerShell.Management\Remove-EventLog.Tests.ps1:1:if
($IsWindows -and !$IsCoreCLR) {

powershell\Modules\Microsoft.PowerShell.Management\TimeZone.Tests.ps1:17:if
($IsWindows) {

powershell\Modules\Microsoft.PowerShell.Security\FileCatalog.Tests.ps1:6:if
($IsWindows) {

2016-12-15 20:14 UTC, iSazonov commented
😕 Why checks failed?

2017-01-03 18:59 UTC, mirichmo requested changes
Thanks for the PR. This is a helpful and needed contribution.

2017-01-03 18:59 UTC, mirichmo commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +                pending     =  if ($IsWindows) { $false } else { $true }
How about 
`pending = !$IsWindows`
instead?

2017-01-03 18:59 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/TimeZone.Tests.ps1
> +        if ($IsWindows) {
The pattern is inconsistent here. Can you please keep consistency and use $IsNotSkipped here as well?

2017-01-03 18:59 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Clear-EventLog.Tests.ps1
> +        $IsNotSkipped = ($IsWindows -and !$IsCoreCLR)
Is `IsNotSkipped` used anywhere else? If not, it should be removed.

2017-01-03 18:59 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-EventLog.Tests.ps1
> +        $IsNotSkipped = ($IsWindows -and !$IsCoreCLR)
Same here

2017-01-03 18:59 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        if ($IsWindows) {
I have a preference for `$IsNotSkipped` here since it is easier to read. It will also maintain consistency across this PR

2017-01-03 19:25 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Clear-EventLog.Tests.ps1
> +        $IsNotSkipped = ($IsWindows -and !$IsCoreCLR)
Fixed

2017-01-03 19:26 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-EventLog.Tests.ps1
> +        $IsNotSkipped = ($IsWindows -and !$IsCoreCLR)
Fixed

2017-01-03 19:30 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/TimeZone.Tests.ps1
> +        if ($IsWindows) {
:confused: $IsNotSkipped is not used anywhere in the file. I do not see  inconsistent here.

2017-01-03 19:38 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        if ($IsWindows) {
:confused: $IsNotSkipped is not used anywhere in the file. There is no need to create a variable to use it once. Yes?
And in general there is no overall style between these files. Each file has its own style.

2017-01-03 19:40 UTC, iSazonov commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +                pending     =  if ($IsWindows) { $false } else { $true }
Fixed.

2017-01-03 21:44 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        if ($IsWindows) {
Looking at this more closely, I'd like to see the try-finally technique used to surround both Describes (like you did in FileCatalog.Tests.ps1). It'll result in the de-duplication of a few lines and more complete grouping of actions in the BeforeAll and AfterAll blocks.

2017-01-03 21:48 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
>          Set-Location -Path $restoreLocation
This is one of the spots I had in mind when I mentioned "more complete grouping of actions...". A principle I'd like the tests to follow: if a Describe is being skipped, it should not do anything. In this case, it is saving and restoring the location; an action that can be bypassed with `if ($IsNotSkipped)`

2017-01-03 21:56 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/TimeZone.Tests.ps1
> +        if ($IsWindows) {
The file is internally consistent, so it passes review. I was thinking about more consistent application of skipping patterns across all test files. The reason I favor `$IsNotSkipped` over `$IsWindows` is that `$IsNotSkipped` enables a single definition of the skipping condition, so any future modifications of it happen via a single line change. Using or modifying $IsWindows requires modifying every use of it throughout the file.

2017-01-04 06:07 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/TimeZone.Tests.ps1
> +        if ($IsWindows) {
Our direction is porting, i.e. skipping tests must generally be disappear in the future and `$IsWindows` and `$IsNotSkipped` should stay in the past :-)

2017-01-04 06:21 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        if ($IsWindows) {
Fixed.

2017-01-04 06:22 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
>          Set-Location -Path $restoreLocation
Clear. Thanks!

Fixed.

2017-01-04 18:08 UTC, mirichmo approved these changes

2017-01-04 18:09 UTC, merged

2017-01-04 18:11 UTC, iSazonov commented
@mirichmo Thanks for the code review and useful comments!