Fix here string '`$a=@`"`n'`"'`n`"@'
PowerShell/PowerShell pull request #2913
Opened 2016-12-21 08:48 UTC by iSazonov

Close #2780 

1. Fix tokenizer
The tokenizer do multiple scans the script line to get tokens. Before
the fix the tokenizer on the first pass examined that string as
double-quoted (Expandable) string not as here string, figured the
average double quotation mark as a closing and then starting with the
single quotation mark continued processing the line as single-quoted
string which had no closing single quotation mark.
The fix stop the first scan pass after getting '=' (assume
assignment-expression '$a=' for next pass).
2. Add test.

2016-12-21 19:44 UTC, lzybkr requested changes

2016-12-21 19:44 UTC, lzybkr commented on test/powershell/Language/Parser/Parser.Tests.ps1
> +        { ExecuteCommand "@`"`n'`"'`n`"@" } | Should Not Throw
This test does not trigger the bug or hit the new code.

2016-12-22 04:10 UTC, iSazonov commented on test/powershell/Language/Parser/Parser.Tests.ps1
> +        { ExecuteCommand "@`"`n'`"'`n`"@" } | Should Not Throw
Fixed.

2016-12-23 17:31 UTC, lzybkr approved these changes

2016-12-23 17:34 UTC, merged