Updating dockerfiles for Windows
PowerShell/PowerShell pull request #3017
Opened 2017-01-19 06:45 UTC by brycem

Cleaned up RELEASE version Dockerfiles for Windows

2017-01-23 21:10 UTC, lzybkr commented
Can you document how the image `brycem/win10build` was built?

We are discussing not building the C/C++ Windows components in PowerShell/PowerShell and instead pull packages from NuGet - would this eliminate the need for your custom image?

2017-01-25 15:13 UTC, brycem commented
That would be a much cleaner solution. Heres the image and a link to the dockerfile in git https://hub.docker.com/r/brycem/win10build/

Outlook für Android herunterladen




On Mon, Jan 23, 2017 at 1:10 PM -0800, "Jason Shirk" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you document how the image brycem/win10build was built?

We are discussing not building the C/C++ Windows components in PowerShell/PowerShell and instead pull packages from NuGet - would this eliminate the need for your custom image?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/PowerShell/PowerShell/pull/3017#issuecomment-274617909>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AGgSlC3BAilzaxU9boofM4EwIGmRohcSks5rVRdOgaJpZM4Lnwdl>.

2017-01-27 03:31 UTC, brycem commented
@lzybkr - Where did you guys shake out on removing the Standalone Win10SDK dependency?  It would definitely simplify.  Looks like CMake is available in NuGet as well.

2017-02-10 01:08 UTC, mirichmo commented
I filed issue #3014, but it hasn't progressed beyond that.

2017-03-02 01:22 UTC, mirichmo commented
@raghushantha - Can you please take a look?

2017-03-02 01:48 UTC, mirichmo requested changes

2017-03-02 01:48 UTC, mirichmo commented on docker/release/nanoserver/Dockerfile
> +    [System.IO.DirectoryInfo]$PsFolder=New-Item -Path $Env:ProgramFiles\PowerShell -ItemType Directory -Force;`
Expand-Archive would simplify this. [Here](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/windows.md#online-deployment-of-powershell-core) is an example.

2017-04-04 23:02 UTC, raghushantha requested changes

2017-04-04 23:02 UTC, raghushantha commented on docker/release/windowsservercore/Dockerfile
> +ARG POWERSHELL_MSI=https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.15/PowerShell_6.0.0-alpha.15-win10-win2k16-x64.msi
@brycem Please pick up the latest release MSI here
https://github.com/PowerShell/PowerShell/releases/latest

Then the experience would be similar to Linux. There we simply apt-get install / yum install from packages.microsoft.com and the image is automatlically populated with latest PS

This comment applies all locations where the MSI is downloaded

2017-04-04 23:02 UTC, raghushantha commented on docker/release/windowsservercore/Dockerfile
> +ARG POWERSHELL_SHA256=CC52D21F3287E412B9C3B73C98BB5B06F8056D49D63201072216DF92B7F2E59B
Not really required to validate the hash. The MSI is authenticode signed & you are downloading from an HTTPS location

2017-04-08 00:58 UTC, brycem commented
Looks like @TravisEz13 has updated the URLs - I'll close this PR

2017-04-08 00:58 UTC, closed without merging