Add Get-StringHash and Get-FileHash cmdlets
PowerShell/PowerShell pull request #3024
Opened 2017-01-20 14:07 UTC by iSazonov

Close #2731 

1. Rewrite Get-FileHash on C# and refactoring tests
The original Get-FileHash output type is `Microsoft.Powershell.Utility.FileHash`. The type was defined by ExtendedTypeDefinition. It is not C# type and reported as `PSCustomObject`.
Therefore, the output type was changed and now it is native C# type `Microsoft.PowerShell.Commands.FileHashInfo`.

2.  Add new cmdlet Get-StringHash and add tests
The original idea was to add a InputString parameter to the common cmdlet but due to a conflict with the Path parameter (paths is strings too!) I had to make a new cmdlet to provide a pipeline support for the InputString parameter.

2017-01-23 21:06 UTC, lzybkr requested changes
@PowerShell/powershell-committee - needs to review the new cmdlet - parameters, output type, allowing null.

2017-01-23 21:06 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
> +        It "Should be able to set the default hash algorithm" {
This test should not be necessary, `PSDefaultParameterValues` is already well tested.

2017-01-23 21:06 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
> +        $testcases =
Should be moved closer to the use to limit the scope of the variable.

2017-01-24 11:50 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-StringHash.Tests.ps1
> +Describe "Get-StringHash" -Tags "CI" {
We can change it after the merger.

2017-01-24 11:56 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-StringHash.Tests.ps1
> +        $testcases =
Fixed.

2017-01-24 11:57 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-StringHash.Tests.ps1
> +
Fixed.

2017-01-24 12:01 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-StringHash.Tests.ps1
> +        It "Should be able to set the default hash algorithm" {
It is from original tests.
Removed.

2017-01-24 12:09 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-StringHash.Tests.ps1
> +            Get-StringHash -InputString $null | Should Be $null
I thought about this example:
```powershell
$stringarray | Get-StringHash 
```
If the string array contains a null string member then we get throw - is this the desired behavior?
The following example does not cause a throw:
```powershell
"a",$null | Select-String -Pattern ".*"
```

2017-01-24 12:18 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +    [Cmdlet(VerbsCommon.Get, "StringHash", HelpUri = "")]
Get-Uptime was merged and #2659 was opened for URI.

2017-01-24 12:33 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +            if (ParameterSetName == StreamParameterSet)
Oh, sorry. I remember your earlier comment about this, but all mixed up :-)
Fixed.

2017-01-24 12:36 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +        private void WriteHashResult(String Algorithm, String hash, String path)
Fixed.

2017-01-24 12:48 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +        [ValidateSet(HashAlgorithmNames.SHA1,
It is from original cmdlet and `HashAlgorithmNames` class.
If there are other useful algorithms, please give a link.
And whether we should do something specifically for Mac?

2017-01-24 12:57 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +                _Algorithm = value.ToUpper();
If we block it by `ValidateSet`, an user will not be able to type an algorithm name in low cases - is it okay?

2017-01-24 13:00 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
> +        New-Variable testDocument -Value (Join-Path -Path (Join-Path -Path $PSScriptRoot -ChildPath assets) -ChildPath testablescript.ps1) -Scope Global -Force
Fixed.

2017-01-24 13:01 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
> +        $testcases =
Fixed.

2017-01-24 13:01 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
> +        It "Should be able to set the default hash algorithm" {
Removed.

2017-01-24 13:23 UTC, iSazonov commented on src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/PowerShellCore_format_ps1xml.cs
> -                    .AddHeader(Alignment.Left, width: 70)
Fixed.

2017-01-24 13:47 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +                        if (File.Exists(newPath))
What I found:
1. `Unblock-File` use the same pattern.
2. For `Path` parameter `GetResolvedProviderPathFromPSPath` has the same problem - "the file might disappear between this check and when we try to read it."

So we could keep consistency here.

Later we try read the file and _ignore_ any exceptions.
The original `Get-FileHash` function call [Write-Error and return](https://github.com/PowerShell/PowerShell/blob/master/src/Modules/Shared/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psm1#L128)
Should we reproduce the same behavior or  _ignore_ any exceptions?

2017-01-24 17:44 UTC, lzybkr commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +                _Algorithm = value.ToUpper();
Never mind - `ValidateSet` ignores case.

Maybe not applicable here, but it's often useful to store the exact argument a user specifies so error messages or whatever look like what they wrote. Of course that means you couldn't use `switch` as easily, but I don't think that's a big deal.

2017-01-24 18:03 UTC, lzybkr commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +        [ValidateSet(HashAlgorithmNames.SHA1,
According to the `ValidateSet` use [here](https://github.com/PowerShell/PowerShell/blob/e568fda5c3dfd85ea18c0406217533849bb6e966/src/Modules/Shared/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psm1#L18), the original function has:

* MACTripleDES
* MD5
* RIPEMD160
* SHA1
* SHA256
* SHA384
* SHA512

I suppose it's not surprising that a couple of these are missing for .Net Core.

We should probably add the missing algorithms for Windows PowerShell or explore alternative implementations to that we can have completely portable scripts.

/cc @SteveL-MSFT

2017-01-24 18:04 UTC, lzybkr commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +                        if (File.Exists(newPath))
Unsound patterns should not be copied, even for consistency.

We should introduce sound patterns, and when feasible and time allows, correct the unsound patterns.

2017-01-24 18:05 UTC, lzybkr commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +                        if (File.Exists(newPath))
Also - ignoring exceptions is usually a terrible idea - I think non-terminating errors is definitely preferred.

2017-01-24 18:08 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-StringHash.Tests.ps1
> +            Get-StringHash -InputString $null | Should Be $null
`$null` is not passed through the pipeline and `Select-String` allows `$null` anyway, so that's not a good example.

2017-01-24 18:10 UTC, lzybkr commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
> +        New-Variable testDocument -Value (Join-Path -Path (Join-Path -Path $PSScriptRoot -ChildPath assets) -ChildPath testablescript.ps1) -Force
Can't this just use `$testDocument = Join-Path ...`?

2017-01-24 18:44 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +        [ValidateSet(HashAlgorithmNames.SHA1,
@lzybkr if .Net Core doesn't support those, we should treat it as a separate issue (not block this PR).  however, we should see if .Net Core will implement them or why they no longer support it (patents?  no longer secure?)

2017-01-24 19:00 UTC, lzybkr commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +        [ValidateSet(HashAlgorithmNames.SHA1,
I believe these are hashing algorithms, so security isn't the issue. My guess is less demand.

But the real question here - are we OK with a PR that would be a breaking change to Windows PowerShell if we took this code back to Windows as is?

2017-01-24 19:07 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +        [ValidateSet(HashAlgorithmNames.SHA1,
The security concern is that hashes are used to determine if something (like a file/package) has been modified.  However, SHA1, for example, has been proven that you can generate collisions meaning that it is feasible someone could modify a file and produce the same resulting SHA1 hash so it appears to be legit.

We can discuss this at the Committee meeting.

2017-01-25 04:01 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-StringHash.Tests.ps1
> +            Get-StringHash -InputString $null | Should Be $null
Yes, but key is that `null` string don't throw an exception here.

2017-01-25 04:42 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
> +                        if (File.Exists(newPath))
Fixed.

2017-01-25 04:51 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
> +        New-Variable testDocument -Value (Join-Path -Path (Join-Path -Path $PSScriptRoot -ChildPath assets) -ChildPath testablescript.ps1) -Force
Fixed.

2017-01-25 04:55 UTC, iSazonov commented
@PowerShell/powershell-committeeTeam 
Should we introduce a new type 'Microsoft.PowerShell.Commands.StringHashInfo' for `Get-StringHash` output similar to `Get-FileHash` output?

2017-01-26 01:06 UTC, lzybkr commented
@PowerShell/powershell-committee has decided we need an RFC for the `Get-StringHash` cmdlet.

The biggest concern was how PowerShell will convert anything to `string`, so the cmdlet will happily hash objects in a potentially unexpected way.

The output type was also of some concern when combined with allowing `null` because it will be difficult to match input with output. We think the output needs the original object in addition to the hash.

2017-01-26 01:08 UTC, lzybkr commented
The committee also agreed that we do not need any updates with regards to the algorithms supported - we've marked the PR wit `Breaking Change` so we can document the difference between Windows PowerShell and PowerShell Core.

2017-01-26 06:28 UTC, iSazonov commented
What will be the road map for the PR?
Could I remove `Get-StringHash` code from the PR?

I do not have the forces for the RFC to write the big text correctly in English. 
Can we ask the author @rkeithhill of the `Get-StringHash` idea to start this RFC?

2017-01-26 16:59 UTC, lzybkr commented
By all means - remove `Get-StringHash` from the PR.

Your English seems more than sufficient to write a RFC, but if @rkeithhill is up for it, I assume he'll jump in.

2017-01-27 16:04 UTC, iSazonov commented
@lzybkr I create new PR with RFC https://github.com/PowerShell/PowerShell-RFC/pull/63

Now `Get-StringHash` was removed from the PR.
Travis again temporary failed 😕

2017-01-30 03:51 UTC, iSazonov commented
@lzybkr  Should I do something else in the PR?

2017-02-04 01:51 UTC, lzybkr approved these changes

2017-02-04 02:11 UTC, merged

2017-02-04 06:44 UTC, iSazonov commented
@lzybkr Thanks!