Fix GetComputerInfo test for looking up registry
PowerShell/PowerShell pull request #3065
Opened 2017-01-27 22:33 UTC by adityapatwardhan

Error is thrown if property is not found.

2017-01-28 02:08 UTC, mirichmo requested changes

2017-01-28 02:08 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
> +                return $regValue
There are a number of paths here that do not explicitly return a value. I'd like to see returns in all paths since you are using a return.

2017-01-28 07:43 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
> -        $regValue = (Get-ItemProperty -Path $key -Name $propertyName).$propertyName
It seems we could do only one improvement:
```powershell
$regValue = (Get-ItemProperty -Path $key -Name $propertyName -ErrorAction SilentlyContinue).$propertyName
```

2017-01-31 21:10 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
> +                return $regValue
Fixed.

2017-01-31 21:10 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
> -        $regValue = (Get-ItemProperty -Path $key -Name $propertyName).$propertyName
Fixed.

2017-02-01 01:19 UTC, mirichmo approved these changes

2017-02-02 01:49 UTC, merged