Create a badge for the daily test runs in travis-ci
PowerShell/PowerShell pull request #3076
Opened 2017-01-30 22:59 UTC by JamesWTruher

It updates an azure blob with an SVG and that location is referenced by the
README.md file. TravisCI doesn't support this directly so in order to report
on the status of a daily test run there, we need to do this.
Provide error reporting in case the badge can't be set

The location where the badge is stored in azure should be moved eventually to a global resource where we keep other azure blobs. We don't have that yet, but this will do. Also, the location in azure is globally readable, but not globally writable. Travis-CI configuration must be updated to include the two required environment variables.

2017-01-31 00:12 UTC, adityapatwardhan requested changes

2017-01-31 00:12 UTC, adityapatwardhan commented on tools/travis.ps1
> +    $headerDate = '2015-12-11'
$headerDate overwritten?

2017-01-31 00:12 UTC, adityapatwardhan commented on tools/travis.ps1
> +        "`n"
Use a stringbuilder instead.

2017-01-31 00:12 UTC, adityapatwardhan commented on tools/travis.ps1
> +    $uri = New-Object System.Uri -ArgumentList $url
use System.Uri::new($url) instead

2017-01-31 00:12 UTC, adityapatwardhan commented on tools/travis.ps1
> +    $hmac = new-object System.Security.Cryptography.HMACSHA256((,$accountKeyBytes))
::new() here as well

2017-01-31 00:12 UTC, adityapatwardhan commented on tools/travis.ps1
> +    write-verbose $signatureString
Do you want to add [CmdletBinding()] to the function?

2017-01-31 17:46 UTC, JamesWTruher commented on tools/travis.ps1
> +    $headerDate = '2015-12-11'
fixed

2017-01-31 17:47 UTC, JamesWTruher commented on tools/travis.ps1
> +    $uri = New-Object System.Uri -ArgumentList $url
fixed

2017-01-31 17:47 UTC, JamesWTruher commented on tools/travis.ps1
> +    $hmac = new-object System.Security.Cryptography.HMACSHA256((,$accountKeyBytes))
fixed

2017-01-31 17:47 UTC, JamesWTruher commented on tools/travis.ps1
> +    write-verbose $signatureString
fixed

2017-01-31 19:38 UTC, adityapatwardhan approved these changes

2017-02-01 23:52 UTC, TravisEz13 commented
Thanks everyone

2017-02-01 23:53 UTC, TravisEz13 approved these changes

2017-02-01 23:53 UTC, merged