Remove async tests for parser
PowerShell/PowerShell pull request #3119
Opened 2017-02-09 00:24 UTC by JamesWTruher

this is a fix for https://github.com/PowerShell/PowerShell/issues/3069
and removes an attempt to work-around the issue of tests hanging on Travis-CI.

The hanging tests in Travis-CI have now been seen in a number of places, getting a dump during this condition has been problematic.

2017-02-09 19:54 UTC, daxian-dbw requested changes

2017-02-09 19:54 UTC, daxian-dbw commented on test/powershell/Language/LanguageTestSupport.psm1
> +        [scriptblock]::Create($src).Invoke() > $null
I guess the finally block below should also be removed?

2017-02-09 19:56 UTC, daxian-dbw commented
Test hang again in Linux CI. I restarted the CI.

2017-02-15 20:46 UTC, JamesWTruher commented on test/powershell/Language/LanguageTestSupport.psm1
> +        [scriptblock]::Create($src).Invoke() > $null
fixed

2017-02-15 22:49 UTC, daxian-dbw approved these changes

2017-02-16 00:39 UTC, merged