Fix GetType() bad pattern and related issues in tests
PowerShell/PowerShell pull request #3134
Opened 2017-02-12 12:55 UTC by iSazonov

$var.GetType() can raise an exception in tests so we should check $var
before make the call. A large part of the tests does not make this
check.
I start with searching ".GetType()" but discovered many related issues
in tests (reduntant and unneeded tests, "throw" bad pattens, bugs,
formattings (sorry!) and so on) - I had to fix them too.

According to our test roadmap, we must increase the code coverage from 45 up to 90% i.e. twice. Bad patterns and bad formatting will slow down our movement. I hope the team will support me in this PR.

2017-02-13 23:24 UTC, daxian-dbw requested changes

2017-02-13 23:24 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
> -    }
if any of those aliases are removed, these tests can catch it. So maybe we should keep these 3 tests?

2017-02-13 23:24 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Csv.Tests.ps1
> +    $actualresult.GetType().BaseType.Name | Should Be "Array"
indentation. there are similar indentation problems down in the changes.

2017-02-13 23:24 UTC, daxian-dbw commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
Is it failing on Linux? I don't see this failure in our daily build ... Can you open an issue for it?

2017-02-13 23:24 UTC, daxian-dbw commented on test/powershell/Language/Scripting/I18n.Tests.ps1
>          $ev[0].Exception.GetType() | Should Be System.Management.Automation.PSInvalidOperationException
You use `$result | Should BeOfType` in some places, and `$result | Should Not BeNullOrEmpty` then `$result.Exception.GetType | Should Be` in some other places. Why don't you unify them with a single pattern?

2017-02-14 15:30 UTC, iSazonov commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        (([int[]](1..5)).clone()) | Should BeOfType [int[]]
Fixed.

2017-02-14 15:38 UTC, iSazonov commented on test/powershell/Language/Scripting/Debugging/DebuggerScriptTests.Tests.ps1
> +                $_.Exception.GetType().Name | Should Be $exception
Don't work 😕

2017-02-14 15:40 UTC, iSazonov commented on test/powershell/Language/Scripting/NativeExecution/NativeLinuxCommands.Tests.ps1
> +        $result.GetType().Name | Should Be String
Done.

2017-02-14 15:43 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
> +        It "(special case) Test for property = OsLocalDateTime" -Pending:$true {
OsLocalDateTime return empty to me. And the test is wrong. Yes, we should open a new Issue...

2017-02-14 15:47 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
> +        $content.GetType().BaseType.Name | Should Be "Object"
I believe that the test is similar to the following after it. So it is better to leave.

2017-02-14 15:51 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
> -    }
We have separate files with tests for aliases. If we need control a list of approved aliases we should make the test there. If it is we should open a new Issue.

2017-02-14 15:55 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Csv.Tests.ps1
> +    $actualresult.GetType().BaseType.Name | Should Be "Array"
I reformat the file.

2017-02-14 15:59 UTC, iSazonov commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
I only add the comment for you. I don't mark it as pending. 
The code don't raise an exception as expected in the test (on windows). So we should open a new Issue.

2017-02-14 16:04 UTC, iSazonov commented on test/powershell/Language/Scripting/I18n.Tests.ps1
>          $ev[0].Exception.GetType() | Should Be System.Management.Automation.PSInvalidOperationException
Sometimes it is clear from above code that '$result' is not empty. Ex.  `$result.Count | Should Be 2`

2017-02-14 16:57 UTC, daxian-dbw commented on test/powershell/Language/Scripting/Debugging/DebuggerScriptTests.Tests.ps1
> +                $_.Exception.GetType().Name | Should Be $exception
I see what is happening. $exception is point to internal types, and thus Pester cannot resolve. #Closed

2017-02-14 17:02 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
> +        $content.GetType().BaseType.Name | Should Be "Object"
#Closed

2017-02-14 17:15 UTC, daxian-dbw commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
Weird, it pass in [daily build](https://ci.appveyor.com/project/PowerShell/powershell-f975h/build/6.0.0-alpha.15-191).
@PaulHigin can you please take a look?

2017-02-14 17:19 UTC, daxian-dbw commented on test/powershell/Language/Scripting/I18n.Tests.ps1
> +        $ev | Should Not BeNullOrEmpty
$ev will always be an arraylist, but it might be empty. I think here you want to test `$ev[0] | Should Not BeNullOrEmpty`.

2017-02-14 17:23 UTC, daxian-dbw commented on test/powershell/Language/Scripting/I18n.Tests.ps1
>          $ev[0].Exception.GetType() | Should Be System.Management.Automation.PSInvalidOperationException
I see, if it's obvious `$result` is not null, you will go with `$result | should BeOfType`. If not, you will check `$result | Should Not BeNullOrEmpty` first.
But after checking "Not BeNullOrEmpty", why not also use `$result | should BeOfType`? I see in some places you just continue to use `$result.GetType() | Should Be`.

2017-02-14 17:46 UTC, PaulHigin commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
?? This test runs fine on Linux for me.  The CI test failures only indicate that the class inheritance tests fail.  Why do you think this test is failing?

2017-02-14 17:54 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
> -    }
Done #3145

2017-02-14 18:01 UTC, iSazonov commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
I copy-paste the code
```powershell
[System.Management.Automation.Runspaces.SSHConnectionInfo]::new(
                    [System.Management.Automation.Internal.AutomationNull]::Value,
                    "localhost",
                    [System.Management.Automation.Internal.AutomationNull]::Value)
```
to interactive session (on Windows) and it don't raise exception.

2017-02-14 18:03 UTC, daxian-dbw commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
@PaulHigin this test expects an exception from `[System.Management.Automation.Runspaces.SSHConnectionInfo]::new` when running on both Linux and Windows, but when running it locally, no exception is thrown (see below). However, I don't see it fail in the daily test run, and that's why we need your insight.
```
[Windows]
PS:11> [System.Management.Automation.Runspaces.SSHConnectionInfo]::new([System.Management.Automation.Internal.Automation
Null]::Value, "localhost", [System.Management.Automation.Internal.AutomationNull]::Value)


UserName                :
ComputerName            : localhost
Credential              :
AuthenticationMechanism : Default
CertificateThumbprint   :
Culture                 : en-US
UICulture               : en-US
OpenTimeout             : 180000
CancelTimeout           : 60000
OperationTimeout        : 180000
IdleTimeout             : -1
MaxIdleTimeout          : 2147483647
``` 
```
[Linux]
PS /home/pi> [System.Management.Automation.Runspaces.SSHConnectionInfo]::new([System.Management.Automation.Internal.AutomationNull]::Value, "localhost", [System.Management.Automation.Internal.AutomationNull]::Value)


UserName                :
ComputerName            : localhost
Credential              :
AuthenticationMechanism : Default
CertificateThumbprint   :
Culture                 : en-US
UICulture               : en-US
OpenTimeout             : 180000
CancelTimeout           : 60000
OperationTimeout        : 180000
IdleTimeout             : -1
MaxIdleTimeout          : 2147483647
```

2017-02-14 18:09 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
> +        It "(special case) Test for property = OsLocalDateTime" -Pending:$true {
Done #3146

2017-02-14 18:11 UTC, PaulHigin commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
Oh I see now.  Yes, this test should be removed because the code now gets the current user name if no user name is specified.  Good find.

2017-02-14 18:22 UTC, iSazonov commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
Clear. Thanks! I'll remove the test.

2017-02-14 18:32 UTC, daxian-dbw commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
@PaulHigin Why doesn't it fail in our daily test run then? There is no current user name when running daily test pass in AppVeyor builder?

2017-02-14 18:39 UTC, PaulHigin commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
Not sure.  But the test is incorrect (no longer needed) because a null UserName parameter is now allowed, and the test should be removed.

2017-02-14 19:14 UTC, JamesWTruher commented on test/powershell/Language/Parser/Ast.Tests.ps1
>          $HtAst.SafeGetValue().GetType().Name | Should be Hashtable
this extra test doesn't really get you that much. If $HtAst is null, or if GetType is null, or $HtAst.SafeGetValue() doesn't return a hashtable, the test will fail regardless.
Doesn't just `$HtAst.SafeGetValue() | should beoftype hashtable` suffice?

2017-02-15 10:50 UTC, iSazonov commented on test/powershell/Language/Parser/Ast.Tests.ps1
>          $HtAst.SafeGetValue().GetType().Name | Should be Hashtable
I removed "GetType().Name" However, previously we need to check that `$HtAst` is not `Null` to exclude exception.

2017-02-15 10:55 UTC, iSazonov commented on test/powershell/engine/Remoting/SSHRemotingAPI.Tests.ps1
> +            # The test is pending because it is wrong or we have bug in code!
The test is removed.

2017-02-15 11:37 UTC, iSazonov commented on test/powershell/Language/Scripting/I18n.Tests.ps1
> +        $ev | Should Not BeNullOrEmpty
We should not trust a cmdlet which we check.
If $ev != Null then $ev[0] never raise.
So I suppose `$ev | Should Not BeNullOrEmpty` is correct.

2017-02-15 14:34 UTC, iSazonov commented
Sorry I accidentally made a rebase 😕

2017-02-15 22:56 UTC, daxian-dbw commented on test/powershell/Language/Scripting/I18n.Tests.ps1
> +        $ev | Should Not BeNullOrEmpty
Understood. #Closed

2017-02-15 23:03 UTC, daxian-dbw approved these changes

2017-02-16 00:40 UTC, merged

2017-02-16 03:09 UTC, iSazonov commented
@daxian-dbw Thanks for the very fast code review! 👍