Add dynamic year for managed entrance message.
PowerShell/PowerShell pull request #3204
Opened 2017-02-26 05:07 UTC by kwiknick

This change is to fix Issue #3148 - Update copyright notices. 
Changed the ManagedEntranceStrings resource file to take in a parameter.  Then edited the ManagedEntrance.cs to grab the year using GetDate.Now and placing it in the banner variable for display when powershell is opened.

2017-02-26 12:32 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
> +            string systemYear = DateTime.Now.Year.ToString();
Do we really need this variable if it is used only in one place?

2017-02-26 14:45 UTC, kwiknick commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
> +            string systemYear = DateTime.Now.Year.ToString();
I pulled it into a local variable because it's being used on line 113 and 115.

2017-02-26 15:36 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
> +            string systemYear = DateTime.Now.Year.ToString();
Maybe I was not accurate. This variable is under the `#if` directive and actually used once in the result code.

2017-02-26 16:16 UTC, lzybkr commented
Maybe we don't even need the year, that would be even simpler.

2017-02-26 17:22 UTC, kwiknick commented
I can change it to not have a year, but I was trying to fulfill what was asked in Issue #3148.  There are no concerns of legal implications if the date isn't in there?


________________________________
From: Jason Shirk <notifications@github.com>
Sent: Sunday, February 26, 2017 10:16 AM
To: PowerShell/PowerShell
Cc: Nicholas Willard; Author
Subject: Re: [PowerShell/PowerShell] Add dynamic year for managed entrance message. (#3204)


Maybe we don't even need the year, that would be even simpler.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/PowerShell/PowerShell/pull/3204#issuecomment-282566872>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AKg2vk1VPO9t9E_ME6YzRrOvu-t4aScYks5rgaVkgaJpZM4MMPrI>.

2017-02-26 17:55 UTC, iSazonov commented
Currently all MSFT applications use a year in copyright (cmd.exe, notepad.exe, skype...)

2017-02-26 19:34 UTC, lzybkr commented
But they do not use a dynamic year - e.g. `cmd.exe` says `(c) 2016 Microsoft Corporation.` on my machine right now.

2017-02-26 19:48 UTC, iSazonov commented
It seems that this (year) is tied to the main release time. I agree that is _internal_ MSFT pattern. Perhaps it has historical legal roots.

2017-02-27 23:10 UTC, andschwa commented
Aye, we need @joeyaiello and @SteveL-MSFT to weigh in on the legal question.

2017-02-28 21:11 UTC, SteveL-MSFT commented
I'll follow up on this.

2017-03-01 02:58 UTC, kwiknick commented
Thanks for all the comments and feedback.  I out of habit brought my fork up to upstream/master, which, as it's supposed to, kicked off the CI builds.

2017-03-01 17:17 UTC, SteveL-MSFT requested changes
Waiting on legal

2017-03-01 17:48 UTC, joeyaiello commented
Just so I understand, is the date dynamically generated at build time or runtime? If I had to guess, I think runtime is probably problematic, but that's just a hunch. 

Either way, I'm sending off the mail to legal now

2017-03-01 18:00 UTC, SteveL-MSFT commented
@joeyaiello I've already started a conversation with legal

2017-03-01 18:15 UTC, kwiknick commented
@joeyaiello It is generated at runtime, which I can see how/why It'd be problematic.  If legal decides that they want the date, I'll get it to generate at build time.  I should've done that in the first place.

2017-03-02 19:27 UTC, daxian-dbw commented
Just found that `dotnet publish` with the RC4 dotnet CLI doesn't have the year in coryright banner now:
```
PS:53> dotnet publish -f netcoreapp1.0 -c release
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

  console -> X:\arena\apps\console\bin\release\netcoreapp1.0\console.dll
```

2017-03-02 21:30 UTC, joeyaiello commented
We'll ask if that's an option to legal as well

2017-03-03 03:58 UTC, iSazonov commented
For legal too: What copyright we should use in the files? These files be published under MIT. There are also new files.

2017-03-03 17:15 UTC, SteveL-MSFT requested changes
We are approved to just use:

// Copyright (C) Microsoft Corporation. All rights reserved.

2017-03-03 17:20 UTC, kwiknick commented
@SteveL-MSFT That's great news!  I'll update it this evening and push the changes.  Thanks everyone for all the collaboration.

2017-03-04 16:00 UTC, kwiknick commented
@SteveL-MSFT the changes have been made and this is ready for review.  Thanks for being so helpful.

2017-03-04 16:34 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
> +                var banner = string.Format(ManagedEntranceStrings.ShellBanner);
string.Format - It seems should be removed.

And why we use Core and non-Core banner?

2017-03-04 17:01 UTC, kwiknick commented
@SteveL-MSFT  Thanks for catching the unnecessary string.Formats.  I forgot to remove them as well a couple using statements.   The way I read the code when I first forked it, was that it shows a different banner based on the OS of the machine.  Do you want me to remove that as well and just have it to be the same message regardless?

2017-03-04 17:41 UTC, iSazonov commented
I remember that @lzybkr open PR to remove Windows PowerShell from the repo so I believe we should remove the non-Core banner.

2017-03-04 19:52 UTC, SteveL-MSFT approved these changes

2017-03-04 19:53 UTC, SteveL-MSFT commented
@iSazonov I believe that PR is to just stop building Windows PowerShell.  I would leave the non-Core banner for now.

2017-03-04 20:50 UTC, iSazonov commented
I agree.

2017-03-04 21:19 UTC, msftclas commented
@kwiknick,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-03-04 21:19 UTC, kwiknick commented
Closed and Reopened to kick off the cla bot.

2017-03-05 07:46 UTC, lzybkr approved these changes

2017-03-05 07:47 UTC, merged