Add Arch Linux installation information
PowerShell/PowerShell pull request #3215
Opened 2017-02-27 04:19 UTC by kylesferrazza

I maintain [powershell](https://aur.archlinux.org/packages/powershell/) and [powershell-git](https://aur.archlinux.org/packages/powershell-git/) on the Arch Linux User Repository.

This pull requests adds information for installing powershell on Arch Linux.

2017-02-27 04:19 UTC, msftclas commented
@kylesferrazza,
Thanks for having already signed the Contribution License Agreement. Your agreement has not been validated yet. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-02-27 16:17 UTC, iSazonov commented
@kylesferrazza Thanks for your contribution!
Also welcome to give us feedbacks from Arch Linux community.

2017-02-28 03:51 UTC, andyleejordan requested changes

2017-02-28 03:51 UTC, andschwa commented on docs/installation/linux.md
> +Powershell is available from the Arch Linux User Repository (AUR) as a [release](https://aur.archlinux.org/packages/powershell/) or the [latest development build](https://aur.archlinux.org/packages/p
I _personally_ prefer links like:

```markdown
Powershell is available from the Arch Linux User Repository (AUR) as a [release][arch-release]
or the [latest development build][arch-git].

[arch-release]: https://aur.archlinux.org/packages/powershell/
[arch-git]: https://aur.archlinux.org/packages/powershell-git/
```

It's easier to maintain / read in plaintext.

2017-02-28 03:51 UTC, andschwa commented on docs/installation/linux.md
> +==========
Nit picking here but I like space between `===` header and paragraph.

2017-02-28 03:51 UTC, andschwa commented on docs/installation/linux.md
> +
Please also add a note that the AUR repos for PowerShell are community maintained, so that these docs don't imply official support.

2017-02-28 03:51 UTC, andschwa commented
BTW I'm super happy about have AUR repos :D I'm an Arch Linux user.

2017-02-28 15:50 UTC, kylesferrazza commented on docs/installation/linux.md
> +==========
Fixed!

2017-02-28 16:09 UTC, iSazonov commented on docs/installation/linux.md
>  All of these steps can be done automatically by the [`download.sh`][download] script.
All `linux.md ` is for official distributives. Add community-supported platform here is misleading (Arch Linux is not on Releases page and not supported by `download.sh`).

We should to either change the structure of this file, or make a new `linux-community.md`.

2017-02-28 17:56 UTC, andschwa commented on docs/installation/linux.md
>  All of these steps can be done automatically by the [`download.sh`][download] script.
@kylesferrazza added, at my request:
> Packages in the AUR are community maintained - there is no official support.

I think this is sufficient, and that `linux.md` is the right place to have links to the existing community support. @SteveL-MSFT / @joeyaiello what do you think?

2017-02-28 17:56 UTC, andyleejordan approved these changes

2017-02-28 23:41 UTC, ditta95aR commented
Update superuser binary

2017-03-01 23:31 UTC, joeyaiello commented on docs/installation/linux.md
>  All of these steps can be done automatically by the [`download.sh`][download] script.
Today, I'd error on @andschwa's side, give as much information as possible.

In the future, we're going to have to figure out what "support" means, but that's in a post-alpha/beta world.

2017-03-02 01:38 UTC, merged