Update VSCode install/debug instructions.
PowerShell/PowerShell pull request #3262
Opened 2017-03-05 22:06 UTC by rkeithhill

Fix #3257

2017-03-05 23:30 UTC, SteveL-MSFT requested changes

2017-03-05 23:30 UTC, SteveL-MSFT commented on docs/learning-powershell/using-vscode.md
> +Once the debug configuration is established, you can select which configuration you want to use during a debug session by selecting one from the debug configuration dropdown in the **Debug** view's t
Should be 'drop-down'

2017-03-05 23:30 UTC, SteveL-MSFT commented on docs/learning-powershell/using-vscode.md
> +1. Open the **Debug** view by pressing **Ctrl+Shift+D** (**Cmd+Shift+D** on Mac).
Add two spaces at the end of each line to get this formatted as a linebreak

2017-03-05 23:30 UTC, SteveL-MSFT commented on docs/learning-powershell/using-vscode.md
> +   When you do this, Visual Studio Code creates a directory and a file **.vscode\launch.json** in the root of your workspace folder.
Genereally, it seems file paths are in quotes, so if you put this in quotes, I think the spellchecker will be fine with it

2017-03-06 00:17 UTC, SteveL-MSFT requested changes

2017-03-06 00:17 UTC, SteveL-MSFT commented on docs/learning-powershell/using-vscode.md
> +    *	**Linux**:        typing **code .** in your terminal
Perhaps Code required a path on Linux previously, but that doesn't seem the be the case anymore.  just `code` is fine for Linux

2017-03-06 00:49 UTC, rkeithhill commented on docs/learning-powershell/using-vscode.md
> +1. Open the **Debug** view by pressing **Ctrl+Shift+D** (**Cmd+Shift+D** on Mac).
I've made all the other changes. But I'm not sure I follow this one.  What is the issue?  I have VSCode set up to trim trailing whitespace which is why this probably changed.

2017-03-06 04:20 UTC, SteveL-MSFT approved these changes

2017-03-06 04:22 UTC, SteveL-MSFT commented
@rkeithhill looks like you'll need to add `vscode` as a valid word in `.spelling` for in the ` - docs/learning-powershell/using-vscode.md` section

2017-03-06 17:19 UTC, merged