Update all W3 links in the resource files to use HTTPS instead of HTTP
PowerShell/PowerShell pull request #3331
Opened 2017-03-14 21:54 UTC by ChrisUbben

2017-03-14 22:06 UTC, TravisEz13 approved these changes

2017-03-14 22:54 UTC, SteveL-MSFT commented
Is there any test we can add to catch any new HTTP URLs added to the product code?

2017-03-14 23:27 UTC, TravisEz13 requested changes
We could add a meta test suite and use a regex to validate we use `https:` and not `http:`

DSC Resources have some meta tests (not for something exactly like this):
https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1

2017-03-16 19:48 UTC, ChrisUbben commented
I created an issue to add some way to verify if new HTTP links have been added to the product code.
New issue #3347.

2017-03-17 18:02 UTC, TravisEz13 approved these changes

2017-03-17 18:04 UTC, merged