tab expansion not working correctly for some parameters
PowerShell/PowerShell pull request #3364
Opened 2017-03-18 00:07 UTC by SteveL-MSFT

code was indexing outside of it's range for the last element causing an exception which fails the whole discovery operation

addresses #1345 

need some pointers on how to add a test for this

2017-03-18 00:50 UTC, lzybkr requested changes
Please add a test.

2017-03-18 02:12 UTC, SteveL-MSFT commented
Didn't find any existing tests nor tests for TabExpansion++ so not sure how to validate

2017-03-18 02:35 UTC, lzybkr commented
You don't need TabExpansionPlusPlus.

You can look at:

```
#212 PS> rg TabExpansion2
powershell\Host\TabCompletion\BugFix.Tests.ps1
4:        $result = TabExpansion2 -inputScript "[system.manage" -cursorColumn "[system.manage".Length
11:        $result = TabExpansion2 -inputScript "1 -sp" -cursorColumn "1 -sp".Length
18:        $result = TabExpansion2 -inputScript "1 -a" -cursorColumn "1 -a".Length
25:        $result = TabExpansion2 -inputScript "[pscu" -cursorColumn "[pscu".Length
#213 PS> rg CompleteInput
powershell\Language\CompletionTestSupport.psm1
69:    $results = [System.Management.Automation.CommandCompletion]::CompleteInput(

powershell\Language\Classes\Scripting.Classes.BasicParsing.Tests.ps1
613:        $completions = [System.Management.Automation.CommandCompletion]::CompleteInput($line, $line.Length, $null)

powershell\Language\Parser\ExtensibleCompletion.Tests.ps1
63:    $results = [System.Management.Automation.CommandCompletion]::CompleteInput(
```

2017-03-18 04:44 UTC, SteveL-MSFT commented
Test added

2017-03-18 09:05 UTC, iSazonov commented on test/powershell/Host/TabCompletion/BugFix.Tests.ps1
> +        $result | Should Not BeNullOrEmpty
If below we check `count` we should remove the line.

2017-03-18 15:43 UTC, SteveL-MSFT commented on test/powershell/Host/TabCompletion/BugFix.Tests.ps1
> +        $result | Should Not BeNullOrEmpty
Agree it's unnecessary

2017-03-19 06:04 UTC, iSazonov commented on test/powershell/Host/TabCompletion/BugFix.Tests.ps1
> +    It "Issue#1345 - 'Import-Module -n<tab>' should work" {
Is it best practice to place a issue number in `It` title? Maybe make a comment below?

2017-03-19 16:40 UTC, SteveL-MSFT commented on test/powershell/Host/TabCompletion/BugFix.Tests.ps1
> +    It "Issue#1345 - 'Import-Module -n<tab>' should work" {
Currently just following convention already defined in this script.  Created new issue to get this test script cleaned-up: https://github.com/PowerShell/PowerShell/issues/3369

2017-03-19 17:10 UTC, iSazonov commented on test/powershell/Host/TabCompletion/BugFix.Tests.ps1
> +    It "Issue#1345 - 'Import-Module -n<tab>' should work" {
👍 
Closed.

2017-03-21 01:11 UTC, SteveL-MSFT commented
@lzybkr anything else needed?

2017-03-21 15:21 UTC, lzybkr approved these changes

2017-03-21 15:23 UTC, merged