Included info on Microsoft Repository
PowerShell/PowerShell pull request #3396
Opened 2017-03-22 15:35 UTC by ewhitesides

https://technet.microsoft.com/en-us/windows-server-docs/compute/linux-package-repository-for-microsoft-software?f=255&MSPPError=-2147217396

2017-03-22 15:35 UTC, msftclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-03-22 23:04 UTC, TravisEz13 requested changes

2017-03-22 23:04 UTC, TravisEz13 commented on docs/installation/linux.md
> +sudo rpm -Uvh http://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
This should have code blocks.  I can add them.  Just ping me if you want me to do it.

2017-03-23 01:55 UTC, ewhitesides commented on docs/installation/linux.md
> +sudo rpm -Uvh http://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
You can go ahead... still getting used to how github works.  Thanks!

2017-03-24 23:17 UTC, joeyaiello commented
First, thanks for this contribution, we desperately needed to put these instructions in docs. 

I went ahead and made a few ordering changes to showcase the repository installation method as the preferred method. However, it looks like another PR came in and did the same before this one got merged. I'm going to fix the merge conflict here as well.

2017-03-24 23:20 UTC, joeyaiello approved these changes

2017-03-24 23:21 UTC, joeyaiello commented
Alright, I made a few more wording changes when fixing the merge commit. I still need to do a pass here at some point on the whole doc, but it's absolutely in a better place than it was a week ago. :smile:

2017-03-24 23:43 UTC, TravisEz13 approved these changes

2017-03-24 23:46 UTC, merged