Add documentation about hosting PowerShell Core
PowerShell/PowerShell pull request #3409
Opened 2017-03-24 01:07 UTC by daxian-dbw

Fix #2291
Add documentation about how to host PowerShell Core in .NET Core application.

2017-03-24 02:59 UTC, daviwil commented
This is really cool!  Quick question, though: does this tie the application to a specific version of PowerShell Core?  Specifically, if I build against Microsoft.PowerShell.SDK of a specific version, is there any way I could get my application to load assemblies from a newer version of PowerShell Core if I have its filesystem path?

I'm asking because I'm re-evaluating whether I could make PowerShell Editor Services a standalone process again, not a module running inside of powershell.exe.

2017-03-24 05:11 UTC, daxian-dbw commented
@daviwil When you build your application this way, a specific version (depending on the package version you use) of PowerShell Core assemblies will be published to your publish folder. But your application is not necessarily tied to them. You can just replace them with a newer version of PS Core assemblies, and your application should continue to work as long as the new PS Core assemblies are targeting the same set of .NET Core packages.

There is one problem, though -- we haven't published any powershell core packages for Linux/OSX yet.
PowerShell Core builds separately for Windows and Linux, so the assemblies are different between Windows and Unix platforms. All PowerShell Core packages we published so far contain windows assemblies only ☹️.

There is a workaround. Build your application using the existing powershell core NuGet packages, but replace the powershell assemblies with those from a Linux/OSX package. That hopefully would work.

2017-03-24 06:40 UTC, iSazonov commented on docs/host-powershell/sample-dotnet1.1/Logic/Logic.csproj
> +    <TargetFramework>netstandard1.6</TargetFramework>
Please clarify why "netstandard1.6", not "netcoreapp1.1" as in docs/host-powershell/sample-dotnet1.1/MyApp/MyApp.csproj ?

2017-03-24 16:06 UTC, mirichmo submitted a review, later dismissed

2017-03-24 16:06 UTC, mirichmo commented on docs/host-powershell/README.md
> +So the above example needs to be altered as follows in a .NET Core application:
Suggested rewording:
The following example demonstrates hosting PowerShell Core in a .Net Core Application:

2017-03-24 16:06 UTC, mirichmo commented on docs/host-powershell/README.md
> +### Example
There should be three sub-headings here:
1. Hosting Windows PowerShell
2. Hosting PowerShell in .Net Core
3. Example .Net Core program

2017-03-24 16:18 UTC, daviwil commented
@daxian-dbw thanks for the explanation!  Seems like it would be more complex go have my own process hosting PowerShell so I think I'll stick with my current model of being hosted inside of powershell.exe :)

2017-03-24 17:18 UTC, daxian-dbw commented on docs/host-powershell/sample-dotnet1.1/Logic/Logic.csproj
> +    <TargetFramework>netstandard1.6</TargetFramework>
Becuase `Logic.dll` is an assembly Library while `MyApp.exe` is an executable. If you inspect the dependencies of `Microsoft.NetCore.App`, you will see that it depends on `NetStandard.Library` and also include the runtime and host related packages.

2017-03-24 17:32 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +- For `SetPowerShellAssemblyLoadContext`,
Fixed.

2017-03-24 17:32 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +it's designed to be used by a native host whose TPA (Trusted Platform Assemblies) list doesn't include powershell assemblies,
Fixed.

2017-03-24 17:33 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +This documentation only covers the `InitializeAndCallEntryMethod` API,
We own those 2 APIs. They are exposed from `PowerShellAssemblyLoadContextInitializer`.

2017-03-24 17:36 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +### Example
Fixed.

2017-03-24 17:42 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +The following code is how you host Windows PowerShell in an application.
I don't intend to introduce how to host Windows PowerShell in full .NET application.  
The code about hosting Windows PowerShell is used as a comparison to show what you need to do in .NET Core for the same purpose.

2017-03-24 17:45 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +So the above example needs to be altered as follows in a .NET Core application:
Same here. The code about hosting windows powershell is used as a comparison to show how this familiar code should be altered when it comes to .NET Core 1.1.

2017-03-24 17:50 UTC, iSazonov commented on docs/host-powershell/sample-dotnet1.1/Logic/Logic.csproj
> +    <TargetFramework>netstandard1.6</TargetFramework>
Thanks!

2017-03-24 17:53 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +The following code is how you host Windows PowerShell in an application.
But I reworded it as you suggested.

2017-03-24 18:11 UTC, daxian-dbw commented
@mirichmo I addressed your comments. Could you please take another look?

2017-03-24 22:28 UTC, joeyaiello requested changes
Just a few small changes, otherwise looks really useful to me.

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +whose Trusted Platform Assemblies (TPA) do not include powershell assemblies,
Properly case "PowerShell"

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +where the TPA list includes powershell assemblies.
Properly case "PowerShell"

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +As shown below, you can insert your business logic code directly in the `'Main'` method.
No reason to use both backticks and single quotes. Backticks will do here.

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +However, when it comes to hosting PowerShell Core, there will be a layer of redirection for the powershell load context to take effect.
"PowerShell" casing

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +In a .NET Core application, the entry point assembly that contains the `'Main'` method is loaded in the default load context,
No single quotes needed

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +In order to have the powershell load context to control assembly loading for the execution of an application,
PowerShell casing

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +the business logic code needs to be extracted out of the entry point assembly and put into a different assembly, say `'Logic.dll'`.
No single quotes

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +The entry point `'Main'` method shall do one thing only -- let the powershell load context load `'Logic.dll'` and start the execution of the business logic.
No single quotes

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +```
Has this document assumed that the user has installed dotnet-cli? Might it be worth putting a pointer to environment instructions (preferably not owned by us) at the top of the document?

2017-03-24 22:28 UTC, joeyaiello commented on docs/host-powershell/README.md
> +```
Also, is this the same on Linux with a different RID? Might that be worth calling out?

2017-03-24 22:37 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +whose Trusted Platform Assemblies (TPA) do not include powershell assemblies,
Fixed.

2017-03-24 22:37 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +where the TPA list includes powershell assemblies.
Fixed.

2017-03-24 22:38 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +As shown below, you can insert your business logic code directly in the `'Main'` method.
Fixed.

2017-03-24 22:38 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +However, when it comes to hosting PowerShell Core, there will be a layer of redirection for the powershell load context to take effect.
Fixed.

2017-03-24 22:38 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +In a .NET Core application, the entry point assembly that contains the `'Main'` method is loaded in the default load context,
Fixed.

2017-03-24 22:39 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +In order to have the powershell load context to control assembly loading for the execution of an application,
Fixed.

2017-03-24 22:39 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +the business logic code needs to be extracted out of the entry point assembly and put into a different assembly, say `'Logic.dll'`.
Fixed.

2017-03-24 22:39 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +The entry point `'Main'` method shall do one thing only -- let the powershell load context load `'Logic.dll'` and start the execution of the business logic.
Fixed.

2017-03-24 23:08 UTC, daxian-dbw commented on docs/host-powershell/README.md
> +```
Unfortunately, as [discussed above](https://github.com/PowerShell/PowerShell/pull/3409#issuecomment-288934991), all powershell NuGet packages that have been published so far only contain powershell assemblies built specifically for Windows. We need to publish NuGet packages that contain both Windows and Unix assemblies, but `dotnet pack` doesn't seem to support that.

#3417 is opened to track this.

2017-03-24 23:14 UTC, daxian-dbw commented
@joeyaiello @mirichmo All comments have been addressed. Can you please take another look?

2017-03-24 23:23 UTC, joeyaiello approved these changes
LGTM, thanks!

2017-03-25 00:53 UTC, mirichmo approved these changes

2017-03-25 00:53 UTC, merged