Autoload TestRemoting.psm1
PowerShell/PowerShell pull request #3430
Opened 2017-03-27 07:44 UTC by iSazonov

Related #3238

Related PR #3342

2017-03-27 23:40 UTC, TravisEz13 commented
cc @PowerShell/area-test

2017-03-28 17:38 UTC, PaulHigin requested changes

2017-03-29 04:16 UTC, iSazonov commented on test/tools/Modules/TestRemoting/TestRemoting.psd1
> +# Minimum version of the Windows PowerShell engine required by this module
Done.

2017-03-29 15:37 UTC, PaulHigin approved these changes
LGTM

2017-03-29 17:10 UTC, TravisEz13 approved these changes

2017-03-29 17:11 UTC, merged