Add dockerfile and test so we can test simple remoting behaviors
PowerShell/PowerShell pull request #3470
Opened 2017-03-31 21:58 UTC by JamesWTruher

this docker file creates an image which can be used to test remoting with containers.
We start with the microsoft/windowsservercore image and then set up the system for
testing by adding a user, setting up configuration for basic auth, installing
PowerShell Core, and creating a configuration endpoint for PSCore.

The tests are very simple; it retrieve $PSVersionTable.PSVersion in the following
connections:
   Full -> Full
   Full -> Core
   Core -> Full
   Core -> Core

This is the starting point for our remoting testing using containers

2017-04-05 22:33 UTC, mirichmo requested changes

2017-04-05 22:33 UTC, mirichmo commented on test/docker/networktest/DockerRemoting.Tests.ps1
> +        # sticks around for a while
What about the container lifecycle commands? `docker container start`, `docker exec`, `docker container stop`, etc? `docker ps` and `docker container list` both show running containers.

Using those commands should prevent the need to use start-sleep.

2017-04-05 22:33 UTC, mirichmo commented on test/docker/networktest/Dockerfile
> +ADD PSCore.msi /PSCore.msi
How does this file get to the Dockerfile "root" directory? Shouldn't it be downloaded from Myget?

2017-04-05 22:33 UTC, mirichmo commented on test/docker/networktest/Dockerfile
> +RUN net user testuser 11aa!!AA /add; `
As long as you are using PowerShell...
New-LocalUser -Name testuser -Password (ConvertTo-SecureString 11aa!!AA -AsPlainText -Force)

2017-04-05 22:33 UTC, mirichmo commented on test/docker/networktest/Dockerfile
> +    net localgroup administrators testuser /add; `
Add-LocalGroupMember -Group Administrators -Member testuser

2017-04-05 22:33 UTC, mirichmo commented on test/docker/networktest/Dockerfile
> +    $corehome = $psexec.directory.fullname; `
You should delete the MSI within this layer to save space

2017-04-05 23:12 UTC, TravisEz13 commented on test/docker/networktest/Dockerfile
> +ADD PSCore.msi /PSCore.msi
We don't have the whole package in MyGet, but I've given Jim feedback on how to get the latest MSI from AppVeyor.

2017-04-19 19:40 UTC, JamesWTruher commented on test/docker/networktest/Dockerfile
> +ADD PSCore.msi /PSCore.msi
this is done with the New-DockerTestBuild.ps1 script. I broke it out to it's own function.

2017-04-19 23:25 UTC, JamesWTruher commented on test/docker/networktest/Dockerfile
> +    $corehome = $psexec.directory.fullname; `
heh - 23mb over a 10GB image - not sure it's a big saving, but ok.

2017-04-20 18:10 UTC, mirichmo requested changes

2017-04-20 22:41 UTC, JamesWTruher commented on test/docker/networktest/New-DockerTestBuild.ps1
> +      'Authorization' = "Bearer {0}" -f $Constants.Token
fixed

2017-04-20 22:41 UTC, JamesWTruher commented on test/docker/networktest/New-DockerTestBuild.ps1
> +        [string]$Status = "success",
fixed

2017-04-20 22:41 UTC, JamesWTruher commented on test/docker/networktest/New-DockerTestBuild.ps1
> +    #$results |?{$_.status -match "success"} | sort-object StartedDay | Select -First $Last
fixed

2017-04-20 22:42 UTC, JamesWTruher commented on test/docker/networktest/New-DockerTestBuild.ps1
> +    # "$($Constants.ApiUrl)/projects/$($Constants.AccountName)/$($Constants.ProjectName)/history?recordsNumber=$Records$startBuildIdString&branch=$ExtensionBranch"
fixed

2017-04-20 22:43 UTC, JamesWTruher commented on test/docker/networktest/New-DockerTestBuild.ps1
> +$TestImage = docker images remotetestimage --format '{{.Repository}}'
oversight - fixed

2017-04-21 00:50 UTC, mirichmo requested changes

2017-04-21 00:50 UTC, mirichmo commented on test/docker/networktest/New-DockerTestBuild.ps1
> +$TestImage = docker images remotetestimage --format '{{.Repository}}'
Here too

2017-04-21 22:40 UTC, JamesWTruher commented
i think i have them all

2017-04-22 00:22 UTC, mirichmo approved these changes

2017-04-22 00:23 UTC, merged

2017-04-24 22:41 UTC, JamesWTruher commented
thanks!