Invariable order of $PSVersionTable
PowerShell/PowerShell pull request #3530
Opened 2017-04-11 13:08 UTC by iSazonov

Fix #3031.
Provides output $PSVersionTable properties in alphabetical order.

2017-04-11 22:04 UTC, SteveL-MSFT requested changes

2017-04-11 22:04 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +using System.Linq;
Why did you add this?

2017-04-11 22:04 UTC, SteveL-MSFT commented
Please add a test

2017-04-12 07:35 UTC, iSazonov commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +using System.Linq;
I've been playing with different options.
Removed.

2017-04-12 07:36 UTC, iSazonov commented
@SteveL-MSFT I added tests.

2017-04-12 17:01 UTC, SteveL-MSFT approved these changes

2017-04-12 18:00 UTC, daxian-dbw commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +    public sealed class PSVersionHashTable : Hashtable, IEnumerable
> public class Hashtable : IDictionary, ICollection, IEnumerable, ...

Hashtable implements IEnumerable, so do you still need to specify `IEnumerable` here?

2017-04-13 03:26 UTC, iSazonov commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +    public sealed class PSVersionHashTable : Hashtable, IEnumerable
VS Code detects this as error and build failed too without explicity adding `IEnumerable`.

2017-04-13 05:04 UTC, merged

2017-04-13 23:25 UTC, lzybkr commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +                Array.Sort(arr, StringComparer.OrdinalIgnoreCase);
I'm not sure I like this sorting - today `PSVersion` shows up first, or at least it should.
With this change, it will be somewhat harder to see

2017-04-13 23:27 UTC, rkeithhill commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +                Array.Sort(arr, StringComparer.OrdinalIgnoreCase);
Agree 100%.  About the **only** thing I ever look for from this info is `PSVersion`.  This will make it harder to see that version.

2017-04-13 23:40 UTC, daxian-dbw commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +                Array.Sort(arr, StringComparer.OrdinalIgnoreCase);
Maybe an `OrderedDictionary` should be used here.

2017-04-14 03:59 UTC, iSazonov commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +                Array.Sort(arr, StringComparer.OrdinalIgnoreCase);
We have several open discussions on adding additional rows. Alphabetical order will be even more useful after that.

If you want only PSVersion why don't use `$PSVersionTable.PSVersion`?

I wonder how it makes Windows PowerShell for `PSVersionHashTable` _hashtable_ ?

I could slightly change this code to move PSVersion in the first place without moving to `OrderedDictionary`

2017-04-14 20:43 UTC, daxian-dbw commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +                Array.Sort(arr, StringComparer.OrdinalIgnoreCase);
> Update: Moving to OrderedDictionary may be not easy. I review the code - GetPSVersionTableForDownLevel is used in serialization.cs and it is based on hashtable. So I didn't even imagine that there can be broken.

This is a good point. Thanks @iSazonov

2017-04-17 16:29 UTC, rkeithhill commented on src/System.Management.Automation/engine/PSVersionInfo.cs
> +                Array.Sort(arr, StringComparer.OrdinalIgnoreCase);
Consider putting PSVersion **and** PSEdition in the first and second positions.  After that, I don't care much about the order. I suppose alphabetical after the first two would be fine.