Download.sh that autodetects current release from github
PowerShell/PowerShell pull request #3535
Opened 2017-04-11 23:46 UTC by DarwinJS

This version detects the currently available version on github.  
Details:
- It uses sed to parse json - so hopefully can be deployed universally without any runtime installs
- self-documenting comment on how to pull directly from the web
- only tested on ubuntu and centos - could use testing on other supported platforms.
- the sed string might be able to be cleaned up with someone who knows sed better than I (like everyone)

2017-04-11 23:46 UTC, msftclas commented
@DarwinJS,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-04-12 18:15 UTC, TravisEz13 commented on tools/download.sh
> -                        package=powershell_6.0.0-alpha.18-1ubuntu1.14.04.1_amd64.deb
Where installation via package manager is available, can we switch to using that?

2017-04-12 18:17 UTC, TravisEz13 requested changes
The build is failing.  It should be fixed

2017-04-12 21:30 UTC, DarwinJS commented on tools/download.sh
> -                        package=powershell_6.0.0-alpha.18-1ubuntu1.14.04.1_amd64.deb
We're on the same page!  I am thinking that when I add the repos I should make the initial install request *specifying* the version as the version that comes down in the version tag on git.  That way if there happens to a sync issue where a newer than the latest "official" release is hanging around, this code only installs the official release tagged as latest on git?

2017-04-12 21:32 UTC, DarwinJS commented
Another question - is the "Centos" release really only good for Centos - or also Rhel?  Right now the logic limits it to Centos.

2017-04-12 21:39 UTC, TravisEz13 commented on tools/download.sh
> -                        package=powershell_6.0.0-alpha.18-1ubuntu1.14.04.1_amd64.deb
I think it should just install the latest version from the repo.  Eventually, we will have a non-pre-release version, and I think then we have a decision to make, but currently, if it's in the repo, it's ready.

2017-04-12 21:56 UTC, DarwinJS commented on tools/download.sh
> -                        package=powershell_6.0.0-alpha.18-1ubuntu1.14.04.1_amd64.deb
Suits me - easier to code ;)

2017-04-12 22:03 UTC, TravisEz13 commented
CentOS, my understanding is that it should work on the same version of Rhel.

2017-04-13 01:11 UTC, DarwinJS commented
I've made a proposal here: https://github.com/PowerShell/PowerShell/issues/3547

2017-04-15 12:06 UTC, DarwinJS commented
@TravisEz13 - is every .sh that is uploaded tested against every distro - or is there a way to specify which ones run on which test targets?

2017-04-23 15:34 UTC, TravisEz13 commented
Which .sh file are we talking about?  I doubt there is a way to specify which distro it is tested on.  that would have to be written.

2017-05-10 22:58 UTC, TravisEz13 commented
What do you want to do with this PR?

2017-05-11 03:04 UTC, DarwinJS commented
I would like to merge it, however, I don't have a way to test the OSX code (that now uses brew.)

Would be especially helpful to test on a pristine system.

2017-06-23 02:16 UTC, TravisEz13 commented
If you fix the merge conflicts, I can probably help you test it.

2017-06-23 10:13 UTC, DarwinJS commented
@TravisEz13 - this is superceded by #3608

2017-07-21 17:31 UTC, TravisEz13 commented
Closing because this is superseded

2017-07-21 17:31 UTC, closed without merging