Convert tab indentations to spaces in *.resx files
PowerShell/PowerShell pull request #3576
Opened 2017-04-16 12:01 UTC by iSazonov

Prepare to pass meta test #3504.

First commit convert tab indentations to spaces in *.resx files.
Second commit add Newlines at EOF.

2017-04-25 22:54 UTC, JamesWTruher commented on src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostStrings.resx
> +Machinen  : {3} ({4})
>Machinen [](start = 0, length = 8)

extra 'n'?

2017-04-26 06:12 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostStrings.resx
> +Machinen  : {3} ({4})
Fexed.

2017-04-27 15:37 UTC, mirichmo requested changes

2017-04-27 15:37 UTC, mirichmo commented on src/Microsoft.PowerShell.Commands.Management/resources/ClipboardResources.resx
> +</root>
Missing newline here

2017-04-27 15:37 UTC, mirichmo commented on src/Microsoft.PowerShell.Commands.Utility/resources/CsvCommandStrings.resx
> +</root>
And here

2017-04-27 15:37 UTC, mirichmo commented on src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
> +</root>
Here

2017-04-27 15:37 UTC, mirichmo commented on src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostStrings.resx
> +</root>
A guess: I think your script was fairly consistent with these. If it made a change in the file, it didn't add an extra newline at the end. I'm going to stop commenting on each individual one. Please make it consistent throughout if you are going to make this change.

2017-04-27 15:38 UTC, mirichmo commented
@lzybkr - I remember that you had some thoughts on this topic so I wanted to make sure you are aware of this PR.

2017-04-27 17:54 UTC, lzybkr commented
Well, my thoughts are basically - style/formatting changes shouldn't be piecemeal - we should deal with all the files at once. And I'd prefer to see one commit per "kind" of change, say replace tabs, or fix file encoding, or add/remove newlines.

The newline at the end is an annoying issue - some tools expect a newline on the last line (like `wc` and `git`), whereas a human reader, a blank line at the end needlessly takes up space on the screen, so I naturally delete it.

So my point here is - unless we have a pre-commit hook, it's a battle we can't win.

2017-04-28 05:26 UTC, iSazonov commented
I prepared Add Metatests #3504 It cannot be activated until all the files are cleaned up.
The same applies to pre-commit hooks - if today we active it each contributor would have to make many changes to the formatings in addition to his code changes.

I believe we must first do the global file cleanup then activate the checks, first, for the current commits, then globally in the nightly tests.

We have already done a few steps:
@lzybkr  removed trailing whitespace #3001 (not in *.resx).
I converted tab indentations to spaces in *.cs files  #3551.

In the PR I convert tab indentations in *.resx. 
Next I plan to convert tab indentations *.test.ps1 (but I can add the commit to the PR if you want) and then remove trailing whitespace in *.resx.

And in the end I plan to add Newline at EOF in all files.

I did not follow the rule "all the files at once" because @TravisEz13 asked to do a work in smaller chunks to simplify a review.

Can we follow this roadmap?

2017-05-10 21:07 UTC, TravisEz13 commented
The risk of doing everything in one large change is that you won't be able to ever merge the change due to merge conflicts.

2017-05-11 05:22 UTC, iSazonov commented
Conflict was resolved.
Newlines will be fixed in another PR.
Can we continue the code review?

2017-06-01 16:12 UTC, iSazonov commented
@mirichmo Could we continue with the PR?

2017-06-07 01:18 UTC, mirichmo approved these changes

2017-06-07 01:19 UTC, merged