Fixing bug #2607 related to ModuleSpec syntax in RequiredModules
PowerShell/PowerShell pull request #3594
Opened 2017-04-19 06:09 UTC by anmenaga

This fixes issue #2607.
'RequiredModules' is a field in module manifest that can reference other modules using ModuleSpecification format.
The basic version of this format (just module name) was working fine, however there was a problem when more detailed version of the format was used (the one that uses module versions or/and GUIDs).
During module import, there is a check for cyclic references through 'RequiredModules' field. The bug was in this check for cyclic references , related to comparison rules for ModuleSpecification  objects - as a result code was incorrectly reporting 'cyclic reference' error in cases when there was none.

Added tests for different ModuleSpecification formats and a test for error when there is actually a cyclic reference.

Test results before the fix:
![requiredmodulefix_before](https://cloud.githubusercontent.com/assets/11860095/25165483/a07f07fe-248b-11e7-9426-d14f4069b479.png)

Test results after the fix:
![requiredmodulefix_after](https://cloud.githubusercontent.com/assets/11860095/25165482/a064c3b2-248b-11e7-8c9c-147832e85139.png)

2017-04-21 21:47 UTC, chunqingchen requested changes

2017-04-21 21:47 UTC, chunqingchen commented on src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
> +                        requiredModules.Add(requiredModuleSpecification, new List<ModuleSpecification> ( requiredModuleInfo.RequiredModulesSpecification ));
does requiredModuleSpecification only needs to be added when currentModule is not null?
this is confusing here. if so, please add comment explains why

2017-04-21 21:47 UTC, chunqingchen commented on test/powershell/engine/Module/TestModuleManifest.ps1
> +            Import-Module $lastModule -ErrorAction Stop
please also check that the module is actually loaded.

2017-04-28 18:01 UTC, anmenaga commented on src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
> +                        requiredModules.Add(requiredModuleSpecification, new List<ModuleSpecification> ( requiredModuleInfo.RequiredModulesSpecification ));
Originally I was thinking that both addition should be bundled together; but thinking more about it - it is better to move the new addition to its own 'if' check. Updated.

2017-04-28 18:01 UTC, anmenaga commented on test/powershell/engine/Module/TestModuleManifest.ps1
> +            Import-Module $lastModule -ErrorAction Stop
Good point; updated.

2017-04-28 22:22 UTC, chunqingchen approved these changes

2017-04-28 22:23 UTC, chunqingchen commented
good to sign off

2017-05-01 00:58 UTC, merged