Installation docs update for Debian 8 and RHEL 7
PowerShell/PowerShell pull request #3709
Opened 2017-05-05 19:45 UTC by anmenaga

This adds separate installation instructions sections for Debian 8 and RHEL 7.

Related to #1903.

2017-05-05 20:43 UTC, SteveL-MSFT commented on docs/installation/linux.md
> +PowerShell Core, for Linux, is published to package repositories for easy installation (and updates).
It might be worth adding that the Ubuntu14 deb is compatible and tested on Deb8 so that people aren't confused by ubuntu14 being in the URL

2017-05-08 16:58 UTC, SteveL-MSFT requested changes
See comment about Ubuntu14 compatibility

2017-05-09 04:54 UTC, SteveL-MSFT commented on docs/installation/linux.md
> +PowerShell Core, for Linux, is published to package repositories for easy installation (and updates).
@joeyaiello since Andrew is out right now, I made the change in this branch.  can you review the text below and approve for provide feedback?

2017-05-09 19:55 UTC, joeyaiello approved these changes
LGTM

2017-05-09 20:14 UTC, SteveL-MSFT approved these changes

2017-05-09 20:17 UTC, TravisEz13 approved these changes

2017-05-09 20:18 UTC, merged