Fix for issue 3349 - Package name should be el7, not el7.centos
PowerShell/PowerShell pull request #3732
Opened 2017-05-08 20:07 UTC by JamesWTruher

#3349 reference Centos is over specific. It should be simply el7 which is more inclusive

2017-05-08 21:02 UTC, PaulHigin approved these changes
LGTM

2017-05-08 21:45 UTC, daxian-dbw commented
@joeyaiello and @SteveL-MSFT please review to see if the name change is good.

2017-05-09 02:41 UTC, joeyaiello approved these changes

2017-05-09 17:30 UTC, SteveL-MSFT approved these changes

2017-05-09 17:30 UTC, SteveL-MSFT commented
We won't delay beta.1 for this change.

2017-05-09 17:32 UTC, SteveL-MSFT requested changes

2017-05-09 17:32 UTC, SteveL-MSFT commented on build.psm1
> +        $rpm_dist = "el7"
I did a quick search and it appears other scripts need to be updated to reflect the name change

2017-05-23 21:57 UTC, JamesWTruher commented
I think I have them all now

2017-05-23 22:27 UTC, daxian-dbw commented
The changes to markdown files and dockerfiles will break our users, because we currently don't have the package named `powershell-6.0.0_beta.1-1.el7.x86_64.rpm`.
The changes to files other than `build.psm1` would be reverted, and those changes should be done in the next release.

2017-05-30 21:34 UTC, SteveL-MSFT commented
@daxian-dbw so your recommendation is that we stage these changes: change build.psm1 so that our next release will have the correct file name, then update all the readme/scripts to use this new filename after the release, correct?

2017-05-30 21:46 UTC, JamesWTruher commented
ok - pulled first commit, running through CI now

2017-05-30 21:50 UTC, SteveL-MSFT commented on build.psm1
> +        $rpm_dist = "el7"
Based on feedback about breaking existing users, we'll need to state the change so related scripts will be changed as part of https://github.com/PowerShell/PowerShell/issues/3888

2017-05-30 21:51 UTC, SteveL-MSFT approved these changes
LGTM

2017-05-30 22:25 UTC, merged