Do not send telemetry in CI
PowerShell/PowerShell pull request #3785
Opened 2017-05-15 21:20 UTC by JamesWTruher

This removes the telemetry semaphore file in CI for both Travis-CI and AppVeyor

These are done in the travis-cs and appveyor scripts because I only want to remove the telemetry from our CI systems. I want to continue to gather telemetry from local builds which tells us how many are using custom vs release builds.

2017-05-15 23:03 UTC, SteveL-MSFT requested changes

2017-05-15 23:03 UTC, SteveL-MSFT commented on tools/appveyor.psm1
> +    $TelemetrySemaphoreFilePath = join-path $env:CoreOutput DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
We should stick with Pascal casing for cmdlet calls to make it consistent and easier to read

2017-05-15 23:11 UTC, JamesWTruher commented on tools/appveyor.psm1
> +    $TelemetrySemaphoreFilePath = join-path $env:CoreOutput DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
do you mean `join-path` should be `Join-Path`? Shall I fix all of these in this file?

2017-05-16 03:11 UTC, iSazonov commented on tools/appveyor.psm1
> +    $TelemetrySemaphoreFilePath = join-path $env:CoreOutput DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
VS Code shows tons of warnings for Build.psm1 - if we want fix it all we should a separate PR.

2017-05-16 03:14 UTC, iSazonov commented on tools/appveyor.psm1
> +        remove-item -force ${TelemetrySemaphoreFilePath}
We can exclude `test-path` - `remove-item -force` will make everything we need.

2017-05-16 03:14 UTC, iSazonov commented on tools/travis.ps1
> +    remove-item -force ${TelemetrySemaphoreFilePath}
The same about `test-path`.

2017-05-16 16:04 UTC, SteveL-MSFT commented on tools/appveyor.psm1
> +    $TelemetrySemaphoreFilePath = join-path $env:CoreOutput DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
We should have a separate issue for other scripts/modules.  For this file, we should just fix the casing on the new code.

2017-05-16 16:35 UTC, SteveL-MSFT commented on tools/appveyor.psm1
> +    $TelemetrySemaphoreFilePath = join-path $env:CoreOutput DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
Created https://github.com/PowerShell/PowerShell/issues/3791

2017-05-16 18:32 UTC, JamesWTruher commented
i think it should be ok now

2017-05-16 20:10 UTC, SteveL-MSFT approved these changes
LGTM

2017-05-17 18:07 UTC, TravisEz13 approved these changes

2017-05-17 18:08 UTC, merged