Update format-hex tests to include -TestCase parameter
PowerShell/PowerShell pull request #3800
Opened 2017-05-17 18:20 UTC by MiaRomero

Addressing issue #3382 'Use -TestCases parameter in FormatHex.Tests.ps1'.

* Replaced the 'foreach' with the -TestCases parameter in the test helper functions.

2017-05-18 00:01 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +function RunInputObjectTestCase($testCases)
I think that these functions should just be inlined into the appropriate context block. Having these functions only makes things a little harder to find. it allows the test case data be closer to the actual test.

2017-05-18 19:42 UTC, lzybkr commented
@MiaRomero - the assignee of a PR is the person responsible for merging to master - and only maintainers can do that merge. We assign issues to regular contributors, but not the PR.

2017-05-23 15:17 UTC, mirichmo commented
@JamesWTruher or @Francisco-Gamino - Do you guys have any other concerns or comments?

2017-05-25 00:56 UTC, mirichmo commented
@miaromero - We need to add you to the Microsoft organization. I just noticed that you are not a member yet.

2017-05-25 06:02 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $output | Should Not Be $null
We should check $output.Count >=1 or =1  not $null

2017-05-25 06:02 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result | Should Not Be $null
We can remove  - next line make the check.

2017-05-25 06:02 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result | Should Not Be $null
We can remove  - next line make the check.

2017-05-25 06:02 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result | Should Not Be $null
We can remove  - next line make the check.

2017-05-25 06:02 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result | Should Not Be $null
We can remove  - next line make the check.

2017-05-25 06:02 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $thrownError | Should Not Be $null
We can remove  - next line make the check.

2017-05-25 06:02 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $errorThrown | Should Not Be $null
We can remove  - next line make the check.

2017-06-06 19:05 UTC, MiaRomero commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result | Should Not Be $null
Thanks, removed in all mentioned instances.

2017-06-06 19:05 UTC, MiaRomero commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $output | Should Not Be $null
Changed.

2017-06-06 19:12 UTC, MiaRomero commented
@JamesWTruher fixed the >1 issue.   The way it was before was not actually testing the contents of the second file so when I corrected it, those tests failed because the output was on two lines.  I changed the input text to avoid the hassle of having two lines of output in the second expected result (then had to create a file with longer text to test the buffer underrun).

2017-06-30 18:00 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +        $skipTest = ([System.Management.Automation.Platform]::IsLinux -or [System.Management.Automation.Platform]::IsOSX)
I'd be happier if this was combined with the construct in 378
IsLinux -or IsOSX -or (-not $certProviderAvailable)
then 378 could just be:
`It "<Name>" -Skip:$skip`
same with the code below

2017-08-16 19:05 UTC, adityapatwardhan requested changes

2017-08-16 19:05 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result[1].ToString() | Should be "00000010   72 20 6F 66 20 6F 75 72 20 64 69 73 63 6F 6E 74  r of our discont"
Should use MatchExactly like here: https://github.com/PowerShell/PowerShell/blob/7b8c6e7f548e5ab98e9d36d073e5af7d989c8f79/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1#L499

2017-08-16 19:05 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result[0].ToString() | Should be "00000000   4E 6F 77 20 69 73 20 74 68 65 20 77 69 6E 74 65  Now is the winte"
Should use MatchExactly like here: https://github.com/PowerShell/PowerShell/blob/7b8c6e7f548e5ab98e9d36d073e5af7d989c8f79/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1#L499

2017-08-16 19:05 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +            $result[2].ToString() | Should be "00000020   65 6E 74                                         ent             "
Should use MatchExactly like here: https://github.com/PowerShell/PowerShell/blob/7b8c6e7f548e5ab98e9d36d073e5af7d989c8f79/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1#L499

2017-08-16 20:53 UTC, MiaRomero commented on test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
> +    Context "Path and LiteralPath Paramaters" {
Fixed

2017-08-16 21:11 UTC, MiaRomero commented
Thanks @adityapatwardhan for the comments - fixed all the Match to MatchExactly.

2017-08-16 21:23 UTC, adityapatwardhan approved these changes
LGTM

2017-08-16 22:50 UTC, merged