Fix for Get-Content -Delimiter including the delimiter in the  array …
PowerShell/PowerShell pull request #3808
Opened 2017-05-18 04:55 UTC by mklement0

…elements returned (#3706)

2017-05-18 04:55 UTC, msftclas commented
@mklement0,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-05-18 11:03 UTC, iSazonov reviewed
@mklement0  It seems you don't fix "tail".

/cc @jeffbi Could you please review?

2017-05-18 16:56 UTC, mklement0 commented
@iSazonov Thanks for catching the `-tail` issue - oddly, the tests pass on _macOS_ (which is where I ran them before submitting the PR). I'll look into it.

2017-05-18 18:31 UTC, iSazonov commented
I believe the problem is in platform difference of Newline.

2017-05-24 17:12 UTC, adityapatwardhan requested changes

2017-05-24 17:12 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
>    It "should throw 'PSNotSupportedException' when you set-content to an unsupported provider" -Skip:($IsLinux -Or $IsOSX) {
Any reason to skip on Linux or OSX?

2017-05-24 18:21 UTC, mklement0 commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
>    It "should throw 'PSNotSupportedException' when you set-content to an unsupported provider" -Skip:($IsLinux -Or $IsOSX) {
I didn't write these tests (and the only modification I made was to resolve aliases to their full cmdlet names), but I can look into it.

2017-05-24 18:23 UTC, mklement0 commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
>    It "should throw 'PSNotSupportedException' when you set-content to an unsupported provider" -Skip:($IsLinux -Or $IsOSX) {
Again, I can't speak to these tests, but perhaps `BugId(BugDatabase.WindowsOutOfBandReleases, 906022)` holds the key? 

Separately, if you have any pointers for why the PR doesn't work on _Windows_ (have yet to dig into it), that would be helpful.

2017-06-01 16:36 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
>    It "should throw 'PSNotSupportedException' when you set-content to an unsupported provider" -Skip:($IsLinux -Or $IsOSX) {
Rather than change it here, I suggest we open a new issue to refactor these test cases to use `-TestCase`

2017-06-01 16:36 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
>    It "should throw 'PSNotSupportedException' when you set-content to an unsupported provider" -Skip:($IsLinux -Or $IsOSX) {
unfortunately, I don't know if that bug database even exists anymore.  that comment is basically worthless now.

2017-06-06 15:28 UTC, mirichmo commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
>    It "should throw 'PSNotSupportedException' when you set-content to an unsupported provider" -Skip:($IsLinux -Or $IsOSX) {
I filed Issue #3945 to cover this comment.

2017-06-06 15:30 UTC, mirichmo commented
@adityapatwardhan I don't see any more outstanding comments. Do you have any additional concerns?

2017-06-06 16:46 UTC, adityapatwardhan approved these changes

2017-06-06 18:35 UTC, mirichmo commented
@mklement0 Please address the failing test:

 [-] should Get-Content with a variety of -Tail and -ReadCount values 68ms
   Expected: {2}
   But was:  {3}
   at line: 104 in C:\projects\powershell\test\powershell\Modules\Microsoft.PowerShell.Management\Get-Content.Tests.ps1
   104:     $result.Length    | Should Be 2

2017-06-07 01:58 UTC, mklement0 commented
@mirichmo: I'll take a look soon. In the meantime, if you have a high-level pointer as to how the platform-specific newline sequence might come into play here (it works in the Unix world, but not on Windows), please let me know.

2017-08-24 15:24 UTC, iSazonov commented
@mklement0 Test failed for `-Tail` parameter. If we use the parameter we call `ReadDelimited()` twice - (1) to seek start position - backward read, (2) read forward and parse the file. In the case we can not simply remove the delimiter character from the stream because we use it in SeekItemsBackward() to correct start position. It seems there is still problem places - leave the research to you 😄  Please continue the PR.

Also I see the code is not optimal and we should refactor this in another PR.

2017-08-26 03:07 UTC, mklement0 commented
Thanks for the tips, @iSazonov.
I hope to get to this soon (I know, deja vu).

2017-08-30 20:16 UTC, mklement0 commented
Note that the only changes to `Get-Content.Tests.ps1` since the original commit were whitespace normalization (conversion to all-spaces, though I now realize that there are some inconsistencies).

Thanks to @iSazonov  for pointing me to what I hope is the right fix, which turned out to be simple in the end.

2017-08-30 21:44 UTC, SteveL-MSFT approved these changes

2017-08-31 05:19 UTC, iSazonov commented on src/System.Management.Automation/namespaces/FileSystemContentStream.cs
> +                        : content.ToString()
Here we evaluate `content.ToString()` twice - maybe do this one before `block.Add()`.

2017-08-31 05:30 UTC, iSazonov commented
@mklement0 Could you please split functional and formatting changes to two commits? This will help us avoid error skipping.
Use soft reset, then  git add -p.

2017-08-31 20:58 UTC, mklement0 commented
@iSazonov: I've made the changes and split them into 2 commits (functional vs. formatting) that replaced the earlier ones. 

I think the Travis CI failure is a transient one, unrelated to my changes (it got stuck while setting up the environment). 

Is there a way to re-initiate the test?

2017-08-31 21:38 UTC, SteveL-MSFT commented
@mklement0 I restarted that job for you

2017-09-01 02:29 UTC, mklement0 commented
Thanks, @SteveL-MSFT. It failed again; it looks like there's a fundamental problem with the macOS builds at the moment: it gets stuck at `make install` for the `curl` Homebrew download.

2017-09-01 17:59 UTC, iSazonov commented
@mklement0 You can "rename" last commit to restart CI jobs.

2017-09-01 18:01 UTC, mklement0 commented
Thanks, @iSazonov, but how do you rename a commit? Amend the commit message and push again?

2017-09-01 18:49 UTC, daxian-dbw commented
Thanks all! Since we got 2 approvals and @iSazonov's comments are also addressed, I will rebase and merge this PR soon (in about one hour). Please let me know if there are any concerns.

2017-09-01 20:01 UTC, merged

2017-09-02 16:45 UTC, iSazonov commented
@mklement0 Yes, you can amend or rebase+reword.