Remove undocumented certificate APIs
PowerShell/PowerShell pull request #3818
Opened 2017-05-19 01:49 UTC by TravisEz13

Addresses #3792

2017-05-19 02:24 UTC, SteveL-MSFT requested changes
Is there sufficient test coverage?

2017-05-19 02:24 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                        if(nameLine.Length > 9)
Any validation needed here?  Prefer to have const DnsNamePrefixLength used than 9

2017-05-19 02:32 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +            return new CertificateProviderCodeSigningDynamicParameters();
This is the code path that is always taken on `Windows PowerShell`.  It should work.

2017-05-19 02:32 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                //TODO: Log Cert Delete
I'm not sure we need these, but I'll open an issue or remove them based on my investigation.

2017-05-19 02:48 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                        if(nameLine.Length > 9)
Yes, I was planning on adding it with the support for punyCode.  The only way I can see puny code being supported is a different record format.

2017-05-19 19:23 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                //TODO: log cert move
filed #3826, until this is resolved

2017-05-19 19:23 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                //TODO: Log Cert Delete
filed #3826, until this is resolved

2017-05-19 20:36 UTC, SteveL-MSFT reviewed
My concerns are addressed, but would like @LeeHolmes to review before we merge

2017-05-22 18:11 UTC, PaulHigin requested changes

2017-05-22 18:11 UTC, PaulHigin commented on test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1
> +Import-Module (Join-Path -Path $PSScriptRoot 'certificateCommon.psm1') -Force
Please put this test prep inside "if ($IsWindows) {}"

2017-05-22 18:19 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> -                if (_filterHandle != null)
probably just performance.  Looking at the CmdLet we only supported filtering by codesigning certs which the tests pass after the change.

2017-05-22 18:20 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                if (extension.Oid.FriendlyName == "Enhanced Key Usage")
Comparing the value would be better.  I'll update the code.

2017-05-22 18:22 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                            if(!_dnsList.Contains(dnsName))
The old code gave all variations back in the results.  So, no.

2017-05-22 18:27 UTC, TravisEz13 commented on test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1
> +Import-Module (Join-Path -Path $PSScriptRoot 'certificateCommon.psm1') -Force
What is the concern here?

2017-05-22 18:30 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> -                if (_filterHandle != null)
line 2636, is filtering.

2017-05-22 18:32 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> -                return new CertificateProviderDynamicParameters();
#resolved

2017-05-22 18:34 UTC, PaulHigin commented on test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1
> +Import-Module (Join-Path -Path $PSScriptRoot 'certificateCommon.psm1') -Force
It seems like we can skip the prep work if not running on Windows.

2017-05-22 18:55 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                if (extension.Oid.FriendlyName == "Enhanced Key Usage")
Except that is the OID for a specific EKU, not specifying an EKU.  The OID should be 2.5.29.37

2017-05-22 19:16 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                if (extension.Oid.FriendlyName == "Enhanced Key Usage")
#Resolved

2017-05-22 19:16 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                    X509EnhancedKeyUsageExtension ext = (X509EnhancedKeyUsageExtension)extension;
#Resolved

2017-05-22 19:18 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +        private static string dnsNamePrefix = "DNS Name=";
#resolved

2017-05-22 19:22 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                        if(nameLine.Length > dnsNamePrefix.Length && nameLine.StartsWith(dnsNamePrefix, System.StringComparison.InvariantCulture))
#resolved

2017-05-22 19:22 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +            if(cert.Subject.Length > distinguishedNamePrefix.Length &&
#resolved

2017-05-22 19:23 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
> +                            if(!_dnsList.Contains(dnsName))
#resolved

2017-05-22 19:44 UTC, TravisEz13 commented on test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1
> +Import-Module (Join-Path -Path $PSScriptRoot 'certificateCommon.psm1') -Force
The only imports functions, the actual prep work is done in the `beforeall` of the feature tests and is skipped on non-windows platforms.

2017-05-22 21:13 UTC, PaulHigin approved these changes
LGTM

2017-05-22 23:34 UTC, SteveL-MSFT approved these changes

2017-05-23 05:33 UTC, merged