Add Homebrew to install docs
PowerShell/PowerShell pull request #3838
Opened 2017-05-22 17:45 UTC by joeyaiello

Fixes #1779 

It would be awesome if someone who actually has a Mac (like @JamesWTruher or @BrucePay) can validate these instructions before we merge them.

Also, it would be great to know how accurate [these directions](https://github.com/PowerShell/PowerShell/compare/master...joeyaiello:HomebrewDocs?expand=1#diff-cb58069b7222dfcd5130fd97bf93e6e1R397) currently are. The reference to .NET Core 1.0.0 makes me think it might be a little outdated.

2017-05-23 22:58 UTC, JamesWTruher commented on docs/installation/linux.md
> +brew uninstall powershell
i needed to do `brew cask uninstall powershell`

2017-05-23 22:58 UTC, JamesWTruher commented on docs/installation/linux.md
> +brew upgrade powershell
i don't think these are right - they're not working for me. I get an error message:
```
brew upgrade powershell
Error: No available formula with the name "powershell" 
```

2017-05-24 17:20 UTC, joeyaiello commented on docs/installation/linux.md
> +brew upgrade powershell
How about `brew cask upgrade powershell`?

2017-05-25 18:22 UTC, joeyaiello commented on docs/installation/linux.md
> +brew uninstall powershell
Fixed.

2017-06-03 04:00 UTC, vors commented on docs/installation/linux.md
> +brew upgrade powershell
```
brew cask reinstall powershell
```

2017-06-03 04:06 UTC, vors requested changes

2017-06-03 04:06 UTC, vors commented on docs/installation/linux.md
> +brew tap caskroom/cask
This line is installation instruction for cask.
It's not clear from the comment that these two lines correspond to two steps above.

I'd break it down into two parts.

2017-06-03 04:06 UTC, vors commented on docs/installation/linux.md
> +If you PowerShell with Homebrew, uninstallation is easy:
Maybe `If you PowerShell installed with Homebrew` ? Not an English expert, but this language feels too playful :)

2017-06-03 04:06 UTC, vors commented on docs/installation/linux.md
> +The easiest fix is to install [Homebrew's OpenSSL][openssl]:
This is auto-included in powershell brew formula (it's a dependency I think)
Worth pointing out here that it's not required as a separate step with brew.

2017-06-06 15:34 UTC, mirichmo commented
@joeyaiello Don't forget about this one

2017-06-06 18:18 UTC, joeyaiello commented on docs/installation/linux.md
> +If you PowerShell with Homebrew, uninstallation is easy:
Hahahaha, I just accidentally a word.

2017-06-06 18:19 UTC, joeyaiello commented on docs/installation/linux.md
> +brew upgrade powershell
Wait, `reinstall` is the upgrade command?

2017-06-06 18:19 UTC, joeyaiello commented
@mirichmo I hadn't! I just didn't realize anyone had responded yet? It's hard for me to get this one right because I don't actually have a Mac....

2017-06-11 10:16 UTC, Happycoil commented on docs/installation/linux.md
> +brew upgrade powershell
@joeyaiello For now at least, see https://github.com/caskroom/homebrew-cask/issues/29301

2017-06-20 01:20 UTC, mirichmo commented
@vors - Are all your concerns addressed?

2017-06-20 17:57 UTC, joeyaiello commented
@mirichmo sorry, this is on me. I've been meaning to grab the Macbook from @daxian-dbw, gotta do my validation real quick.

2017-06-22 18:04 UTC, joeyaiello commented on docs/installation/linux.md
> +brew upgrade powershell
Oh, interesting...thanks for the pointer. Looks like that's the way to go now. I'm updating the docs accordingly.

2017-06-27 17:33 UTC, joeyaiello commented
Okay, sorry for taking so long on this. @mirichmo: it should be good to go now. I validated all the instructions on a Macbook. :)

2017-06-28 23:42 UTC, mirichmo commented
@vors Do you have any additional comments or concerns?

2017-07-11 13:26 UTC, jpogran commented
FWIW, followed these instructions on macOS 10.12.5 with homebrew and cask and it worked for me

2017-08-07 21:31 UTC, joeyaiello commented
@mirichmo I think I have enough approval (and have adequately addressed @vors' concerns).

2017-08-07 22:27 UTC, merged