Update README.md
PowerShell/PowerShell pull request #3873
Opened 2017-05-27 07:38 UTC by SRGOM

Added link to "awesome-powershell“

2017-05-27 07:38 UTC, msftclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-05-27 16:04 UTC, iSazonov reviewed
Leave a comment

2017-05-27 16:04 UTC, iSazonov commented on README.md
> +## Addons and libraries
I believe "Add-Ons" is better term.
Also please add it in https://github.com/PowerShell/PowerShell/blob/master/.spelling

2017-05-27 17:33 UTC, iSazonov commented
Please remove trailing spaces:
> C:\projects\powershell\README.md: 84: MD009 Trailing spaces

2017-05-28 04:50 UTC, SteveL-MSFT requested changes

2017-05-28 04:50 UTC, SteveL-MSFT commented on README.md
> +[Awesome powershell](https://github.com/janikvonrotz/awesome-powershell) is a great curated list of add-ons and resources.
Correct casing PowerShell

2017-05-28 07:12 UTC, SRGOM reviewed
My approve option is greyed out sorry...

2017-05-28 17:41 UTC, iSazonov commented
@SRGOM Approve option is for reviewers only.

2017-05-30 17:48 UTC, joeyaiello requested changes

2017-05-30 17:48 UTC, joeyaiello commented on README.md
> +[Awesome powershell](https://github.com/janikvonrotz/awesome-powershell) is a great curated list of add-ons and resources.
With this change, I can approve

2017-06-07 23:25 UTC, merged