Make Move-Item work with its -Include, -Exclude, and -Filter parameters
PowerShell/PowerShell pull request #3878
Opened 2017-05-30 03:35 UTC by jeffbi

Fixed #2385 

Invoke the correct overload of SessionState.Path.GetResolvedPSPathFromPSPath, passing the cmdlet context object.

2017-05-30 04:04 UTC, jeffbi commented
@iSazonov Can you take a look at the Appveyor failure? I'm looking at the details and they seem to show two failure points, neither of which have anything to do with this PR.

2017-05-30 04:20 UTC, iSazonov commented
@jeffbi I see the same in other PRs.

2017-05-30 04:29 UTC, iSazonov reviewed
Original Issue say that the cmdlet works well but writes unexpected error message - I don't  see the check in tests.

2017-05-30 05:46 UTC, jeffbi commented
@iSazonov Well, what it actually said what that the cmdlet successfully performed the action that was _intended_, then wrote an error. That's not quite the same as it worked well.

I've updated the tests to check that the `Move-Item` was successful, and also to ensure verify that files meant to be unaffected were unaffected.

2017-05-30 06:02 UTC, iSazonov commented
LGTM.

2017-06-05 21:27 UTC, adityapatwardhan requested changes

2017-06-05 21:27 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            New-Item -ItemType Directory -Path $filterPath
Should be 
```Powershell
New-Item -ItemType Directory -Path $filterPath | Out-Null
```
to avoid on console output of created item

2017-06-05 21:27 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            Test-Path -Path $barPath | Should Be $false
Use  ```Powershell $barPath | Should Not Exist"  ```

2017-06-05 21:27 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            $? | Should Be $true
Difficult to debug from logs. Instead use 
```Powershell 
Move-Item -Path $filePath -Destination $moveToPath -Include "bar*" -ErrorVariable e -ErrorAction SilentlyContinue
$e | Should BeNullOrEmpty
```

2017-06-05 22:59 UTC, jeffbi commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            New-Item -ItemType Directory -Path $filterPath
Fixed.

2017-06-05 22:59 UTC, jeffbi commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            $? | Should Be $true
Fixed

2017-06-05 22:59 UTC, jeffbi commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            Test-Path -Path $barPath | Should Be $false
Fixed

2017-06-05 23:10 UTC, adityapatwardhan approved these changes

2017-06-06 03:41 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            #Test-Path -Path $barPath | Should Be $false
Please remove the comment.

2017-06-06 03:44 UTC, iSazonov commented
@jeffbi Thanks for the fix!

LGTM. (After removing one unneeded comment)

2017-06-06 04:30 UTC, jeffbi commented on test/powershell/Modules/Microsoft.PowerShell.Management/Move-Item.Tests.ps1
> +            #Test-Path -Path $barPath | Should Be $false
Thanks for catching that. Fixed.

2017-06-06 04:31 UTC, jeffbi commented
@iSazonov, @adityapatwardhan Thanks for the review.

2017-06-08 19:35 UTC, TravisEz13 commented
@jeffbi Can you update or remove the company in your profile?  If it is accurate, please email me internally about additional steps you need to take.

@adityapatwardhan Please make your Microsoft Organization membership public.

2017-06-23 02:14 UTC, merged