Added functionality to load Windows Powershell Modules
PowerShell/PowerShell pull request #3900
Opened 2017-05-31 23:06 UTC by adityapatwardhan

A lot of binary modules written for Windows Powershell (Full cLR) use GAC for their assemblies.
CoreCLR does not have a GAC and hence fails to locate the assemblies.

Added functionality to search the well known location of GAC on Windows to load the assemblies.
This functionality can be opted-in by adding a key-value to PowershellProperties.json file at $PSHOME.
The key-value pair for enabling GAC loading is: "AllowGacLoading" : "true"

2017-05-31 23:31 UTC, daxian-dbw commented
Talked to @adityapatwardhan offline. The GAC probing logic should be put in AssemblyLoadContext and hook up with the `Resolving` event of the default loader. `Assembly.Load` will trigger the `Resolving` event if the default loader cannot resolve the assembly request. Implicit assembly loading is also taken care of by `Assembly.Load` in this way.

2017-05-31 23:50 UTC, daxian-dbw commented on src/System.Management.Automation/engine/PropertyAccessor.cs
> +        /// <returns>Always true, as this is for Full CLR.</returns>
We don't need to do this for FullCLR. Assembly.Load already takes care of GAC in FullCLR.

2017-06-01 00:23 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/PropertyAccessor.cs
> +        /// <returns>Always true, as this is for Full CLR.</returns>
I had two options.. 
1. Add it to the interface, hence need to implement it in RegistryAccessor and JsonConfigFileAccessor.
2. Implement it as a static method on JsonConfigFileAccessor and break the strategy pattern.

I ended up going with number 1.

2017-06-01 00:54 UTC, anmenaga commented on src/System.Management.Automation/engine/ExecutionContext.cs
> +                // GAC only has 1 file in the folder, so we can pick index 0.
Several versions of same assembly?
What if a binary module references v2 of an assembly, when GAC has v1 and v2 of that assembly installed?

2017-06-01 16:25 UTC, SteveL-MSFT requested changes

2017-06-01 16:25 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/ExecutionContext.cs
> +            string winDirPath = Environment.GetEnvironmentVariable("WINDIR");
seems like this may be called often enough to cache

2017-06-01 16:25 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/PropertyAccessor.cs
> +            return ReadValueFromFile<bool>(fileName, "AllowGacLoading");
@joeyaiello did we agree to make this opt-out vs opt-in?  I think that for most customers, they won't know to add a setting to a config file and will give up on PSCore6.  Perhaps we should default to opt-out and document this is best effort?

2017-06-01 16:25 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
> +        $PSProperties | Add-Member -MemberType NoteProperty -Name 'AllowGacLoading' -Value 'true'
there should be a test case to validate the default config and behavior

2017-06-01 16:25 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
> +        $modulePath = Join-Path $env:windir "System32/WindowsPowershell/v1.0/Modules/PSScheduledJob"
can we validate the x86 path as well?

2017-06-01 16:53 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/PropertyAccessor.cs
> +            return ReadValueFromFile<bool>(fileName, "AllowGacLoading");
@SteveL-MSFT @joeyaiello I believe it was discussed to be opt-in due to performance implications. From what I see, the performance difference is not noticeable. So should I change it to opt-out?

2017-06-01 17:41 UTC, joeyaiello commented on src/System.Management.Automation/engine/PropertyAccessor.cs
> +            return ReadValueFromFile<bool>(fileName, "AllowGacLoading");
Let's push the issue while we're in beta by making it default. I'd rather people complained about performance than have no one discover this feature. We can always roll it back out and do strong documentation later. 

So yeah, I say the default should be on, and then we should get customer feedback that tells us to turn it off.

2017-06-03 18:22 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/PropertyAccessor.cs
> +            return ReadValueFromFile<bool>(fileName, "AllowGacLoading");
Agree, we can revisit based on feedback

2017-06-07 17:34 UTC, adityapatwardhan commented
Closing this PR and will start a new one for changes in AssemblyLoadContext.

2017-06-07 17:34 UTC, closed without merging