Add version to PowerShell banner
PowerShell/PowerShell pull request #3916
Opened 2017-06-02 09:09 UTC by iSazonov

Close #3895 

Motivation
---
Since we support side-by-side, it makes it easier to see which PowerShell version you started rather than checking $psversiontable or $pshome.

Fix
---

Add "GitCommitId" to PowerShell banner.

2017-06-03 03:53 UTC, vors requested changes

2017-06-03 03:53 UTC, vors commented on src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
> +Version: {0}</value>
I think the version proposed by @SteveL-MSFT originally reads nicer:

```
PowerShell {0}
Copyright (C) Microsoft Corporation. All rights reserved.
```

For example, here is how python banner looks like
```
Python 2.7.10 (default, Oct 18 2015, 00:31:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

2017-06-03 06:24 UTC, iSazonov commented on src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
> +Version: {0}</value>
I think it doesn't look elegant :-) but fixed.

2017-06-03 18:14 UTC, SteveL-MSFT approved these changes
LGTM

2017-06-07 07:03 UTC, iSazonov commented
@vors Can you approve and merge?

2017-06-07 22:59 UTC, merged