Update ISSUE_TEMPLATE.md - added code blocks
PowerShell/PowerShell pull request #3953
Opened 2017-06-06 19:56 UTC by mklement0

Fix for #3952. Adds fenced code blocks / output blocks to the `Steps to reproduce`, `Expected behavior` and `Actual behavior` sections, so as to facilitate proper formatting.

2017-06-06 19:56 UTC, msftclas commented
@mklement0,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-06-06 21:11 UTC, SteveL-MSFT requested changes

2017-06-06 21:11 UTC, SteveL-MSFT commented on .github/ISSUE_TEMPLATE.md
> +```none
I would suggest defaulting the code block to `powershell` instead of `none`, same below

2017-06-06 21:30 UTC, mklement0 commented on .github/ISSUE_TEMPLATE.md
> +```none
@SteveL-MSFT: `powershell` is for highlighting PowerShell _source code_, whereas  _output_ will generally _not_ be _source code_ - in which case highlighting as if it _were_ can be distracting.

2017-06-07 05:10 UTC, SteveL-MSFT commented on .github/ISSUE_TEMPLATE.md
> +```none
Makes sense

2017-06-07 05:10 UTC, SteveL-MSFT approved these changes

2017-06-07 05:54 UTC, iSazonov commented
LGTM.

2017-06-07 13:59 UTC, merged