Added logic in AssemblyLoadContext to load assembly from GAC.
PowerShell/PowerShell pull request #3981
Opened 2017-06-09 18:54 UTC by adityapatwardhan

When Resolve method is not able to find the assembly, we try to look it up from GAC.
If found, the assembly is loaded and cached.
There is a TestHook to disable GAC loading, but it is enabled by default.

2017-06-09 18:54 UTC, adityapatwardhan commented
Rebasing did not get rid of the changes in test unrelated to this commit.

2017-06-09 21:47 UTC, SteveL-MSFT commented
@adityapatwardhan if you click the TestCases tab, the test failure is your new test loading PSScheduledJob module.  The other error output isn't fatal and fixed by https://github.com/PowerShell/PowerShell/pull/3968

2017-06-10 00:07 UTC, SteveL-MSFT requested changes

2017-06-10 00:07 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +        private string winDir;
convention is to use leading underscore for private fields

2017-06-10 00:07 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && PowerShellAssemblyLoadContextTestHooks.AllowGACLoading)
Wouldn't it be better to `#ifdef !UNIX` line 265 (calling this method) above as well as this whole method?

2017-06-10 00:07 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +            char dirSeparator = IO.Path.DirectorySeparatorChar;
const?

2017-06-10 00:07 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +            char dirSeparator = IO.Path.DirectorySeparatorChar;
const?

2017-06-10 00:07 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +                var choosenVersionDirectory = Directory.GetDirectories(tempAssemblyDirPath).OrderBy(d => d).LastOrDefault();
I think this is a typo: chosenVersionDirectory

2017-06-10 00:26 UTC, adityapatwardhan commented
@SteveL-MSFT  Fixed all CR comments.

2017-06-10 03:44 UTC, SteveL-MSFT requested changes

2017-06-10 03:44 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +#ifdef !UNIX
You still have to return null if UNIX right?

2017-06-14 18:51 UTC, adityapatwardhan commented
Having a look at the test failure.

2017-06-14 20:08 UTC, adityapatwardhan commented
@SteveL-MSFT  All comments / issues fixed. Please have a look.

2017-06-15 18:12 UTC, SteveL-MSFT approved these changes
LGTM

2017-06-15 18:16 UTC, adityapatwardhan commented
@daxian-dbw  Can you also have a look. Thanks!

2017-06-15 19:51 UTC, daxian-dbw commented
Looking now.

2017-06-15 20:18 UTC, daxian-dbw approved these changes

2017-06-15 20:26 UTC, merged

2017-06-16 06:07 UTC, iSazonov commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +    public static class PowerShellAssemblyLoadContextTestHooks
We have [public static class InternalTestHooks](https://github.com/PowerShell/PowerShell/blob/578f9e5e8b86835e5c40be4a9306adf91d5899af/src/System.Management.Automation/engine/Utils.cs#L1588) for test hooks.

2017-06-16 17:07 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CoreCLR/CorePsAssemblyLoadContext.cs
> +    public static class PowerShellAssemblyLoadContextTestHooks
@iSazonov  That is in a different assembly, so could not re-use it.