Run PowerShell in latest Kali
PowerShell/PowerShell pull request #4035
Opened 2017-06-16 19:44 UTC by mrpnkt

2017-06-16 19:44 UTC, msftclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-06-17 12:42 UTC, iSazonov commented
@mrpnkt Thanks for your contribution!

Markdown test failed - please correct.

2017-06-17 21:25 UTC, mrpnkt reviewed
error in code block language (markdown fail)

2017-06-22 02:21 UTC, TravisEz13 commented on docs/installation/linux.md
> +wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.18/PowerShell-6.0.0-alpha.18-x86_64.AppImag
You are missing an `e` in `AppImage`

2017-06-22 02:22 UTC, TravisEz13 requested changes
see code comments

2017-06-23 01:46 UTC, TravisEz13 requested changes

2017-06-23 01:46 UTC, TravisEz13 commented on docs/installation/linux.md
> +chmod a+x PowerShell-6.0.0-alpha.18-x86_64.AppImag
Also here

2017-06-23 01:46 UTC, TravisEz13 commented on docs/installation/linux.md
> +./PowerShell-6.0.0-alpha.18-x86_64.AppImag
and here

2017-06-25 19:14 UTC, TravisEz13 approved these changes

2017-06-25 19:15 UTC, merged