Address static analysis issues in SSH remoting
PowerShell/PowerShell pull request #4083
Opened 2017-06-22 22:25 UTC by SteveL-MSFT

- remoteRunspaces is not used TFS:10618323
- not checking return value of ResumeThread() TFS:10618344

2017-06-23 01:04 UTC, mirichmo requested changes

2017-06-23 01:04 UTC, mirichmo commented on src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
> +                if (returnValue == 4294967295) // same as (DWORD)-1
We should not use magic numbers in the code. Please define a descriptive constant for this value.

2017-06-23 03:12 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
> +                if (returnValue == 4294967295) // same as (DWORD)-1
fixed

2017-06-24 14:46 UTC, SteveL-MSFT commented
@mirichmo fixed

2017-06-26 15:55 UTC, PaulHigin approved these changes
LGTM

2017-06-28 17:39 UTC, mirichmo requested changes

2017-06-28 17:39 UTC, mirichmo commented on src/System.Management.Automation/utils/PlatformInvokes.cs
> +        internal static uint RESUME_THREAD_FAILED = 4294967295; // (DWORD)-1
Please use System.UInt32.MaxValue instead

2017-06-28 18:55 UTC, SteveL-MSFT commented on src/System.Management.Automation/utils/PlatformInvokes.cs
> +        internal static uint RESUME_THREAD_FAILED = 4294967295; // (DWORD)-1
will fix, seems obvious now :)

2017-06-28 23:27 UTC, mirichmo approved these changes

2017-06-28 23:27 UTC, merged