Add -SkipHeaderValidation switch to Invoke-WebRequest and Invoke-RestMethod to support adding headers without validating the header value.
PowerShell/PowerShell pull request #4085
Opened 2017-06-22 22:58 UTC by dantraMSFT

Fixes https://github.com/PowerShell/PowerShell/issues/2895

Some sites require header values that do not conform to strict validation in the CoreCLR's HttpRequestMessage.Headers collection causing calls to Invoke-WebRequest and Invoke-RestMethod to fail with a FormatException.

This change adds a -SkipHeaderValidation switch that allows the headers to be added without validation.

2017-06-23 00:54 UTC, SteveL-MSFT commented
You need to rebase and only include the commits for this PR

2017-06-23 16:19 UTC, dantraMSFT commented
Rebased.

2017-06-23 17:30 UTC, SteveL-MSFT requested changes

2017-06-23 17:30 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +
Looks like you accidentally added whitespace

2017-06-23 17:30 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error.FullyQualifiedErrorId | Should Be "System.FormatException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand"
Use the `ShouldBeErrorId` pattern https://github.com/PowerShell/PowerShell/search?utf8=%E2%9C%93&q=ShouldBeErrorId&type=

2017-06-23 17:30 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error.FullyQualifiedErrorId | Should Be "System.FormatException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand"
Use the `ShouldBeErrorId` pattern

2017-06-23 17:30 UTC, SteveL-MSFT commented on test/tools/Modules/HttpListener/HttpListener.psm1
> +                        "echo"
"echo" doesn't seem to be necessary as "response" basically does the same thing.  I would suggest updating "response" if you want json (perhaps based on "contenttype"

2017-06-23 18:16 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error.FullyQualifiedErrorId | Should Be "System.FormatException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand"
I can't use ShouldBeErrorId for those statements; it expects a ScriptBlock to execute and a thrown exception.

2017-06-23 18:26 UTC, dantraMSFT commented on test/tools/Modules/HttpListener/HttpListener.psm1
> +                        "echo"
Changing "response"  to use JSON for the output breaks many tests.

2017-06-23 18:30 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error.FullyQualifiedErrorId | Should Be "System.FormatException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand"
ShouldBeErrorId does not work here; it expects a script block and then catches the exception to verify the error id.

2017-06-23 18:30 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +
Will fix

2017-06-23 20:27 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +
I updated the file and removed all trailing whitespace per the using-vscode.md to get the file to a 'clean' state.

2017-06-23 22:43 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error.FullyQualifiedErrorId | Should Be "System.FormatException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand"
Ok

2017-06-23 22:43 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error.FullyQualifiedErrorId | Should Be "System.FormatException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand"
Ok

2017-06-23 22:44 UTC, SteveL-MSFT commented on test/tools/Modules/HttpListener/HttpListener.psm1
> +                        "echo"
I'm not suggesting always return json.  "response" takes a contenttype argument you can use.

2017-06-23 23:31 UTC, dantraMSFT commented on test/tools/Modules/HttpListener/HttpListener.psm1
> +                        "echo"
I think it makes more sense to have a separate 'echo' test.  The returned data for response would be very different; it currently doesn't echo the request, and using contentype to control that doesn't make sense to me.

2017-06-23 23:50 UTC, SteveL-MSFT commented on test/tools/Modules/HttpListener/HttpListener.psm1
> +                        "echo"
ok

2017-06-23 23:50 UTC, SteveL-MSFT submitted a review, later dismissed

2017-06-24 17:07 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +
Local and online diff sometimes surprise us.
Here may be a real difference in '`r`n' and ``n`.

2017-07-05 16:26 UTC, dantraMSFT commented
@TravisEz13 please merge this PR.

2017-07-07 21:55 UTC, TravisEz13 commented
@dantraMSFT  Please resolve merge conflicts

2017-07-10 17:19 UTC, dantraMSFT commented
@TravisEz13: Conflicts resolved.

2017-07-11 18:37 UTC, TravisEz13 commented
@dantraMSFT  You used an "email address" to commit which is not associated with your GitHub account.  Please add the association.
@SteveL-MSFT I'm removing your approval since the PR has changed.

2017-07-11 18:44 UTC, dantraMSFT commented
@SteveL-MSFT, please reapprove this PR.

2017-07-12 23:06 UTC, dantraMSFT commented
@TravisEz13: Can you look at this? Steve is out until next week.

2017-07-13 05:57 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
We can remove this - next line makes the check.

2017-07-13 05:57 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should Not BeNullOrEmpty
Tha same.

2017-07-13 05:57 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
The same.

2017-07-13 05:57 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
Tha same.

2017-07-13 05:57 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should Not BeNullOrEmpty
The same.

2017-07-13 05:57 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
The same.

2017-07-13 19:52 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
The check is intentional.  Checking for $result.Error provides a better failure id if the underlying request fails versus the  NullReferenceException that would occur in the next statement.

2017-07-13 19:52 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should Not BeNullOrEmpty
The check is intentional.  Checking for $result.Error provides a better failure id if the underlying request fails versus the  NullReferenceException that would occur in the next statement.

2017-07-13 19:53 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
The check is intentional. Checking for $result.Error provides a better failure id if the underlying request fails versus the NullReferenceException that would occur in the next statement.

2017-07-13 19:53 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should Not BeNullOrEmpty
The check is intentional. Checking for $result.Error provides a better failure id if the underlying request fails versus the NullReferenceException that would occur in the next statement.

2017-07-13 19:53 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
The check is intentional. Checking for $result.Error provides a better failure id if the underlying request fails versus the NullReferenceException that would occur in the next statement.

2017-07-14 05:12 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
I believe NullReferenceException would occur only if we call a method but we call a property.

2017-07-14 16:49 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
You're right but the end result does not change.  If the request does not complete successfully, I want to know that.  Testing the content doesn't help me diagnose that and, in fact, obfuscates it.

2017-07-14 17:24 UTC, merged

2017-07-14 17:24 UTC, TravisEz13 commented
Thanks everyone

2017-07-14 17:25 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
> +        $response.Error | Should BeNullOrEmpty
Thanks for clarify!