Added code coverage analysis to identify missing coverage
PowerShell/PowerShell pull request #4097
Opened 2017-06-23 17:32 UTC by adityapatwardhan

The hot spots are identified on two metrics: likelihood of usage and number or missing lines. Adding coverage for these gaps should increase the code coverage significantly.

2017-06-23 22:55 UTC, SteveL-MSFT requested changes

2017-06-23 22:55 UTC, SteveL-MSFT commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +Code coverage runs are enabled on daily Windows builds for PowerShell 6.0. The results of the latest build are available at: [CodeCov.io](https://codecov.io/gh/PowerShell/PowerShell)
PowerShell Core 6.0

2017-06-23 22:55 UTC, SteveL-MSFT commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +Code coverage runs are enabled on daily Windows builds for PowerShell 6.0. The results of the latest build are available at: [CodeCov.io](https://codecov.io/gh/PowerShell/PowerShell)
Also use semantic line breaks (each sentence on own line, makes it easier to see diffs)

2017-06-23 22:55 UTC, SteveL-MSFT commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- We need tests from PSReadline repo or ignore coverage data for this module.
We should probably ignore for now

2017-06-23 22:55 UTC, SteveL-MSFT commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- CDXML cmdlet coverage. It is 0% as CDXML is broken due to CoreCLR [issue](https://github.com/dotnet/corefx/issues/18877).
We should make these checkboxes instead of bullet points

2017-06-23 22:55 UTC, SteveL-MSFT commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- Remove Snapin code from CommandDiscovery
This should just be an issue with `Code Cleanup` label

2017-06-27 18:03 UTC, adityapatwardhan commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- We need tests from PSReadline repo or ignore coverage data for this module.
In a separate PR I will filter out Microsoft.Powershell.PSReadline*

2017-06-27 18:11 UTC, adityapatwardhan commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- Remove Snapin code from CommandDiscovery
Opened issue #4118

2017-06-27 18:11 UTC, adityapatwardhan commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- CDXML cmdlet coverage. It is 0% as CDXML is broken due to CoreCLR [issue](https://github.com/dotnet/corefx/issues/18877).
Fixed

2017-06-27 18:11 UTC, adityapatwardhan commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +Code coverage runs are enabled on daily Windows builds for PowerShell 6.0. The results of the latest build are available at: [CodeCov.io](https://codecov.io/gh/PowerShell/PowerShell)
Fixed.

2017-06-27 18:14 UTC, adityapatwardhan commented
@SteveL-MSFT  @JamesWTruher  Please have look. I have addressed feedback.

2017-06-27 18:43 UTC, SteveL-MSFT approved these changes
LGTM

2017-06-28 09:03 UTC, iSazonov commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- [ ] Lots of non-windows code can be ifdef'ed out.
Should we add tracking Issue #3565?

2017-06-28 09:03 UTC, iSazonov commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- [ ] Remove Snapin code from CommandDiscovery
Should we add tracking Issue #4118?

2017-06-28 17:01 UTC, SteveL-MSFT commented on docs/testing-guidelines/CodeCoverageAnalysis.md
> +- [ ] Lots of non-windows code can be ifdef'ed out.
We should add link to existing issues if they exist.  Good catch!

2017-06-28 17:08 UTC, adityapatwardhan commented
@iSazonov  Good catch. Issue links added.

2017-07-03 19:11 UTC, adityapatwardhan commented
@SteveL-MSFT I have pushed another commit for adding links to filed issues.
@TravisEz13 This is ready to merge.

2017-07-06 22:45 UTC, adityapatwardhan commented
@TravisEz13  Can we merge this?

2017-07-07 16:48 UTC, merged