add CODE_OF_CONDUCT.md
PowerShell/PowerShell pull request #4109
Opened 2017-06-26 21:27 UTC by SteveL-MSFT

https://github.com/PowerShell/PowerShell/community complains we don't have a code-of-conduct, it appears to be specifically looking for existence of this file

2017-06-26 22:14 UTC, vors approved these changes

2017-06-27 22:10 UTC, mirichmo requested changes

2017-06-27 22:10 UTC, mirichmo commented on CODE_OF_CONDUCT.md
> +# Code of Conduct
I'm not sure that this fully satisfies the requirements. From the link you provided, it states that you should, "Place a CODE_OF_CONDUCT file in your project’s root directory, and link to it from your README, so it’s visible to your community."

You created the file, but readme.md doesn't link to the file.

2017-06-27 23:26 UTC, SteveL-MSFT commented on CODE_OF_CONDUCT.md
> +# Code of Conduct
I'll add a link

2017-06-27 23:37 UTC, mirichmo approved these changes

2017-06-28 17:34 UTC, merged