Added comma to replaced characters in assemblyname
PowerShell/PowerShell pull request #4136
Opened 2017-06-28 19:58 UTC by TimCurwick

A script with a native class will not run if it is saved with a name or full path with a comma.

I added the comma to the list of characters that are replaced with a similar character when creating an assemblyName based on a file path. Added pester test to test.

Discussed with Jason Shirk.

2017-06-28 19:58 UTC, msftclas commented
@TimCurwick,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-06-28 22:06 UTC, adityapatwardhan requested changes

2017-06-28 22:06 UTC, adityapatwardhan commented on test/powershell/Language/Classes/Scripting.Classes.RunPath.Tests.ps1
> +    It "Script with a class definition can run from a path with a comma" {
Same comments as above test

2017-06-28 22:06 UTC, adityapatwardhan commented on test/powershell/Language/Classes/Scripting.Classes.RunPath.Tests.ps1
> +    It "Script with a class definition can run from a path with a comma" {
These two test cases can be combined into 1 using the -TestCases parameter for It. Example: https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1#L147

2017-06-28 22:06 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/parser/PSType.cs
>              // First character is a special mark that allows us to cheaply ignore dynamic generated assemblies in ClrFacede.GetAssemblies()
Typo in comment for ClrFacade.

2017-06-28 22:12 UTC, lzybkr requested changes

2017-06-28 22:12 UTC, lzybkr commented on test/powershell/Language/Classes/Scripting.Classes.RunPath.Tests.ps1
> +            'class MyClass { [string]$MyProperty }; $True' | Out-File -FilePath $FilePath
Use `testdrive:` or `$testdrive` - then Pester will ensure the file is deleted when the test completes.

2017-06-28 22:12 UTC, lzybkr commented on test/powershell/Language/Classes/Scripting.Classes.RunPath.Tests.ps1
> +        $Success | Should Be $True
Avoid `Should Be $True` - this results in a typically unhelpful message in the log.

I suggest a test that actually uses the class, so maybe something like:

Instead, try something like:

```powershell
`@
class MyClass { static [string]$MyProperty = $PSScriptRoot }
[MyClass]::MyProperty
'@ > $testDrive/My,Test.ps1

& $testDrive/My,Test.ps1 | Should Match ".*My,Test.ps1"
```

Or something like that.

2017-06-28 23:28 UTC, TimCurwick commented on test/powershell/Language/Classes/Scripting.Classes.RunPath.Tests.ps1
> +        $Success | Should Be $True
$PSScriptRoot doesn't work inside a class.

2017-06-28 23:31 UTC, adityapatwardhan requested changes

2017-06-28 23:31 UTC, adityapatwardhan commented on test/powershell/Language/Classes/Scripting.Classes.RunPath.Tests.ps1
> +Describe "Script with a class definition run path" {
Missing -Tags 'CI'

2017-06-28 23:57 UTC, lzybkr commented on test/powershell/Language/Classes/Scripting.Classes.RunPath.Tests.ps1
> +        { . $FilePath } | Should Not Throw
This test is not necessary - the next test covers this case.

2017-07-05 23:05 UTC, daxian-dbw commented
@adityapatwardhan and @lzybkr could you please take another look? I think the author has addressed all your comments.

2017-07-05 23:44 UTC, adityapatwardhan approved these changes

2017-07-06 18:31 UTC, daxian-dbw approved these changes

2017-07-06 18:32 UTC, merged

2017-07-06 18:33 UTC, daxian-dbw commented
@TimCurwick Thanks for your contribution! 👍