Move powershell to `2.0.0-preview3-25426-01` using the .NET CLI `2.0.0-preview2-006502`
PowerShell/PowerShell pull request #4144
Opened 2017-06-30 00:48 UTC by daxian-dbw

Fix #3649

Summary
----------
Move PowerShell to .NET Core `2.0.0-preview3-25426-01` by explicitly specify the `RuntimeFrameworkVersion` in .csproj files. `2.0.0-preview3` CLI doesn't work (see https://github.com/dotnet/cli/issues/7013, it's closed but I don't think it should be), so we use .NET CLI `2.0.0-preview2-006502` for now.

Also add `test/Test.Common.props` to hold common properties for test projects.

Note
-----
I have verified the CoreFx issues listed in #3649 are fixed in this .NET Core version.
I have verified that `PackageManagement` and `PowerShellGet` tests are all passed.
I have verified that `Login-AzureRmAccount` from `AzureRM.Netcore` works in powershell with this .NET Core version.

2017-06-30 16:45 UTC, adityapatwardhan requested changes

2017-06-30 16:45 UTC, adityapatwardhan commented on build.psm1
> +$dotnetCLIRequiredVersion = "2.0.0-preview2-006502"
preview3?

2017-06-30 16:45 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
> +    <PackageReference Include="System.Data.SqlClient" Version="4.4.0-preview3-25423-02" />
Is 02 expected? or should it be 01?

2017-06-30 16:45 UTC, adityapatwardhan commented on src/System.Management.Automation/System.Management.Automation.csproj
> +    <PackageReference Include="Microsoft.Win32.Registry.AccessControl" Version="4.4.0-preview3-25423-02" />
Same here 02 or 01?

2017-06-30 16:45 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
> +        # Test is pending on Unix platforms because of a behavior change in the latest .NET Core.
The issue #20456 is closed, do we still need to have the test case pending?

2017-06-30 16:45 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
> +        # See https://github.com/dotnet/corefx/issues/20456 for more information.
Same as above.

2017-06-30 16:52 UTC, daxian-dbw commented on build.psm1
> +$dotnetCLIRequiredVersion = "2.0.0-preview2-006502"
preview3 .NET CLI is still broken, please see the description of this PR.
Now we are using .NET CLI preivew2 to build, but target preview3 .NET Core Framework.

2017-06-30 16:55 UTC, daxian-dbw commented on src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
> +    <PackageReference Include="System.Data.SqlClient" Version="4.4.0-preview3-25423-02" />
Yes, it is expected. `Microsoft.NetCore.App 2.0.0-preview3-25426-01` references to packages of the build `25423-02` (built in 6/23). However, for `ServiceModel` related packages, they only have `25423-01` built on that day, so `25423-01` is used for `ServiceModel` related packages.

2017-06-30 16:56 UTC, daxian-dbw commented on src/System.Management.Automation/System.Management.Automation.csproj
> +    <PackageReference Include="Microsoft.Win32.Registry.AccessControl" Version="4.4.0-preview3-25423-02" />
02 is expected. Please see my response above.

2017-06-30 17:15 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
> +        # Test is pending on Unix platforms because of a behavior change in the latest .NET Core.
The behavior change was by design, to better align with Full .NET. So yes, this test and the corresponding fix need to be revisited. Here is the tracking issue: #4145

2017-06-30 17:15 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
> +        # See https://github.com/dotnet/corefx/issues/20456 for more information.
Ditto.

2017-06-30 17:26 UTC, daxian-dbw commented
@adityapatwardhan Your comments are addressed, please take another look when you have time. Thanks!

2017-06-30 19:07 UTC, adityapatwardhan approved these changes

2017-06-30 20:07 UTC, merged

2017-07-04 16:05 UTC, chuanjiao10 commented
Powershell 6.0 beta4 release notes, will it be added?

Because .net preview 2
Powershell support: (or experimental support)
• SUSE Linux Enterprise Server 12 SP2
• Debian 9
• Fedora 25 and 26 (beta)

I am looking forward

2017-07-05 16:46 UTC, daxian-dbw commented
@chuanjiao10 new distro supports are tracked by #3961

2017-07-06 06:20 UTC, chuanjiao10 commented
daxian-dbw: ok 3q