added test coverage for -notcontains, -is, -isnot operators
PowerShell/PowerShell pull request #4179
Opened 2017-07-03 22:18 UTC by SteveL-MSFT

-like and -contains already has coverage

Fix https://github.com/PowerShell/PowerShell/issues/4162

2017-07-06 22:43 UTC, adityapatwardhan requested changes

2017-07-06 22:43 UTC, adityapatwardhan commented on test/powershell/Language/Operators/ComparisonOperator.Tests.ps1
> +        @{result = $true; operator = "-contains"; rhs = "'Hello'"},
Test for case sensitive variants? ccontains and cnotcontains? There are some tests below. Can we move them to this It and add it as part of -TestCases array.

2017-07-07 16:14 UTC, SteveL-MSFT commented on test/powershell/Language/Operators/ComparisonOperator.Tests.ps1
> +        @{result = $true; operator = "-contains"; rhs = "'Hello'"},
I'll do some general cleanup of the tests

2017-07-08 00:41 UTC, SteveL-MSFT commented
@adityapatwardhan addressed

2017-07-08 18:38 UTC, adityapatwardhan approved these changes
LGTM

2017-07-11 19:27 UTC, merged