Remove UTC and SQM telemetry code
PowerShell/PowerShell pull request #4190
Opened 2017-07-05 22:45 UTC by JamesWTruher

Implementation of #3807 

The historical telemetry code uses WindowsUTC which is not applicable to non-Windows platforms and is superseded by our ApplicationInsight telemetry. `#if LEGACYTELEMETRY` was used to make it easier to track when we add our next round of telemetry.

Change should not be visible to the user, unless they were inspecting the eventlog looking for it. Any SQM telemetry appears to have been disabled in June 2016.

2017-07-07 17:05 UTC, SteveL-MSFT requested changes

2017-07-07 17:05 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
>          IHostProvidesTelemetryData
Can you rearrange the order to avoid the `#else`?

2017-07-13 17:51 UTC, SteveL-MSFT requested changes

2017-07-13 17:51 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
> +        IHostSupportsInteractiveSession
I think this should be:
```c#
#if LEGACYTELEMETRY
  IHostProvidesTelemetryData,
#endif
  IHostSupportsInteractiveSession
```

2017-07-13 21:38 UTC, SteveL-MSFT approved these changes
LGTM

2017-07-14 16:48 UTC, daxian-dbw commented
The old telemetry implementation are still kept in code base (PSTelemetryMethods.cs, PSTelemetryWrapper.cs). Shall we delete them in this PR?

2017-07-14 18:04 UTC, SteveL-MSFT commented
@daxian-dbw current thinking is to keep it for now.  We'll likely add more telemetry in 6.1.0 and we can see what we can reuse from the old telemetry and clean up the code completely at that time.

2017-07-17 16:44 UTC, merged