Checkbox to open PowerShell after the (Windows) installation
PowerShell/PowerShell pull request #4203
Opened 2017-07-09 13:54 UTC by bergmeister

…shed. Default value is unchecked.

The official WiX guide was followed: http://wixtoolset.org/documentation/manual/v3/howtos/ui_and_localization/run_program_after_install.html

2017-07-09 13:54 UTC, msftclas commented
@bergmeister,
Thanks for having already signed the Contribution License Agreement. Your agreement has not been validated yet. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-07-14 21:38 UTC, SteveL-MSFT requested changes

2017-07-14 21:38 UTC, SteveL-MSFT commented on assets/Product.wxs
> +	<Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" Value="Open PowerShell" />
Replace `PowerShell` with `$(env.ProductName)`

2017-07-14 22:08 UTC, bergmeister commented on assets/Product.wxs
> +	<Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" Value="Open PowerShell" />
Good idea. Done and manually tested on the MSI artifact of CI to verify the CheckBox text is still 'Open PowerShell' after using a variable for it.

2017-07-14 22:53 UTC, SteveL-MSFT approved these changes
Thanks for the contribution!  LGTM

2017-07-15 01:10 UTC, merged