Add test to validate 'Assembly.LoadFrom' behavior
PowerShell/PowerShell pull request #4285
Opened 2017-07-18 18:54 UTC by daxian-dbw

Add validation test for #4192

2017-07-18 22:02 UTC, SteveL-MSFT requested changes

2017-07-18 22:02 UTC, SteveL-MSFT commented on test/powershell/engine/Basic/Assembly.LoadFrom.ps1
> +        $TempPath = [System.IO.Path]::GetTempFileName()
Why not just use $testdrive?

2017-07-18 22:14 UTC, daxian-dbw commented on test/powershell/engine/Basic/Assembly.LoadFrom.ps1
> +        $TempPath = [System.IO.Path]::GetTempFileName()
Once the assembly is loaded, the file cannot be removed. If I use `$testdrive`, Pester will try to remove it afterward and result in non-failure errors.

2017-07-18 22:59 UTC, SteveL-MSFT commented on test/powershell/engine/Basic/Assembly.LoadFrom.ps1
> +        $TempPath = [System.IO.Path]::GetTempFileName()
Got it, perhaps add a comment

2017-07-18 23:06 UTC, daxian-dbw commented on test/powershell/engine/Basic/Assembly.LoadFrom.ps1
> +        $TempPath = [System.IO.Path]::GetTempFileName()
A comment is added.

2017-07-18 23:27 UTC, SteveL-MSFT approved these changes
LGTM

2017-07-19 05:10 UTC, merged

2017-07-19 05:41 UTC, iSazonov commented
Should we test loading from different default paths? It seems we had an issue with CoreFX.

2017-07-19 15:13 UTC, daxian-dbw commented
@iSazonov can you please elaborate? And which CoreFx issue?

2017-07-19 15:21 UTC, iSazonov commented
I mean the comment https://github.com/PowerShell/PowerShell/issues/4192#issuecomment-313457476

2017-07-19 15:48 UTC, daxian-dbw commented
This test is to cover the corefx issue described in that comment. `Consumer.dll` and `Provider.dll` are in the same folder and the former implicit references to the latter.