Increase test coverage for Rename-Item and Move-Item
PowerShell/PowerShell pull request #4329
Opened 2017-07-24 18:00 UTC by jeffbi

Addresses parts of #4148.

2017-07-25 18:17 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +            Rename-Item -Path $testFile -NewName $newTestFile
Suggest using -ErrorAction Stop for the operations that you expect to succeed.  It will be clearer than diagnosing why the Should statement failed.

2017-07-25 18:18 UTC, dantraMSFT requested changes
Suggest using -ErrorAction Stop for the operations that you expect to succeed. It will be clearer than diagnosing why the Should statement failed.

2017-07-25 21:04 UTC, jeffbi commented
Fixed.

2017-07-25 22:10 UTC, dantraMSFT approved these changes

2017-07-28 20:46 UTC, adityapatwardhan requested changes
Minor comment.

2017-07-28 20:53 UTC, SteveL-MSFT requested changes

2017-07-28 20:53 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +        It "Verify Move-Item as substitue for Rename-Item" {
Typo: substitute

2017-07-28 20:53 UTC, SteveL-MSFT commented
Add test for `Access Denied`

2017-08-01 04:42 UTC, jeffbi commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +        It "Verity Move-Item will not move to an existing file" {
Fixed.

2017-08-01 04:42 UTC, jeffbi commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +        It "Verify Move-Item as substitue for Rename-Item" {
Fixed

2017-08-01 04:43 UTC, jeffbi commented
Added tests for access-denied. @SteveL-MSFT thanks for the pointer.

2017-08-01 15:44 UTC, SteveL-MSFT approved these changes
LGTM

2017-08-01 16:06 UTC, adityapatwardhan approved these changes

2017-08-02 16:51 UTC, merged