Increase code coverage of Get-ChildItem on file system.
PowerShell/PowerShell pull request #4342
Opened 2017-07-25 17:34 UTC by jeffbi

Addresses part of #4148.

Using the `-Name` parameter on `Get-ChildItem` exercises a part of the file system provider code not previously covered by tests.

2017-07-25 22:16 UTC, dantraMSFT requested changes

2017-07-25 22:16 UTC, dantraMSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +            $fileName | Should BeExactly $fileName
This compares to itself.
I suggest calling Get-ChildItem twice, once with -Name to get the name string and once without to get the fileinfo. The test would look something like the following:
$filename | Should BeExactly $fileInfo.Name

2017-07-25 22:33 UTC, jeffbi commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +            $fileName | Should BeExactly $fileName
Yikes! Bad typo on my part. That should have been `$filename | Should BeExactly $testFile`. Is making that change sufficient, or would you prefer the dual-call method?

2017-07-25 22:42 UTC, dantraMSFT commented
You're better off comparing the returned value against the name property since, I believe, that's the intent.

2017-07-25 22:46 UTC, jeffbi commented
Well, the intent was to check that I got the item I asked for, which is why I was comparing against `$testFile`. But I'll go ahead with your recommendation.

2017-07-26 01:06 UTC, dantraMSFT approved these changes

2017-07-26 01:32 UTC, dantraMSFT commented
Sorry jeffbi; I should have been clearer.  When I said the intent of -Name, I mean the intent is to return the Name property of the FileInfo object.
The current implementation of FileInfo 'does' preserve the file name as it was passed in; however, since it's not documented explicitly, I avoid depending on it.
Additionally, I would expect the test to succeed with other values, such as .\filename.txt, ./filename.txt, and /etc/filename.txt
I hope that clarifies my feedback.

2017-08-01 20:16 UTC, merged