Add test coverage for Registry
PowerShell/PowerShell pull request #4354
Opened 2017-07-26 22:34 UTC by jeffbi

Addresses parts of #4148 

Add coverage for `Get-Item`, `Get-ChildItem`, `Set-Item`, and `Clear-Item`

2017-07-27 21:08 UTC, SteveL-MSFT commented
Missing tests:

- [ ] [invalid hive root](https://codecov.io/gh/PowerShell/PowerShell/src/master/src/System.Management.Automation/namespaces/RegistryProvider.cs#L174)
- [ ] validate `-whatif` works for `set-item` and `clear-item`
- [ ] attempt accessing path you don't have access to

2017-07-28 18:58 UTC, jeffbi commented
@SteveL-MSFT These test run with the tag `RequireAdminOnWindows`. Is there a Registry path that admin would not have access to?

2017-07-28 20:01 UTC, SteveL-MSFT commented
@jeffbi try `HKLM:\sam`

2017-07-28 20:53 UTC, adityapatwardhan requested changes
Minor comment

2017-07-28 20:53 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        It "Verity Clear-Item" {
Typo Verity->Verify

2017-07-28 20:59 UTC, SteveL-MSFT requested changes

2017-07-28 20:59 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
> +        It "Verity Clear-Item with -WhatIf" {
Typo here has well `Verify`

2017-07-28 22:15 UTC, jeffbi commented
Typos fixed.

The Travis failure seems to be in a test for Invoke-Item.

2017-07-28 22:17 UTC, SteveL-MSFT commented
@jeffbi I have a PR to change the invoke-item tests to Feature as they shouldn't be CI anyways

2017-07-28 22:17 UTC, SteveL-MSFT approved these changes
LGTM

2017-07-28 22:40 UTC, adityapatwardhan approved these changes

2017-08-02 16:53 UTC, merged