remove appx packaging
PowerShell/PowerShell pull request #4376
Opened 2017-07-28 20:36 UTC by TravisEz13

2017-07-28 20:56 UTC, SteveL-MSFT requested changes

2017-07-28 20:56 UTC, SteveL-MSFT commented on tools/packaging/packaging.psm1
> +        [ValidateSet("deb", "osxpkg", "rpm", "msi", "appx", "zip", "AppImage", "nupkg")]
shouldn't you remove `appx` here?

2017-07-29 17:35 UTC, TravisEz13 commented on tools/packaging/packaging.psm1
> +        [ValidateSet("deb", "osxpkg", "rpm", "msi", "appx", "zip", "AppImage", "nupkg")]
Fixed

2017-07-30 23:55 UTC, SteveL-MSFT commented on tools/packaging/packaging.psm1
> +        [ValidateSet("deb", "osxpkg", "rpm", "msi", "zip", "AppImage", "nupkg")]
Isn't `nupkg` support part of your other PR?

2017-08-01 16:41 UTC, TravisEz13 commented on tools/packaging/packaging.psm1
> +        [ValidateSet("deb", "osxpkg", "rpm", "msi", "zip", "AppImage", "nupkg")]
fixed but squashed history to avoid conflict with nuget change

2017-08-01 17:21 UTC, adityapatwardhan commented
@TravisEz13 Can you add in the description why we are making this change.

2017-08-01 17:25 UTC, SteveL-MSFT approved these changes
LGTM

2017-08-01 21:49 UTC, TravisEz13 commented
@daxian-dbw  Thanks for resolving confilcts

2017-08-02 00:24 UTC, merged