Tests for New-WinEvent
PowerShell/PowerShell pull request #4384
Opened 2017-07-28 22:24 UTC by anmenaga

Some tests for New-WinEvent that bring code coverage of the class to 80%.

2017-07-28 23:12 UTC, adityapatwardhan requested changes

2017-07-28 23:12 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +        It 'Simple New-WinEvent' -Skip:(-not $IsWindows) {
You may want to use $PSDefaultParameterValues to set the value of skip.

2017-07-28 23:12 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            (Get-WinEvent -filterHashtable $filter).Count -gt 0 | Should be $true
Should be,
```Powershell
(Get-WinEvent -filterHashtable $filter).Count | Should BeGreaterThan 0
```

2017-07-31 03:17 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            { New-WinEvent -ProviderName NonExistingProvider -Id 0 } | ShouldBeErrorID 'System.ArgumentException,Microsoft.PowerShell.Commands.NewWinEventCommand'
Typo. Please change "ShouldBeErrorID" -> "ShouldBeErrorId".

2017-07-31 03:17 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            New-WinEvent -ProviderName Microsoft-Windows-PowerShell -Id 32868 *> $logPath # this will print the warning with expected event template to the file
Please move the comment on separate line.

2017-07-31 23:24 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +        It 'Simple New-WinEvent' -Skip:(-not $IsWindows) {
Yup, I saw that approach; but don't really like it; I think having skip conditions explicitly on each test makes it easier to investigate test failures.

2017-07-31 23:25 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            (Get-WinEvent -filterHashtable $filter).Count -gt 0 | Should be $true
Updated.

2017-07-31 23:25 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            { New-WinEvent -ProviderName NonExistingProvider -Id 0 } | ShouldBeErrorID 'System.ArgumentException,Microsoft.PowerShell.Commands.NewWinEventCommand'
Updated.

2017-07-31 23:25 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            New-WinEvent -ProviderName Microsoft-Windows-PowerShell -Id 32868 *> $logPath # this will print the warning with expected event template to the file
Moved.

2017-07-31 23:28 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +        It 'Simple New-WinEvent' -Skip:(-not $IsWindows) {
The recommendation according to the testing guidelines is to use PSDefaultParameterValues. Please see: https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md

2017-07-31 23:37 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +        It 'Simple New-WinEvent' -Skip:(-not $IsWindows) {
Updated.

2017-08-01 00:07 UTC, adityapatwardhan requested changes

2017-08-01 00:07 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            New-WinEvent -ProviderName Microsoft-Windows-PowerShell -Id 40962 -Version 1 # simple event without any payload
Move the comment to a separate line.

2017-08-01 00:16 UTC, SteveL-MSFT requested changes
Which issue does this address if any?

2017-08-01 00:16 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            New-WinEvent -ProviderName Microsoft-Windows-PowerShell -Id 40962 -Version 1 # simple event without any payload
use something like

```powershell
$PSProviderId = 40962
```

2017-08-01 19:17 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            New-WinEvent -ProviderName Microsoft-Windows-PowerShell -Id 40962 -Version 1 # simple event without any payload
Updated.

2017-08-01 19:18 UTC, anmenaga commented
This goes toward #4156

2017-08-01 19:27 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            New-WinEvent -ProviderName Microsoft-Windows-PowerShell -Id 40962 -Version 1 # simple event without any payload
updated.

2017-08-01 20:19 UTC, adityapatwardhan approved these changes

2017-08-02 00:40 UTC, SteveL-MSFT commented
Based on the code coverage, you're missing some tests:
https://codecov.io/gh/PowerShell/PowerShell/src/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventDescriptor.cs
- [ ] EventDescriptor constructor validation like: [System.Diagnostics.Eventing.EventDescriptor]::new(-1, 0, 0, 0, 0, -1, 0)
- [ ] Reading back members of EventDescriptor
https://codecov.io/gh/PowerShell/PowerShell/src/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProvider.cs
- [ ] Dispose(), Close(), destructor
- [ ] IsEnabled()
- [ ] different data types
- [ ] WriteMessagEvent()
- [ ] WriteEvent
- [ ] WriteTransferEvent
https://codecov.io/gh/PowerShell/PowerShell/src/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProviderTraceListener.cs
- [ ] EventProviderTraceListener

The Reader code should probably be a different PR

2017-08-02 18:54 UTC, anmenaga commented
@SteveL-MSFT All of the things that you've mentioned is ETW code and will go into separate PR.
This PR is specific to New-WinEvent cmdlet code.

2017-08-02 19:50 UTC, SteveL-MSFT approved these changes

2017-08-03 22:28 UTC, adityapatwardhan commented
@iSazonov  Can you have a look again?

2017-08-04 03:49 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            # simple event without any payload
I believe we can remove the comment. And maybe move to the test name.

2017-08-04 03:51 UTC, iSazonov commented
With one minor comment LGTM.

2017-08-04 17:31 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            # simple event without any payload
@anmenaga can you address this?

2017-08-04 19:00 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Diagnostics/New-WinEvent.Tests.ps1
> +            # simple event without any payload
Updated.

2017-08-04 19:04 UTC, adityapatwardhan approved these changes

2017-08-07 21:24 UTC, merged