Improve code coverage for Get-Item cmdlet
PowerShell/PowerShell pull request #4385
Opened 2017-07-28 22:31 UTC by JamesWTruher

Add tests for Get-Item to improve code coverage of the cmdlet. Additional tests for:
- literalpath parameter
- force parameter
- alternate streams
- dynamic parameter -filter
- exclude and include parameters
- Get-Item against registry drive
- Error conditions bad provider and bad drive

2017-07-28 23:03 UTC, adityapatwardhan approved these changes
Minor comment about other providers

2017-07-28 23:03 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        }
function, alias and environment provider also have similar gaps. Either add tests is this PR or a new one.

2017-07-29 00:15 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +            $skip = $false
Instead of calling it `$skip`, I think it would be better to call it `$skipNotWindows`

2017-07-29 00:18 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        It "Should respect -Include" {
Do we need to test using both `-Include` and `-Exclude`?

2017-07-29 00:19 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        It "Should return an error if the drive does not exist" {
Access Denied test?

2017-07-29 00:20 UTC, SteveL-MSFT requested changes

2017-07-29 00:20 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +
Extra empty line

2017-08-02 23:49 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +            $skip = $false
fixed

2017-08-02 23:52 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +
removed

2017-08-02 23:58 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        It "Should return an error if the drive does not exist" {
getting this working cross-platform is not obvious, so I left this one out

2017-08-03 00:26 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        }
those won't improve coverage in the cmdlet, but the underlying provider. Those tests need to be added, to be sure, but could be more associated with the provider

2017-08-03 00:26 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        It "Should respect -Include" {
sure

2017-08-03 01:43 UTC, SteveL-MSFT requested changes

2017-08-03 01:43 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        It "Should return an error if the drive does not exist" {
I think you can just use existing cmdline tools on each platform to create a file in testdrive and modify the permissions to deny access

2017-08-03 01:43 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        It "Should return an error if the drive does not exist" {
Alternatively, just do it for Windows for now

2017-08-08 00:44 UTC, adityapatwardhan commented
@JamesWTruher Can you answer feedback from @SteveL-MSFT

2017-08-08 17:28 UTC, JamesWTruher commented on test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
> +        It "Should return an error if the drive does not exist" {
i would rather get this in as is and add it later - it adds a very small additional percentage to coverage

2017-08-09 19:46 UTC, adityapatwardhan commented
@JamesWTruher can you updated the issue with the remaining tasks? Then I can go ahead an merge this change.

2017-08-09 21:14 UTC, adityapatwardhan commented
Merging this PR as the issue #4148 already has a pending item for AccessDenied.

2017-08-09 21:15 UTC, merged