Clean up '#if CORE' in PropertyAccessor.cs
PowerShell/PowerShell pull request #4429
Opened 2017-07-31 15:01 UTC by iSazonov

Related #3565 and #4357.

2017-07-31 18:12 UTC, daxian-dbw commented on src/System.Management.Automation/engine/PropertyAccessor.cs
>      internal class RegistryAccessor : ConfigPropertyAccessor
Maybe the `RegistryAccessor` should be removed now to increase the code coverage of this file. @mirichmo what do you think?

2017-07-31 21:56 UTC, mirichmo requested changes

2017-07-31 21:56 UTC, mirichmo commented on src/System.Management.Automation/engine/PropertyAccessor.cs
>              Instance = Platform.IsInbox
This can be simplified to:
Instance = new JsonConfigFileAccessor(); 

Platform.IsInbox() should be removed from the code as well

2017-07-31 21:56 UTC, mirichmo commented on src/System.Management.Automation/engine/PropertyAccessor.cs
>      internal class RegistryAccessor : ConfigPropertyAccessor
It is safe to remove since RegistryAccessor is only used for Windows PowerShell

2017-08-01 04:13 UTC, iSazonov commented on src/System.Management.Automation/engine/PropertyAccessor.cs
>              Instance = Platform.IsInbox
"Instance = " is fixed.

For `Platform.IsInbox()` I'll open new PR (We have still 4 reference on it).

2017-08-03 15:33 UTC, mirichmo approved these changes

2017-08-03 15:34 UTC, merged