Clean up '#if CORE' in PSPrincipal.cs
PowerShell/PowerShell pull request #4433
Opened 2017-07-31 15:35 UTC by iSazonov

Related #3565 and #4357.

~~The build is failed with "'TimeZone' is obsolete: 'System.TimeZone has been deprecated."~~

~~It seems 'TimeZone' is necessary for backward compatibility with Windows PowerShell. How can we resolve this? Remove?~~

Some files depends on depredicated TimeZone type - migrate them to use TimeZoneInfo.

2017-08-03 20:04 UTC, PaulHigin requested changes

2017-08-03 20:04 UTC, PaulHigin commented on src/System.Management.Automation/engine/remoting/fanin/PSPrincipal.cs
> +        private TimeZoneInfo clientTimeZone;
Minor issue.  We are trying to move away from explicit field members for properties and instead to this:
```powershell
public TimeZoneInfo ClientTimeZone
{
    get;
    internal set;
}
```
Can you please remove the private clientTimeZone field?

2017-08-04 04:12 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/fanin/PSPrincipal.cs
> +        private TimeZoneInfo clientTimeZone;
Fixed.

2017-08-04 14:27 UTC, PaulHigin approved these changes
LGTM.  Thanks!

2017-08-04 18:36 UTC, adityapatwardhan requested changes

2017-08-04 18:36 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
> +
Please remove extra line.

2017-08-06 18:24 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
> +
Fixed.

2017-08-07 16:36 UTC, adityapatwardhan approved these changes

2017-08-07 21:27 UTC, merged