added tests for primitive types, dictionary type, and enumerable type for convertto-xml
PowerShell/PowerShell pull request #4503
Opened 2017-08-04 22:23 UTC by SteveL-MSFT

Based on https://codecov.io/gh/PowerShell/PowerShell/src/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs

Since I'm going to be on vacation, I'm submitting PR now rather than when I finish going through the whole file

2017-08-04 22:54 UTC, anmenaga requested changes

2017-08-04 22:54 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Xml.Tests.ps1
> +    It "Serialize dictionary type" {
If you're using terminology from the source code, then I would call this test
"Serialize ContainerType.Dictionary type"

2017-08-04 22:54 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Xml.Tests.ps1
> +    It "Serialize enumerable type" {
Like above; maybe rename the test to "Serialize ContainerType.Enumerable type"

2017-08-04 22:54 UTC, anmenaga commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Xml.Tests.ps1
> +        $x.Objects.Object[0].Type = "fruit"
For this line and below:
Are these assignments ("=") meant to be verifications ( | Should ) ?

2017-08-06 03:29 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Xml.Tests.ps1
> +    It "Serialize dictionary type" {
ok

2017-08-06 03:29 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Xml.Tests.ps1
> +    It "Serialize enumerable type" {
ok

2017-08-06 03:29 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Xml.Tests.ps1
> +        $x.Objects.Object[0].Type = "fruit"
yeah, that's a mistake

2017-08-07 18:04 UTC, adityapatwardhan approved these changes

2017-08-07 18:06 UTC, adityapatwardhan requested changes
Please fix CI errors.

2017-08-07 18:06 UTC, adityapatwardhan commented
CI failing with:

Expected string length 5 but was 27. Strings differ at index 0.
Expected: {fruit}
But was:  {<2f125142>.<bbb5d5d6>.fruit}
-----------^

2017-08-14 22:03 UTC, SteveL-MSFT commented
@anmenaga @adityapatwardhan feedback addressed

2017-08-14 22:05 UTC, adityapatwardhan approved these changes

2017-08-15 16:41 UTC, adityapatwardhan commented
@anmenaga Can you have a look?

2017-08-15 20:17 UTC, anmenaga approved these changes

2017-08-16 19:13 UTC, merged