Only push to NuGet for Full Build (cron)
PowerShell/PowerShell pull request #4517
Opened 2017-08-07 17:59 UTC by TravisEz13

Currently, every merge is also publishing.

2017-08-08 16:40 UTC, adityapatwardhan requested changes
I found another issue, we seem to be updating the badge on full build, including the one with [Feature]. We need a way to identify a CRON build and then do nuget publish and badge update.

2017-08-08 16:40 UTC, adityapatwardhan commented on tools/travis.ps1
> +            # 1 - It's a fullBuild (allready checked, for not a PR)
Typo in allready -> already

2017-08-08 16:54 UTC, adityapatwardhan requested changes

2017-08-08 16:54 UTC, adityapatwardhan commented on tools/travis.ps1
> +            if($isFullBuild -and $env:NUGET_KEY -and $env:NUGET_URL -and [system.io.path]::GetExtension($package) -ieq '.nupkg')
This also published if it is [Feature] run?

2017-08-08 17:23 UTC, TravisEz13 commented on tools/travis.ps1
> +            if($isFullBuild -and $env:NUGET_KEY -and $env:NUGET_URL -and [system.io.path]::GetExtension($package) -ieq '.nupkg')
Only if we merge a feature... that is equivalent to a daily build, I'm fine with it.  If it's a PR, it won't publish.   And if you squash merge, you will likely, remove the `[Feature]` from the commit message.

2017-08-08 17:26 UTC, TravisEz13 commented on tools/travis.ps1
> +            if($isFullBuild -and $env:NUGET_KEY -and $env:NUGET_URL -and [system.io.path]::GetExtension($package) -ieq '.nupkg')
actually, a true merge would change the description of the last commit message too.  Only merging to master using the rebase option would have this possible effect.

2017-08-09 19:12 UTC, TravisEz13 commented
The badge issue is being fixed in #4536

2017-08-09 19:22 UTC, daxian-dbw commented on tools/travis.ps1
> +            if($isFullBuild -and $env:NUGET_KEY -and $env:NUGET_URL -and [system.io.path]::GetExtension($package) -ieq '.nupkg')
After merging a PR to master, if the commit message happen to have `[Feature]` tag, we will publish the nuget package as well. Is that desired? Maybe we should use `$isDailyBuild` instead.

2017-08-09 22:45 UTC, TravisEz13 commented on tools/travis.ps1
> +            if($isFullBuild -and $env:NUGET_KEY -and $env:NUGET_URL -and [system.io.path]::GetExtension($package) -ieq '.nupkg')
Rebased, and updated.

2017-08-09 23:17 UTC, daxian-dbw approved these changes

2017-08-09 23:19 UTC, adityapatwardhan approved these changes
LGTM

2017-08-11 15:50 UTC, merged