Shellexecute
PowerShell/PowerShell pull request #4523
Opened 2017-08-07 23:25 UTC by daxian-dbw

Fix #4499 

This PR includes following major changes:
1. `ProcessStartInfo.UseShellExecute` is now supported in .NET Core on Windows. So we need to remove our implementation of `ShellExecute` and use the .NET Core API directly.
2. Enable `NativeCommandProcessor` to open files using default program associated with the shell.
3. Fix `NativeCommandProcessor` to properly clean up in case an exception is thrown in `Prepare` and `ProcessRecord`.

2017-08-08 00:30 UTC, adityapatwardhan requested changes

2017-08-08 00:30 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
> +            if (Platform.IsWindowsDesktop)
Maybe cache the value in a variable instead of looking it up twice in the same method.

2017-08-08 00:30 UTC, adityapatwardhan commented on src/System.Management.Automation/namespaces/FileSystemProvider.cs
> +                invokeProcess.StartInfo.UseShellExecute = !Platform.IsNanoServer && !Platform.IsIoT;
Can we use Platform.IsWindowsDesktop here?

2017-08-08 00:30 UTC, adityapatwardhan commented on test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
> +        elseif ($IsWindows) {
We can use Platform.IsWindowsDesktop if it is made public.

2017-08-08 00:30 UTC, adityapatwardhan commented on test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
> +            $_.FullyQualifiedErrorId | should be "NativeCommandFailed"
Use ShouldBeErroId. Example : https://github.com/PowerShell/PowerShell/blob/0cd7a4a0c930340eceb7585f1042be889ce1e744/test/powershell/engine/Attributes.Tests.ps1#L22

2017-08-08 00:30 UTC, adityapatwardhan commented on src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
> +        internal static bool IsWindowsDesktop
Should we consider making this public? This will be very useful in tests.

2017-08-08 00:30 UTC, adityapatwardhan commented on test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
> +            while (((Get-Date) - $startTime).TotalSeconds -lt 10 -and (-not (Test-Path "$HOME/nativeCommandProcessor.Success"))) {
Polling for a file can be a common pattern. Consider implementing a generic file watcher function in HelpersCommon.psm1

2017-08-08 00:54 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
> +            if (Platform.IsWindowsDesktop)
Updated the code to cache the value in `Platform.IsWindowsDesktop`.

2017-08-08 00:54 UTC, daxian-dbw commented on src/System.Management.Automation/namespaces/FileSystemProvider.cs
> +                invokeProcess.StartInfo.UseShellExecute = !Platform.IsNanoServer && !Platform.IsIoT;
Sure. Will update the code.

2017-08-08 00:54 UTC, daxian-dbw commented on test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
> +        elseif ($IsWindows) {
Good point. Will update.

2017-08-08 01:01 UTC, daxian-dbw commented on src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
> +        internal static bool IsWindowsDesktop
Done.

2017-08-08 01:01 UTC, daxian-dbw commented on test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
> +            $_.FullyQualifiedErrorId | should be "NativeCommandFailed"
Fixed.

2017-08-08 01:04 UTC, daxian-dbw commented on test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
> +            while (((Get-Date) - $startTime).TotalSeconds -lt 10 -and (-not (Test-Path "$HOME/nativeCommandProcessor.Success"))) {
Sounds reasonable. Opened #4524. Will address in a separate PR.

2017-08-08 06:59 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                $notepadProcess.Name | Should Be notepad
Maybe use quotas - "notepad"?

2017-08-08 06:59 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                Stop-Process -InputObject $notepadProcess
Should we move this in `AfterAll`?

2017-08-08 15:21 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                $notepadProcess.Name | Should Be notepad
OK, will update.

2017-08-08 15:22 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                Stop-Process -InputObject $notepadProcess
I think it should stay here, as it's specific to this test when running on full desktop.

2017-08-08 15:31 UTC, daxian-dbw commented
There are 2 failures in AppVeyor feature test run and both are related to `Invoke-RestMethod`, not related to the changes made in this PR. So the feature test run is good.

2017-08-08 15:42 UTC, daxian-dbw commented
@adityapatwardhan @iSazonov Your comments have been addressed. Please take another look. Thanks!

2017-08-08 16:33 UTC, adityapatwardhan requested changes

2017-08-08 16:33 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
> +            if (Platform.IsWindowsDesktop)
@daxian-dbw This does not seem to be fixed.

2017-08-08 16:38 UTC, daxian-dbw commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
> +            if (Platform.IsWindowsDesktop)
The value is cached in a static field in `Platform.IsWindowsDesktop` property.

2017-08-08 16:41 UTC, adityapatwardhan approved these changes
LGTM

2017-08-09 04:12 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                Stop-Process -InputObject $notepadProcess
I don't like commands after `Should` 😄

2017-08-09 04:49 UTC, iSazonov reviewed
Since the PR is a cleanup we could add fix - we use "UseShellExecute" constant three times in Process.cs and could move it to private static variable.

2017-08-09 04:49 UTC, iSazonov commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +                // Do the cleanup and rethrow the exception
It is obvious comment. Please add in the comment why we do this.

2017-08-09 04:49 UTC, iSazonov commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +                // Do the cleanup...
Again obvious comment.  Please remove or enhance.

2017-08-09 04:49 UTC, iSazonov commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +            if (!Platform.IsWindowsDesktop) { return false; }
Formatting - Can we use the one line pattern for `if`?

2017-08-09 04:49 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                $notepadProcess.Name | Should Be "notepad"
We use "notepad" in three lines (66, 68, 69 and maybe 65) so maybe use a variable?

2017-08-09 16:15 UTC, daxian-dbw commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +            if (!Platform.IsWindowsDesktop) { return false; }
Yes, as long as the if block is a single simple statement like this one.

2017-08-09 16:25 UTC, daxian-dbw commented
The "Default" constant string is used in 9 places and should be cleaned too (change to const variable, instead of static). But I think they should be in separate PRs as they will introduce too many diffs and make it hard to see the focus of this PR.

2017-08-09 16:25 UTC, daxian-dbw commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +                // Do the cleanup and rethrow the exception
Fixed.

2017-08-09 16:33 UTC, daxian-dbw commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +                // Do the cleanup...
Fixed.

2017-08-09 16:38 UTC, daxian-dbw commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                $notepadProcess.Name | Should Be "notepad"
Fixed.

2017-08-09 16:45 UTC, adityapatwardhan approved these changes
LGTM

2017-08-10 03:08 UTC, iSazonov commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +                // Do the cleanup and rethrow the exception
Closed.

2017-08-10 03:08 UTC, iSazonov commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +                // Do the cleanup...
Closed.

2017-08-10 03:08 UTC, iSazonov commented on src/System.Management.Automation/engine/NativeCommandProcessor.cs
> +            if (!Platform.IsWindowsDesktop) { return false; }
Closed.

2017-08-10 03:09 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
> +                $notepadProcess.Name | Should Be "notepad"
Closed.

2017-08-10 03:10 UTC, iSazonov commented
LGTM.

2017-08-10 18:52 UTC, daxian-dbw commented
@iSazonov @adityapatwardhan Thanks for the review! Aditya, can you please merge this PR? My follow-up work on the file watcher test helper needs to update the tests in this PR (#4524).

2017-08-10 20:32 UTC, merged