Add codeowner files
PowerShell/PowerShell pull request #4565
Opened 2017-08-12 19:52 UTC by TravisEz13

add codeowner file to automatically assign reviewers and to describe who owns areas.

2017-08-12 20:29 UTC, iSazonov reviewed
Nicks should be fixed in all file.

2017-08-12 20:29 UTC, iSazonov commented on .github/CODEOWNERS
> +# daxian-dbw @vors @lzybkr @BrucePay @steveL-MSFT
daxian-dbw -> `@daxian-dbw`

2017-08-12 20:29 UTC, iSazonov commented on .github/CODEOWNERS
> +# @lzybkr @steveL-MSFT @adityapatwardhan
`@steveL-MSFT` -> `@SteveL-MSFT`

2017-08-12 20:29 UTC, iSazonov commented on .github/CODEOWNERS
> +# @travisez13 @leeholmes @steveL-MSFT @PaulHigin @chunqingchen
`@travisez13` -> `@TravisEz13`

2017-08-13 14:55 UTC, TravisEz13 commented
I addressed @iSazonov 's feedback

2017-08-14 00:42 UTC, SteveL-MSFT commented on .github/CODEOWNERS
> +# @TravisEz13 @leeholmes @SteveL-MSFT @PaulHigin @chunqingchen
You should remove Lee and Chunqing

2017-08-14 00:44 UTC, SteveL-MSFT requested changes
You should remove my name from everywhere except demos.

2017-08-14 15:08 UTC, TravisEz13 commented
@SteveL-MSFT  Updated

2017-08-14 16:57 UTC, adityapatwardhan requested changes

2017-08-14 16:57 UTC, adityapatwardhan commented on .github/CODEOWNERS
> +src/System.Management.Automation/help              @@Francisco-Gamino @adityapatwardhan
@@Francisco-Gamino -> @Francisco-Gamino

2017-08-14 16:57 UTC, adityapatwardhan commented on .github/CODEOWNERS
> +src/System.Management.Automation/engine/debugger/  @BrucePay@dantraMSFT @PaulHigin
Space between @BrucePay  and @dantraMSFT

2017-08-14 22:31 UTC, SteveL-MSFT requested changes

2017-08-14 22:31 UTC, SteveL-MSFT commented on .github/CODEOWNERS
> +# @TravisEz13 @leeholmes @PaulHigin @chunqingchen
remove leeholmes, he isn't generally available so Paul, Travis, or I will pull him in when needed.  Remove chunqing

2017-08-14 22:45 UTC, TravisEz13 commented on .github/CODEOWNERS
> +# @TravisEz13 @leeholmes @PaulHigin @chunqingchen
#Resolved

2017-08-14 22:46 UTC, TravisEz13 commented on .github/CODEOWNERS
> +src/System.Management.Automation/help              @@Francisco-Gamino @adityapatwardhan
#Resolved

2017-08-14 22:46 UTC, TravisEz13 commented on .github/CODEOWNERS
> +src/System.Management.Automation/engine/debugger/  @BrucePay@dantraMSFT @PaulHigin
Resolved

2017-08-15 00:23 UTC, dantraMSFT commented on .github/CODEOWNERS
> +src/System.Management.Automation/DscSupport        @TravisEz13
You can add dantraMSFT to DSC as well.

2017-08-15 00:32 UTC, TravisEz13 commented on .github/CODEOWNERS
> +src/System.Management.Automation/DscSupport        @TravisEz13
Added

2017-08-15 00:48 UTC, SteveL-MSFT approved these changes

2017-08-15 04:24 UTC, iSazonov commented
Travis CI temporary failed - I restarted it.

2017-08-15 17:32 UTC, adityapatwardhan approved these changes
LGTM

2017-08-15 18:41 UTC, daxian-dbw approved these changes

2017-08-15 19:04 UTC, merged

2017-08-15 19:35 UTC, daxian-dbw commented
> +test/                                              `@JamesWTruher` `@TravisEz13` `@adityapatwardhan`

Just realized that this cause Jim, Travis and Aditya to be dragged into almost every PR review.
Maybe we shouldn't specify 'test/' in the codeowner file.

2017-08-15 21:04 UTC, TravisEz13 commented
Rules later in the file are supposed to override previous rules.  Let's see how it actually works before we change it.

2017-08-15 21:20 UTC, TravisEz13 commented
But looking at least one PR it looks like it takes the aggregate of what it finds from the rules.  Do you want me to submit a PR removing the area-test rule?