For reliability, start using pester PassThru object to verify tests passed
PowerShell/PowerShell pull request #4644
Opened 2017-08-22 19:06 UTC by TravisEz13

This should fix #4641.
Thanks, @markekraus  for reporting.

2017-08-22 22:31 UTC, anmenaga requested changes

2017-08-22 22:31 UTC, anmenaga commented on build.psm1
> +        [Parameter(ParameterSetName='Unelevate',Mandatory=$true)]
Why was this added?

2017-08-22 22:31 UTC, anmenaga commented on build.psm1
> +                    Import-Clixml -Path $passThruFile | Where-Object {$_.TotalCount}
Looking at the code below, when TotalCount is 0 that means no test were run.
Will this where-object filter work as expected in this case (TotalCount is 0)?

2017-08-22 22:31 UTC, anmenaga commented on build.psm1
> +    if($PSCmdLet.ParameterSetName -eq 'file')
Should this be 'xml' ?

2017-08-22 22:31 UTC, anmenaga commented on build.psm1
> +        throw 'Unknow Show-PSPester parameter set'
Typo 'unknown'.

2017-08-22 22:42 UTC, markekraus commented on build.psm1
> +            if($PassThru.IsPresent)
add a space between `if` and `(`

2017-08-22 22:43 UTC, markekraus commented on build.psm1
> +                try {
move `{` to new line

2017-08-22 22:44 UTC, markekraus commented on build.psm1
> +            if ( "System.Xml.XmlDocumentXPathExtensions" -as [Type] ) {
Move `{` to new line

2017-08-22 22:46 UTC, markekraus commented on build.psm1
> +    if($PSCmdLet.ParameterSetName -eq 'file')
add space between `if` and `(`

2017-08-22 22:46 UTC, markekraus commented on build.psm1
> +    elseif($PSCmdLet.ParameterSetName -eq 'object')
add space between `elseif` and `(`

2017-08-22 22:47 UTC, markekraus commented on build.psm1
> +            else {
move `{` to new line

2017-08-22 22:47 UTC, markekraus commented on build.psm1
> +    elseif($PSCmdLet.ParameterSetName -eq 'PesterPassThruObject')
add space between `elseif` and `(`

2017-08-22 22:48 UTC, markekraus commented on build.psm1
> +        if($ResultObject.TotalCount -le 0)
add space between `if` and `(`

2017-08-22 22:48 UTC, markekraus commented on build.psm1
> +        elseif($ResultObject.FailedCount -gt 0)
add space between `elseif` and `(`

2017-08-22 22:51 UTC, TravisEz13 commented on build.psm1
> +        [Parameter(ParameterSetName='Unelevate',Mandatory=$true)]
Unelevate cannot be used with PassThru.   Just making sure no one tries

2017-08-22 22:58 UTC, TravisEz13 commented on build.psm1
> +                    Import-Clixml -Path $passThruFile | Where-Object {$_.TotalCount}
Resloved

2017-08-22 22:58 UTC, TravisEz13 commented on build.psm1
> +    if($PSCmdLet.ParameterSetName -eq 'file')
Resolved

2017-08-22 22:58 UTC, TravisEz13 commented on build.psm1
> +        throw 'Unknow Show-PSPester parameter set'
resolved

2017-08-22 22:59 UTC, TravisEz13 commented on build.psm1
> +            if($PassThru.IsPresent)
resolved

2017-08-22 22:59 UTC, TravisEz13 commented on build.psm1
> +                try {
reloved

2017-08-22 23:00 UTC, TravisEz13 commented on build.psm1
> +            if ( "System.Xml.XmlDocumentXPathExtensions" -as [Type] ) {
resolved

2017-08-22 23:00 UTC, TravisEz13 commented on build.psm1
> +    if($PSCmdLet.ParameterSetName -eq 'file')
resolved

2017-08-22 23:01 UTC, TravisEz13 commented on build.psm1
> +    elseif($PSCmdLet.ParameterSetName -eq 'object')
resolved

2017-08-22 23:01 UTC, TravisEz13 commented on build.psm1
> +    elseif($PSCmdLet.ParameterSetName -eq 'PesterPassThruObject')
resolved

2017-08-22 23:01 UTC, TravisEz13 commented on build.psm1
> +        if($ResultObject.TotalCount -le 0)
resolved

2017-08-22 23:02 UTC, TravisEz13 commented on build.psm1
> +        elseif($ResultObject.FailedCount -gt 0)
resolved

2017-08-22 23:06 UTC, TravisEz13 commented on build.psm1
> +        [Parameter(ParameterSetName='Unelevate',Mandatory=$true)]
I'll file an issue to move the Unelevated tests to use the same mechanism to verify that the tests passed, which should get rid of this.

2017-08-22 23:10 UTC, TravisEz13 commented on build.psm1
> +        [Parameter(ParameterSetName='Unelevate',Mandatory=$true)]
File #4648

2017-08-23 00:04 UTC, anmenaga approved these changes

2017-08-23 05:34 UTC, daxian-dbw commented on build.psm1
> +                    Start-NativeExecution -sb {& $powershell -noprofile -c $Command} | ForEach-Object { Write-Host $_}
Since all output from `Invoke-Pester` will be captured by `Export-Clixml`, what will be passed to `Foreach-Object`?

2017-08-23 05:34 UTC, daxian-dbw commented on tools/travis.ps1
> +    }
Why does this issue only happen to Travis CI? I assume it doesn't happen in AppVeyor as AppVeyor.psm1 is not chnaged to use the new parameter `-PassThru`.

2017-08-23 08:08 UTC, iSazonov commented
May be useful [comment](https://github.com/PowerShell/PowerShell/pull/2600#issuecomment-261486201)

2017-08-23 16:55 UTC, TravisEz13 commented on build.psm1
> +                    Start-NativeExecution -sb {& $powershell -noprofile -c $Command} | ForEach-Object { Write-Host $_}
Only the PassThru object is captured by Export-Clixml... everything else is done by a write host, but when we run another PowerShell process that gets turned into an output.  Thus, the complexity.

2017-08-23 16:57 UTC, TravisEz13 commented on tools/travis.ps1
> +    }
Due to the use of `-Unelevate`

2017-08-23 16:58 UTC, TravisEz13 commented on tools/travis.ps1
> +    }
@anmenaga  already asked a question, why I marked these two options as mutually exclusive.  I plan on making the code paths more similar after this gets merged.

2017-08-26 15:26 UTC, merged