PowerShell/PowerShell#4843 Credentials on Set-Service
PowerShell/PowerShell pull request #4844
Opened 2017-09-15 07:33 UTC by joandrsn

2017-09-15 07:33 UTC, msftclas commented
@__joandrsn__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-09-15 07:36 UTC, msftclas commented
__@joandrsn__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, Microsoft Pull Request Bot_

2017-09-15 08:45 UTC, iSazonov reviewed
@joandrsn Many thanks for your contribution!

Please add a description in the PR.
Also please add tests (see Set-Service.Tests.ps1).

2017-09-15 08:45 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
> +        internal PSCredential credential = null;
For the new code, it is preferable to use auto property. Especially because `credential` is not used.

2017-09-15 08:45 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
> +                        // modify startup type or display name or credential
Please start comments with capitalized char. We shouldn't add bad patterns.

2017-09-15 08:45 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
> +                            // set up the Credential parameter
Please remove obvious comment.

2017-09-15 10:04 UTC, joandrsn commented
@iSazonov thank you for the feedback. I have updated my pull request. But I still need to create tests for the code I have written.
Unfortunatly I don't know the credentials of the computer that the tests will be running on, so I'm not sure how to write the testcase.
Do you have any documentation on what I can and can't write in the tests?

2017-09-15 10:21 UTC, iSazonov commented
@joandrsn Please see [tests for New-Service](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1#L104)
I think you should (1) create new test service (WMI?) (2) check that you can change its properties. (3) remove the test service.

Also you should add "[Feature]" in header first position of last commit that CI start the _feature_ tests.

2017-09-15 11:58 UTC, joandrsn commented
@iSazonov I have now added the test, but when executing the test with what it is written within the test, you will receive an error `The account name is invalid or does not exist, or the password is invalid for the account name specified` since the users `username` and `username2` does not exist.

I have tested with my own 2 users and it seems to work, but is this okay?

2017-09-15 12:47 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +    It "Set-Service can create a new service called '<name>' and change the credentials" -TestCases @(
"Set-Service can create a new service" - it is incorrect.

2017-09-15 12:51 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +                $service | Remove-CimInstance
Please add "-Force -ErrorAction SilentlyContinue"

2017-09-15 12:56 UTC, iSazonov commented
@joandrsn I think we should try to create a real user account for the test with "Log on as a service" privilege.

2017-09-15 12:59 UTC, joandrsn commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +                $service | Remove-CimInstance
Neither `Get-CimInstance` nor `Remote-CimInstance` has a force parameter. But I can add `-ErrorAction SilentlyContinue`

2017-09-15 13:01 UTC, joandrsn commented
@iSazonov 
I figured out that I could use some built in users from Windows.
Currently I'm using `.\Guest` when creating the service and `.\Administrator` when changing the credentials. Would you rather have it create a user and delete the user again?

2017-09-15 13:46 UTC, iSazonov commented
Guest and Administrator accounts haven't "Log on as a service" privilege and we don't know password. So we should create test users.

2017-09-15 14:22 UTC, joandrsn commented
They don't have the access, but the test passes. I guess that might not be a good way to test (using invalid credentials to validate a test).

Do you have suggestion on how you would add the user? `Add-LocalUser` has been disabled since #4272. I can't find any other test modules in the repository which creates and deletes a user.

2017-09-15 14:25 UTC, SteveL-MSFT commented
@joandrsn thanks for the contribution!  Look at what I've done [here](https://github.com/PowerShell/PowerShell/pull/4756/files#diff-c2f140f155813763bf7a3492a6a03196) to create my own user and removing at end of test

2017-09-15 15:19 UTC, iSazonov commented
For PowerShell team: We haven't tests to really create new service and change its properties. So we should refactor all tests after the PR will be merged. Maybe create tracking Issue?

2017-09-15 16:55 UTC, SteveL-MSFT commented
@iSazonov it seems the test case added by @joandrsn does a `new` and then `set`, were you thinking of something different?

2017-09-15 17:02 UTC, SteveL-MSFT requested changes

2017-09-15 17:02 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +            $service | Should Not BeNullOrEmpty
this check isn't necessary as the next line will fail

2017-09-15 17:02 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +            $service.StartName | Should Be $creds.UserName
BeExactly?

2017-09-15 17:02 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +            $service | Should Not BeNullOrEmpty
This check isn't necessary

2017-09-15 17:02 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +            $service = Get-CimInstance Win32_Service -Filter "name='$name'" -ErrorAction SilentlyContinue
You can simply this to just:

```powershell
Get-CimInstance ... | Remove-CimInstance -ErrorAction SilentlyContinue
```

2017-09-15 17:14 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +            $null = net user $endUsername $testPass /add
Minor comment - we usually use the pattern  `net user $startUsername $testPass /add > $null`

2017-09-15 17:14 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +        @{name = "testsetcredential"; startUsername = "user1"; endUsername = "user2"}
It is single test and we should remove TestCases.

2017-09-15 17:14 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +            $creds = [pscredential]::new(".\$endUsername", $password)
Please add new line to split into logical blocks.

2017-09-15 17:14 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +            $null = net user $endUsername /delete
The same about $null

2017-09-15 17:22 UTC, SteveL-MSFT approved these changes

2017-09-15 17:29 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
> +        param()
Please remove.

2017-09-15 17:39 UTC, iSazonov approved these changes
@joandrsn Many thanks!

I'll merge on next week.

2017-09-16 19:20 UTC, iSazonov commented
>it seems the test case added by @joandrsn does a  new  and then  set , were you thinking of something different?
@SteveL-MSFT I've analyzed these tests more closely.
I don't understand why we need test "SetServiceCommand can be used as API for '<parameter>' with '<value>'". It seems we should do the checks on real service by invoke.
It seems we don't check that New- and Set-Service ignore System and Boot in StartupType.

2017-09-16 19:41 UTC, SteveL-MSFT commented
@iSazonov The "use as API" tests are specifically for covering the getter/setters for the parameters which is only used when called as an API and not when used as cmdlet parameter.  If we're missing some variations, we should add those, but perhaps as a different PR.

2017-09-18 10:23 UTC, merged

2017-09-18 10:23 UTC, iSazonov commented
@joandrsn Many thanks for your contribution!