Add the timezone offset correctly
PowerShell/PowerShell pull request #4867
Opened 2017-09-19 20:40 UTC by JamesWTruher

It must be padded to 3 digits and prepended with either '-' or '+'

2017-09-19 21:19 UTC, adityapatwardhan commented
@JamesWTruher Please add more detail in the description about the issue. It would be hard to summarize the fix for the release notes with the current description.

2017-09-20 00:36 UTC, SteveL-MSFT requested changes

2017-09-20 00:36 UTC, SteveL-MSFT commented on test/powershell/engine/Cdxml/Cdxml.Tests.ps1
> +        if ( $offsetMinutes -ge 0 ) {
You can simply this by simply doing:

```powershell
$offsetFormat = "{0:+000;-000}"
```

2017-09-21 00:29 UTC, adityapatwardhan commented
@JamesWTruher Can you take a look at Steve's suggestion.

2017-09-21 16:54 UTC, JamesWTruher commented on test/powershell/engine/Cdxml/Cdxml.Tests.ps1
> +        if ( $offsetMinutes -ge 0 ) {
nice - fixed

2017-09-21 18:13 UTC, adityapatwardhan commented
@SteveL-MSFT can you have another look.

2017-09-21 19:12 UTC, SteveL-MSFT approved these changes

2017-09-22 18:25 UTC, merged