Add tests for New-Object constrained mode
PowerShell/PowerShell pull request #4929
Opened 2017-09-27 11:47 UTC by chunqingchen

addresses #4154

After reviewing the code coverage file and existed tests, creating object under constrained mode is not covered.

2017-09-27 20:36 UTC, adityapatwardhan requested changes

2017-09-27 20:36 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/New-Object.Tests.ps1
> +    if (-not (Get-Command Invoke-LanguageModeTestingSupportCmdlet -ea Ignore))
Use `-ErrorAction` instead

2017-09-27 20:36 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/New-Object.Tests.ps1
> +    It "New-Object object cannot create COM object under constrained mode" -skip:(-not $IsWindows) {
I think we should add these tests here: https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1#L226

2017-09-28 15:11 UTC, chunqingchen commented
@adityapatwardhan your comment is resolved

2017-09-28 15:46 UTC, adityapatwardhan requested changes

2017-09-28 15:46 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
> +        It "New-Object object cannot create COM object under constrained mode" -skip:(-not $IsWindows) {
Can this be another test case in the same context  https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1#L277

2017-10-06 17:45 UTC, adityapatwardhan commented
@chunqingchen  Please resolve conflict in 'test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1 '

2017-10-18 18:24 UTC, adityapatwardhan commented
@chunqingchen ping..

2017-10-27 09:49 UTC, chunqingchen commented
I think this is duplicated in the constrained tests. I think we can just close this pr without submitting it.

2017-10-30 18:02 UTC, adityapatwardhan commented
@chunqingchen  I think you can close the PR. Maybe put a link to the code where we have coverage.

2017-10-30 18:03 UTC, closed without merging