Add a CR to CommandNotFoundException error string
PowerShell/PowerShell pull request #4934
Opened 2017-09-27 18:37 UTC by jpsnover

We're here at PowerShell Unplugged at Ignite, and this error message could *really* use a carriage return!

2017-09-27 19:19 UTC, SteveL-MSFT requested changes
Thanks for the contribution, but string resources should not contain newlines as it may produce unexpected results when it goes through FormatAndOutput

2017-09-27 19:19 UTC, SteveL-MSFT commented on src/System.Management.Automation/resources/DiscoveryExceptions.resx
> +    <value>The term '{0}' is not recognized as the name of a cmdlet, function, script file, or operable program.
Formatting should be handled by FormatAndOutput.  String messages should not contain newlines.

2017-09-29 18:37 UTC, SteveL-MSFT commented on src/System.Management.Automation/resources/DiscoveryExceptions.resx
> +    <value>The term '{0}' is not recognized as the name of a cmdlet, function, script file, or operable program.
Perhaps adding new newlines is something we should consider for other strings as it can improve readability.

2017-09-29 18:37 UTC, SteveL-MSFT approved these changes

2017-09-29 19:16 UTC, merged

2017-10-02 07:25 UTC, iSazonov commented
Please clarify what was idea here.
Before the change:
```
> qwerty
qwerty : The term 'qwerty' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ qwerty
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (qwerty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
After the change:
```
PS C:\Users\sie\Documents\GitHub\iSazonov\PowerShell> qwerty
qwerty : The term 'qwerty' is not recognized as the name of a cmdlet, function, script file, or operable program.
      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ qwerty
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (qwerty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
Or idea was to change command line error formatting?
From:
```
l> .\debug\powershell.exe -sma
The argument '-sma' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
To:
```
l> .\debug\powershell.exe -sma
The argument '-sma' is not recognized as the name of a script file. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

2017-10-03 06:33 UTC, iSazonov commented
@SteveL-MSFT Could you please clarify?

2017-10-03 16:26 UTC, SteveL-MSFT commented
@iSazonov I believe the intent was to have the next sentence on the next line left justified.  The whitespace should have been removed.  I'll submit PR.