enable using filesystem from a UNC location
PowerShell/PowerShell pull request #4998
Opened 2017-10-03 22:26 UTC by SteveL-MSFT

The problem is while validating the path, it splits `\\server\share\folder` by the backslash so the root is just `\` and the path ends up being `\server\share\folder` which isn't valid.  Fix is on Windows to add extra slash if the root is `\`

Fix https://github.com/PowerShell/PowerShell/issues/4990

2017-10-03 23:20 UTC, anmenaga requested changes

2017-10-03 23:20 UTC, anmenaga commented on src/System.Management.Automation/namespaces/NavigationProviderBase.cs
> +                        builder.Append('\\');
Probably better to use DefaultPathSeparatorString instead of char constant.

2017-10-04 00:53 UTC, SteveL-MSFT commented
I don't like the change being outside of the filesystemprovider, let me see if I can rework this.

2017-10-04 01:09 UTC, daxian-dbw commented
@SteveL-MSFT yeah, it would be the best if we can fix the `GetParentPath` to take into account UNC paths.

2017-10-04 01:22 UTC, SteveL-MSFT commented
@daxian-dbw `GetParentPath` gets called repeatedly to validate the entire path from leaf to root.  I think putting the fix in NormalizePath() may be better.

2017-10-04 03:39 UTC, iSazonov reviewed
I unlike the fix - it seems a performance is bad.
I do `cd \\localhost\c$` and discover that we call `NormalizePath` 6-9 times for the same path!

2017-10-04 03:39 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +    It "Can Get-ChildItems from a UNC location" -Skip:(!$IsWindows) {
Should we check Set-Location too?

2017-10-04 03:56 UTC, SteveL-MSFT commented on test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
> +    It "Can Get-ChildItems from a UNC location" -Skip:(!$IsWindows) {
Sure

2017-10-04 13:59 UTC, SteveL-MSFT commented
@iSazonov I've noticed that the providers get called a lot.  Perhaps GetParentPath() is the right place even thought that gets called a lot as well, but we only need to make it a UNC path again if it's at the root.

2017-10-04 14:20 UTC, iSazonov commented
I wonder why we have to call NormalizePath method so many times on the same path? Maybe we can fix this?

2017-10-04 15:52 UTC, SteveL-MSFT commented
@iSazonov I created https://github.com/PowerShell/PowerShell/issues/5002 as the perf work item

2017-10-06 17:43 UTC, adityapatwardhan commented
@anmenaga  Please update your review.

2017-10-09 16:24 UTC, adityapatwardhan commented
@anmenaga  ping...

2017-10-09 20:22 UTC, anmenaga approved these changes
LGTM.
Too many paths. :)

2017-10-09 21:03 UTC, adityapatwardhan approved these changes
LGTM

2017-10-09 21:05 UTC, merged