add notimplementedException to cmdlets that are temporary not support…
PowerShell/PowerShell pull request #5083
Opened 2017-10-11 08:44 UTC by chunqingchen

resolve #4355

Adding notimplemented exception to cmdlets that are not supported on non-windows platforms

2017-10-11 13:34 UTC, iSazonov commented
Usually we exclude not ported cmdlets with `#if !UNIX` (or exclude whole file in csproj) and remove from [psd1](https://github.com/PowerShell/PowerShell/tree/master/src/Modules/Unix)

Also we need correct tests in [DefaultCommands.Tests.ps1](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/engine/Basic/DefaultCommands.Tests.ps1)

2017-10-18 07:14 UTC, chunqingchen commented
@iSazonov in issue  #4355 you mentioned not implantation exception should be added instead of excluding the cmdlets. Is that not the case now?

2017-10-18 10:59 UTC, iSazonov commented
@chunqingchen Sorry, my comment was not approved. I remember @daxian-dbw said that it is better exclude code in csproj - it is easy to track. @daxian-dbw Could you confirm?

2017-10-23 19:28 UTC, adityapatwardhan requested changes

2017-10-23 19:28 UTC, adityapatwardhan commented on test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
> +                  @{command = "New-PSSessionConfigurationFile -Path c:\path"; testname = "New-PSSessionConfigurationFile"}
For consistency sake, can we use non-windows path here?

2017-10-23 19:28 UTC, adityapatwardhan commented on test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
> +                  @{command = "Test-PSSessionConfigurationFile -Path c:\path"; testname = "Test-PSSessionConfigurationFile"}
For consistency sake, can we use non-windows path here?

2017-10-27 10:44 UTC, chunqingchen commented
@adityapatwardhan your comments are resolved.

2017-10-28 17:50 UTC, TravisEz13 commented
The last commit is lot linked to a github account.   Please resolve.

2017-10-31 22:37 UTC, adityapatwardhan commented
@chunqingchen The title and the description needs to be updated to match the implementation.

2017-11-01 08:56 UTC, chunqingchen commented
@adityapatwardhan updated

2017-11-01 10:12 UTC, iSazonov commented on src/System.Management.Automation/engine/InitialSessionState.cs
> +}
Please add new line at EOF.

2017-11-01 10:12 UTC, iSazonov commented on test/powershell/engine/Basic/DefaultCommands.Tests.ps1
> +}
Please add new line at EOF.

2017-11-01 20:57 UTC, chunqingchen commented
@iSazonov your comment is resolved

2017-11-02 03:10 UTC, iSazonov reviewed
Leave a comment

2017-11-02 03:10 UTC, iSazonov commented on test/powershell/engine/Basic/DefaultCommands.Tests.ps1
> +}
@chunqingchen Sorry, we should add newline after the last brace not before.

2017-11-02 03:10 UTC, iSazonov commented on src/System.Management.Automation/engine/InitialSessionState.cs
> +}
@chunqingchen Sorry, we should add newline after the last brace not before.

2017-11-02 22:53 UTC, TravisEz13 commented on src/System.Management.Automation/engine/InitialSessionState.cs
> +}
missing newline

2017-11-02 22:53 UTC, TravisEz13 commented on test/powershell/engine/Basic/DefaultCommands.Tests.ps1
> +}
missing newline

2017-11-02 22:54 UTC, TravisEz13 approved these changes
Fix minor issue and it should be good

2017-11-02 23:59 UTC, chunqingchen commented
@TravisEz13 new line added.

2017-11-03 03:27 UTC, iSazonov reviewed
Should we exclude the code from compilation?

2017-11-03 03:27 UTC, iSazonov commented on src/System.Management.Automation/engine/InitialSessionState.cs
> +
Please revert the formatting change and remove the line.

2017-11-03 03:27 UTC, iSazonov commented on test/powershell/engine/Basic/DefaultCommands.Tests.ps1
> +
Please revert the formatting change and remove the line.

2017-11-06 18:24 UTC, adityapatwardhan commented
@chunqingchen Please run all tests using `[Feature]` in your git commit message.

https://github.com/PowerShell/PowerShell/blob/a1b7f8be3ea4ac7e4f7a67e6261ad68cdb23143d/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr

2017-11-08 15:03 UTC, chunqingchen commented
@adityapatwardhan @iSazonov your comments are resolved. Thanks

2017-11-08 17:37 UTC, iSazonov commented
I believe the PR need #5378 to pass CI Appveyor.

2017-11-10 00:25 UTC, adityapatwardhan commented
@chunqingchen Can you have a look at the Travis CI failure?

2017-11-10 17:53 UTC, adityapatwardhan approved these changes

2017-11-10 18:03 UTC, iSazonov commented
CI Travis was passed but not reported.

2017-11-10 18:35 UTC, adityapatwardhan commented
Merging as CI has passed but webhook did not update status to GitHub.

2017-11-10 18:36 UTC, merged

2018-02-21 22:38 UTC, vinodc commented
@paulcallen Would you happen to know if `New-PSSessionOption` has been disabled? We updated to the latest version from 6.0.0 beta1 and this no longer works. It was previously working great and we have been using it with `New-PSSessionOption` since https://github.com/PowerShell/psl-omi-provider/issues/67 was merged in.

2018-02-22 00:45 UTC, dantraMSFT commented
@vinodc I'll dig into this.  For now, you can use [System.Management.Automation.Remoting.PSSessionOption]::new() and populate the returned object.

BTW: What's the use case you have for it on Linux.  Perhaps it was missed with the cmdlet was removed.

2018-02-22 01:07 UTC, vinodc commented
@dantraMSFT Thanks for the quick response. We are programmatically accessing Office 365 PowerShell cmdlets and in the process our code creates PSSessionOption objects. We can work around this, but wanted to make sure that the overall implementation itself is still supported for related commands used to connect to Office 365 PowerShell, starting with `New-PSSessionOption`.

On a broader note, this is related to piped commands failing (https://github.com/PowerShell/PowerShell/issues/6206), where we were recommended to update PowerShell first to see if we could reproduce the failure on the latest version, which resulted in these new issues coming up.

2019-05-05 18:06 UTC, dreyTee commented
> @paulcallen Would you happen to know if `New-PSSessionOption` has been disabled? 
Have same issue when trying to  use WINRM from linux without proper server certificate:
Getting error:
`Use the PSSessionOption -SkipCACheck and -SkipCNCheck`
Trying to use thes options with `New-PSSessionOption` but can't:
`New-PSSessionOption : The term 'New-PSSessionOption' is not recognized as the name of a cmdlet, function, script file, or operable program.`
Please advise a workaround a least.

2019-05-05 18:31 UTC, iSazonov commented
@dreyTee Please open new issue for your question.