-Verbose should not override $ErrorActionPreference
PowerShell/PowerShell pull request #5113
Opened 2017-10-14 04:29 UTC by SteveL-MSFT

Fix https://github.com/PowerShell/PowerShell/issues/2247

2017-10-17 19:34 UTC, anmenaga requested changes
This change is only for Verbose;
however, original issue says that it was approved for both: Verbose and Debug : "Committee agrees that we should fix this so that -ErrorAction works correctly and not overridden by -Debug or -Verbose".
Should this change be done for Debug as well?

2017-10-17 20:16 UTC, SteveL-MSFT commented
@anmenaga that's a fair point about `-Debug`.  I'll update this.

2017-10-18 01:49 UTC, SteveL-MSFT commented
@anmenaga can you review again?

2017-10-18 15:09 UTC, adityapatwardhan requested changes

2017-10-18 15:09 UTC, adityapatwardhan commented on test/powershell/Language/Scripting/ActionPreference.Tests.ps1
> +            New-Item @params
` > $null`

2017-10-18 15:40 UTC, SteveL-MSFT commented on test/powershell/Language/Scripting/ActionPreference.Tests.ps1
> +            New-Item @params
will add

2017-10-18 17:09 UTC, anmenaga approved these changes

2017-10-18 21:38 UTC, SteveL-MSFT commented
@adityapatwardhan can you review again?

2017-10-23 19:19 UTC, adityapatwardhan approved these changes

2017-10-26 20:40 UTC, merged

2017-10-28 11:07 UTC, mintsoft commented
Is this likely to make it into the final for Powershell 6?

2017-10-28 14:01 UTC, markekraus commented
@mintsoft This was merged to master so it will be in the release unless it needs to be reverted for some reason.