Add compliance label description
PowerShell/PowerShell pull request #5355
Opened 2017-11-06 19:21 UTC by TravisEz13

2017-11-06 19:36 UTC, adityapatwardhan approved these changes

2017-11-06 19:42 UTC, TravisEz13 commented
restarted travis-ci mac due to a dotnet nuget download failure.

2017-11-13 18:58 UTC, SteveL-MSFT requested changes

2017-11-13 18:58 UTC, SteveL-MSFT commented on docs/maintainers/issue-management.md
> +  Microsoft to continue to sign and release packages from the project as official Microsoft packages.  The time frame
Please use semantic newlines (put each sentence on separate line)

2017-11-14 17:48 UTC, SteveL-MSFT approved these changes

2017-11-14 18:37 UTC, merged