move rcedit step to build rather than packaging
PowerShell/PowerShell pull request #5404
Opened 2017-11-10 02:13 UTC by SteveL-MSFT

Fix https://github.com/PowerShell/PowerShell/issues/5403

2017-11-10 17:24 UTC, TravisEz13 requested changes

2017-11-10 17:24 UTC, TravisEz13 commented on build.psm1
> +        $ProductVersion = (git --git-dir="$PSScriptRoot/.git" describe) -Replace '^v'
Use release tag parameter to get version if it was passed it.  This is needed for release builds.

2017-11-10 17:24 UTC, TravisEz13 commented on build.psm1
> +        $ProductVersion = (git --git-dir="$PSScriptRoot/.git" describe) -Replace '^v'
Please use `Get-PSCommitId` instead of rewriting this code `git --git-dir="$PSScriptRoot/.git" describe`

2017-11-10 18:18 UTC, TravisEz13 requested changes

2017-11-10 18:18 UTC, TravisEz13 commented on build.psm1
> +            $ReleaseTag = Get-PSCommitId
you still need to remove the v at the beginning.
Get-PSVersion will do that for you, but I don't have a function to do this for the releasetag.

2017-11-10 18:57 UTC, TravisEz13 commented on build.psm1
> +            $ReleaseVersion = $ReleaseTag -replace '^v'
$ReleaseTagToUse should already be this value

2017-11-10 18:57 UTC, TravisEz13 approved these changes

2017-11-10 19:53 UTC, adityapatwardhan approved these changes
LGTM

2017-11-10 22:01 UTC, bergmeister commented
Minor but worth pointing out: The bracing style is inconsistent.

2017-11-10 23:08 UTC, SteveL-MSFT commented
@bergmeister I think that's a fair point.  Will update for the code I added.

2017-11-11 18:22 UTC, daxian-dbw approved these changes

2017-11-11 18:29 UTC, daxian-dbw commented
The macOS CI was canceled by Travis-CI ...
Given that changes in this PR don't affect PowerShell on Linux/macOS, I will merge this PR.

2017-11-11 18:32 UTC, merged

2017-11-11 18:35 UTC, daxian-dbw commented
@TravisEz13 note that even the step is moved to build phase, it's the `publish\pwsh.exe` that gets modified, so you need to copy the `pwsh.exe` from the publish folder when doing the signing.