Remove AddTypeCommandBase class
PowerShell/PowerShell pull request #5407
Opened 2017-11-10 10:19 UTC by iSazonov

As discussed in 5158:
- Remove AddTypeCommandBase class.
- Minor code cleanups.
- Fix comments.

2017-11-15 06:15 UTC, iSazonov commented
@daxian-dbw @SteveL-MSFT Can we review and merge before RC? - it is formally breaking change.

2017-11-15 18:38 UTC, SteveL-MSFT commented
Although technically a breaking change, I think the risk is low that we can take it after 6.0.0 rather than delay the RC

2017-11-15 23:15 UTC, PaulHigin requested changes

2017-11-16 03:35 UTC, iSazonov commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
> +                    String.Join("\n", value);
My bad. 
Fixed.

2017-11-16 16:17 UTC, PaulHigin approved these changes

2017-11-17 03:49 UTC, merged