get PowerShellGet from the PowerShell Gallery
PowerShell/PowerShell pull request #5452
Opened 2017-11-14 23:21 UTC by TravisEz13

get PowerShellGet from the PowerShell Gallery as this is the production location of the module and more reliable than myget

2017-11-14 23:37 UTC, adityapatwardhan requested changes

2017-11-14 23:37 UTC, adityapatwardhan commented on build.psm1
> +    ) -SourceLocation "https://www.powershellgallery.com/api/v2/"
This call to Restore-PSModule can be combined with the call at line # 607. The name is an array.

```Powershell

Restore-PSModule -Destination $modulesDir -Name @( 
         'Microsoft.PowerShell.Archive','PowerShellGet'
     ) -SourceLocation "https://www.powershellgallery.com/api/v2/"

2017-11-15 18:13 UTC, adityapatwardhan approved these changes

2017-11-15 18:18 UTC, daxian-dbw approved these changes

2017-11-15 18:19 UTC, merged