Packaging: make mac package require 10.12 or newer
PowerShell/PowerShell pull request #5649
Opened 2017-12-07 21:13 UTC by TravisEz13

## PR Summary

Make mac package require 10.12 or newer.
The Apple example XML had a background image added as well, so I added a background image:
![image](https://user-images.githubusercontent.com/10873629/33738943-014c9d00-db50-11e7-9628-310ce6427438.png)

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [NA] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [NA] Issue filed - Issue link:
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [NA] [Add `[feature]` if the change is significant or affectes feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2017-12-07 22:48 UTC, TravisEz13 commented
@thezim If you are familiar with this area, would you review this.  Look at the issue for the main reason for the change.

2017-12-07 22:50 UTC, adityapatwardhan requested changes

2017-12-07 22:50 UTC, adityapatwardhan commented on tools/packaging/packaging.psm1
> +    $distributionXmlPath = Join-Path -Path $tempDir -ChildPath '/powershellDistribution.xml'
I think the `/` is not required in `'/powershellDistribution.xml'`

2017-12-07 22:50 UTC, adityapatwardhan commented on tools/packaging/packaging.psm1
> +    #$FpmPackage = Rename-Item -Path $FpmPackage.FullName -NewName $newPackagePath -PassThru -ErrorAction Stop
Remove this line

2017-12-08 00:19 UTC, adityapatwardhan approved these changes

2017-12-08 03:40 UTC, thezim commented
@TravisEz13 The package does not contain the launcher when I build your branch. Not sure if this is product of #5625 or I'm missing something in the build. Can you please verify if the launcher is there?

2017-12-08 07:49 UTC, TravisEz13 commented
@thezim Thanks for the review.  The issue was caused by the previous PR.  I have updated this PR.  Thanks.

2017-12-08 18:48 UTC, daxian-dbw reviewed
LGTM. Left two non-blocking comments which can be addressed in separate PRs.

2017-12-08 18:48 UTC, daxian-dbw commented on tools/packaging/packaging.psm1
> +        Start-NativeExecution -sb {productbuild --distribution $distributionXmlPath --resources $resourcesDir $newPackagePath}
Non-blocking: it's better to add a comment explaining that `productbuild is a xcode command line tool which will be installed when homebrew is installed`.

2017-12-08 18:48 UTC, daxian-dbw commented on tools/packaging/packaging.psm1
> +
Non-blocking: remove an extra new line.

2017-12-08 18:55 UTC, merged