Minor docker release tests updates
PowerShell/PowerShell pull request #5692
Opened 2017-12-14 21:12 UTC by anmenaga

## PR Summary
This PR has 2 updates to release docker tests:
1) Pester module was recently removed from PS packages - this broke Docker release tests; this change adds a call to Restore-PSPester so that tests could run as expected.
2) Removing caching during docker builds as it was causing random failures during test passes.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [N/A] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affectes feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

2017-12-14 21:17 UTC, daxian-dbw commented
Maybe this PR should target the `6.0.0` branch. @TravisEz13 what do you think?

2017-12-14 21:18 UTC, TravisEz13 commented on docker/tests/Templates/centos7/Dockerfile
> +RUN pwsh -c "Import-Module /PowerShell/build.psm1;Restore-PSPester -Destination /usr/local/share/powershell/Modules;exit (Invoke-Pester $TESTLISTSTUB -PassThru).FailedCount"
was there supposed to be a change to `Restore-PSPester` to add `-Destination`

2017-12-14 21:21 UTC, TravisEz13 requested changes

2017-12-14 21:21 UTC, TravisEz13 commented on docker/tests/containerTestCommon.psm1
> +        $buildArgs += "--no-cache"
Please don't do this.  This will make the other tests very slow.  Please fix your docker files, or make this an option, that only your tests use.

2017-12-14 21:29 UTC, TravisEz13 commented on docker/tests/containerTestCommon.psm1
> +        $buildArgs += "--no-cache"
after talking to @anmenaga  offline this looks fine.

2017-12-14 23:40 UTC, daxian-dbw approved these changes

2017-12-15 01:18 UTC, TravisEz13 approved these changes

2017-12-15 21:59 UTC, merged