Packaging: simply building an installable package for Windows
PowerShell/PowerShell pull request #5871
Opened 2018-01-11 21:47 UTC by bergmeister

## PR Summary

This is the continuation of [PR 5499 ](https://github.com/PowerShell/PowerShell/pull/5499) that had to be abandoned due to a fatal merge conflict and I did not want to risk accidentally reverting recent fixes.

- Remove unnecessary/unused default for productGuid because it always gets a new Guid when being called from `Start-PSPackage`
- Add defaults for required files but also add extra path validation attribute
- Rename ProductGuid to ProductCode

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

2018-01-12 20:19 UTC, SteveL-MSFT requested changes

2018-01-12 20:19 UTC, SteveL-MSFT commented on build.psm1
> +        cd $RootPathOfPowerShellCheckout
Is it better to use the term `Repo` instead of `Checkout`?

2018-01-12 20:19 UTC, SteveL-MSFT commented on build.psm1
>          # Product Guid needs to change for every version to support SxS install
This comment should probably be changed to: Product Code needs to be different for every version

2018-01-12 20:19 UTC, SteveL-MSFT commented on tools/packaging/packaging.psm1
>                      # Product Guid needs to be unique for every PowerShell version to allow SxS install
This comment should probably be changed to: Product Code needs to be different for every version

2018-01-12 20:29 UTC, bergmeister commented
@SteveL-MSFT OK, I addressed your comments.

2018-01-13 00:18 UTC, TravisEz13 commented on build.psm1
> +        # Product Code needs to change for every version to support SxS install
Does this comment make sense any more?

`The ProductCode property is a unique identifier for the particular product release`

from https://msdn.microsoft.com/en-us/library/windows/desktop/aa370854(v=vs.85).aspx

2018-01-13 00:20 UTC, TravisEz13 commented on tools/packaging/packaging.psm1
> +                    # Product Code needs to be unique for every PowerShell version to allow SxS install
This is not correct either...  but here just remove the `to allow SxS install` part.

2018-01-13 00:20 UTC, TravisEz13 commented on assets/Product.wxs
>    <!-- UpgradeCode GUID MUST REMAIN SAME THROUGHOUT ALL VERSIONS, otherwise, updates won't occur. -->
This is actually where the comment about SxS should be.

2018-01-13 00:21 UTC, TravisEz13 requested changes
I have some comments about the comments

2018-01-16 18:23 UTC, TravisEz13 approved these changes

2018-01-16 23:32 UTC, SteveL-MSFT approved these changes

2018-01-17 23:34 UTC, merged