Enable setting PSSession Name when using SSHTransport
PowerShell/PowerShell pull request #5954
Opened 2018-01-19 18:28 UTC by SteveL-MSFT

## PR Summary

When using `New-PSSession -SSHTransport -Name ...` the `Name` parameter wasn't being used when creating the remoterunspace so an automatically generated one was always created.
Fix is to use a different overload for creating the remote runspace so that the name is used.

Test will have to wait until we have infrastructure for remoting tests and `Enable-SSHRemoting` work is complete.

Fix https://github.com/PowerShell/PowerShell/issues/5951

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [X] Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [NA] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

2018-01-19 19:12 UTC, iSazonov reviewed
Leave a comment

2018-01-19 19:12 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
> +                string rsName = GetRunspaceName(index, out rsId);
We could remove line 1085:
```c#
string rsName = GetRunspaceName(index, out int rsIdUnused); 
```

2018-01-19 19:12 UTC, iSazonov commented on src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
> +                string rsName = GetRunspaceName(index, out rsId);
The same.

2018-01-19 21:58 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
> +                string rsName = GetRunspaceName(index, out rsId);
Yeah, can't believe I missed that.

2018-01-19 22:00 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
> +                string rsName = GetRunspaceName(index, out rsId);
will fix

2018-01-19 22:26 UTC, SteveL-MSFT commented
Need to redo this fix.  `GetRunspaceName` assumes WinRM.

2018-01-20 09:56 UTC, iSazonov commented
@SteveL-MSFT I found related Issue #2426 - can we address it in the PR (in part of the names at least)?

2018-01-22 17:45 UTC, PaulHigin requested changes

2018-01-22 21:41 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
> +                        string rsName = GetRunspaceName("WSMan", rsIndex, out rsId);
Makes sense.  Will fix.

2018-01-22 21:45 UTC, SteveL-MSFT commented
@iSazonov based on #2426, it seems that the autogenerated name can actually be simplified to just `RunspaceN` and instead of putting the transport into the name, have it as a separate property.  I can do that as part of this PR.

2018-02-01 17:50 UTC, PaulHigin approved these changes

2018-02-01 17:50 UTC, PaulHigin commented on src/System.Management.Automation/engine/remoting/client/remoterunspaceinfo.cs
> +        public String Transport
Minor comment: You could use the new property accessor expression syntax here
```
public String Transport => GetTransportName();
```

2018-02-04 21:12 UTC, merged