Update-Help test updates
PowerShell/PowerShell pull request #6093
Opened 2018-02-02 23:18 UTC by anmenaga

## PR Summary

Currently building PS is required on a test machine for a test pass to succeed.
One of the test work items is to decouple test passes from build requirement; i.e. tests should be runnable on released PS packages.
This PR fixes test code (Update-Help tests) that currently fail on released PS packages.

Test results (`test\powershell\engine\Help`) before fix:
![beforefix](https://user-images.githubusercontent.com/11860095/35758953-963a9606-086e-11e8-99d1-ac2dc5dd1abe.png)

Test results (`test\powershell\engine\Help`) after fix:
![afterfix](https://user-images.githubusercontent.com/11860095/35758962-a4d0062e-086e-11e8-935a-f815543a206e.png)

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [NA] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

2018-02-03 10:06 UTC, iSazonov commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +    Remove-Item -Path $filepath -ErrorAction SilentlyContinue
Please add `-Force`.

2018-02-06 17:27 UTC, adityapatwardhan requested changes

2018-02-06 17:27 UTC, adityapatwardhan commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +    # Update-Help fails if module path is Not writable, so skip tests in this situation
Yes, we do not run the tests under sudo on Linux.

2018-02-06 17:27 UTC, adityapatwardhan commented on test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
> +function PathIsReadOnly
Can we move this function to a common file and then dot source it in both the test files.

2018-02-06 17:27 UTC, adityapatwardhan commented on test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
> +            # -Skip and -$Pending are mutually exclusive on It block, so skip Pending tests
Skip and Pending have specific meanings. you can use splatting to choose one of them for the It block.

2018-02-07 03:34 UTC, iSazonov commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +    # Update-Help fails if module path is Not writable, so skip tests in this situation
Perhaps we should not complicate these tests if we want to implement #5645?

2018-02-08 19:31 UTC, adityapatwardhan commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +    # Update-Help fails if module path is Not writable, so skip tests in this situation
I believe we need to go through a bunch to tests when #5645 is done. We can revert these changes then.

2018-02-20 18:12 UTC, adityapatwardhan commented
Now that RequiresSudoOnUnix is available. We can simplify the logic over here. Please have a look at: https://github.com/PowerShell/PowerShell/pull/6145

2018-03-02 19:08 UTC, adityapatwardhan commented
I believe https://github.com/PowerShell/PowerShell/pull/6223 should fix the issue this PR is trying to fix. 
@anmenaga if you agree, please close the PR.

2018-03-14 18:39 UTC, anmenaga commented
this is covered by #6223 .

2018-03-14 18:39 UTC, closed without merging