Remove Restore-PSPester as we have moved to the latest version of Pester
PowerShell/PowerShell pull request #6112
Opened 2018-02-06 15:25 UTC by daxian-dbw

## PR Summary

Remove Restore-PSPester as we have moved to the latest version of Pester via PR #6064

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

2018-02-06 16:54 UTC, adityapatwardhan approved these changes
LGTM

2018-02-06 18:07 UTC, TravisEz13 requested changes

2018-02-06 18:07 UTC, TravisEz13 commented on docs/testing-guidelines/testing-guidelines.md
> +Make sure that you run `Save-Module -Name Pester -Path $PSHOME\Modules` before running `Start-PSPester`
This isn't quite accurate.  It should be the $PSHome of the process that is started by Start-PSPester.

2018-02-06 18:36 UTC, JamesWTruher approved these changes
I think that Travis' comment is reasonable, it's one of the reasons I left it in the earlier functions, as `$PSHOME` is the right `$PSHOME` in the circumstance where it would be run.

2018-02-06 19:27 UTC, TravisEz13 commented
It might be easier to update the Restore-PSPester to do the correct action.

2018-02-06 19:48 UTC, daxian-dbw commented
Update the PR to just change `Restore-PSPester` to use `Save-Module` within it.

2018-02-06 20:32 UTC, TravisEz13 approved these changes

2018-02-06 20:34 UTC, JamesWTruher approved these changes

2018-02-07 05:51 UTC, iSazonov commented
@daxian-dbw Could you please correct PR header and description?

2018-02-07 16:33 UTC, daxian-dbw commented
@iSazonov Good catch. Updated.

2018-02-07 21:44 UTC, merged