Make it clearer how and what to mark as not applicable
PowerShell/PowerShell pull request #6209
Opened 2018-02-21 18:53 UTC by TravisEz13

## PR Summary

Make it easier and clearer how and what to mark as not applicable

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking]
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:  (https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- **Testing - New and feature**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-02-21 23:54 UTC, bergmeister commented
I always find that ticking the first 3 checkboxes is a pointless exercise. They should be just one checkbox stating something like `PR summary/title follows rules here` with a link to a more or less detailed document section describing it.

2018-02-22 18:08 UTC, TravisEz13 commented
@bergmeister I agree partially on the first 3 checkboxes and updated the checklist, but just because we can't force people doesn't mean we can't remind them.  As a maintainer, the results are much better with the checklist.

The problem with using unchecked as not applicable could mean they haven't gotten around to it or that it's not applicable, but I think I would be ok with it.  I added the maintainers and Steve for additional feedback.

2018-02-22 18:09 UTC, adityapatwardhan requested changes

2018-02-22 18:09 UTC, adityapatwardhan commented on .github/PULL_REQUEST_TEMPLATE.md
> +        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-add
Add another item to point to : https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission for copyright header.

2018-02-22 18:40 UTC, iSazonov commented
Should we add a point for [Breaking Change] in commit header? I already lost one.

2018-02-22 19:04 UTC, TravisEz13 commented
I think the breaking change in the commit header is a maintainer requirement.

2018-02-22 19:04 UTC, adityapatwardhan approved these changes
Please add psd1 to the list.

2018-02-22 19:04 UTC, adityapatwardhan commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submi
Also for psd1, the author, company, copyright fields must be consistent.

2018-02-22 19:04 UTC, adityapatwardhan commented on .github/PULL_REQUEST_TEMPLATE.md
> +        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-add
Closed.

2018-02-22 19:11 UTC, iSazonov approved these changes

2018-02-22 23:09 UTC, SteveL-MSFT requested changes

2018-02-22 23:09 UTC, SteveL-MSFT commented on .github/PULL_REQUEST_TEMPLATE.md
> +    - [ ] Not Applicable
Perhaps change this to:

Not Applicable or can only be tested interactively

2018-02-23 01:33 UTC, SteveL-MSFT approved these changes

2018-02-23 01:47 UTC, daxian-dbw approved these changes

2018-02-23 23:25 UTC, merged