fix for #6482 - Make sure that the width of the column is a least the size of the label for Semantic Version
PowerShell/PowerShell pull request #6487
Opened 2018-03-24 04:21 UTC by JamesWTruher

which in this case is the same as the property name

When the label is too short, an unhelpful error will be emitted
this fixes https://github.com/PowerShell/PowerShell/issues/6482
 
## PR Summary

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed - Issue link: https://github.com/PowerShell/PowerShell/issues/6482
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-03-24 04:45 UTC, stknohg commented
This pull request only partially resolves the problem.

We need to change `TableWriter` class like below.

current :
https://github.com/PowerShell/PowerShell/blob/9bc81ad695c7eba777255a2905aec58adc90daa1/src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs#L292-L310

after change (example):

```csharp
            // add padding for the columns that are shorter
            for (int col = 0; col < scArray.Length; col++)
            {
                int paddingBlanks = _si.columnInfo[validColumnArray[col]].width;
                if (col > 0)
                    paddingBlanks += ScreenInfo.separatorCharacterCount;
                else
                {
                    paddingBlanks += _startColumn;
                }
                int paddingEntries = screenRows - scArray[col].Count;
                if (paddingEntries > 0)
                {
                    for (int j = 0; j < paddingEntries; j++)
                    {
                        scArray[col].Add(col == scArray.Length - 1 ? "" : StringUtil.Padding(paddingBlanks));
                    }
                }
            }
```

2018-03-26 16:04 UTC, SteveL-MSFT requested changes

2018-03-26 16:04 UTC, SteveL-MSFT commented on test/powershell/engine/Basic/SemanticVersion.Tests.ps1
> +    Context "Formating" {
Typo: formatting

2018-03-26 16:09 UTC, JamesWTruher commented on test/powershell/engine/Basic/SemanticVersion.Tests.ps1
> +    Context "Formating" {
fixed

2018-03-27 02:59 UTC, stknohg commented
#6504 will fix this issue.
I retract the previous comment.

2018-03-27 19:37 UTC, SteveL-MSFT approved these changes

2018-03-28 20:33 UTC, adityapatwardhan approved these changes

2018-03-28 20:34 UTC, merged