Remove support for file to opt-out of telemetry, only support env var
PowerShell/PowerShell pull request #6601
Opened 2018-04-09 07:48 UTC by SteveL-MSFT

## PR Summary

Since a PR added support to opt out of telemetry via an environment variable, we can remove the
always intended to be temporary solution of deleting a file to opt out of telemetry since the
environment variable can be defined at the system level and exist before even installing PowerShell Core.

Fix https://github.com/PowerShell/PowerShell/issues/6078

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-04-09 16:35 UTC, adityapatwardhan requested changes

2018-04-09 16:35 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
>                  // if the semaphore file exists, try to send telemetry
Please update the comment.

2018-04-09 16:35 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
> +                var enabled = GetEnvironmentVariableAsBool(TelemetryOptoutEnvVar, false);
Please use named arguments.

2018-04-09 18:16 UTC, TravisEz13 commented on tools/appveyor.psm1
> +    $env:POWERSHELL_TELEMETRY_OPTOUT = 1
Why not add this in `Start-PSPester`?

2018-04-09 18:17 UTC, TravisEz13 submitted a review, later dismissed

2018-04-09 20:13 UTC, daxian-dbw requested changes

2018-04-09 20:13 UTC, daxian-dbw commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
> +                var enabled = GetEnvironmentVariableAsBool(TelemetryOptoutEnvVar, false);
This is not right. You are returning `false` by default (when the env variable is not set), and thus we will not send telemetry by default. You should pass `true` as the default value.

2018-04-09 20:13 UTC, daxian-dbw commented on tools/appveyor.psm1
> +    $env:POWERSHELL_TELEMETRY_OPTOUT = 1
Setting 1 to the env variable means you enable the telemetry. You should set 0 here.

2018-04-09 20:13 UTC, daxian-dbw commented on tools/travis.ps1
> +    $env:POWERSHELL_TELEMETRY_OPTOUT = 1
Same here, you should set 0 here.

2018-04-09 22:29 UTC, daxian-dbw commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
> +                var enabled = GetEnvironmentVariableAsBool(TelemetryOptoutEnvVar, false);
`POWERSHELL_TELEMETRY_OPTOUT = 1` or `POWERSHELL_TELEMETRY_OPTOUT = yes` means to not send telemetry, while `POWERSHELL_TELEMETRY_OPTOUT = 0` or `POWERSHELL_TELEMETRY_OPTOUT = no` means to send telemetry?

This looks so not intuitive to me. When I set `POWERSHELL_TELEMETRY_OPTOUT = no`, I would expect it means no telemetry, literally.

2018-04-09 22:46 UTC, daxian-dbw commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
> +                var enabled = GetEnvironmentVariableAsBool(TelemetryOptoutEnvVar, false);
My bad, I misread POWERSHELL_TELEMETRY_OPTOUT to POWERSHELL_TELEMETRY_**OUTPUT** ...

2018-04-09 22:53 UTC, daxian-dbw approved these changes

2018-04-11 18:18 UTC, TravisEz13 commented
I've tried to figure out why travis-ci is failing.  I'm going to close an re-open to PR to see if that resolves the issue.

2018-04-11 18:20 UTC, TravisEz13 submitted a review, later dismissed
The YML change seems to have broken Travis-CI

2018-04-11 18:26 UTC, TravisEz13 commented
I added a fix to the YML

2018-04-12 04:39 UTC, SteveL-MSFT commented
@TravisEz13 @adityapatwardhan your feedback has been addressed

2018-04-12 16:09 UTC, adityapatwardhan approved these changes

2018-04-13 17:29 UTC, merged