updating error when running powershell installer as root
PowerShell/PowerShell pull request #6771
Opened 2018-04-28 21:01 UTC by bjh7242

## PR Summary

Testing on Ubuntu, if the user is root, the $SUDO variable will be blank when attempting to execute the command 'sudo -v' on line 99. By checking if the EUID is not 0 will verify that the $SUDO variable was set above so that 'sudo -v' executes correctly as opposed to executing just '-v' which will throw an error as an unknown command.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-04-30 19:42 UTC, TravisEz13 requested changes
please respond to

2018-04-30 19:42 UTC, TravisEz13 commented on tools/installpsh-debian.sh
> +if [[ $EUID != 0 && "$SUDO" -eq "sudo" && ! ("'$*'" =~ skip-sudo-check) ]]; then
The sudo check should be equivalent because we only set `$SUDO` to `sudo` if `$EUID != 0`

2018-04-30 19:42 UTC, TravisEz13 commented on tools/installpsh-debian.sh
> +if [[ $EUID != 0 && "$SUDO" -eq "sudo" && ! ("'$*'" =~ skip-sudo-check) ]]; then
verified... there is an error in the conditional... change `"$SUDO" -eq "sudo"` to `"$SUDO" == "sudo"` and remove your change

2018-04-30 19:51 UTC, bjh7242 commented
Just pushed the requested update

2018-04-30 19:52 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=6771) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=6771) before we can accept your contribution.<br/><br/>:x: bjh7242 [sign now](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=6771)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/PowerShell/PowerShell?pullRequest=6771) it.</sub>

2018-04-30 19:52 UTC, TravisEz13 commented
@bjh7242 I made the other scripts consistent per @iSazonov 's request.

2018-04-30 19:53 UTC, TravisEz13 approved these changes

2018-04-30 19:55 UTC, TravisEz13 commented
@bjh7242 My changes triggered the code complexity rules (code across multiple files) that mean you need to sign the CLA?  Would you mind signing?

2018-04-30 20:07 UTC, bjh7242 commented
So I'm getting this error right now. I'm about to be AFK for the next 12ish hours, but I'll check again tomorrow morning to see if there are still issues with the site

![microsoftcla](https://user-images.githubusercontent.com/4334716/39447606-5a96133a-4c90-11e8-93e3-510decaa7027.png)

2018-04-30 20:10 UTC, TravisEz13 commented
FYI, this [answer] explains what was going on.

2018-04-30 20:13 UTC, TravisEz13 commented
@bjh7242 I have asked for help with CLA.  I'll get back to you when I get an answer.

2018-04-30 20:58 UTC, MichaelTsengLZ commented
@bjh7242 Thank you so much for reporting this. I just fixed the CLA system. Could you give it a try again?

2018-05-01 12:12 UTC, bjh7242 commented
Just signed it, let me know if you need anything else from me. Thanks!

2018-05-01 17:35 UTC, merged

2018-05-01 17:36 UTC, TravisEz13 commented
@bjh7242  Thanks for your contribution.