Fixed uninitialized variable in the help function that was causing it to fail in strict mode
PowerShell/PowerShell pull request #6781
Opened 2018-04-30 23:11 UTC by BrucePay

## PR  #Summary

Fix for #6497. Changed the "help" function in InitialSessionState.cs to initialize the problematic variable so the function won't fail.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-04-30 23:42 UTC, SteveL-MSFT requested changes

2018-04-30 23:42 UTC, SteveL-MSFT commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +            # run in nested scope to keep strict mode fromo affecting other tests.
typo `from`, probably also remove the trailing punctuation which is inconsistent with general comments

2018-04-30 23:42 UTC, SteveL-MSFT commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +        [bool] $help | Should -Be $true
Perhaps: `$help | Should -Not -BeEmptyOrNull` instead?  If it should fail, the test failure output may make it easier to understand what is going on

2018-05-01 18:16 UTC, TravisEz13 commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +        $help | Should -Not -BeNullOrEmpty $true
the `$true` should not be needed.

```powershell
describe 'test' {
   it 'failing test' {
       '' | should -not -BeNullOrEmpty
   }
   it 'passing test' {
       '' | should -BeNullOrEmpty
   }
 }
```

2018-05-01 18:18 UTC, TravisEz13 requested changes
see comment

2018-05-03 17:34 UTC, closed without merging