Blacklist System.Windows.Forms form loaded to prevent a crash
PowerShell/PowerShell pull request #6822
Opened 2018-05-05 00:04 UTC by TravisEz13

## PR Summary

Blacklist System.Windows.Forms (WinForms) form loaded to prevent a crash

### Before the change

WinForms would load but `System.Drawing` would not when you actually tried to display a form.
![image](https://user-images.githubusercontent.com/10873629/39657385-4d81b300-4fbc-11e8-8d4e-a3da8184e64c.png)
Then when the form was disposed the process would crash with a `TypeLoadException`.  Here are details from the crash dump:
![image](https://user-images.githubusercontent.com/10873629/39657423-8eeed426-4fbc-11e8-8ac9-0473067a0294.png)

After this change, we refuse to load WinForms preventing the crash:
![image](https://user-images.githubusercontent.com/10873629/39657495-1f0e1044-4fbd-11e8-92d6-34c160c8f7df.png)

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-05-05 18:29 UTC, iSazonov commented on test/powershell/engine/Basic/Assembly.Load.ps1
> +        {[System.Reflection.Assembly]::Load('system.windows.forms')} | Should -Throw -ErrorId $ErrorId
Typo - should be `Load($Name)`

2018-05-07 18:17 UTC, adityapatwardhan requested changes

2018-05-07 19:12 UTC, daxian-dbw commented on test/powershell/engine/Basic/Assembly.Load.Tests.ps1
> +        {[System.Reflection.Assembly]::Load($Name)} | Should -Throw -ErrorId $ErrorId
`Assembly.Load` seems working with short name too:

```powershell
PS:1> [System.Reflection.Assembly]::Load("System.Management.Automation")

GAC    Version        Location
---    -------        --------
False  v4.0.30319     F:\pscore\System.Management.Automation.dll`
```

2018-05-07 19:12 UTC, daxian-dbw approved these changes

2018-05-07 19:13 UTC, daxian-dbw commented
LGTM, but please address the pending comments.

2018-05-07 19:23 UTC, adityapatwardhan approved these changes

2018-05-07 23:38 UTC, merged