Fix Windows Event Log channel isolation semantics
PowerShell/PowerShell pull request #6956
Opened 2018-05-30 07:14 UTC by Robo210

Remove isolation attribute from Analytic and Debug channels. These channel types always have an isolation of Custom, regardless of what is put here in the manifest.

The Admin channel was enabled by default, but the comments for the channel indicated that it should be off by default and thus it is OK to use a huge file size and have it stop collecting events when the size is reached. This looks like a copy/paste error where the logging element was copied from a channel with a different isolation type, so fix it by duplicating the Operational channel's logging element instead.

Since no events are being written to the Admin channel currently, set it to disabled by default. This avoids the Windows Event Log pre-allocating a file for the channel.

## PR Summary

Avoid setting incorrect values in the ETW manifest that get silently ignored by mc/wevtutil.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-06-06 05:35 UTC, daxian-dbw approved these changes
Thanks @Robo210!
The changes look good to me.
@dantraMSFT Can you please take a look?

2018-06-06 18:20 UTC, dantraMSFT requested changes
There's no reason to have an admin channel, it's not used for any events and I see no indication that it will change.

2018-06-06 18:20 UTC, dantraMSFT commented on src/PowerShell.Core.Instrumentation/PowerShell.Core.Instrumentation.man
>                chid="C_ADMIN"
Since there are no events referencing this channel, it should simply be removed, not disabled.

2018-06-06 19:05 UTC, dantraMSFT commented on src/PowerShell.Core.Instrumentation/PowerShell.Core.Instrumentation.man
> +          <!--There are four channels defined for Windows PowerShell instrumentation
Sorry, I should have mentioned this before, you'll want to remove these comments around Admin as well.

2018-06-08 06:03 UTC, iSazonov commented
Reopen The PR to restart CI Appveyor.

2018-06-13 05:45 UTC, iSazonov commented
@dantraMSFT Please update your review.

2018-06-14 01:50 UTC, dantraMSFT approved these changes

2018-06-14 05:27 UTC, merged

2018-06-14 05:27 UTC, iSazonov commented
@Robo210 Thanks for your contribution!