Fix broken links due to PR 6899 that removed GitHub docs on installation docs, known issues and breaking changes due to complete migration to docs.microsoft.com
PowerShell/PowerShell pull request #6981
Opened 2018-06-03 10:41 UTC by bergmeister

## PR Summary

To fix broken links due to PR #6899 and remove unneeded spelling items

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-06-04 05:26 UTC, iSazonov approved these changes
Leave a comment

2018-06-04 14:09 UTC, sdwheeler approved these changes
LGTM

2018-06-04 20:25 UTC, TravisEz13 approved these changes

2018-06-05 16:57 UTC, adityapatwardhan requested changes

2018-06-05 16:57 UTC, adityapatwardhan commented on .github/ISSUE_TEMPLATE.md
> +- Refer to the [known issues](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/known-issues-ps6?view=powershell-6).
Maybe we should drop the `en-us` part from the url. So it will redirect to appropriate language according to locale. @sdwheeler am I correct?

2018-06-05 16:57 UTC, adityapatwardhan commented on README.md
> +[in-windows]: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6
The above comment about `en-us` also applies to all urls here.

2018-06-05 18:29 UTC, bergmeister commented
@adityapatwardhan I removed the en-us culture in the links

2018-06-05 19:14 UTC, adityapatwardhan approved these changes

2018-06-06 01:49 UTC, rkeithhill commented
Assuming this PR looks good, it needs to be merged.  Not cool having the install instructions links be broken for multiple days.  Props to @bergmeister for fixing this!

2018-06-06 02:37 UTC, merged