Remove MapSecurityZoneWithUrlmon method and related code
PowerShell/PowerShell pull request #7103
Opened 2018-06-18 20:37 UTC by rjmholt

## PR Summary

Fixes #6919.

Removes the `MapSecurityZoneWithUrlmon` method and the native interface it uses.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-06-18 21:03 UTC, anmenaga requested changes
Neither "PR Summary" nor original issue have a description why this change is necessary.

2018-06-18 23:21 UTC, TravisEz13 commented
@anmenaga 
> Neither "PR Summary" nor original issue have a description why this change is necessary.

@rjmholt says in the summary 
> MapSecurityZoneWithUrlmon uses an unsupported API call, and this ensures we use a supported API to improve quality.

2018-06-18 23:22 UTC, TravisEz13 approved these changes

2018-06-18 23:27 UTC, daxian-dbw requested changes

2018-06-18 23:27 UTC, daxian-dbw commented on src/System.Management.Automation/utils/ClrFacade.cs
>              string sysRoot = System.Environment.GetEnvironmentVariable("SystemRoot");
This variable is not used anymore.

2018-06-18 23:27 UTC, daxian-dbw commented on src/System.Management.Automation/utils/ClrFacade.cs
>              public const int S_OK = 0x00000000;
Is this one still used anywhere?

2018-06-18 23:27 UTC, daxian-dbw commented on src/System.Management.Automation/utils/ClrFacade.cs
>              internal static extern uint GetACP();
This function doesn't seem to be used anymore.

2018-06-18 23:38 UTC, anmenaga approved these changes

2018-06-18 23:40 UTC, anmenaga commented
@TravisEz13 "edited" after I posted the request. :)

2018-06-19 00:42 UTC, TravisEz13 commented
@anmenaga  I'm not sure you get notified of edits and the timing wasn't perfectly clear.

2018-06-20 16:51 UTC, daxian-dbw approved these changes

2018-06-21 21:15 UTC, rjmholt commented
Looks like the test failure is `pwrshplugin.dll`:
```
  Describing JEA session Get-Help test
    [-] Error occurred in Describe block 9.84s
      ItemNotFoundException: Cannot find path 'C:\projects\powershell\src\powershell-win-core\bin\Release
      etcoreapp2.1\win7-x64\publish\pwrshplugin.dll' because it does not exist.
```

2018-06-21 21:15 UTC, rjmholt commented
Not sure if that can be fixed in this PR

2018-06-25 06:46 UTC, merged