Fix error position for switch-statement condition and for-statement initializer
PowerShell/PowerShell pull request #7305
Opened 2018-07-18 01:03 UTC by daxian-dbw

## PR Summary

Fix #7150

- Make switch-statement report correct error position when it fails to evaluate the condition.
- Make for-statement report correct error position when it fails to evaluate the initializer.

**Before:**
```powershell
PS> $test = 1; switch ($null[0]) { default {} }
Cannot index into a null array.
At line:1 char:1
+ $test = 1; switch ($null[0]) { default {} }
+ ~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray

PS> $test = 1; for ($null[0];;) {}
Cannot index into a null array.
At line:1 char:1
+ $test = 1; for ($null[0];;) {}
+ ~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray
```
**After:**
```powershell
PS> $test = 1; switch ($null[0]) { default {} }
Cannot index into a null array.
At line:1 char:20
+ $test = 1; switch ($null[0]) { default {} }
+                    ~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray

PS> $test = 1; for ($null[0];;) {}
Cannot index into a null array.
At line:1 char:17
+ $test = 1; for ($null[0];;) {}
+                 ~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray
```

### Break point check

#### For switch-statement condition, retain the same behavior as is:

**Script Content**
```powershell
PS> cat .\about2.ps1
$Test = 1..2
switch ($Test)
{
    default {'a'}
}
```

```powershell
PS> .\about2.ps1
Entering debug mode. Use h or ? for help.

Hit Line breakpoint on 'F:\tmp\about2.ps1:1'

At F:\tmp\about2.ps1:1 char:1
+ $Test = 1..2
+ ~~~~~~~~~~~~
PS>> v
At F:\tmp\about2.ps1:2 char:9
+ switch ($Test)
+         ~~~~~
PS>> v
At F:\tmp\about2.ps1:4 char:14
+     default {'a'}
+              ~~~
PS>> v
a
At F:\tmp\about2.ps1:2 char:9
+ switch ($Test)
+         ~~~~~
PS>> v
At F:\tmp\about2.ps1:4 char:14
+     default {'a'}
+              ~~~
PS>> v
a
At F:\tmp\about2.ps1:2 char:9
+ switch ($Test)
+         ~~~~~
PS>> v
```

#### For for-statement initializer, fix the incorrect breaking point position when the initializer is a simple command expression:

**Script Content**
```powershell
PS> cat .\about2.ps1
$i = 1
for ('str'.Length;
     $i -gt 0; $i--)
{
    "v"
}
```

**Before:**
```powershell
PS> .\about2.ps1
Hit Line breakpoint on 'F:\tmp\about2.ps1:1'

At F:\tmp\about2.ps1:1 char:1
+ $i = 1
+ ~~~~~~
PS>> v
At F:\tmp\about2.ps1:3 char:6
+      $i -gt 0; $i--)
+      ~~~~~~~~
PS>> v
At F:\tmp\about2.ps1:5 char:5
+     "v"
+     ~~~
PS>> v
v
At F:\tmp\about2.ps1:3 char:16
+      $i -gt 0; $i--)
+                ~~~~
PS:40>> v
At F:\tmp\about2.ps1:3 char:6
+      $i -gt 0; $i--)
+      ~~~~~~~~
PS>> v
```

**After:**
```powershell
PS> .\about2.ps1
Hit Line breakpoint on 'F:\tmp\about2.ps1:1'

At F:\tmp\about2.ps1:1 char:1
+ $i = 1
+ ~~~~~~
PS>> v
At F:\tmp\about2.ps1:2 char:6
+ for ('str'.Length;
+      ~~~~~~~~~~~~
PS>> v
At F:\tmp\about2.ps1:3 char:6
+      $i -gt 0; $i--)
+      ~~~~~~~~
PS>> v
At F:\tmp\about2.ps1:5 char:5
+     "v"
+     ~~~
PS>> v
v
At F:\tmp\about2.ps1:3 char:16
+      $i -gt 0; $i--)
+                ~~~~
PS>> v
At F:\tmp\about2.ps1:3 char:6
+      $i -gt 0; $i--)
+      ~~~~~~~~
PS>> v
```

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-07-18 01:04 UTC, daxian-dbw commented on src/System.Management.Automation/engine/parser/Compiler.cs
> +        private int AddSequencePoint(IScriptExtent extent)
Note: this method is added to make sure that one extent can only be added to the sequence list once.

2018-07-19 23:38 UTC, daxian-dbw commented
@BrucePay Can you please review this PR when you have time? Thanks!

2018-07-21 14:51 UTC, SteveL-MSFT requested changes

2018-07-21 14:51 UTC, SteveL-MSFT commented on test/powershell/Language/Scripting/ErrorPosition.Tests.ps1
> +    It "for statement initializer evaluation failure should report correct error position" {
There should also be a test for while/do loops

2018-07-21 14:51 UTC, SteveL-MSFT commented on test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
> +for ("string".Length;
In the product code, there's a special check for while/do loops, but I don't see a test here for that?

2018-07-24 16:32 UTC, SteveL-MSFT approved these changes

2018-07-24 17:24 UTC, PaulHigin approved these changes
LGTM

2018-07-24 20:48 UTC, daxian-dbw commented on src/System.Management.Automation/engine/parser/Compiler.cs
> +                // For switch statement, we don't want the debugger to stop at 'stmt.Condition' before evaluating it.
The `checkBreakpoints: false` when calling `UpdatePositionExpr` means not checking breaking point for this sequence point update.

2018-07-24 20:50 UTC, daxian-dbw commented on test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
> +            $path = Setup -PassThru -File BasicTest.ps1 -Content $script
That sounds good. Can you please show an example of how to check for debugger stop position?

2018-07-24 21:33 UTC, PaulHigin commented on test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
> +            $path = Setup -PassThru -File BasicTest.ps1 -Content $script
You can create a type (Add-Type) that has a method to handle the runspace.debugger.DebuggerStop event and then check the event argument InvocationInfo extent (I think).  Contact me offline for more info.

2018-07-24 22:09 UTC, daxian-dbw commented on test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
> +            $path = Setup -PassThru -File BasicTest.ps1 -Content $script
OK. I will play with it, and add more tests in a separate PR.

2018-07-25 16:56 UTC, merged