Add support for parsing Link Header with variable whitespace
PowerShell/PowerShell pull request #7322
Opened 2018-07-20 19:47 UTC by SteveL-MSFT

add support for variable whitespace in link header

## PR Summary

Thanks to the @cruscio's analysis, it appears that the Link Header allows for any amount of whitespace or even no whitespace.  The currently explicitly expect a single whitespace after the semicolon in the Link Header before the `Rel` property.

Fix is to change the regex to allow for variable or no whitespace and associated tests to handle these two cases.  Changed `GetLink` helper to support passing in whitespace to use.

Fix https://github.com/PowerShell/PowerShell/issues/5667

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-07-20 20:46 UTC, TravisEz13 requested changes

2018-07-20 20:46 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
> +            string pattern = "<(?<url>.*?)>;\\s*rel=\"(?<rel>.*?)\"";
Please do not introduce any overlapping terms

2018-07-20 21:50 UTC, TravisEz13 commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
> +            string pattern = "<(?<url>.*?)>;\\s*rel=\"(?<rel>.*?)\"";
Resolved, I misread the Regex

2018-07-20 21:51 UTC, TravisEz13 approved these changes

2018-07-21 09:40 UTC, markekraus submitted a review, later dismissed
LGTM

2018-07-21 12:24 UTC, markekraus requested changes
LGTM, but need to update WebListener documentation https://github.com/PowerShell/PowerShell/tree/master/test/tools/WebListener#link

2018-07-21 14:32 UTC, SteveL-MSFT commented
@markekraus added documentation!

2018-07-21 20:06 UTC, markekraus approved these changes

2018-07-24 05:56 UTC, merged