Format Management csproj with updated codeformatter
PowerShell/PowerShell pull request #7346
Opened 2018-07-24 06:29 UTC by iSazonov

## PR Summary

Related #4708.

Format Microsoft.PowerShell.Commands.Management.csproj by codeformatter with default options.

The codeformatter is used that I compiled with newest Roslyn packages (version 2.8.2).

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-07-24 16:21 UTC, SteveL-MSFT requested changes

2018-07-24 16:21 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
> +        // Include
Perhaps delete this comment

2018-07-24 16:21 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
> +            // get
Delete

2018-07-24 16:21 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
> +            // set
delete

2018-07-24 16:21 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
> +        // Exclude
delete

2018-07-24 16:23 UTC, SteveL-MSFT requested changes

2018-07-24 16:23 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
> +        // Exclude
Delete

2018-07-25 03:50 UTC, iSazonov commented
@SteveL-MSFT You comments was addressed

2018-07-25 05:00 UTC, SteveL-MSFT approved these changes

2018-07-25 17:51 UTC, daxian-dbw approved these changes
Good work! Thanks @iSazonov

2018-07-26 17:14 UTC, merged