Default to DefaultConsoleWidth when DotNet says WindowWidth is 0
PowerShell/PowerShell pull request #7465
Opened 2018-08-06 21:53 UTC by TravisEz13

## PR Summary

Default to DefaultConsoleWidth when DotNet says WindowWidth is 0

This resolves an issue in an environment like VSTS when pwsh is spawned and DotNet is not able to determine the Console Width.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-08-07 05:33 UTC, iSazonov commented
@TravisEz13 Please look #6883 - could we move commits from #6883 to the PR?

2018-08-07 17:02 UTC, TravisEz13 commented
@iSazonov  I knew I saw this before, thanks

2018-08-07 17:08 UTC, TravisEz13 commented
Unfortunately, the tests added in 6883 are will not work in any of our CI systems as we aren't using a console that you can adjust the width of.  I don't think it's worth bringing them forward.  We would need to implement something new that emulates the console during the tests.

2018-08-07 19:49 UTC, adityapatwardhan requested changes

2018-08-07 19:49 UTC, adityapatwardhan commented on src/System.Management.Automation/engine/Utils.cs
> +<<<<<<< HEAD
merge headers are left here.

2018-08-07 21:56 UTC, adityapatwardhan requested changes

2018-08-07 21:56 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
> +                Format-table -inputobject $testObject | Out-String -Stream | ForEach-Object{$_.length} | Sort-Object | Select-Object -Last 1 | Should -Be 120
use 
```PowerShell
Format-table -inputobject $testObject | Out-String -Stream | ForEach-Object{$_.length} | Sort-Object -Bottom 1
```

2018-08-07 21:56 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
> +                Format-Table -inputobject $testObject | Should -Not -BeNullOrEmpty
No needed i guess

2018-08-07 22:00 UTC, adityapatwardhan approved these changes

2018-08-07 22:01 UTC, adityapatwardhan commented
@TravisEz13  There seems to be a new CodeFactor issue. Can you have a look.

2018-08-07 22:11 UTC, TravisEz13 commented
The CodeFactor issue is basically an existing design issue around the test hooks

2018-08-07 22:27 UTC, merged

2018-08-14 00:40 UTC, TravisEz13 commented
We would have to have something that allows us to mock `System.Console`

2018-08-14 05:31 UTC, iSazonov commented
I found related discussion https://stackoverflow.com/questions/5852862/mocking-system-console-behaviour
There is a link to https://blogs.msdn.microsoft.com/ploeh/2006/10/21/console-unit-testing/

`[console]::SetOut` looks interesting.