Update .Net Core/SDK docs about version 2.0 to be about version 2.x
PowerShell/PowerShell pull request #7467
Opened 2018-08-06 22:29 UTC by bergmeister

## PR Summary

As per title. Due to the upgrade to .Net Core 2.1 in 6.1, it is better to not be specific about the version of .Net Core or the SDK.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-08-07 17:03 UTC, bergmeister commented
@TravisEz13 I addressed the spelling issues.

2018-08-07 17:07 UTC, daxian-dbw approved these changes

2018-08-07 22:15 UTC, TravisEz13 approved these changes

2018-08-07 22:36 UTC, dantraMSFT requested changes

2018-08-07 22:36 UTC, dantraMSFT commented on docs/building/macos.md
> +.NET Core 2.x (and by transitivity, us) only supports macOS 10.12+.
Does the third bullet item also need to be changed?  

Downloads and installs a preview version of .NET Core SDK 2.0 to ~/.dotnet

2018-08-07 22:36 UTC, dantraMSFT commented on docs/cmdlet-example/command-line-simple-example.md
>  ### The fix for missing netstandard.dll
There are stale references to 2.0 in this section.  Two that stand out are

* "Install the .NET Core SDK 2.0 for Windows, if it isn't already installed."
This actually links to the .NET Core 2.1 page.  Perhaps updating the link label to also use 2.x

* Copy-Item 'C:\Program Files\dotnet\sdk\2.0.0\Microsoft...
A note about the version number varying might help so users arent' blindly copy/pasting the text and getting errors.

2018-08-30 00:48 UTC, daxian-dbw commented
@dantraMSFT I pushed a commit to address your comments. Please take another look.

2018-08-30 22:55 UTC, dantraMSFT approved these changes

2018-08-30 23:51 UTC, merged

2018-09-02 17:12 UTC, bergmeister commented
@daxian-dbw Thanks for helping out, I was quite busy the last weeks due to moving house and forgot about this PR.

2018-09-04 16:57 UTC, daxian-dbw commented
@bergmeister No worries, that's what we maintainers do 😄