Add tests for Import-Module -Force
PowerShell/PowerShell pull request #7491
Opened 2018-08-09 20:31 UTC by rjmholt

## PR Summary

Add testing for the behaviour of Import-Module -Force.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-08-10 06:40 UTC, iSazonov approved these changes
LGTM with one comment.

2018-08-10 06:40 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
> +Describe "Import-Module -Force behaviour" {
Please add -Tag "CI".

2018-08-10 17:26 UTC, rjmholt commented
Sorry @iSazonov, I was demonstrating to some people how to contribute simple tests to the PowerShell repo.

But I would actually like to add this test and bunch of others, so I'll add a few more to this and we can make it into a more useful PR.

2018-08-10 17:48 UTC, iSazonov commented
We could merge this as is. You can make new PR for new tests.

2018-08-10 18:51 UTC, rjmholt commented
@iSazonov Done!

2018-08-12 13:55 UTC, iSazonov commented
I guess you will add tests for nested module scenarios with `-Force`.

2018-08-30 07:40 UTC, iSazonov commented
@adityapatwardhan Could you please review?

2018-08-30 16:47 UTC, adityapatwardhan requested changes

2018-08-30 16:47 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
> +        # Another edit
Please remove this line.

2018-09-17 13:17 UTC, iSazonov commented
@rjmholt Please rebase to reconfigure CIs

2018-09-18 03:43 UTC, iSazonov commented
@adityapatwardhan Please update your code review.

2018-09-18 17:05 UTC, adityapatwardhan approved these changes

2018-09-19 04:32 UTC, merged