Remove SuspendJob and ResumeJob sources from compilation
PowerShell/PowerShell pull request #7650
Opened 2018-08-28 18:12 UTC by JamesWTruher

The classes for the cmdlets are present but the Cmdlet attribute has been removed. There is no reason why we should be compiling these files, and it very slightly impacts our code coverage numbers.

This can be taken for 6.2, there is no reason to take it for 6.1

## PR Summary
Remove SuspendJob and ResumeJob from compilation

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-08-28 18:23 UTC, adityapatwardhan requested changes

2018-08-28 21:53 UTC, JamesWTruher commented on src/System.Management.Automation/System.Management.Automation.csproj
> +    <Compile Remove="engine\remoting\commands\CustomShellCommands.cs" />
definitely should be all platforms to remove.
fixed

2018-08-28 21:59 UTC, adityapatwardhan approved these changes

2018-08-29 17:35 UTC, TravisEz13 approved these changes

2018-08-30 00:07 UTC, dantraMSFT approved these changes

2018-08-30 00:09 UTC, daxian-dbw approved these changes

2018-08-30 00:11 UTC, merged