Add daily build non-windows platforms
PowerShell/PowerShell pull request #7683
Opened 2018-08-31 23:45 UTC by TravisEz13

## PR Summary

Add daily build non-windows platforms
  - Also, add a way to force feature tests to run

Branched from #7658 as the windows CI is taking a long time to work out the test issues

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-09-01 00:15 UTC, TravisEz13 commented
Linux build with `FORCE_FEATURE=True` https://powershell.visualstudio.com/PowerShell/_build/results?buildId=1245&view=logs

2018-09-01 00:17 UTC, TravisEz13 commented
macos build with `FORCE_FEATURE=True` https://powershell.visualstudio.com/PowerShell/_build/results?buildId=1246

2018-09-03 05:47 UTC, iSazonov commented
@TravisEz13 Have you already considered running the tests with a robot like CoreFX team does? This is more convenient than add `[Feature]`.

2018-09-04 17:15 UTC, adityapatwardhan requested changes

2018-09-04 17:15 UTC, adityapatwardhan commented on tools/travis.ps1
> +        Write-Host "##vso[build.updatebuildnumber]Daily-$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhss"))"
the format should be `yyyyMMddhhmm` ss is for seconds.

2018-09-04 17:15 UTC, adityapatwardhan commented on tools/travis.ps1
> +$hasFeatureTag = $commitMessage -match '\[feature\]' -or $env:FORCE_FEATURE -eq 'True'
Could you add an comment about `FORCE_FEATURE` and `FORCE_PACKAGE`

2018-09-06 02:15 UTC, TravisEz13 commented
@adityapatwardhan your issues have been addressed as well as codefactor and the test issues

2018-09-06 17:06 UTC, adityapatwardhan requested changes

2018-09-06 17:06 UTC, adityapatwardhan commented on .vsts-ci/windows.yml
> +    displayName: Capture envirenment
typo environment

2018-09-06 17:06 UTC, adityapatwardhan commented on src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
>                  PipelineFinishedWaitHandle waiterThereIsAFlyInMySoup = new PipelineFinishedWaitHandle(tempPipeline);
Please change name of the variable.

2018-09-06 17:06 UTC, adityapatwardhan commented on tools/travis.ps1
> +        Write-Verbose "commitMessage: $commitMessage" -verbose
Should Write-Log be used here instead?

2018-09-06 17:06 UTC, adityapatwardhan commented on tools/travis.ps1
> +# or the environment valiable `FORCE_FEATURE` equals `True`
typo variable

2018-09-06 19:19 UTC, adityapatwardhan approved these changes

2018-09-06 19:24 UTC, SteveL-MSFT approved these changes

2018-09-06 19:27 UTC, merged