Improve markdown Formatting of beginners guide
PowerShell/PowerShell pull request #7684
Opened 2018-09-01 12:42 UTC by fbehrens

I just improved the formatting of this markdown document.

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-09-01 12:42 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=7684) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=7684) before we can accept your contribution.<br/><br/>:x: fbehrens [sign now](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=7684)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/PowerShell/PowerShell?pullRequest=7684) it.</sub>

2018-09-03 05:44 UTC, iSazonov approved these changes

2018-09-05 20:11 UTC, anmenaga commented
I edited description and filled necessary checkboxes of the description template.

2018-09-05 20:16 UTC, SteveL-MSFT requested changes

2018-09-05 20:16 UTC, SteveL-MSFT commented on docs/learning-powershell/powershell-beginners-guide.md
> +```
Should be: 
 \```powershell

2018-09-07 18:41 UTC, anmenaga commented
@SteveL-MSFT your feedback was addressed; please take a look again.

2018-09-07 18:41 UTC, anmenaga approved these changes

2018-09-07 20:38 UTC, alexandair commented on docs/learning-powershell/powershell-beginners-guide.md
>  PS /> Get-Process
Remove a space between backticks and "powershell".

2018-09-07 22:26 UTC, SteveL-MSFT approved these changes

2018-09-17 17:21 UTC, adityapatwardhan commented
@fbehrens Please rebase or send in a new commit to trigger `PowerShell-CI-spelling` CI.

2018-09-24 16:56 UTC, adityapatwardhan approved these changes

2018-09-24 16:57 UTC, merged

2018-09-26 05:52 UTC, fbehrens commented
Thanks for merging :)

2018-09-26 05:56 UTC, iSazonov commented
@fbehrens Thanks for your contribution!