Updating ModulePath.Tests for fxdependent package
PowerShell/PowerShell pull request #7772
Opened 2018-09-12 20:56 UTC by anmenaga

## PR Summary

It turns out that some tests rely on having 'pwsh' executable for starting powershell.
This is not the case when framework dependent 'fxdependent' package is used (in which case PS is started by command like `dotnet /opt/microsoft/powershell/pwsh.dll`.

Specifically ModulePath.Tests are used in package validation before every PS release and failures in them block testing fxdependent package that we are adding.

The fix is to skip failing tests that rely on 'pwsh' executable in testing fxdependent package.
A better fix would be to add a generic test utility function that returns proper PS starting command based on environment where Pester runs. But since current failures are blocking package validation, we can add this utility function later (I'll open an test issue to track this).

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-09-12 21:05 UTC, adityapatwardhan requested changes

2018-09-12 21:05 UTC, adityapatwardhan commented on test/powershell/engine/Module/ModulePath.Tests.ps1
> +        if ( -not (Test-Path $powershell))
this can be 

```PowerShell
$skipNoPwsh = -not (Test-Path $powershell)
```

2018-09-12 21:15 UTC, anmenaga commented on test/powershell/engine/Module/ModulePath.Tests.ps1
> +        if ( -not (Test-Path $powershell))
Updated.

2018-09-13 04:30 UTC, iSazonov approved these changes

2018-09-17 17:14 UTC, adityapatwardhan approved these changes

2018-09-17 20:22 UTC, merged