Improve Send-MailMessage tests
PowerShell/PowerShell pull request #7793
Opened 2018-09-15 18:56 UTC by ThreeFive-O

## PR Summary

Use newer Pester syntax on Send-MailMessage cmdlet tests:

- Use Pester test cases
- Add logic to store current mailbox content before running tests
- Refactoring of code

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-09-24 16:50 UTC, adityapatwardhan requested changes

2018-09-24 16:50 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1
> +}
Please add a newline between these lines.

2018-09-24 16:51 UTC, adityapatwardhan commented
@ThreeFive-O It seems that the test is marked as pending on Linux. Is that expected?

I would prefer not to have a different name when the test is pending versus when it succeeds. This help in tracking history of tests.

2018-09-25 17:29 UTC, ThreeFive-O commented
@adityapatwardhan I can't really see the full output of the PowerShell-CI-linux test run from Pester. The test should only be marked as pending, if no SMTP server is available on the CI or if the user password can't be retrieved from /etc/password.
It's the same logic as the old test. Do you have any information if the PowerShell-CI-linux hosts a local Postfix SMTP server?

2018-09-25 20:53 UTC, adityapatwardhan commented
@ThreeFive-O You can go to logs and see that both tests are marked as pending:

`
2018-09-15T19:08:37.4876307Z   Describing Send-MailMessage
`
`
2018-09-15T19:08:37.5576199Z ??
`

If there are not running on Linux-CI then maybe add more logging with `Write-Verbose -Verbose` for the reason on skipping.

@TravisEz13  would the following work on Linux-CI hosts?

```PowerShell
$tc = New-Object -TypeName System.Net.Sockets.TcpClient -ArgumentList "localhost", 25
```

2018-09-26 00:57 UTC, TravisEz13 commented
It would only work if a mail host has been installed.

2018-09-28 15:56 UTC, ThreeFive-O commented
I think that explains why the test is marked as pending. The daily build of the master branch is also marked as pending:
```
2018-09-28T10:15:30.5317964Z   Describing Basic Send-MailMessage tests
2018-09-28T10:15:30.6222472Z ??
```
@TravisEz13 and @adityapatwardhan How should we proceed? Make another PR which installs Postfix mail server on the PowerShell-CI-Linux? Honestly I'm not very familiar with that.

On the other hand I'm working on a solution for #3950. But this is time-consuming, given the fact I want to enhance the test for the cmdlet first.

2018-10-10 19:15 UTC, anmenaga commented
@TravisEz13 @adityapatwardhan please provide your feedback on questions in the last post.

2018-10-10 20:39 UTC, TravisEz13 commented
I would recommend adding a setup script for postfix and adding a step to the linux.yml to install it.  Detect if it's there and skip the test if it's not there.  This would give us the most flexibility.

2018-11-21 08:01 UTC, closed without merging

2019-02-12 12:36 UTC, ThreeFive-O commented
Superseded by PR #8859