Change default of `Start-PSBuild` to include `-PSModuleRestore`
PowerShell/PowerShell pull request #7881
Opened 2018-09-27 20:40 UTC by SteveL-MSFT

## PR Summary

Most of the time when building PowerShell privately to validate a fix, it is desirable to include the modules that normally ship with PowerShell Core.  Without explicitly setting `-PSModuleRestore` you'll immediately notice that PSReadLine is not there so you do another build with that switch.  This change makes `-PSModuleRestore` default adding a `-NoPSModuleRestore` for cases where you don't want the modules.  The `-PSModuleRestore` switch is retained for compatibility reasons.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-09-27 20:49 UTC, adityapatwardhan approved these changes

2018-09-28 05:20 UTC, iSazonov approved these changes

2018-10-01 20:27 UTC, TravisEz13 commented on build.psm1
> +    if (!$NoPSModuleRestore)
This should only be done for the default parameter set

2018-10-01 20:31 UTC, TravisEz13 commented on build.psm1
> +    if (!$NoPSModuleRestore)
It'll do the wrong thing for `-PSModuleRestore:$false` or equivalent

2018-10-01 20:31 UTC, TravisEz13 requested changes
see comments

2018-10-01 21:12 UTC, TravisEz13 approved these changes

2018-10-03 19:49 UTC, merged