Update README.md
PowerShell/PowerShell pull request #7952
Opened 2018-10-05 17:11 UTC by razinc

+ Advantages of Using PowerShell

2018-10-23 20:38 UTC, joeyaiello requested changes
I'm actually surprised these "Learning PowerShell" docs are still here. Ideally, all of this content should be moved to PowerShell/PowerShell-Docs (possibly somewhere like [here](https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6)

In the meantime, I'd rather not continue to add to these (rather, we should subtract and push it over to docs.microsoft.com)

2018-11-01 09:50 UTC, iSazonov commented
@SteveL-MSFT Who can address the @joeyaiello request? I think we should close the PR.

2019-01-06 12:03 UTC, iSazonov commented
@joeyaiello Please update your review.

2019-01-25 23:54 UTC, TravisEz13 commented on docs/learning-powershell/README.md
> +Advantages of Using PowerShell
@razinc 	or @RDIL 	

Could you clean up this file with markdownlint?

The rules are in the root of the repo.  There is a Visual Studio code extension for markdown lint which works well if you open from the root of the repo.

2019-01-26 08:00 UTC, iSazonov commented
I'd remove the file and add a reference on new docs to root readme.md.

2019-02-25 20:00 UTC, iSazonov commented
@joeyaiello @SteveL-MSFT What is conclusion for the PR?

2019-03-27 20:41 UTC, RDIL commented
@SteveL-MSFT @HemantMahawar @joeyaiello ?

2019-03-27 21:26 UTC, TravisEz13 commented
This doc should be migrated.  See https://github.com/PowerShell/PowerShell/pull/7952#issuecomment-457776829

2019-05-06 22:21 UTC, closed without merging