Allow root node of format.ps1xml to have attributes that are ignored
PowerShell/PowerShell pull request #7987
Opened 2018-10-10 20:54 UTC by SteveL-MSFT

## PR Summary

Currently, if a format.ps1xml file has attributes on the `<Configuration>` node, it is a terminating error.  We should allow for loose validation so that common attributes from other tooling is simply ignored if not understood.  @PowerShell/powershell-committee had discussed this and agreed with making this change.

Types.ps1xml doesn't have this strict validation so no change was needed, but added tests for both format and types ps1xml.

Also removed `Pending` from a test that passes.

Address one aspect of #7749

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-10-10 21:14 UTC, anmenaga approved these changes
LGTM

2018-10-11 02:29 UTC, SteveL-MSFT commented
Figured out cause of test failure, but not sure why yet.  A different test is updating formatdata with invalid ps1xml.  Somehow, this causes importing of some (but not all) modules to fail complaining about the invalid ps1xml file.  Can repro it manually with 6.1.0 without my change so my change is unrelated, but looks like a real bug.  Investigating further.

2018-10-11 03:02 UTC, SteveL-MSFT commented
It appears the problem is that the invalid format ps1xml still gets into the formattable of the session so when importing a module that has a format.ps1xml it fails to update due to the previously bad format.ps1xml file still being cached.

2018-10-11 05:11 UTC, SteveL-MSFT commented
@anmenaga can you re-review?  Had to make additional fixes due to CI test failures

2018-10-11 20:06 UTC, anmenaga commented
Looks good to me.

2018-10-11 20:07 UTC, anmenaga commented
@adityapatwardhan this contains fix for CI failures. Please give this PR a priority.

2018-10-11 21:02 UTC, adityapatwardhan requested changes

2018-10-11 22:11 UTC, SteveL-MSFT commented
I'll submit the test-connection test fix as separate PR since it's affecting other PRs

2018-10-11 23:57 UTC, adityapatwardhan commented
@SteveL-MSFT now that the test CI fix is merge, please remove the fix in this PR.

2018-10-12 17:59 UTC, SteveL-MSFT commented
@adityapatwardhan can you update your review?

2018-10-12 18:04 UTC, adityapatwardhan approved these changes

2018-10-12 18:31 UTC, merged