Added Learn Windows PowerShell' in a Month of Lunches
PowerShell/PowerShell pull request #8067
Opened 2018-10-18 14:28 UTC by tobvil

Added one of the most popular PowerShell books 'Learn Windows PowerShell in a Month of Lunches' by Donald W. Jones and Jeffrey Hicks

## PR Summary

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-10-18 14:36 UTC, lassehastrup commented
Great add! Also the book that got me started with PowerShell!

2018-10-19 00:50 UTC, TravisEz13 approved these changes

2018-10-19 00:54 UTC, TravisEz13 commented
There is a duplicate PR:  https://github.com/PowerShell/PowerShell/pull/8041

2018-10-19 05:20 UTC, SteveL-MSFT submitted a review, later dismissed
LGTM

2018-10-19 08:15 UTC, tobvil commented
The PR: #8041 references the 2nd edition of the book. The 3rd is the edition in this PR is the newest edition of the book.

2018-10-19 19:43 UTC, adityapatwardhan requested changes

2018-10-19 19:43 UTC, adityapatwardhan commented on docs/learning-powershell/README.md
> +- [Learn Windows PowerShell in a Month of Lunches](https://www.amazon.com/Learn-Windows-PowerShell-Month-Lunches/dp/1617294160) by Don Jones and Jeffrey Hicks
I would like the same pattern. Please move the URL below as others.

2018-10-23 18:33 UTC, adityapatwardhan approved these changes

2018-10-23 18:34 UTC, merged