Avoid file deletion in Start-Transcript when not appending
PowerShell/PowerShell pull request #8131
Opened 2018-10-26 13:08 UTC by paalbra

## PR Summary

Currently Start-Transcript will delete the file it refers to if it's not set to append. This might lead to issues if the user running the command only has access to the file and not the parent folder. This PR makes sure the file is emptied rather than deleted. There are more details in the issue. Fix #4065. 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

## P.S.

This is my first PR in this project. I'm hopefully doing things right...

2018-10-27 10:44 UTC, iSazonov commented
My understanding is that currently we write an error and remove the file. Your suggestion is  don'nt remove the file but wipe. Right?

/cc @mklement0 What do you think about the special case?

2018-10-27 11:44 UTC, paalbra commented
> My understanding is that currently we write an error and remove the file. Your suggestion is don'nt remove the file but wipe. Right?

Well, kind of. The file is deleted and when Start-Transcript tries to recreate the file you get an access denied error (if the access is set in a way mentioned in #4065 ). But it is a bit OS/filesystem dependent.

This can be avoided by not deleting the file, but rather wiping it.

The fix should not alter the behavior of successful usage of Start-Transcript, but it will fix this special access case.

2018-10-27 18:46 UTC, mklement0 commented
I too agree that we shouldn't special-case this:

`Start-Tanscript` makes no promises about preexisting files; it blindly tries to replace them, and always creates the new files with the default permissions.

In other words: loss of any preexisting file with the same name is always to be expected and no relationship between the old and the new file can and should be assumed.

That creation of a _new_ file then fails, is a separate issue, and requires that the permissions be set accordingly on the enclosing directory to allow file creation by the current user - which strikes me as reasonable.

@paalbra: Your scenario sounds exotic and the steps to reproduce it (as shown in #4065) are quite involved. Is this a real-life scenario you've run into, and why would you expect to run into this repeatedly?

2018-10-28 04:54 UTC, iSazonov commented
@mklement0 Thanks!

@SteveL-MSFT Please confirm that current behavior is "by-design" and we can not accept the PR.

2018-10-28 18:42 UTC, paalbra commented
Yes, I've run into this issue in my real-life environment. I don't view this issue as a special or exotic case myself.

You could even compare this to Out-File which also has an Append parameter. Out-File has no issues with the same access permissions set because Out-File doesn't delete the file. I would expect both commands to work in this setup and this is what I try to fix with this PR.

2018-10-28 18:50 UTC, SteveL-MSFT commented
@paalbra I appreciate you bringing up this inconsistent experience and taking the time to submit a PR, however, we need to balance changes with impact to backwards compatibility.  In this specific case, it seems the current behavior is documented so it's not a strong enough justification to change the current behavior.  (I'm always open to reconsidering if there's sufficient community feedback)

2018-10-28 18:51 UTC, paalbra commented
With the current behavior you also have other bad side effects. E.g. you can't point Start-Transcript to a symlink. If you do Start-Transcript will just delete the symlink and create a file.

There is simply no reason for Start-Transcript to delete the file. I should just overwrite the file. This is also what it says that it does in the documentation. Overwriting a file is not the same as recreating a file. So I think the current documentation and behavior don't match.

2018-10-28 18:56 UTC, paalbra commented
I really can't agree that the behavior is the same as the documentation.

Again you could compare Start-Transcript and Out-File. They both have similar documentation when it comes to Append and NoClobber, but they do not behave the same way.

2018-10-28 18:57 UTC, mklement0 commented
@paalbra: 

I see your point now: `Out-File` (without `-Append`)  / `>` and `Set-Content` indeed open a preexisting file and _truncate_ it before writing the new content.
`>` in POSIX-like shells works the same.

In light of this, I think your PR has merit.

@SteveL-MSFT: 

Unless I'm missing something, I think this PR would be an easy consistency improvement that shouldn't impact existing scripts.

2018-10-28 22:41 UTC, SteveL-MSFT commented
@paalbra I misunderstood the intent, but thanks to @mklement0 I get it.  Based on the explanation, I would agree that this PR makes sense particularly in the symlink case.

2018-10-28 22:43 UTC, SteveL-MSFT commented
@paalbra it would be great if you can add a test for this specific behavior.  You can probably just check the file creation date hasn't changed.

2018-10-29 10:19 UTC, paalbra commented
@SteveL-MSFT I'm not very familiar with the project yet, since this is my first PR, but I'll certainly look into adding more tests.

2018-10-29 13:33 UTC, iSazonov commented
@paalbra  Test is here https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.Powershell.Host/Start-Transcript.Tests.ps1

2018-10-29 15:07 UTC, SteveL-MSFT commented
@paalbra Just give it a try and we'll make suggestions :)

2018-10-29 22:30 UTC, paalbra commented
A bit more of searching the web led me to the [FileSystemWatcher ](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=netframework-4.7.2) class.

I guess I could use one of those and make a test that makes sure no file deletion events are emitted when running Start-Transcript. This seems a bit excessive to me though. Any thoughts?

2018-10-29 22:49 UTC, SteveL-MSFT commented
@paalbra Thanks for making the effort.  I agree that using FileSystemWatcher is overkill for this.  I suspect you can't reply on the `CreationTime` because the filesystem or disk driver hasn't flushed it before the write happens within that window.  Another option (on Windows, perhaps skip on non-Windows) is to remove `Delete` permission from that file and check that no error is returned (see `Set-Acl`)

2018-10-30 17:01 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=8131) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=8131) before we can accept your contribution.<br/><br/>:x: paalbra [sign now](https://cla.opensource.microsoft.com/PowerShell/PowerShell?pullRequest=8131)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/PowerShell/PowerShell?pullRequest=8131) it.</sub>

2018-10-30 18:00 UTC, paalbra commented
I decided to try the FileSystemWatcher path since I got it working on Windows and Ubuntu (the test is failing in master and passing in my branch).

But for some reason it's failing on MacOS. I'm really not sure why and I currently have no Mac available for debugging. I'll try to get my hands on a Mac some day soon though...

2018-10-30 18:30 UTC, SteveL-MSFT commented
@paalbra there may be an issue in CoreFx where the file on macOS is deleted or that the event is being incorrectly raised

2018-10-30 18:32 UTC, vexx32 commented
@paalbra looks like the file gets deleted on MacOS when you're not expecting it to, at least from the build logs:
```
2018-10-30T18:20:10.2962680Z TEST FAILURES
2018-10-30T18:20:10.2962740Z Description: Should not delete the file if it already exist
2018-10-30T18:20:10.2963680Z Name:        Start-Transcript, Stop-Transcript tests.Should not delete the file if it already exist
2018-10-30T18:20:10.2963770Z message:
2018-10-30T18:20:10.2964240Z Expected $null, but got 'FileDeleted'.
2018-10-30T18:20:10.2964700Z stack-trace:
2018-10-30T18:20:10.2965270Z at <ScriptBlock>, /Users/vsts/agent/2.141.1/work/1/s/test/powershell/Modules/Microsoft.Powershell.Host/Start-Transcript.Tests.ps1: line 127
2018-10-30T18:20:10.2965760Z 127:         Receive-Job $job | Should -Be $null
2018-10-30T18:20:10.2965830Z 1 tests in test/powershell failed
2018-10-30T18:20:10.2965890Z At /Users/vsts/agent/2.141.1/work/1/s/build.psm1:1347 char:13
2018-10-30T18:20:10.2966380Z +             throw "$($x.'test-results'.failures) tests in $TestArea f ...
2018-10-30T18:20:10.2966450Z +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-10-30T18:20:10.2966990Z + CategoryInfo          : OperationStopped: (1 tests in test/powershell failed:String) [], RuntimeException
2018-10-30T18:20:10.2967050Z + FullyQualifiedErrorId : 1 tests in test/powershell failed
```

2018-10-30 19:46 UTC, mklement0 commented
I have no explanation, but here's a data point: I just ran the test locally against this PR's code on my macOS 10.14 machine, and it succeeded in 100 successive invocations.

2018-10-31 04:49 UTC, iSazonov commented
How we open the file? If "Read shared" we could open the file twice and check its content by second handle.

2018-11-02 20:55 UTC, mklement0 commented
Interesting, @paalbra, but there's some consistency: I hadn't used the `test:` drive in my tests.

2018-11-02 22:51 UTC, SteveL-MSFT commented
Perhaps to help isolate if this is a `$TestDrive` issue or something due to PSDrives, can you try creating a PSDrive and see if you still get delete events?

> New-PSDrive -PSProvider FileSystem -Name MyTestDrive -Root $env:TMPDIR

2018-11-03 16:45 UTC, paalbra commented
Ok, so I've done some more testing. On MacOS the TestDrive doesn't seem to be "clean" between tests. Somehow the state/file deletion events "bleed through" from other tests. I've tried to resolve this by creating a new, unique path within my test and this seems to work. `$transcriptFilePath = Join-Path $TestDrive ([System.IO.Path]::GetRandomFileName())`

Any thoughts or feedback on this method?

2018-11-03 16:54 UTC, paalbra commented
I guess this is something you might want for all tests. So a better solution might be to create a new unique path in the `BeforeAll` block. I'm not sure I should touch that block in this PR though. It might be better to create this as an separate issue?

2018-11-03 18:07 UTC, mklement0 commented
I think creating a unique path for this PR is definitely the way to go.

My sense is that we needn't worry about the other tests, as they don't use file-system watchers.

It is curious that only macOS is affected, though. 

There are several open issues for the `FileSystemWatcher` type in the CoreFx repo, though only 
 one macOS-specific one and one cross-platform one: https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+filesystemwatcher++in%3Atitle

Another thing to try - though more out of curiosity, given that the use `[System.IO.Path]::GetRandomFileName()` seems like the best solution - is to call CLI `sync` beforehand, which commits pending disk writes system-wide - note that this can be expensive.

2018-11-03 19:10 UTC, SteveL-MSFT commented
@paalbra thanks for taking the time to investigate this.  My suggestion is for this PR to have the macOS specific code path (with appropriate comments).  Agree with @mklement0 that the other tests are probably ok although not ideal.  It may be worthwhile to see if `sync` helps which would indicate to me that this is an OS problem with caching.

2018-11-03 20:46 UTC, paalbra commented
Adding `sync` doesn't seem to help. I've also tried adding sleep like this:

```powershell
It "Should not delete the file if it already exist" {
    # Create an existing file
    #$transcriptFilePath = Join-Path $TestDrive ([System.IO.Path]::GetRandomFileName())
    Out-File $transcriptFilePath
    Start-Sleep -Seconds 20

    $FileSystemWatcher = [System.IO.FileSystemWatcher]::new((Split-Path -Parent $transcriptFilePath), (Split-Path -Leaf $transcriptFilePath))

    $Job = Register-ObjectEvent -InputObject $FileSystemWatcher -EventName "Deleted" -SourceIdentifier "FileDeleted" -Action {
        return "FileDeleted"
    }

    Start-Transcript -Path $transcriptFilePath
    Stop-Transcript

    Unregister-Event -SourceIdentifier "FileDeleted"

    # Nothing should have been returned by the FileSystemWatcher
    Receive-Job $job | Should -Be $null
}
```

The above actually makes the test pass on MacOS.

My guess is that the `FileSystemWatcher` receives some kind of old events. Maybe events from the previous `AfterEach` block where the file is removed.

I think the current solution, with unique file path, is the best for all OSes.

2018-11-06 06:24 UTC, iSazonov approved these changes

2018-11-06 19:07 UTC, SteveL-MSFT requested changes
Only need to address @iSazonov's comment on try..finally

2018-11-06 21:29 UTC, paalbra commented on test/powershell/Modules/Microsoft.Powershell.Host/Start-Transcript.Tests.ps1
> +        Unregister-Event -SourceIdentifier "FileDeleted"
I pushed a commit doing this now

2018-11-07 01:08 UTC, SteveL-MSFT approved these changes
LGTM . Thanks!

2018-11-07 03:34 UTC, merged

2018-11-07 03:35 UTC, iSazonov commented
@paalbra Thanks for your contribution!