Whitelist Az module for culture directory skipping
PowerShell/PowerShell pull request #8142
Opened 2018-10-29 18:27 UTC by rjmholt

## PR Summary

Fixes https://github.com/PowerShell/PowerShell/issues/8125.

Takes out the optimisation to skip directories named like cultures when listing modules. If we have a better way to preserve some of the performance benefits, I can happily implement!

Also generalised some of the test code a bit. Realised afterward that it wasn't as helpful as I thought, but it's done now at least. Commits are separate, so that can be dumped if we want.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [x] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

I haven't marked "Not Breaking" yet, since technically this is a change in outward behaviour. But I don't think this behaviour is documented and I doubt anyone knew about it let alone relied upon it. But want to leave that judgement for others to decide.

2018-10-29 20:50 UTC, anmenaga commented
Restarted `PowerShell-CI-linux` & `PowerShell-CI-macos` test runs.

2018-10-29 20:50 UTC, SteveL-MSFT commented
@rjmholt can you do a perf test on Windows to see if there's any noticeable degradation?

2018-10-30 01:46 UTC, lzybkr commented
IIRC, this was pretty important for performance. The culture directories sometimes have a bunch of `psd1` files which we analyze as a module manifest and bail when we realize they aren't.

Some options I can think of
1. Check the folder depth first, skipping the culture check only for folders immediately below a path in PSModulePath.
1. Process culture folders, but cache the "failure" somehow - messy and not helpful for first ever start, e.g. in a container
1. Whitelist `az`
1. Rename the `az` module

I'm curious, does the `az` module have localized resources for the `az` culture? It'd be good to test that works as well.

2018-10-30 04:13 UTC, vexx32 commented
Given the commonality of the `Az` module I wouldn't be surprised if someone else creates a module with a similarly-styled name, if one or more doesn't already exists. Folks tend to copy anything with any kind of an 'official' stamp on it, after all.

Whitelisting may be the simplest option for now, but unless we want to *forbid* future modules with such short names / folder names, is there a more elegant and generalisable solution available?

2018-10-30 05:16 UTC, rjmholt commented
Noted about the perf.

Two lines of questioning so I can try and understand the general problem better:
- Why does this "lots of culture dirs on the module path" phenomenon occur? Is it a specific other scenario/application that's using them? Why do they contain `psd1` files (and are they not PowerShell manifests)? Is any of this written up or coded anywhere?
- Is there an example anyone has of such a directory that has both modules and culture dirs I could look at?

2018-10-30 05:43 UTC, lzybkr commented
Does this just affect autoloading?

And what servicing 5.1?

2018-10-30 05:48 UTC, SteveL-MSFT commented
@lzybkr I don't believe this qualifies to service 5.1.  The Az module is still loaded and works, this only affects listing the loaded modules.

2018-10-30 05:50 UTC, rjmholt commented
@lzybkr The issue seems to be with `Get-Module -ListAvailable` (see https://github.com/Azure/azure-powershell/issues/7563), although I wouldn't be surprised if that meant there are issues elsewhere.

2018-10-30 19:48 UTC, lzybkr commented
It is unlikely I would have added that code to make `Get-Module -ListAvailable` faster, I was focused on first ever PowerShell startup when that code was written.

I'm pretty sure that code is called during module analysis for module auto-loading.

2018-10-30 20:22 UTC, rjmholt commented
Ok, I'm personally leaning toward whitelisting just `Az` at the moment, although I'm not a huge fan of hardcoding it.

2018-10-31 02:53 UTC, rjmholt commented
I've implemented a whitelist. I've left a note on the whitelist describing a workaround for other modules in future if needed.

2018-10-31 16:59 UTC, adityapatwardhan commented
@rjmholt  Please have a look at CodeFactor issue.

2018-10-31 16:59 UTC, adityapatwardhan commented
Restarted CI for pick up build failure test fix.

2018-10-31 18:55 UTC, SteveL-MSFT requested changes

2018-10-31 18:55 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/Modules/ModuleUtils.cs
> +            "Az"
Perhaps add a comment that this is for the Azure PowerShell module

2018-10-31 18:55 UTC, SteveL-MSFT commented on src/System.Management.Automation/engine/Modules/ModuleUtils.cs
> +        private static readonly HashSet<string> ModuleNameCultureWhitelist = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
I think for private members you should still use the underscore prefix

2018-10-31 20:08 UTC, SteveL-MSFT approved these changes

2018-10-31 21:21 UTC, lzybkr commented
The `s_` prefix was introduced when running the Roslyn code formatter and it seems to still be used heavily, so I'm not sure why Code Factor wins out on this one.

2018-10-31 22:31 UTC, rjmholt commented
I also like (*prefer*) `s_`. I find it very informative, we use it everywhere, and it meshes nicely with `_` for non-static Private.

2018-10-31 23:46 UTC, vexx32 commented
Maybe we ought to add a StyleCop exemption for this sort of thing? I've run into it before as well.

2018-11-01 03:06 UTC, SteveL-MSFT commented
I believe CodeFactor is using the [StyleCop](https://github.com/PowerShell/PowerShell/blob/53e6ec6eadc2f363fc671e96b34ade4dda3fe8eb/Settings.StyleCop) rules we've set.  I'm ok with changing the rules to allow for `s_`.  My main desire is to have consistency so if most of the code is using `s_` we should adopt that.

2018-11-01 06:45 UTC, iSazonov commented
@rjmholt Please use `s_` and we'll look which rules we should fix.

2018-11-02 17:41 UTC, rjmholt commented
Thanks @iSazonov!

2018-11-02 20:33 UTC, anmenaga commented
Restarted appveyor test pass for WebListener failure.

2018-11-05 22:09 UTC, rjmholt commented
Only remaining checks are the CodeFactor rules we agreed to ignore.

2018-11-06 06:15 UTC, iSazonov commented
Because of we do `new CultureInfo(dir)`  my suggestion is to use on-demand cache for GetCultureInfo() (we could reuse it in Get-Culture cmdlet and vise versa) and then build a HashSet for culture names.  

@mklement0 Could you please look the PR? Again cultureinfo is here :-)

2018-11-06 11:21 UTC, kilasuit commented
Sorry but this is an absolutely atrocious Idea and IMO should not be merged.

Please stop putting bandaids around actual problems that will then lead to further issues down the line.

At the end of the day the AzureRM PowerShell team found this issue with their wise minds to change their module name in the first place, and is inherently their issue, and whilst this issue affects any module with 2 chars for the name this is not the correct long term fix to implement


@lzybkr first suggestion is a much better suggestion for the longer term and that should be the one that is favoured especially for those that may want an `IT` Module or an `EN` module in future.

2018-11-06 15:58 UTC, lzybkr commented
In case it wasn't clear, my list was ordered by my preference.

2018-11-06 17:09 UTC, rjmholt commented
Ok, I'll see if I can rework this to account for depth. The problem I imagine might occur there is with nested modules, particularly in `Get-Module -ListAvailable -All`.

The caching idea doesn't help the performance scenario this optimisation was introduced to help I don't think, so going that route would mean a fair amount of complexity to do something slightly better than just removing the optimisation.

The whitelist option at least means you can always fix the problem by adding to the whitelist. In this situation, everything is a bandaid, but only one of the solutions is an expandable bandaid. But I agree that it's far from ideal.

@kilasuit FWIW putting your criticism more constructively would be appreciated. Comments in these repos can get heated, and seeing them every day they can start to add up.

2018-11-06 17:41 UTC, iSazonov commented
@rjmholt Why you think that culture name caching doesn't help?
Please look all culture name formats with `[cultureinfo]::GetCultures(0xf)`. There is names like `sr-Latn-RS`, `sms-FI`, `vo-001`, `zgh`. Seems a cache would be more simple and faster then a parser or regex.

2018-11-06 18:02 UTC, rjmholt commented
The caching only comes *after* a module has determined to be a module. At first run, you have to read *every* directory and only add them to the cache if they are both (1) a module and (2) a culture name. 

The cache will slow down first startup and speed up later runs. But the whole culture name skip optimisation was made to improve startup time. So going the cache route will undo the original optimisation scenario.

There's nothing wrong with the idea though -- it's probably worth adding.

2018-11-07 03:28 UTC, iSazonov commented
My suggestion is to filter directories here https://github.com/PowerShell/PowerShell/blob/4f8814031bf7c4c13bf04c376565a077ca9be2fd/src/System.Management.Automation/engine/Modules/ModuleUtils.cs#L90
Also we could use predefined culture name list (without call GetCultures() at start time because the list is changed rarely.
And we could use DirectoryInfo/FileInfo classes to exclude extra kernel calls if we want increase startup performance.

2018-11-12 19:10 UTC, adityapatwardhan commented
@rjmholt Please resolve merge conflict.

2018-11-13 17:24 UTC, lzybkr commented
@daxian-dbw - that could still require enumerating many files which isn't always fast. I think the depth check is perfectly reasonable.

2018-11-13 17:34 UTC, daxian-dbw commented
> that could still require enumerating many files which isn't always fast.

@lzybkr Totally agree.
@rjmholt's concern on the depth check is when `-All` is specified. In that case, we want to find all modules nested in a module folder, where we will need to check the `az` folder under a module folder, and the depth check is not sufficient anymore. I admit that `-All` is not commonly used, but since we want to have a general fix, I guess we need to take that switch into account as well.

2018-11-13 17:57 UTC, lzybkr commented
Does `-All` even work? I tried it in Windows PowerShell saw no results for as long as I was willing to wait.

2018-11-13 18:31 UTC, vexx32 commented
Yep. 

Takes about 1.5x as long as PowerShell 6.1, but Windows PowerShell does work. Both of them successfully listed all modules with `Get-Module -List -All`

2018-11-13 19:12 UTC, mklement0 commented
To perhaps offer a solution for future modules:

We could add support for placing localization folders in a dedicated subfolder of a module's root folder with a then-reserved name (the introduction of which can in itself be problematic), such as `Resources`.

Modules written for that new convention then wouldn't have the ambiguity problem, and the presence of the reserved folder would mean that everything else can assumed to be non-localization folders.

If there are concerns about folder-hierarchy depth / path length, the suboptimal alternative would be a reserved folder-name extension, the way that macOS uses `.lproj`, for instance (though the `.app` bundles there _also_ use a `Resources` subfolder).

2018-11-13 19:18 UTC, rjmholt commented
@mklement0 +1 on dedicated folder (or a manifest configuration to avoid being opinionated, but that's a backcompat breaker I suppose). A similar implementation detail to this one [lead to dotfiles on UNIX](https://plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp) and the official solution is to have a [standard directory/location for those files](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

2018-11-14 04:56 UTC, iSazonov commented
I see that _CoreFX_ files is placed in locale folders. Currently it is Microsoft.CodeAnalysis*.

2018-11-28 18:57 UTC, adityapatwardhan commented
@rjmholt Please have a look at the merge conflict.

2018-12-19 19:17 UTC, closed without merging

2018-12-20 19:07 UTC, rjmholt commented
> @rjmholt Robert Holt FTE Could you indicate the reason for closing?

We haven't settled on an implementation and this branch is stale.

It will be easier to open a new PR with a minimal change I think.