removed duplicating parts from license file
PowerShell/PowerShell pull request #8143
Opened 2018-10-29 18:44 UTC by azkarmoulana

All rights reserved had been duplicated in the license file and removed duplicating one necessarily

2018-10-30 16:44 UTC, SteveL-MSFT requested changes

2018-10-30 16:44 UTC, SteveL-MSFT commented on LICENSE.txt
> -Copyright (c) Microsoft Corporation. All rights reserved.
If we follow the copyright text in other files, we should keep this one here and remove line 5.

2018-10-30 16:44 UTC, SteveL-MSFT commented on LICENSE.txt
> +THIRD PARTY AND OTHER SOFTWARE, WHICH ARE SET FORTH IN ThirdPartyNotices.txt
This line should not be removed

2018-10-30 17:04 UTC, azkarmoulana commented on LICENSE.txt
> +THIRD PARTY AND OTHER SOFTWARE, WHICH ARE SET FORTH IN ThirdPartyNotices.txt
@SteveL-MSFT changes done

2018-10-30 23:46 UTC, SteveL-MSFT approved these changes
LGTM.  Thanks for the contribution!

2018-10-31 00:20 UTC, TravisEz13 approved these changes

2018-10-31 00:20 UTC, merged