Change default issue template to use different categories
PowerShell/PowerShell pull request #8203
Opened 2018-11-07 22:12 UTC by SteveL-MSFT

## PR Summary

Leverage GitHub ability to have multiple options when user clicks "New Issue" to have better issues opened and direct users to Docs repo and UserVoice for Windows PowerShell issues.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-11-07 22:14 UTC, TravisEz13 approved these changes

2018-11-07 23:57 UTC, anmenaga commented on .github/ISSUE_TEMPLATE/Bug_Report.md
>  You can install the latest version from https://github.com/PowerShell/PowerShell/releases
Lines 13-14 are about the same thing.
Probably make 'latest released version' in line 13 a hyperlink with url from line 14; and remove line 14.

2018-11-07 23:57 UTC, anmenaga commented on .github/ISSUE_TEMPLATE/Documentation_Issue.md
> +Please open documentation issues that is not specifically for documentation within the
`is` -> `are`

2018-11-14 21:55 UTC, joeyaiello commented on .github/ISSUE_TEMPLATE/Support_Question.md
> +about: If you have a question, you can try asking in the PowerShell Slack channel first.
```suggestion
about: If you have a question, you can try asking in the PowerShell Slack channel first. If you need official support, refer to the [PowerShell Support Lifecycle](http://aka.ms/pslifecycle)
```

2018-11-14 21:56 UTC, joeyaiello commented on .github/ISSUE_TEMPLATE/Support_Question.md
> +# Community Resources
```suggestion
# Support Question

## Official support

[PowerShell Support Lifecycle](http://aka.ms/pslifecycle)

## Community Resources
```

2018-11-14 21:57 UTC, joeyaiello commented on .github/ISSUE_TEMPLATE/Windows_PowerShell.md
> +about: Windows PowerShell issues/suggestions need to be reported to UserVoice
```suggestion
about: Windows PowerShell issues/suggestions need to be reported to [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)
```

2018-11-14 22:36 UTC, joeyaiello requested changes
Changes are single comments

2018-11-14 22:37 UTC, joeyaiello approved these changes

2018-11-15 01:32 UTC, SteveL-MSFT commented
@TravisEz13 this is ready to be merged

2018-11-16 18:17 UTC, TravisEz13 approved these changes

2018-11-16 18:18 UTC, merged