Remove workaround for fixed invalid json array deserializing bug
PowerShell/PowerShell pull request #8346
Opened 2018-11-28 09:33 UTC by louistio

## PR Summary

This PR removes a workaround that was added because of a bug in the underlying json deserializing library [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json).

It is no longer required as [the bug](https://github.com/JamesNK/Newtonsoft.Json/issues/1321) has been fixed in [Newtonsoft.Json 10.0.3](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/10.0.3), see fix [here](https://github.com/JamesNK/Newtonsoft.Json/commit/1a0ae2a42ddd69f2584424731ae3212363a2bd5c).

This workaround was added in #3823 and involves using a regex to detect a json array and calling `JArray.Parse` before deserialization to throw an exception on an invalid array. As a result, removing it will increase `ConvertFrom-Json` & `Invoke-RestMethod` performance. 

### Current behavior
```powershell
PS D:\> ConvertFrom-Json '["1",'
ConvertFrom-Json : Conversion from JSON failed with error: Unexpected end of content while loading JArray. Path '[0]', line 1, position 5.
At line:1 char:1
+ ConvertFrom-Json '["1",'
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

### After workaround removal
```powershell
PS D:\> ConvertFrom-Json '["1",'
ConvertFrom-Json : Conversion from JSON failed with error: Unexpected end when reading token. Path ''.
At line:1 char:1
+ ConvertFrom-Json '["1",'
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively

2018-11-28 23:19 UTC, PaulHigin requested changes
Please add a test to ensure the expected exception is thrown on invalid array.

2018-11-29 02:15 UTC, louistio commented
@PaulHigin done!

2018-11-29 12:17 UTC, iSazonov approved these changes

2018-11-29 17:04 UTC, PaulHigin approved these changes
LGTM

2018-11-30 11:49 UTC, merged

2018-11-30 11:49 UTC, iSazonov commented
@louistio Thanks for your contribution!

2018-11-30 20:15 UTC, daxian-dbw commented
It looks to me this PR causes the following feature-level test to fail:
https://github.com/PowerShell/PowerShell/blob/3794a5e39f31ebacfc2ec2e9ad687c9bf3772cba/test/powershell/Modules/Microsoft.PowerShell.Utility/Pester.Commands.Cmdlets.Json.Tests.ps1#L1446-L1459

This PR didn't have [feature] tag in commit message, so the feature-level tests didn't run.

2018-11-30 20:56 UTC, TravisEz13 commented
We already had feature tests for this case and they are failing after the removal of the workaround.  I'm reverting the change.

2018-11-30 22:05 UTC, louistio commented
I'm sorry about this inconvenience, I was not aware of the existence of this particular test and should have been.

I debugged this issue locally as soon as I could, the new error is caused by yet another `Newtonsoft.Json` bug, which I have reported to their repository [here](https://github.com/JamesNK/Newtonsoft.Json/issues/1930).

Sorry again.

2018-12-01 00:44 UTC, TravisEz13 commented
@louistio 	No problem, things happen.  To automatically run the tests, prefix the last commit with `[feature]`.
I would be nice if the fix actually covered the scenario.

2018-12-01 09:02 UTC, iSazonov commented
Oh, seems we need re-pack our tests or at least update the code comment. @louistio Could you please make PR and update the comment with new information?