Remove dependabot attribution and generate changelog sections using `CL-*` labels
PowerShell/PowerShell pull request #8386
Opened 2018-12-03 20:35 UTC by adityapatwardhan

## PR Summary

* Remove dependabot attribution from change log.
* Create sections in generated change log using the `CL-*` labels.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-12-03 21:31 UTC, PaulHigin requested changes

2018-12-03 21:31 UTC, PaulHigin commented on tools/releaseTools.psm1
> +    $unlabeledPRs = @()
Please add comments explaining each array object.

2018-12-03 21:31 UTC, PaulHigin commented on tools/releaseTools.psm1
> +        Write-Error "PRs should be tagged with multiple CL labels. PRs with multiple labels: $($multipleLabelsPRs.number -join ' ')"
"... should **not** be tagged..."

2018-12-03 21:31 UTC, PaulHigin commented on tools/releaseTools.psm1
> +        Write-Error "PRs should at least one CL label. PRs missing labels: $($unlabeledPRs.number -join ' ')"
"... should **have** at least one..."

2018-12-03 21:35 UTC, adityapatwardhan commented on tools/releaseTools.psm1
> +        Write-Error "PRs should be tagged with multiple CL labels. PRs with multiple labels: $($multipleLabelsPRs.number -join ' ')"
Good catch :)

2018-12-03 21:40 UTC, adityapatwardhan commented on tools/releaseTools.psm1
> +        Write-Error "PRs should at least one CL label. PRs missing labels: $($unlabeledPRs.number -join ' ')"
Fixed.

2018-12-03 21:41 UTC, adityapatwardhan commented
@PaulHigin I updated the PRs, please have another look.

2018-12-03 22:17 UTC, TravisEz13 approved these changes

2018-12-03 22:19 UTC, TravisEz13 commented on tools/releaseTools.psm1
> +#requires -Version 6.0
Our guidance says the copyright has to be first... This is obviously a reasonable exception, but should we update the guidance?

2018-12-03 22:32 UTC, PaulHigin approved these changes
LGTM

2018-12-03 22:34 UTC, merged

2018-12-04 03:43 UTC, iSazonov commented
How do we track unlabeled commits and reverted commits?