Change hashtable to use OrdinalIgnoreCase to be case-insensitive in all Cultures
PowerShell/PowerShell pull request #8566
Opened 2018-12-31 02:43 UTC by SteveL-MSFT

## PR Summary

Ubuntu18.04 seems to default to `C.UTF-8` for LANG (representing InvariantCulture) which results in a case-sensitive hashtable since CurrentCultureIgnoreCase doesn't work for that culture.  Fix is to use OrdinalIgnoreCase instead.

Fix https://github.com/PowerShell/PowerShell/issues/7761

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2018-12-31 03:35 UTC, lzybkr commented
I'm pretty sure this is a breaking change.

2018-12-31 07:45 UTC, iSazonov commented
> Ubuntu18.04 seems to default to C.UTF-8 for LANG (representing InvariantCulture)

Could you please reference where it come from and why?

Is there other cultures like `C.UTF-8` on Unix and Windows with the problem?

2018-12-31 08:08 UTC, SteveL-MSFT commented
@iSazonov read the details in the related issue

2018-12-31 13:21 UTC, ffeldhaus commented
@iSazonov In my opinion this pull request correctly fixes the issue described in #7761 and we should keep wider discussion of changing other culture-insensitive in other places out of this pull request.

As this is a serious issue in a core functionality (Hashtable) and as it is present on the default culture of Ubuntu 18.04 (C.utf8) and thus exposed to a large number of users in my opinion this should be merged with high priority and backport to 6.1.X and 6.0.X.

2018-12-31 13:49 UTC, iSazonov commented
My request is not to block the PR. My fear is that there may be other places prone to this problem. This analysis may be useful for fixing other issues.

2018-12-31 17:56 UTC, ffeldhaus requested changes
Issues also affects Mac OS, so test should run on Mac OS as well.

2018-12-31 17:56 UTC, ffeldhaus commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +    It "When LANG is C.UTF-8" -Skip:(!$IsLinux) {
The issue affects Mac OS X as well, so please change to
```suggestion
    It "When LANG is C.UTF-8" -Skip:($IsWindows) {
```

2019-01-01 23:05 UTC, bergmeister approved these changes
Looks good to me, only a minor, optional suggestion to improve readability of the test :)

2019-01-01 23:05 UTC, bergmeister commented on test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
> +        sh -c 'LANG=C.UTF-8 pwsh -c ''$h=@{h=1};$h.H''' | Should -Be 1
Minor nit: using the `-command` parameter on `pwsh` would be slightly more readable and using a different letter for the hashtable property.
```suggestion
        sh -c 'LANG=C.UTF-8 pwsh -command ''$h=@{p=1};$h.P''' | Should -Be 1
```

2019-01-02 14:38 UTC, ffeldhaus approved these changes
Addresses the issue and test is good as well now!

2019-01-08 00:52 UTC, anmenaga approved these changes

2019-01-09 23:06 UTC, SteveL-MSFT commented
@PowerShell/powershell-committee reviewed this and agrees to take this change as the intention was to always have Hashtable keys case-insensitive

2019-01-10 04:11 UTC, merged

2019-01-16 23:36 UTC, TravisEz13 commented
@iSazonov 	Only one `CL-*` tag.  If it is a breaking change, don't put it in one of the others.

2019-02-02 22:53 UTC, adamedx commented
Wow, thank you for fixing this. I am new to PowerShell Core and using it on Linux, and it seemed that this was intentional. I sent a lot of time fixing the casing of my hash tables. I'm guessing this is also the issue I ran into with sort-object, which gives different results on Linux and Windows:
```powershell
PS> $PSVersionTable.Platform;('a', 'ab', 'aC' | Sort-Object ) -join ','
Win32NT
a,ab,aC
PS> $PSVersionTable.Platform;('a', 'ab', 'aC' | Sort-Object ) -join ','
Unix
a,aC,ab
```

2019-02-03 10:12 UTC, ffeldhaus commented
@adamedx I think it would be a good idea to track this in a separate issue and link it to #8064 where similar issues are being tracked.