Fix broken urls
PowerShell/PowerShell pull request #8653
Opened 2019-01-15 19:40 UTC by TravisEz13

## PR Summary

Fix broken URL
  - Also, move other static analysis tests into that CI.
  - Also, make the link analysis a pester test (partly to make sure the step fails in case of an error) 

## PR Context  

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2019-01-15 20:34 UTC, RDIL approved these changes
Looks good to me, also shouldn’t Azure DevOps have prevented you from using this same PR to check since you modified its tests?

2019-01-15 21:30 UTC, TravisEz13 commented
none of the CI systems, commonly available, I'm aware of are smart enough to block PRs that both change the tests and what they tests.  It's a hard problem and in most cases you wouldn't want to.

2019-01-15 21:44 UTC, RDIL commented
@TravisEz13 https://rdil.rocks/depression/ps-build-failure.png

2019-01-15 21:46 UTC, TravisEz13 commented
Yup, working on it.

2019-01-15 21:47 UTC, RDIL commented
👍

2019-01-15 21:59 UTC, RDIL commented
Just a suggestion: I would have it log if the file has no links so it doesn't look like the file was skipped over or something like that.

2019-01-15 22:04 UTC, TravisEz13 commented
I'll add a case like that which is logged when no results are returned.

2019-01-15 22:10 UTC, PaulHigin requested changes

2019-01-15 22:10 UTC, PaulHigin commented on test/common/markdown/markdown-link.tests.ps1
> +        $job = start-job {
You might consider using ThreadJobs (https://www.powershellgallery.com/packages/ThreadJob/1.1.2) since they are lighter weight.

2019-01-15 22:10 UTC, PaulHigin commented on test/common/markdown/markdown-link.tests.ps1
> +                $failures = $result -like '*[✖]*' | ForEach-Object { $_.Substring(4) }
Please add comments to illustrate expected success and failure result format.

2019-01-15 22:10 UTC, PaulHigin commented on test/common/markdown/markdown.tests.ps1
> +            $skip = $true
Where is $skip used?

2019-01-15 22:10 UTC, PaulHigin commented on test/common/markdown/markdown.tests.ps1
> +        Start-Process `
Clean up should only be performed if install was successful?

2019-01-15 22:20 UTC, adityapatwardhan approved these changes
Approved with one non-blocking comment.

2019-01-15 22:20 UTC, adityapatwardhan commented on test/common/markdown/markdown-link.tests.ps1
> +        Get-Job | stop-job
Maybe use `Get-Job | Remove-Job -Force`

2019-01-15 22:43 UTC, daxian-dbw approved these changes

2019-01-15 23:51 UTC, RDIL commented on test/common/markdown/markdown-link.tests.ps1
> +        # WARNING: Keep markdown-link-check pinned at 3.7.2 OR ELSE...
What was I thinking when I wrote the `OR ELSE...` part haha
It will only break tests (not end the world)

2019-01-16 00:17 UTC, PaulHigin approved these changes

2019-01-16 00:20 UTC, merged