Codeowners: count all Markdown files as documentation
PowerShell/PowerShell pull request #8748
Opened 2019-01-25 19:22 UTC by RDIL

## PR Summary
Makes users that are Codeowners of `Documentation` own all markdown files
  

## PR Context  
Popular files like the README have no codeowners.  

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [X] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [X] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2019-01-25 21:25 UTC, TravisEz13 requested changes

2019-01-25 21:37 UTC, TravisEz13 commented on .github/CODEOWNERS
> +*.md        @joeyaiello @TravisEz13
I think we would have to split up the markdown files... maybe by folder.

2019-01-25 21:39 UTC, RDIL commented on .github/CODEOWNERS
> +*.md        @joeyaiello @TravisEz13
Sounds like it would work.  If you want, I could also do it (but its fine if not)

2019-01-26 13:05 UTC, RDIL commented
Should I close it?

2019-01-26 13:58 UTC, iSazonov commented
@RDIL TravisEz13 is self-assigned so please wait.

2019-01-28 18:21 UTC, TravisEz13 commented
Let's go ahead and close this.

2019-01-28 18:21 UTC, closed without merging

2019-01-28 18:21 UTC, RDIL commented
Alright.