Fix cleanup config files
PowerShell/PowerShell pull request #8761
Opened 2019-01-28 04:47 UTC by iSazonov

## PR Summary

Related #8715. 

Add attempts to delete configuration files.

## PR Context  

There sometimes is a race condition in xUnit tests - powershell.config.json file is blocked in one process and another process tries to remove the file.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2019-01-28 14:30 UTC, RDIL approved these changes

2019-01-28 17:30 UTC, SteveL-MSFT requested changes

2019-01-28 17:49 UTC, iSazonov commented on test/xUnit/csharp/test_PSConfiguration.cs
> +                catch
Fixed.

2019-01-28 17:49 UTC, iSazonov commented on test/xUnit/csharp/test_PSConfiguration.cs
> +            var count = 10;
Fixed.

2019-01-29 04:13 UTC, iSazonov commented
@SteveL-MSFT Please update your review.

2019-01-29 06:35 UTC, SteveL-MSFT approved these changes

2019-01-29 19:27 UTC, adityapatwardhan approved these changes

2019-01-30 01:24 UTC, merged