Fixing issue with help progress
PowerShell/PowerShell pull request #8788
Opened 2019-01-29 23:32 UTC by powercode

The Get-Help cmdlet never calls WriteProgress with a RecordType set to Completed, so the progress is left being rendered even after the Get-Help cmdlet has completed.

  

## PR Summary

  

## PR Context  

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2019-02-05 23:19 UTC, adityapatwardhan commented
@powercode Love the change! Could you add some tests? Something like the following.

```PowerShell
Describe "Testing Get-Help Progress" {
 It "Last ProgressRecord should be Completed" {
  $j = Start-Job { Get-Help DoesNotExist }
  $j | Wait-Job
  $j.ChildJobs[0].Progress[-1].RecordType | Should -Be ([System.Management.Automation.ProgressRecordType]::Completed)
}}
```

2019-02-07 04:29 UTC, iSazonov commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +Describe "Testing Get-Help Progress" -Tags @('CI') {
I expect that it is slow tests so we should make it 'Feature'.

2019-02-07 12:27 UTC, iSazonov approved these changes
LGTM with one style comment.

2019-02-07 12:27 UTC, iSazonov commented on src/System.Management.Automation/help/HelpCommands.cs
>                  // finally clear the ScriptBlockAst -> Token[] cache
Please add new line before comment.

2019-02-08 03:58 UTC, iSazonov commented
Reopen to restart all CIs (no response).

2019-03-05 19:57 UTC, adityapatwardhan requested changes

2019-03-06 03:45 UTC, iSazonov commented on test/powershell/engine/Help/HelpSystem.Tests.ps1
> +        $j.ChildJobs[0].Progress[-1].RecordType | Should -Be ([System.Management.Automation.ProgressRecordType]::Completed)
It should be in try-finally.

2019-03-11 17:33 UTC, adityapatwardhan approved these changes

2019-03-11 17:36 UTC, adityapatwardhan commented
@powercode Pushed an empty commit to execute `Feature` tests. The new tests are categorized as `Feature`.

2019-03-11 18:26 UTC, merged