Update AppVeyor comments in Implicit.Remoting.Tests.ps1
PowerShell/PowerShell pull request #9020
Opened 2019-03-01 17:41 UTC by RDIL

# PR Summary
We are getting close to no AppVeyor references 🎉 
Updates comments as Azure is now used

## PR Context
AppVeyor removed ( #8686 )

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed:  #8686 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [X] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2019-03-04 15:54 UTC, PaulHigin approved these changes

2019-03-11 22:18 UTC, TravisEz13 requested changes

2019-03-11 22:30 UTC, RDIL commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
> +        ## Implicit credential doesn't work in the Azure DevOps builder, so mark all tests here '-pending'.
Just started a build to validate this.

2019-03-12 01:11 UTC, RDIL commented
@TravisEz13 yeah no it doesn't work

2019-03-12 13:12 UTC, RDIL commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
> +        ## Implicit credential doesn't work in the Azure DevOps builder, so mark all tests here '-pending'.
Yeah no doesn't work

2019-03-12 13:12 UTC, RDIL commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
> +        It "Should have a new session when the disconnected session cannot be re-connected" -Pending:(Test-IsVstsLinux -or Test-IsVstsWindows)
```suggestion
        It "Should have a new session when the disconnected session cannot be re-connected" -Pending:(Test-IsVstsLinux -or Test-IsVstsWindows) {
```

2019-03-12 19:21 UTC, TravisEz13 commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
> +        ## Implicit credential doesn't work in the Azure DevOps builder, so mark all tests here '-pending'.
Thanks

2019-03-12 19:23 UTC, TravisEz13 commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
> +        It "Should have a new session when the disconnected session cannot be re-connected" -Pending:(Test-IsVstsLinux -or Test-IsVstsWindows) {
```suggestion
        It "Should have a new session when the disconnected session cannot be re-connected" -Pending:(Test-IsVstsLinux -or Test-IsVstsWindows -or $IsMacOS) {
```

2019-03-12 19:25 UTC, TravisEz13 commented on test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
> +        ## Implicit credential doesn't work in the Azure DevOps builder, so mark this test '-pending'.
```suggestion
        ## Implicit credential doesn't work in the Windows Azure DevOps builder, so mark this test '-pending'.
        ## Also, this feature doesn't work on macOS or Linux
```

2019-03-13 19:50 UTC, TravisEz13 approved these changes

2019-03-13 19:52 UTC, TravisEz13 commented
@RDIL 	Don't worry about the CLA bot working on every commit.  It worked on the first commit `f1fb8b2`.  You can see by clicking the status indicator next to it.  Mentioning which commit it worked in, might be helpful though.

2019-03-13 19:52 UTC, merged