Fix macOS
PowerShell/PowerShell pull request #9188
Opened 2019-03-21 19:03 UTC by RDIL

# PR Summary
The jobs name is fully lowercase
Fixes the issue found by @iSazonov 

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

2019-03-21 19:18 UTC, iSazonov commented
The same for "linux"

@SteveL-MSFT Can it be case-insensetive?

2019-03-23 01:45 UTC, SteveL-MSFT commented
@PoshChan Please rebuild mAcOS

2019-03-23 01:46 UTC, PoshChan commented
@SteveL-MSFT, could not find a matching build target

2019-03-23 01:47 UTC, RDIL commented
@SteveL-MSFT typo

2019-03-23 01:51 UTC, SteveL-MSFT commented
@RDIL testing case-insensitivity which is what I expected

2019-03-23 01:54 UTC, RDIL commented
Oh

2019-03-23 02:08 UTC, SteveL-MSFT commented
Intent was to be case-insensitive, but forgot that `ConvertFrom-Json -AsHashTable` results in a case-sensitive hashtable.  I believe I can fix this on the server side.

2019-03-23 02:13 UTC, SteveL-MSFT commented
@PoshChan-Staging Please rebuild MACos

2019-03-23 02:13 UTC, PoshChan-Staging commented
@SteveL-MSFT, successfully started rebuild of `PowerShell-CI-macOS`

2019-03-23 02:16 UTC, SteveL-MSFT commented
@PoshChan please rebuild linux

2019-03-23 02:17 UTC, PoshChan commented
@SteveL-MSFT, all requests start with the magic word `Please`.

2019-03-23 02:20 UTC, RDIL commented
lol

2019-03-23 02:23 UTC, SteveL-MSFT commented
@PoshChan-Staging please rebuild LINux

2019-03-23 02:24 UTC, PoshChan-Staging commented
@SteveL-MSFT, successfully started rebuild of `PowerShell-CI-Linux`

2019-03-23 02:24 UTC, SteveL-MSFT commented
@PoshChan pLeASE rEbuild wINDOws

2019-03-23 02:26 UTC, PoshChan commented
@SteveL-MSFT, successfully started rebuild of `PowerShell-CI-windows`

2019-03-23 02:26 UTC, SteveL-MSFT commented
Ok, I believe @PoshChan is fully case-insensitive now :)

So, this PR isn't necessary except for aesthetic reasons.  But then you might as well fix Windows, macOS, and Linux with "correct" casing :)

2019-03-23 02:46 UTC, SteveL-MSFT approved these changes

2019-03-23 02:48 UTC, SteveL-MSFT requested changes

2019-03-23 02:48 UTC, SteveL-MSFT commented on .poshchan/settings.json
>                  "PowerShell-CI-windows",
```suggestion
                "PowerShell-CI-Windows",
```

2019-03-23 02:48 UTC, SteveL-MSFT commented on .poshchan/settings.json
> +                "PowerShell-CI-macos",
```suggestion
                "PowerShell-CI-macOS",
```

2019-03-23 02:48 UTC, SteveL-MSFT commented on .poshchan/settings.json
> +                "PowerShell-CI-linux"
```suggestion
                "PowerShell-CI-Linux"
```

2019-03-23 19:27 UTC, SteveL-MSFT approved these changes

2019-03-23 20:31 UTC, TravisEz13 approved these changes

2019-03-23 20:31 UTC, merged