Check to be sure that the test result file has actual results before uploading
PowerShell/PowerShell pull request #9253
Opened 2019-03-30 00:17 UTC by JamesWTruher

# PR Summary

VSTS produces a warning if the result set is 0, we will skip uploading this to avoid the warning and better support automation scenarios.

## PR Context

We have automation which checks our test results and if the result set is 0 for that file, a warning is produced. This PR will avoid uploading that file into the test results (which is valid, as there are no run tests). We will still add the file to our artifact list for completeness.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

2019-03-30 17:21 UTC, TravisEz13 commented on build.psm1
> +        if ( @(([xml](Get-Content $Path)).SelectNodes(".//test-case")).Count -gt 0 ) {
The test is filtering all XUnit files...
```suggestion
        if ( @(([xml](Get-Content $Path)).SelectNodes(".//test-case") -or $Type -eq 'XUnit').Count -gt 0 ) {
```

2019-03-30 17:22 UTC, TravisEz13 requested changes
Make sure XUnit results are published.

2019-04-01 22:41 UTC, TravisEz13 approved these changes

2019-04-01 22:44 UTC, TravisEz13 commented
@PoshChan 	Please remind me in 1 hour

2019-04-01 22:44 UTC, PoshChan commented
@TravisEz13, all requests start with the magic word: Please

2019-04-01 22:46 UTC, TravisEz13 commented
@PoshChan Please remind me in 1 hour

2019-04-01 22:46 UTC, PoshChan commented
@TravisEz13, will remind you in 1 hour

2019-04-01 23:46 UTC, PoshChan commented
@TravisEz13, this is the reminder you requested 1 hour ago

2019-04-01 23:47 UTC, merged