Add amazonlinux
PowerShell/PowerShell pull request #9314
Opened 2019-04-07 16:56 UTC by TravisEz13

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

2019-04-07 17:26 UTC, PoshChan commented
@TravisEz13, your last commit had 1 failures in `PowerShell-CI-linux`
PackageManagement Acceptance Test.install-packageprovider, Expect succeed
```powershell
Expected 'gistprovider' to be found in collection @(), but it was not found.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1: line 46
46:         $ipp | Should -Contain "gistprovider"
```

2019-04-08 16:01 UTC, PaulHigin requested changes

2019-04-08 17:50 UTC, TravisEz13 commented on .vsts-ci/install-ps.yml
> +    - /.vsts-ci/install-ps.yml
not really, it's just saying run this if this file changes.

2019-04-08 18:29 UTC, adityapatwardhan approved these changes

2019-04-08 18:30 UTC, adityapatwardhan commented on .vsts-ci/install-ps.yml
> +      $PSVersionTable
Convert to version and throw if not less than 6.2.0

2019-04-08 21:05 UTC, PaulHigin approved these changes

2019-04-08 21:45 UTC, merged