Avoid using Invoke-Expression
PowerShell/PowerShell pull request #9459
Opened 2019-04-24 23:48 UTC by xtqqczze

# PR Summary

Remove the use of Invoke-Expression in a few cases as per AvoidUsingInvokeExpression PSScriptAnalyzer rule.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively

2019-04-25 20:36 UTC, adityapatwardhan commented
Closing and re-opening to re-trigger CI

2019-04-25 21:59 UTC, TravisEz13 commented on build.psm1
> +            Start-NativeExecution [scriptblock]::Create("curl -sO $obtainUrl/uninstall/$uninstallScript")
`[scriptblock]::Create` and then invoking it is equivalent of Invoke-Expression.

2019-04-25 22:01 UTC, TravisEz13 commented on build.psm1
> +            Start-NativeExecution [scriptblock]::Create("curl -sO $obtainUrl/uninstall/$uninstallScript")
```suggestion	
            $uninstallScriptUrl = "$obtainUrl/uninstall/$uninstallScript"
            Start-NativeExecution {curl -sO $uninstallScriptUrl}
```

2019-04-25 22:01 UTC, TravisEz13 commented on build.psm1
> +            Start-NativeExecution [scriptblock]::Create("$sudo bash ./$uninstallScript")
Can you make the equivalent fix to what I suggested, here?

2019-04-25 22:02 UTC, TravisEz13 commented on build.psm1
> +                    Start-NativeExecution [scriptblock]::Create("$sudo apt-get update -qq")
```suggestion
                    Start-NativeExecution {$sudo apt-get update -qq}
```

2019-04-25 22:02 UTC, TravisEz13 commented on build.psm1
> +                    Start-NativeExecution [scriptblock]::Create("$sudo apt-get install -y -qq $Deps")
```suggestion
                    Start-NativeExecution {$sudo apt-get install -y -qq $Deps}
```

2019-04-25 22:03 UTC, TravisEz13 commented on src/PowerShell.Core.Instrumentation/RegisterManifest.ps1
> +Start-NativeExecution [scriptblock]::Create($command) $true
just no

2019-04-25 22:06 UTC, TravisEz13 commented
FYI, Feature tests are always run.  `[feature]` doesn't doe anything anymore.

2019-06-21 22:27 UTC, TravisEz13 commented on build.psm1
> +            Start-NativeExecution ([scriptblock]::Create("curl -sO $obtainUrl/uninstall/$uninstallScript"))
Using create ScriptBlock is worse that just using a script block.  Please change the curl part back.

2019-06-21 22:28 UTC, TravisEz13 commented on build.psm1
> +            Start-NativeExecution ([scriptblock]::Create("$sudo bash ./$uninstallScript"))
To be 100% clear, this is what invoke-expression does... so we are not fixing any issue here.

2019-06-21 22:29 UTC, TravisEz13 requested changes
see comment

2019-08-01 12:00 UTC, closed without merging