Add support for null usernames in Web Cmdlet Basic Auth
PowerShell/PowerShell pull request #9536
Opened 2019-05-05 00:45 UTC by markekraus

# PR Summary

It is possible to construct PSCredential objects with null or empty usernames. However, doing so makes it impossible to retrieve the plain-text password from the PSCredential.GetNetworkCredential() API. There are some Web APIs which may require a null or empty username. This PR changes the way the password is parsed from the Credential parameter such that a null or empty username will not impact conversion to plain-text.

## PR Context

Closes #9017

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

2019-05-05 11:44 UTC, iSazonov approved these changes

2019-05-05 14:22 UTC, SteveL-MSFT requested changes

2019-05-05 14:22 UTC, SteveL-MSFT commented on src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
> +            var password = new NetworkCredential(null,Credential.Password).Password;
```suggestion
            var password = new NetworkCredential(null, Credential.Password).Password;
```

2019-05-05 16:54 UTC, iSazonov commented
@SteveL-MSFT CodeFactor helped us with such formatting issues. Is it possible to bring it back?

2019-05-06 21:42 UTC, SteveL-MSFT approved these changes

2019-05-06 21:43 UTC, SteveL-MSFT commented
@iSazonov seems odd that Codacy wouldn't also catch such an issue

2019-05-06 22:21 UTC, adityapatwardhan approved these changes

2019-05-06 22:54 UTC, PaulHigin approved these changes

2019-05-07 00:15 UTC, merged

2019-05-07 00:15 UTC, adityapatwardhan commented
@markekraus Thank you for your contribution.

2019-05-07 03:41 UTC, iSazonov commented
@SteveL-MSFT seems odd that Codacy wouldn't also catch such an issue

Sorry, I don't understand that you mean.
CodeFactor greatly motivated us. We fixed most of style issues. Now there are mainly documentation issues. Since we are generating XML documentation, we should fix such issues as well. We could create something like "continues documentations" so that the XML documentation transparently flows into Docs repo. Therefore, I never wanted to turn off doc issues in CodeFactor. (Although if we turn this off we will have very few reported issues)
On the other hand, Codacy also sometimes looks very strange. There are sometimes false positives.
Together they (CodeFActor and Codacy) would be good.

2019-05-08 04:26 UTC, iSazonov commented
Without CodeFactor, we will begin again to collect formatting errors and fall into discussions of this.  
Each reviewer will make conflicting requests. 
It will be sad this is a great job of correcting the formatting to be destroyed.
We already have some such PRs. I really don't understand why CodeFactor was removed if it motivated us to correct above 60000 (!) style issues and make all PRs style clean.