Convert windows CI to stages
PowerShell/PowerShell pull request #9607
Opened 2019-05-15 01:17 UTC by TravisEz13

# PR Summary

## PR Context

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

2019-05-15 20:41 UTC, adityapatwardhan requested changes

2019-05-15 20:41 UTC, adityapatwardhan commented on .vsts-ci/windows-daily.yml
> +    - /tools/releaseBuild/**/*
Fix paths

2019-05-15 20:41 UTC, adityapatwardhan commented on .vsts-ci/windows-daily.yml
> +    - /tools/releaseBuild/**/*
Same as above

2019-05-15 21:00 UTC, adityapatwardhan approved these changes

2019-05-15 21:07 UTC, TravisEz13 commented
@PoshChan Please remind me in 4 hours

2019-05-16 01:08 UTC, PoshChan commented
@TravisEz13, this is the reminder you requested 4 hours ago

2019-05-16 17:30 UTC, merged