Add test for New-Item -Force
PowerShell/PowerShell pull request #9971
Opened 2019-06-20 20:36 UTC by robdy

# PR Summary

I created new test for checking if `New-Item -Force` creates a file if the folder in path is missing. It also checks that when `-Force` is not used, the command fails.

## PR Context

This is my first PR so feel free to give your feedback what I could do better :)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

2019-06-20 21:01 UTC, adityapatwardhan requested changes

2019-06-20 21:01 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
> +}
Add an end of line here.

2019-06-20 21:01 UTC, adityapatwardhan commented on test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
> +        { New-Item $FullyQualifiedFile -Force -ErrorAction Stop } | Should -Not -Throw
Please all add verification for whether the file was created. 

```PowerShell
$FullyQualifiedFile | Should -Exist 
```

2019-06-24 17:11 UTC, adityapatwardhan approved these changes

2019-06-24 17:59 UTC, daxian-dbw commented
@PoshChan Please remind me in 24 hours

2019-06-25 09:48 UTC, iSazonov commented on test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
> +		$FullyQualifiedFolder = Join-Path -Path $TestDrive -ChildPath $testFolder
Indentation. Please use spaces.

Please check indentations below too.

2019-06-25 10:00 UTC, robdy commented on test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
> +		$FullyQualifiedFolder = Join-Path -Path $TestDrive -ChildPath $testFolder
Good catch, fixed!

2019-06-25 10:03 UTC, iSazonov approved these changes
@robdy Thanks for your contribution!

2019-06-25 17:59 UTC, PoshChan commented
@daxian-dbw, this is the reminder you requested 24 hours ago

2019-06-25 18:03 UTC, merged